### ISSUE TITLE
Physics universal function to calculate interface temperature - T_int

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1000]
A function is needed to determine T at cell interfaces (given T at cell centers) in K

There is guidance on what this algorithm looks like here:

https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2605384045/Vertical+Coordinate?focusedCommentId=2605417001#comment-2605417001

**Comment by bartgol** [comment]
I believe we decided not to do this. `ColumnOps` already provides an utility for inverting the int->mid formula and compute midpoint quantities from the corresponding interface ones (plus a boundary condition at the top or bottom), though it has some drawbacks. #998 suggests an alternative implementation, but given that there's really no need for such a routine, that one should probably be closed too. Either way, this one can be closed.

**Comment by PeterCaldwell** [comment]
We decided not to implement the Tint universal function for the v1 release because it would cause BFB problems. We will revisit the issue for SCREAMv1.1 as noted in #1035.
