### ISSUE TITLE
Physics universal function to calculate layer height from surface - z_int, z_mid & dz

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1002]
A function is needed to determine geopotential height offset (height above the surface in meters) at cell interfaces (`z_int`) and cell midpoints (`z_mid`). As well as layer thickness, `dz`.

There is guidance on what this algorithm looks like here:

https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2605384045/Vertical+Coordinate?focusedCommentId=2605417001#comment-2605417001

**Comment by bartgol** [comment]
I think #1019 took care of this. Closing.
