### ISSUE TITLE
[AD] Input data directory lookup for stand-alone testing

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1022]
Up until now SCREAM hasn't had to worry about passing the location of data files generally stored in a machines central data location.  Most data files have been small enough to be included in the repo under the `scream/data` directory.

As we get closer to full-scale runs we will need to be able to query the input data directory locations for a specific machine from the `config_machine.xml` file and pass that root directory information to the AD and likely the individual processes.

In CIME builds we can take advantage of the `case_build` infrastructure.  But in stand-alone builds we will most likely have to implement our own way to query this info.

The task is to design and implement the code needed to query the machine config file and pass that to the AD, presumably through the input.yaml file.

-Not as important- What do we do when a file is missing?  In a CIME build those files are automatically downloaded.  Do we want something similar in SCREAM stand-alone builds?  How often will a user need a file that is missing from a stand-alone build, having not already tried a CIME build?

**Comment by bartgol** [comment]
What if we completely ignore this issue, namely, if the user needs some data, he/she/they should go get it, and put it in `$bld_dir/data`? If the files are small enough, they can be shipped with the repo, stored in `$scream_src_dir/data`, as we do now. For larger files, one has to put them in the bld folder manually before running.

**Comment by jgfouca** [comment]
Assigning myself since this is somewhat CIME related.

**Comment by PeterCaldwell** [comment]
I'm fine with this initial impl requiring the user to specify full paths for all input data or to put (at least symlinks) to the data into a particular directory or something. Convenience routines aren't essential...
