### ISSUE TITLE
C++ RRM

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1026]
* HOMMEXX: Make the mesh/comm infrastructure handle RRM.
* AD: Not sure yet.

**Comment by ambrad** [comment]
I'm working on this and some TOM dissipation optimizations here: https://github.com/E3SM-Project/scream/compare/master...ambrad:scream:ambrad/hommexx/be-enhancements#diff-049b39f835b425fc258472404ebec8c081acf0e72297109ac103a7d801c6525b

**Comment by ambrad** [comment]
Update:
* The dycore-side impl is done and I have a standalone C++-vs-F90 RRM test running and passing on Chrysalis and tests with structured grids using the new BE impl BFB with the old on Chrysalis and Ascent.
* I'm focusing now on verifying PE-layout invariance with fine-grained sweeping of ranks and threads on Chrysalis and Ascent.
* Next I'll do the final performance runs with low and high workloads on Ascent and probably Cori-KNL.
* Then I'll clean up the commits and move them to E3SM.

**Comment by ambrad** [comment]
This PR requires checking the performance of two changes: the BE backend rewrite and the HV TOM improvements. The following performance results on Cori-KNL and Ascent show results for the old and new BE backends with the HV TOM improvements active, followed by the performance of master.

I need to run with two nodes instead of one on Cori-KNL, which increases variability substantially. The following timers are representative. In particular, both the new pack and unpack routines are faster than the old. The HV TOM improvement shows up in "a:tl-ae advance_hypervis_dp".
```
Cori-KNL (2 nodes x 64 ranks/node x 2 threads/rank; 1 node => OOM):
  BoundaryExchange backend:
    /global/cscratch1/sd/ambradl/e3sm_scratch/cori-knl/ne30pg2v1.nlev128
    old (timing.65819898.230110-150603)
        "a:amb_pack_min_max"           128 6.144000e+03   4.422064e+01     0.374   0.302
        "a:amb_unpack_min_max"         128 6.144000e+03   7.143616e+00     0.070   0.043
        "a:amb_pack_scon"              128 3.870720e+05   5.445228e+02     4.867   3.500
        "a:amb_unpack"                 128 3.870720e+05   6.677891e+02     5.580   4.818
        "a:tl-sc prim_run_subcycle_c"  128 6.144000e+03   1.660401e+04   129.902 129.575
        "a:caar compute"               128 3.686400e+05   3.697852e+03    29.872  27.738
        "a:caar_bexchV"                128 1.843200e+05   1.220387e+03    10.419   6.928
        "a:tl-ae advance_hypervis_dp"  128 3.686400e+04   1.217262e+03    10.314   8.577
        "a:hvf-bhwk"                   128 3.686400e+04   6.354812e+02     5.277   4.556
        "a:hvf-bexch"                  128 1.105920e+05   5.580245e+02     5.423   3.142
        "a:compose_transport"          128 6.144000e+03   4.144163e+03    32.622  32.164
    new (timing.65819614.230110-144424)
        "a:amb_pack_min_max"           128 6.144000e+03   4.385175e+01     0.386   0.315
        "a:amb_unpack_min_max"         128 6.144000e+03   8.459248e+00     0.085   0.057
        "a:amb_pack_ucon"              128 3.870720e+05   5.051612e+02     4.218   3.302
        "a:amb_unpack"                 128 3.870720e+05   5.276053e+02     4.508   3.598
        "a:tl-sc prim_run_subcycle_c"  128 6.144000e+03   1.665683e+04   130.427 129.949
        "a:caar compute"               128 3.686400e+05   3.779447e+03    30.811  28.571
        "a:caar_bexchV"                128 1.843200e+05   1.152549e+03    10.088   7.158
        "a:tl-ae advance_hypervis_dp"  128 3.686400e+04   1.229182e+03    10.378   8.685
        "a:hvf-bhwk"                   128 3.686400e+04   6.470293e+02     5.306   4.813
        "a:hvf-bexch"                  128 1.105920e+05   5.611220e+02     5.246   3.180
        "a:compose_transport"          128 6.144000e+03   4.110529e+03    32.519  31.917
  HV TOM changes to SphereOperators and BE 3D un/pack and comm:
    /global/cscratch1/sd/ambradl/e3sm_scratch/cori-knl/ne30pg2v1.ref.nlev128 (timing.65819576.230110-144022)
        "a:tl-sc prim_run_subcycle_c"  128 6.144000e+03   1.729269e+04   135.314 134.928
        "a:caar compute"               128 3.686400e+05   3.827495e+03    31.213  28.729
        "a:caar_bexchV"                128 1.843200e+05   1.280674e+03    11.081   8.087
        "a:tl-ae advance_hypervis_dp"  128 3.686400e+04   1.611209e+03    13.246  11.771
        "a:hvf-bhwk"                   128 3.686400e+04   6.802983e+02     5.601   4.993
        "a:hvf-bexch"                  128 1.105920e+05   7.193735e+02     6.466   4.398
        "a:compose_transport"          128 6.144000e+03   4.157903e+03    32.789  32.175
```

```
Ascent in progress
```

**Comment by bartgol** [comment]
I agree that few% slower for structured grids is not enough to justify two code bases, and we should use a single impl.

Two questions on your first timers table:

1. is `a:amb_pack_scon` in the old part the same as `a:amb_pack_ucon` in the new?
2. The new minmax unpack seems to perform ~20% slower than the old one. It's a very small timer compare to others, so I'm not concerned for performance, but I wondered if there's a reason for why that's much worse than the normal unpack, or if that might point to some issue in the impl.

**Comment by ambrad** [comment]
1. Right. Those timers are temporary: `s` for structured, `u` for unstructured. I gave one of the timers a different name so I could easily grep a bunch of timer files and know which backend was used.
2. I'll check, but I'm pretty sure that's noise. Cori-KNL is very noisy at that level of timing.

**Comment by ambrad** [comment]
I need to do final testing of the upstream repo with rebased commits, but the following is true of my working branch:
1. On Weaver, ll 'nightly'-profile theta cxx_vs_f90 tests pass. All _ut tests pass. I ran 9 preqx cxx_vs_f90 tests and they all pass. Finally, the new RRM cxx_vs_f90 test passes.
2. On Chrysalis, all HOMME(BFB) tests pass against baselines except the known DP-related ones.
3. On Ascent, ERS_Ln362.ne30pg2_ne30pg2.F2010-SCREAMv1 passes.

**Comment by ambrad** [comment]
E3SM PR is https://github.com/E3SM-Project/E3SM/pull/5395.

**Comment by ambrad** [comment]
I'll need another E3SM PR for EAMxx build support: https://github.com/E3SM-Project/E3SM/pull/5426

**Comment by ambrad** [comment]
And I'll need a SCREAM-side PR to complete the build and compset details: https://github.com/E3SM-Project/scream/pull/2141
