### ISSUE TITLE
Revisit universal functions

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1035]
We are trying to minimize the number of variables in the field manager, recalculating things on the fly instead. We punted on p_int and have t_int calculated in a weird local way in radiation for SCREAMv1. We should revisit what variables are calculated on the fly vs stored in the field manager for v1.1.

**Comment by PeterCaldwell** [comment]
Note that @bartgol believes we can never have p_int calculated outside of the dycore: 

> the nh pressure has the big problem of having the top bc alongside being involved in the no-penetration bc at the surface (unlike, say, T_int, where we only have a bc at the bottom). Dynamics has a relatively involved way of ensuring the surface pressure is compatible with the bc. I doubt we can have a p_int routine that does a similar job outside of dyn.

**Comment by AaronDonahue** [comment]
I'm pretty sure this has been resolved.
