### ISSUE TITLE
ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0 with new dyamond simulation

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1041]
Using latest scream repo that we are calling v0.1, I tried a ne1024 case with:

```
resolution=ne1024pg2_r0125_oRRS18to6v3
compset=F2010-SCREAM-HR-DYAMOND2
checkout_date=20210505
branch=fd721e4  
run_descriptor=SCREAMv01
```

I hit the following error on cori. The last line of atm.log indicates it happens after the first ATM step.

```
10729:  WARNING:CAAR: dp3d too small. dt_remap may be too large
10729:  k,dp3d(k), dp0:          125  -60.8230392366906        366.680908203207     
10729:  WARNING:CAAR: theta<   100.000000000000       applying limiter
10729:  k,vtheta(k):          125  -204.364531901029     
10729: Image              PC                Routine            Line        Source             
10729: e3sm.exe           000000000375FD8A  Unknown               Unknown  Unknown
10729: e3sm.exe           0000000001E52E8E  shr_abort_mod_mp_         114  shr_abort_mod.F90
10729: e3sm.exe           0000000000B4EE2D  eos_mp_pnh_and_ex         140  eos.F90
10729: e3sm.exe           0000000000B4E830  eos_mp_pnh_and_ex          73  eos.F90
10729: e3sm.exe           0000000000B6769B  prim_state_mod_mp         889  prim_state_mod.F90
10729: e3sm.exe           0000000000AFF54E  prim_driver_base_        1439  prim_driver_base.F90
10729: e3sm.exe           0000000000AFE4E6  prim_driver_base_        1168  prim_driver_base.F90
10729: e3sm.exe           0000000000F50543  dyn_comp_mp_dyn_r         386  dyn_comp.F90
10729: e3sm.exe           00000000032E6313  Unknown               Unknown  Unknown
10729: e3sm.exe           000000000328EEAA  Unknown               Unknown  Unknown
...
10729:  ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0


case:
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/SCREAMv010.SCREAM-DY2.ne1024pg2.20210505

launch script:
/global/cscratch1/sd/ndk/wacmy/run_scream/my-run.SCREAMv01.ne1024pg2_scream.sh
```

Here are some notable changes to launch script:
```
    ! Add dycore settings for coarser topography
    pgrad_correction = 1
    hv_ref_profiles = 2
    hv_theta_correction = 1
    bnd_topo='/global/cfs/cdirs/e3sm/terai/topo/USGS-gtopo30_ne1024np4pg2_fx1t-SGH.nc'
```

**Comment by mt5555** [comment]
if it is early in the simulation, then I think this is a spinup issue.

If its late in the simulation, then it is an indication that the current settings cant handle the rough topography and we need to consider using smoother topography, or smaller timesteps (or more dissipation)

**Comment by PeterCaldwell** [comment]
I think the fail was on the first step. So should Noel set dt_remap to half what it was to see if it runs? Or is that the wrong parameter to change? Or should he switch to 3/4 what dt_remap was? Or ???

**Comment by mt5555** [comment]
tracking the NE256 results here:

https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2716598273/NE256+Topography+evaluation

Ideally we would know what works in NE256 first and that would tells us what to try in NE1024.  But the NE256 results are late, so probably good to start testing in parallel.  AT NE1024, I would recommend we start with:

1. x16 (default) topo, but with new topo namelist settings.   High confidence this should run, but does it need a new IC due to spinup issues?
2. fx2t + new namelist settings.  (smoother topography, fallback if fx1t is too unstable)
3. fx1t + new namelist settings:  try with se_step=3x smaller than the default.

**Comment by ndkeen** [comment]
The new news: Using `se_tstep=4.6875` did allow the run to go further. It ran 209 timesteps before stopping with OOM.

Did something change such that we might expect more memory use?

https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2729607334/Issues+running+ne1024+with+v0.1+--+EOS+bad+state+d+phi+dp3d+or+vtheta+dp+0

**Comment by PeterCaldwell** [comment]
> Did something change such that we might expect more memory use?

Not to my knowledge. Were we pretty close to the memory limit before? Can you check whether memory is increasing with time (i.e. do we have a memory leak)?

**Comment by ndkeen** [comment]
Peter C found that the hash we were using (from ~May  6th) did not have a recent bugfix: 
`Pull Request #1036 from E3SM-Project/scream/aarondonahue/quickfix_for_spa`
which could easily be the reason for having OOM issue.

**Comment by ndkeen** [comment]
We ended up working around this issue by using decreased timestep, ie `se_tstep=4.6875`. So far, all cases we've tried using this timestep have run at least a day.

However, just this weekend, I attempted to continue a ne1024 case beyond day2 and hit a potentially similar error. In the 3rd day of simulation, after ATM step 548, we see another `EOS bad state` error.

This is a case we were calling "extra output" as Chris gave me some additional lines to user_nl_eam.
One difference between day3 and day1/day2 is that I made some changes to threading env variables (adding more memory to each thread and changing the way threads are spaced on the cores) -- I don't suspect these changes would impact the simulation (only looking for performance differences), however, I've submitted day3 again without these changes.

```
6200:  bad state in EOS, called from: prim_state_mod
6200:  bad state in EOS, called from: prim_state_mod
6200:  bad i,j,k=           4           4          21
6200:  bad i,j,k=           3           1          21
6200:  vertical column: dphi,dp3d,vtheta_dp
6200:  vertical column: dphi,dp3d,vtheta_dp
6200:   1   -17173.7741       65.0043    85070.4484
6200:   1   -17170.0569       65.0043    85052.1038
...
6200: 127     -361.4758      415.9879   126802.2885
6200: 128     -263.3057      303.7001    92608.1803
6200: 128     -263.2462      303.6477    92580.4773
6200:  ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0
6200:  ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0

/projects/ClimateEnergy_4/ndkeen/SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n1536a16x8.topo1.IC1
alias: SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n1536a16x8.topo1.ts4.eo
```

**Comment by ndkeen** [comment]
closing issue as no longer immediate or easily reproducible
