### ISSUE TITLE
Read Topography input data into the grids manager

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1056]
The surface topography needs to be read in from netCDF and stored somewhere for use by dynamics and physics.  The natural candidate would be to store this information in the grids manager.

The motivation for storing this information in the grids manager is:
1. It is assumed to be needed for all simulations.  So not process specific.
2. It is static, i.e. it doesn't change with time.

**Comment by AaronDonahue** [comment]
@bartgol , do we do this now?  @tcclevenger do you know?  Can we close this issue?

**Comment by bartgol** [comment]
Yes.
