### ISSUE TITLE
Always use "wet mixing ratios" (specific humidity)

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1066]
We decided in #531 and #1008 that SCREAMv1 should insist that all advected variables in the field manager are specific humidities (known colloquially in E3SM and SCREAM as "wet mixing ratios"). In other words, advected quantities are always defined as amount of stuff divided by mass of *total* air rather than mass of *dry* air. 

The goal of this issue is to make sure we implement this decision correctly. Steps are:

- [x] dycore interface is coded up under the assumption that all mixing ratios are "wet" (which should be trivial)
- [x] create a universal function for converting between wet and dry mixing ratios
- [ ] make sure all physics parameterizations that expect dry mixing ratios call the conversion universal functions in their interface layer to keep things working properly
- [ ] make sure our saturation mixing ratio calculation assumes wet or dry mixing ratios as appropriate. We might need to support both wet and dry saturation mixing ratio calculations. 

Tagging this issue with both v0.1 and v1 because the current F90 implementation probably has some wet vs dry bugs in it. Note that while wet vs dry is something we should get right, the 2 options are practically identical so this work should have an almost imperceptible effect on climate.

**Comment by bartgol** [comment]
I think this has been addressed, @PeterCaldwell feel free to reopen if that's not true.
