### ISSUE TITLE
Possibility of using boost::units features

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#108]
Following @pressel's comment on one of the confluence discussions, I have been looking at the `boost::units` library (actually, it's just headers). It is very interesting. I am trying to use it for the specification of units in the `Field` structure stack. That can be done easily, and I think it adds value (makes units specification easy and less error prone).

What I want to ask you though is whether it could be useful to bring in also `boost::units::quantity`, which is a scalar type templated on the units, which are then used to enforce compile-time safety. It is a way to use the language to ensure we combine physically compatible quantities. For instance, the code could look like this:

...
// Inside some scream header:
using LengthUnitType = ...; // some long type
using ForceUnitType = ...; // some long type
using EnergyUnitType = ...; // some long type

// In a piece of code inside a parametrization
quantity<LengthUnitType,Real> my_length(...);
quantity<ForceUnitTypee,Real> my_force(...);
auto apples_and_oranges = my_length + my_force; // Compiler error! Can't sum quantities with different units.
auto work = my_length*my_force; // Ok: units of work will be EnergyUnitType
...

The potential advantages are mainly two: 

1) more clarity of the code: the meaning of a variable is encoded not just in its name, but also in its _type_)
2) safety: you cannot accidentally combine apples and oranges, like writing `a+(b+c)*d` instead of `(a+b+c)*d`.

The big issue with the quantity headers is that the functions are not device friendly. For the most part, it only boils down to adding `KOKKOS_INLINE_FUNCTION` in front of all of them. We can specialize the `quantity` class on `scream::Real`  and overload free functions for this particular type, to add the macro (along eliminating a whole lot of code that we don't need). It would be a relatively quick process, modulo all portability checks.

Possible downsides are the addition of boost as a dependency, although it is fairly common to find it as a tpl on HPC facilities.  We have some options: we could rely on what the HPC cluster has (but machine files need to be updated), we could  snapshot boost in our external folder (especially considered we only use boost as headers), we could copy and paste only the files needed in a boost subdir (like we did in homme for the Vector class from KokkosKernels). The latter is probably the  last resort, and least desirable, imho.

Note: the fields will be still stored as `Real*` in the field manager (otherwise we need one container per units). When the user 'reshapes' the view (which is already needed in order to get the proper N-d layout), he/she can also change the data type from `Real*` to  `quantity<Units,Real>*` (or even a packed version of that), since `quantity` is only a lightweight (zero-overhead, I think) decoration of the stored value type (i.e., `sizeof(quantity<U,value_type>)==sizeof(value_type)`). 
Notice, therefore, that this feature is 'optional'. We could have a parametrization using only `quantity`, and a parametrization never using it. We would not force anything down the developers' throats. We would just offer an option. Imho, a valuable option.

What are your thoughts?

**Comment by bartgol** [comment]
I should point out that `boost::units` would already be helpful even if we don't use `boost::units::quantity`, since it would make it easy to specify/check units of `Fields`. E.g.:, this is what I would do:

...
// In a scream header
namespace scream {
namespace units {
using SI = boost::units::si;
const auto m = SI::meter;
const auto s = SI::second;

const auto km = 1e3*m;
}}

// Later, create a field, and set it in the repo
FieldIdentifier fid(my_name,my_tags,my_dims);
fid.set_units(m/s);
repo.register_field(fid);

// Inside another parametrization
FieldIdentifier fid2(my_name,my_tags,my_dims);
fid.set_units(km/s);
repo.register_field(fid2); // the repo can generate an error, since the same field exists, but with different units.
...

**Comment by ambrad** [comment]
How does this interact with vectorization packs? If packs present an issue, is it still possible to get most of the value of the boost units capability? Could we smoothly use all capabilities in a debug build but only some in an opt build? `quantity` itself is almost certainly nothing but a struct around a `T` (e.g., `double`), so in principle one could have a pack of `quantity`s. Just questions and speculation.

**Comment by bartgol** [comment]
I thought about it and I don't see why it wouldn't work. I haven't tried it (though I could on a CPU build in fact, the issue with the vanilla boost impl is only on gpus). The way boost works is by overloading op+-*/ as weel as the 'root' and 'pow' functions, so they _should_ seamlessly work when wrapped in a pack.

I will double check this conjecture on a cpu build, where I can just pull in boost, and verify it.

On a general infrastructure level, would there be reasons for the E3SM project to avoid pulling in a dependency on boost? Although it is a fairly common tpls on clusters (and we could simply modify some machine files that use scream to also load boost modules, or simply snapshot it into the `external` folder), I am not sure what the policy is in E3SM about adding dependencies. Perhaps @jgfouca or @rljacob or anyone from the infrastructure team has some thoughts about it?

**Comment by jgfouca** [comment]
@bartgol , is boost::units a header-only package?

**Comment by bartgol** [comment]
Yes.

**Comment by bartgol** [comment]
To be clear: it requires also some other (core) part of boost, but still as header-only.

**Comment by jgfouca** [comment]
The would be pretty easy to accommodate in our build system. We've been putting externals in E3SM/externals.

**Comment by jgfouca** [comment]
It may make sense to just grab it as a submodule so that all header-only libraries would be available.

**Comment by bartgol** [comment]
I did a quick test on blake:

```
#include <catch2/catch.hpp>

#include <boost/units/quantity.hpp>
#include <boost/units/systems/si/time.hpp>

#include "share/scream_types.hpp"
#include "share/scream_pack.hpp"
#include "share/quantity.hpp"

TEST_CASE("quantity", "") {
  using namespace scream;
  using namespace boost::units;

  using Time = quantity<si::time,Real>;

  pack::Pack<Time,8> a(1.0);
  pack::Pack<Time,8> b(2.0);

  auto c = a+b;

  for (int i=0; i<8; ++i) {
    REQUIRE (c[i].value()==3.0);
  }
}
```

Here `share/quantitty.hpp` is a copied and pasted version of the boost one, with specialization on `value_type = scream::Real` and a couple of minor tweaks (like allowing construction from value_type, which boost does not allow (only offers static construction function)).

The intel report says all the loops (in the init as well as in op+ and op=) are vectorized. However, the remark

`remark #15321: Compiler has chosen to target XMM/YMM vector. Try using -qopt-zmm-usage=high to override`

seems to suggest that the compiler prefers to use smaller (than 512) vector units (if I understand it correctly). @ambrad I've seen this in the opt report of other tests too (e.g., the packs test). I'm not sure if you've noticed it in the past, nor whether it should concern us. But I think the bottomline concerning this issue is that the use of quantity does not deteriorate vectorization.

**Comment by bartgol** [comment]
I still need to check the performance (e.g., see if there's a hit summing `quantity`'s compared to summing `Real`'s, just to be super safe that this is indeed a zero-overhead addition.

However, before doing all the tests on cpu/gpu (the latter requiring to overload/specialize some functions/structs), I want to know whether other developers consider this a valuable addition or not. If not, then I will bring in boost just to specify the fields units, but will not offer the possibility of reshaping a `Field` into a view of `quantity`'s.

Note: once the users have their hands on the reshaped view, they can still do it, of course. What I meant is that we will not offer support for it inside the `Field::get_reshaped_view` method, nor we will advertise it in our AD design document.

**Comment by bartgol** [comment]
One thing that the use of quantity needs when it comes to pack is to increase the template signature of `operator * (const Pack&,const Pack&)` (and the division one as well) to allow for different scalar types in the two packs. In particular, the units of the two inputs may be different, and the output units must be deduced based on the type of the result of `Pack1::scalar * Pack2::scalar` (and will never be the same of either one of the inputs, unless one of the two is a dimensionless quantity).

**Comment by ambrad** [comment]
Is it possible that it should be `quantity<Pack>` rather than `Pack<quantity>`? A single pack won't have multiple types of quantities and should be thought of (conceptually) as a scalar.

**Comment by ambrad** [comment]
Separately, re: `quantity`, I'm concerned about (1) compiler overhead, since this effectively introduces a bunch of new types, leading to a bunch of new instantiations and (2) a new layer of types, leading to more type deduction issues.

**Comment by bartgol** [comment]
re: compiler overhead. This could be a problem, as you point out, because of the bloating in template instantiations for things like packs and views.
re: deduction issues. We don't have a ton of places where we template on the scalar type, mostly just in the pack and subview utils. There may be a slight increase in metaprogramming, to accommodate the new scalar type, but I suspect it would not be too insane.

re: pack of quantity vs quantity of pack. In practice, either one works, and similar (if not the same) code should be generated. From a conceptual point of view, I like better `Pack<quantity>`, since the physical quantity is the inner scalar, while a Pack is just a programming hack to get more speed. A 'time' object should be a single Real, not N Real's.

That said, swapping them (i.e., `quantity<Pack>`) would allow to keep the pack meta stuff unchanged, which is indeed a positive aspect. On the other hand, unpacking becomes a little more cumbersome:

- with `Pack<quantity> a,b;` we get `a[i] += b[i];`
- with `quantity<Pack> a,b;` we get `a.value()[i] += b.value()[i];`

i.e., with pack on the outside, we can operate always at the `quantity` level, while with pack on the inside, we may need to open up the `quantity` object just to be able to open up the pack...

I am going to do a little test on compilation time with quantities on a small (but not too small) piece of code, and see what is the impact. Another possibility (which I think you hinted at before) is to enable quantities only in debug builds.

**Comment by ambrad** [comment]
We should also think about how to capture correctness for some of the most error-prone quantities, like dry vs moist mixing ratios, each of which is potentially viewed in this framework as dimensionless (kg kg^-1). We'd want to capture 'dry' and 'moist' as part of the units specification, kg/(dry kg) and kg/(moist kg).

**Comment by bartgol** [comment]
This would be possible, but not really easy (we would need to define a new units system, cause SI is bound to only 7 independent ones, so any mass would collapse to the same unit). I am not sure we would like to distinguish these kind of quantities though, since 1) the distinction of quantities with the same units is beyond the 'physics' scope, and more in the 'model' scope, and 2) it may complicate downstream calculations, since you can't combine kg/(dry kg) and kg/(moist kg) anymore in any way (i'm not talking just about summing mixing ratios, but all downstream quantities that depend on them would be incompatible). 

I agree that moist vs dry could be a (relatively) common source of error, but I'm not sure units would be the appropriate way of preventing these errors.

**Comment by bartgol** [comment]
Closing, since we agreed boost is probably too much. There is an outstanding branch introducing an in-house units structure without the compile-time checks, which should be enough for out needs.
