### ISSUE TITLE
SCREAM should use adjust_ps=.false.

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1081]
In EAM, adjust_ps=.true. puts all the pressure change due to changes in moisture during physics into the surface pressure without changing dp. If false, moisture changes in each vertical layer are used to adjust the pressure for that layer. This 2nd option makes more sense, but E3SMv2 needs to use the first option in order to avoid last-minute non-BFB changes. SCREAM should:

- [ ] switch SCREAMv0.1 to use adjust_ps=.false.
- [ ] check whether this switch has any practical effect
- [ ] if switching SCREAMv0.1 to adjust_ps=.false. doesn't have major deleterious impacts, we should switch SCREAMv1 to *only* support the adjust_ps=.false. option.

**Comment by oksanaguba** [comment]
Is this about F code? if so, would it be good to put a PR to e3sm master first?

**Comment by oksanaguba** [comment]
@PeterCaldwell would you please confirm that I can put this in e3sm master and it will be picked up with the next merge?

**Comment by mt5555** [comment]
to put this in master, we will need an #ifdef SCREAM or something similar, since only BFB changes currently allowed.
Or we could wait until after v2 release to make this change and a few others.

**Comment by oksanaguba** [comment]
For e3sm I would keep adjust_ps=.true. , and in scream one could first use it in the namelist and then switch the default? I assume we want it in both e3sm and scream, so I wanted to avoid conflicts.

**Comment by bartgol** [comment]
Is this option settable from namelist?

**Comment by oksanaguba** [comment]
not yet, but will be

**Comment by PeterCaldwell** [comment]
Ok, I vote that we change this setting in our SCREAM run scripts until we are allowed to change the default in E3SM repo.

**Comment by oksanaguba** [comment]
this is in master:
```
#ifdef MODEL_THETA_L
  if (dt_remap_factor==0) then
     adjust_ps=.true.   ! stay on reference levels for Eulerian case
  else
#ifdef SCREAM
     adjust_ps=.false.  ! Lagrangian case can support adjusting dp3d or ps
#else
     adjust_ps=.true.   ! Lagrangian case can support adjusting dp3d or ps
#endif
  endif
#else
  adjust_ps=.true.      ! preqx requires forcing to stay on reference levels
#endif
```
