### ISSUE TITLE
It is possible to get negative nr_selfcollect_tend in P3

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1094]
Looking at this line in p3_rain_self_collection_impl.hpp we notice that it is possible to get negative values for `dum` and subsequently a negative rain_self_collection tendency.

All it takes is for `dum2-dum1 > 0.00030136833` which will cause `2 - exp(2300 * (dum2-dum1) < 0`

This was found looking at FPE errors in p3_tests as part of the PR #1090 effort.

The question is, should we limit `dum` to be >=0 or handle this case in some other way.

**Comment by hassanbeydoun** [comment]
I think this is ok since nr_selfcollect_tend includes rain drop breakup (when dum2>dum1) which is a negative tendency. Now that I think of about it, it is confusing that rain drop breakup is hidden away in the self-collection routine.

**Comment by AaronDonahue** [comment]
Closing this per the comment by @hassanbeydoun
