### ISSUE TITLE
Resolve discontinuities in the code brought on by the use of limiters.

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1098]
There are a handful of locations where the use of limiters leads to discontinuities in model variables. 

Additionally, there are inefficiencies in the code where the same mask is used for multiple `.set` commands, where an "if" statement with `mask.any()` could consolidate these "set" commands into a single loop that will only execute when `mask.any()` is true.

**Comment by AaronDonahue** [comment]
@ambrad , I created this issue so that we don't lose sight of the issues you brought up in the SCREAMv1 telecon yesterday.  Don't feel like you have to do anything.  But at least now it will stay on our radar.

Although if you do bump into any lines of code that would fit into this category you could always copy/paste the file and line in question to the conversation here and then when someone does decide to resolve the issue they will have a map to where to look.

**Comment by ambrad** [comment]
@AaronDonahue I already reported the discontinuities in #1089 and provided specific cases. I'm not too worried about the inefficiencies; these can be cleaned up as devs come across them. Thus, would you mind if I close this issue?

**Comment by AaronDonahue** [comment]
@ambrad , I don't mind at all.
