### ISSUE TITLE
Update import/export for variables between E3SM and SCREAM in SurfaceCoupling

### ISSUE THREAD

**Issue by tcclevenger** [E3SM-Project/scream#1101]
Update mct_coupling to correctly copy data between E3SM and SCREAM for CIME runs. Use chart in [FM chart confluence page](https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/1927512393/Field+Manager+Variable+Names) to get the appropriate matching of variables.

**Comment by bartgol** [comment]
@tcclevenger Isn't this fixed?

**Comment by tcclevenger** [comment]
It still needs to be verified with `import_data != 0`. @singhbalwinder is working on getting a compset where this is the case running.
