### ISSUE TITLE
Radiation interface needs to do solar radiative transfer only on daytime columns

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/scream#1102]
Currently, our radiative interface code passes all columns (both day and night) to the RRTMGP solvers. This is a problem in the shortwave, because the codes are only valid for daytime columns (cosine of solar zenith angle greater than 0) and the RRTMGP codes assume that only daytime values are passed. The approach in EAM is to subset the inputs to the solar code to daytime-only values ahead of time. We should probably do the same here, although we *could* consider adding conditionals to the shortwave kernels to simply pass over the nighttime columns. This second approach may degrade performance more than the cost of the data copies to subset the data ahead of time though.

**Comment by bartgol** [comment]
Two details may be important to determine performance of the approach that add conditionals in the kernels:

- how many times would you have to evaluate the conditional for each given column?
- if the conditional is false, would a different code branch be executed, or would the code simply skip a code block? In other words, is it an `if (..) {..} else {..}` or just `if(..) {..}`?
