### ISSUE TITLE
Radiation interface needs to update solar zenith angle

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/scream#1107]
Solar zenith angle needs to be updated each time step based on day, time of day, and latitude and longitude. This will probably require porting `share/utils/shr_orb_mod.F90` to C++ (I think only the `shr_orb_avg_cosz` routine needs to be ported).

**Comment by AaronDonahue** [comment]
https://github.com/E3SM-Project/scream/blob/master/share/util/shr_orb_mod.F90 for quick reference

**Comment by bartgol** [comment]
I believe #1175 addressed precisely this issue. @AaronDonahue @brhillman , if this is still an issue, feel free to reopen.
