### ISSUE TITLE
[AD] Scorpio input class doesn't need grids manager.

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1109]
Currently the scorpio input class requires the grids manager at construction.  Looking into the code this is subsequently used just to retrieve the grid itself.  It would be cleaner and make more sense to just pass the grid directly at construction and not need the grids manager or grid name.

A secondary step to this task is to audit if a similar simplification can be accomplished for the scorpio output class.

**Comment by bartgol** [comment]
As a side bonus, this would make the unit tests simpler (and, therefore, easier to maintain), since there would be no need to create a grids manager.
