### ISSUE TITLE
[AD] Issues/PR's for Luca to audit

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1113]
This is a list I am creating to track PR's or Issues that may come up in the next couple of weeks that could benefit from having @bartgol take a look at them.

In particular I will list those Issues that may have been resolved, or merged to master that normally would have had Luca as a reviewer.  I anticipate a handful of changes going in the next few weeks and I thought this might be a good way to get Luca up to speed on what has happened once he gets back.

- [ ] #1112 
- [x] #1108  - solved by #1118
- [ ] #1115 
- [ ] #1119 
- [ ] #1120

**Comment by bartgol** [comment]
Thanks for making it easier for me to catch up!
