### ISSUE TITLE
Remove all use of `get_view` from Field, and possibly remove that method too.

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1145]
This is causing way too many bugs, especially since we started allowing subfields (which, for technical reasons, do not store the subfield view inside, but the view of the 'parent' field).

The last example is the field property checks: the checks are implemented in a rank-agnostic way, by looping over the entries in `field.get_view()`. This is already somewhat wrong due to the fact that the view might contain padding (for pack sizes larger than 1), but it's flat out bad in case of subfields.

I'm adding this to v1, since it's showed up twice in the last week (slowing down development, while tracking down seemingly odd behaviors).

Note: I'm not pointing the finger and blaming people for these bugs. It's just a confusing thing, which I always wanted to get rid of, and is now showing its dangerousness in all its might.

**Comment by bartgol** [comment]
@AaronDonahue, @tcclevenger , @jeff-cohere What would you think if, in the process, I renamed the `get_reshaped_view<T>()` to `get_view<T>()`? Since this would be the only method that allows to extract the view, it would seem natural to just call it `get_view`...

**Comment by tcclevenger** [comment]
> @AaronDonahue, @tcclevenger , @jeff-cohere What would you think if, in the process, I renamed the `get_reshaped_view<T>()` to `get_view<T>()`? Since this would be the only method that allows to extract the view, it would seem natural to just call it `get_view`...

I agree.

**Comment by AaronDonahue** [comment]
Yes, I agree too.  `get_reshaped_view` implies a different kind of `get_view` may be available somewhere.
