### ISSUE TITLE
Reorganize structure of build directory

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1159]
After discussing with @AaronDonahue and @PeterCaldwell , it seems that the way we organize our build folder is a bit confusing. In particular, some of the tests executables are foudn inside the `src` subfolder instead of the `tests` one. That's b/c cmake, by default, mirrors the src tree into the build tree. When scream started, it was decided to keep a `tests` folder inside each parametrization folder (and, by extension, inside each src code folder, like `src/share/tests`). I'm not super fond of this choice, but such was the initial design.

There are two options:
- Change the structure of our repo, moving all our tests folders inside the `tests` one (organizing them by where they come from). Pros: it's a standard approach across projects (and would remove most of the `if (NOT SCREAM_LIB_ONLY)` occurrences). Cons: tests source code would not be shipped "near" the corresponding lib src code.
- Keep the repo structure, but add tests subdirectories so that their binary tree location is inside the main tests folder. Pros: we keep the same structure as we have now, and keep tests source code near the corrsponding lib src code. Cons: it is a tad confusing (at least to me) when I run cmake and the build tree is not a mirror of the souce one.

For the former approach, we could do:
```
scream-src
  - src
    - control
    - dynamics
    - physics
       - p3
       - shoc
       ...
    - share
  - tests
    - unit
      - control
      - dynamics
      - physics
        - p3
        - shoc
        ...
      - share
    - driver_tests
      - coupled
        - homme_physics
      - uncoupled
        - homme
        - p3
        ...
```
For the second approach, we could make it so that such a structure is created in the build directory, but keeping the current source tree organization.

The tree I sketched out is just the first option I could think of, and can obviously be changed (in either approach).

It would be nice to hear the opinion of as many developers as possible on a) which approach to use, b) how to organize the tests folder (either in the repo, or only in the build folder), and c) whether this is even an issue for you or not.

**Comment by jgfouca** [comment]
I don't have a strong opinion, but I kind of like how things are now. Having the tests close to the source code reduces directory navigation and makes recursive operations like grep easy to do for all package-related things.

**Comment by bartgol** [comment]
I think the main concern is that future users (e.g., once scream is merged in e3sm) might find it confusing to find a test exec inside `bld/src/...`, the point being that one expects no execs in a folder called 'src'.

Tests close to their source are appealing, and common in projects that are divided in "packages". I guess if scream's `src` folder was called `packages` (I'm not promoting this name, just using it as an example), I assume there would be no confusion: `bld/packages/pkg_name/tests` contains test for the package `$pkg_name`, while `bld/tests` contains tests for the project as a whole.

Option 2 allows to leave the source tree as is, simply rearranging the build tree.

**Comment by jeff-cohere** [comment]
In HAERO, we have a `haero/` folder that contains the core of the library, including headers. This has the benefit of the `packages` approach you mention above, and it also lets us use `haero/` as a "folder" for our include files in a way that remains intact both when you're developing the library and when you're compiling a program that uses the library wherever it's installed. If there's a drawback, it's the oddity of a `haero` directory right inside the top-level `haero` folder (if you don't rename it when you do a `git clone`). But I haven't heard anyone complaining about that.

This approach seems to make sense for HAERO, because we support a library and a few tools (in their own subdirectories off the top of the tree). But our source tree is a lot more shallow than SCREAM's is at the moment, and might require some work on the source tree.

**Comment by bartgol** [comment]
I've seen that approach, and I almost used it for EKAT. I ended up putting all source in `$ekat_root/src/ekat`, since I thought that something like `$ekat_root/ekat` might be confusing, especially since for many people `$ekat_root=ekat`(e.g., we would have `externals/ekat/ekat/...` when seen as scream submodule).

For scream, having all src code in a `scream` folder in the toplevel scream folder would have a similar consequence: `components/scream/scream/...`.

I'm thinking the easiest solution here is to simply specify a non-standard binary dir when adding tests subfolders. E.g., in `src/physics/p3/CMakeLists.txt`, we could do

```
if (NOT SCREAM_LIB_ONLY)
  add_subdirectory(tests ${SCREAM_BINARY_DIR}/tests/physics/p3)
endif()
```
The downside of this is that we need to make sure we don't accidentally pick the same bin folder for two different src folders (but it's a fairly small risk, and caught immediately at the first build).

**Comment by brhillman** [comment]
I don't feel too strongly about this but maybe I'm one of the few who actually like how we have it laid out now so I'll make an argument in favor of what we have. I think it at least separates tests that I think of as "scream-specific-tests" vs "package-specific-tests". For example, for radiation, we have some utility functions that are mostly agnostic to how the radiation code is being used, these go in `components/scream/src/physics/rrtmgp/tests`, and they are mostly if not entirely independent of anything scream-specific, and I try to maintain independence from other scream libraries/headers here. But things that are scream infrastructure specific, or specific to how the radiation code is used within scream will go in `components/scream/tests/rrtmgp` (i.e., the coupled tests, the AD standalone test).

**Comment by bartgol** [comment]
@brhillman do you care about the fact that some test execs are in the `$bld_dir/src/` tree?

I think the feedback seems to be "keep the source tree as is". I want to understand if the same holds for the build tree. If so, we can close this.

**Comment by brhillman** [comment]
It doesn't bother me, but I'm willing to be convinced to be bothered by it. I think it maybe threw me at first, but I guess I just got used to the fact that the bld tree mimics the source tree, and now I actually find it kind of nice because I know where to find the exact tests I'm looking for. But again, I don't really feel strongly either way.

**Comment by bartgol** [comment]
You should not be convinced that something is not working well for you. If it works for you, it means we don't have to change, and can spend time on other stuff.

@PeterCaldwell @AaronDonahue I think the consensus seems to be that "things work fine the way they are". I am going to close this issue, so we don't steal any more time to people. If you think this is a discussion that should be continued, feel free to re-open.
