### ISSUE TITLE
Investigate column GlobalID in HOMME

### ISSUE THREAD

**Issue by tcclevenger** [E3SM-Project/scream#1178]
In Homme, `elem%GlobalID` do not appear to be monotonically assigned over ranks (i.e. rank0's element ids are not necessarily less than those of rank1). Also, a ranks set of ids are not necessarily a continuous block (ex. `rank0: 1-32,81-96`; `rank1: 33-80`). This is affecting the HOMME interface, particularly with how column area is computed (not previously caught by checks). Also could have I/O ramifications.

I've added the "bug " label. TBC,  this is a bug in the HOMME interface code, not in HOMME.

**Comment by tcclevenger** [comment]
The PR https://github.com/E3SM-Project/scream/pull/1180 addresses the indexing issues in area/lat/lon computation in the interface.

**Comment by bartgol** [comment]
Additionally, #1195 fixes column GIDs to match what CIME expects. @singhbalwinder confirmed that now the outputed lat/lon coord fields match the ones from EAM. I think this issue can be considered closed. @tcclevenger if you think there's more to do, feel free to reopen.
