### ISSUE TITLE
Implement a lenient column positivity check

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1184]
In Homme, it can happen (at least during random unit testing, we're not sure whether this can realistically happen with real data) that the output tracers array Q has some negative entries. The magnitude of these negative entries is very small, roughly of the order of few epsilon times the max of the tracer over the whole column.

A robust way to check for negative values, while allowing these small entries to happen would be to craft a new FieldPropertyCheck that (using a scalar 3d field for the example):

- computes `m(icol) = max(abs(f(icol,:)))`
- check that `f(icol,k) > -factor*epsilon*m(icol)` (where factor can default to 0, to turn this into a Positivity check).
- if repair is allowed, repair f as `f = std::max(0, f);`

Notice that this check differs quite a bit from FieldPositivityCheck and also from FieldWithinIntervalCheck. Mainly, the difference is that the threshold (`-factor*epsilon*m(icol)`) is different from the repair value. In other words, we have three bands: 1) f>0, all good, no repair needed, 2) -thresh<f<0: bad, but we can repair to 0, 3) f<-thresh: ugly, error out.

**Comment by ambrad** [comment]
@bartgol still relevant?

**Comment by bartgol** [comment]
We already introduced 2 sets of bounds. Although that's only for the case where one is willing to repair the field, I think that's enough to cover the scenario that this issue was intended to fix.
