### ISSUE TITLE
Make usage of share folder from main e3sm more consistent/robust.

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1188]
Some modules like `shr_const_mod` are provided by F90 files in `$repo_root/share/util`. That folder (**unfortuntately**) does not create a library, and is intended to be used by host cmake code (it simply adds sources).

 At the same time, however, homme has copies of some of those modules in `components/homme/utils/csm_share`. In `src/dynamics/homme/CMakeLists.txt` we _remove_ the `csm_share` files from homme's source files while creating the dyn lib, but _only if_ we are in a CIME build, in which case we just link the csm share lib.
 
 However, rrtmgp is building the files from `$repo_root/share/util` in a library, which may cause conflict in standalone mode (where homme also builds its internal copy).
 
I think we should build the F90 share lib in standalone mode, and never use homme's internal copy of those files (I don't think homme wants it anymore, and probably would be fine removing the folder, and using e3sm's version, but someone needs to do that change...).

**Comment by ambrad** [comment]
@bartgol is this issue still relevant?

**Comment by bartgol** [comment]
I don't think so, since we changed homme to link against the share library, rather than use its own copies. Closing.
