### ISSUE TITLE
Idea for Field internal storage.

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1189]
Random 5pm thought: what if we templated Field just on a bool (const vs non-const), and internally always store a view of `char*` (or `const char*`). After all, we have to specify the data type when extracting the view, so there's no bonus in storing a view of `Real*` vs a view of `char*`...

This way, we could store integer data in fields, as well as store both single and double precision inside the same FieldManager.

Bonus: we would be able to store FieldPropertyCheck's inside the FieldHeader, since they would no longer require to know the scalar type of the field.

I haven't formulated all my thoughts yet, but wanted to put this up there for discussion.

@jeff-cohere @tcclevenger @AaronDonahue

**Comment by bartgol** [comment]
Side product: testing integer I/O would be easier if we could have integer fields.

**Comment by tcclevenger** [comment]
What does it mean to store `Real` data in a view of `char*`?

I definitely like the idea of being able to mix int/single/double precision in the same FM (I believe this has already been an issue? Can't remember..).

**Comment by jeff-cohere** [comment]
If I'm not mistaken, Luca is referring to `char*` as a canonical way to refer to byte arrays in C/C++.

If we have to specify the data type anyway, this doesn't add any additional complexity. And I can think of several uses for these other types. So I'm for it.

**Comment by bartgol** [comment]
We would always allocate the view as `View<T*>`, with T being whatever _actual_ data type you need (int, float, double, whatever), and _then_ store it in a `View<char*>`. This is similar to C's using `void*` to pass around pointers of an unknown type (later casted to the correct type based on some flags). Unfortunately, `View` cannot use `void*` as internal pointer, since it needs to declare a reference type to the view entries. So we could use char*.

When you extract the view from a Field, we already specify the scalar type (as a part of the data type), so we can reinterpret cast on the fly. We could even store the actual scalar type name (obtained via ekat::ScalarTraits), to make sure you don't as for a view of completely unrelated type.

The drawback of this would be that all atm procs would now have to specify (inside the FieldRequest) what kind of scalar type T they need (or, at least, sizeof(T)), so that it can be set in the alloc prop when the field is registered in the FM. Perhaps it could be another template arg to `add_field`, so something like `add_field<Required, Real>(...)`.

**Comment by bartgol** [comment]
Thanks Jeff. Yes, I should have probably be more clear: I meant use `char*` as a "universal" pointer, the way it's often done in C/C++ libraries.

**Comment by jeff-cohere** [comment]
I think `add_field<Required, Real>(...)` (and friends) sounds good enough to try.

**Comment by bartgol** [comment]
#1370 Addressed this.
