### ISSUE TITLE
P3: potential non-B4B code modifications that emerged during refactor 

### ISSUE THREAD

**Issue by pressel** [E3SM-Project/scream#121]
In the process of refactoring P3 into a large number of subroutines, a few potential opportunities to improve the code have emerged that would be non-B4B. In order to keep this refactor B4B we have delayed these improvements. This issue is to record those opportunities. 

1. Remove first iteration droplet activation in droplet_activation subroutine since P3 no longer handles super-saturation. (https://github.com/E3SM-Project/scream/pull/119#discussion_r308316378)

2. Change threshold for qc_not_small from 1e-8 to qsmall in cloud_water_autoconversion subroutine. (https://github.com/E3SM-Project/scream/pull/119#discussion_r308319083)

**Comment by AaronDonahue** [comment]
@PeterCaldwell , is this still an open issue?  I can't seem to see any bugfixes mentioned in this issue and the PR that is linked has been merged.  Can we close this?
