### ISSUE TITLE
Erratic testing beavior on weaver

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1211]
There seem to be issues with testing on weaver. Mainly, there are two sub-issues.

1. The nightly testing sometimes reports an internal compiler error, when building `atmosphere_microphysics.cpp`. This behavior has been recorded when running on weaver1 and weaver4 compute nodes, but did not happen on weaver2 (no data for the other ones), although on weaver2 we observed bad initial state for Homme (negative dp/dphi/vtheta in EOS during init). The internal compiler error does *not* happen for AT runs. I am not sure what builds these errors belong to (nightlies jobs use the same folder every time, so I can't go and inspect different builds outputs separately).
2. The AT runs are failing the `homme_standalone_ut_np1_omp1` test in release build on weaver1, due to negative/nan layer thickness in homme, either after 3 or 6 timesteps. On weaver2, on top of the release failure, the same bad initial state as in the nightly test runs is observed for the full_debug build.

For the 2nd sub-issue: when running on weaver1, after the failure occurs, running test-all-scream with the `--quick-rerun` option, or simply running the test manually from the folder, does not yield a failure anymore.

**Comment by AaronDonahue** [comment]
@bartgol , I've experienced the #1 error myself on the CPU machine quartz, and I can consistently recreate it.  It only occurs for me when I try to run the homme_stand_alone executable through `gdb`.  I haven't complained about it because I've been able to debug on lassen so it hasn't been an issue.  

You can try and see if your local CPU machine does the same thing.

**Comment by bartgol** [comment]
@AaronDonahue which part of 1? I kind of smushed a few in there. I doubt you get the compiler error, so I'm guessing you get the neg dp/dph/vtheta during initialization?

**Comment by AaronDonahue** [comment]
Yes, this error:
```
           1  ABORTING WITH ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0
```

**Comment by bartgol** [comment]
@jgfouca I think we fixed the erratic behavior once we upgraded to gcc 8.5, so I'm going to close this. Feel free to re-open if you think this is not fully solved.
