### ISSUE TITLE
Recompute z_int/dz on-the-fly

### ISSUE THREAD

**Issue by tcclevenger** [E3SM-Project/scream#1220]
Each ATM process should recompute dz/z_int on-the-fly and z_int should be removed from IC files.

**Comment by AaronDonahue** [comment]
I think this has been resolved.

**Comment by tcclevenger** [comment]
Sorry @AaronDonahue, I didn't seem to want to close any of these....

**Comment by AaronDonahue** [comment]
no worries @tcclevenger , I was just doing a quick audit to see if I could get the issues size down.  I closed a few ancient ones of my own ;-)
