### ISSUE TITLE
Typo in timer name causes many warnings to e3sm.log

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1228]
In `components/eam/src/dynamics/se/dyn_comp.F90` it looks like we have a typo in the timer name for the `stop`:

```
           call t_startf('prim_run_subcycle')
           call prim_run_subcycle(dyn_state%elem,hybrid,nets,nete,&
               tstep, single_column_in, TimeLevel, hvcoord, n)
           call t_stopf('prim_run_sybcycle') !<---
```

Which all still works, but will print many (depending on how often this is called, of course) warnings to e3sm.log. Simulation still OK, but might be slowed down and the timing data in that timer will be inaccurate.

```
1: GPTLstopf thread 0: timer for a:prim_run_sybcycle had not been started.
1: GPTLstopf thread 5: timer for a:prim_run_sybcycle had not been started.
1: GPTLstopf thread 1: timer for a:prim_run_sybcycle had not been started.
```

Last night I ran a 48-step test of our next ne1024 case using the new repo to find this. It printed that message 8250179 times, so that's about 170k lines of output that are written to e3sm.log every step -- likely would have caused some issues.

I just verified this error is not in e3sm. It looks like just a typo during the last upstream merge and is only in scream repo.

**Comment by bartgol** [comment]
This looks like an issue for E3SM, rather than scream. Can I transfer it there?

**Comment by ndkeen** [comment]
I noted above that the bug is not in e3sm repo.

**Comment by bartgol** [comment]
Ah, I grepped it in my e3sm local repo, but should have updated it first. Sorry about that. I missed your last line.

**Comment by crterai** [comment]
I don't know how much time is spent writing these warnings but it might be the reason why some of our tests are not completing in time. Is it a quick PR of just fixing the typo or is there anything more to it?
