### ISSUE TITLE
Pull DSE calculation out of shoc internals and just in the interface

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1249]
Currently SHOC computes the DSE internally but really only needs the temperature.  It does this because EAM uses DSE (or possibly enthalpy) instead of temperature as a state variable.

In SCREAM we will be using temperature.

In keeping with the plan to have processes not be focused on a particular model the task is to extract the DSE calculations from inside SHOC and move them out to the interface.  That way EAM and SCREAM can each deal with temperature as they want to and shoc is independent of either.

**Comment by AaronDonahue** [comment]
@bogensch , I made this issue 3 years ago, but can't really remember what its about.  Do you happen to know if this is still a thing?  Should I close this issue?

**Comment by bogensch** [comment]
close
