### ISSUE TITLE
Roll back to a single FieldManager

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1254]
The reason we split the single FM into one FM per grid was related to issues creating the a copy of the tracers group on the dyn grid. However, recent changes in the group request logic have simplified that (or, at least, fixed it, and made it more robust). We can now safely roll back to one FM to rule them all, which would have the benefit of hiding some FM-related code currently inside the AD.

**Comment by AaronDonahue** [comment]
@bartgol , have we resolved this?

**Comment by bartgol** [comment]
No, this is something I would like to implement at some point, but I will likely never will.
