### ISSUE TITLE
Turn SurfaceCoupling into an atmosphere process

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1255]
This is not required, but would have a few benefits:

- The DAG construction would not have to treat the SC as a special case
- The initialization of atm inputs would be more linear, without the need to check if an atm input is by chance imported by the SC.
- The SC export method would not have to check whether this is an AD run.

**Comment by PeterCaldwell** [comment]
I'm psyched about this change. I think it would make the code much more logical/intuitive for new users.

**Comment by oksanaguba** [comment]
Is it the same as removing application of QFLX and SHFLX from clubb/shoc? I would vote for such change, too. it is a better design to separate it from clubb and would give us more control. not sure if fluxes need to be sub cycled and diffused by clubb if they are too strong.

**Comment by bartgol** [comment]
@oksanaguba This is unrelated to that, I think. This issue is only a perspective change of the software design. That said, we can always change what happens inside the SC class, to incorporate more/less stuff.

**Comment by PeterCaldwell** [comment]
Luca is right - this is just about software engineering. I'm not sure surface fluxes can be separated from clubb/shoc since they serve as the lower boundary condition for those schemes.

**Comment by whannah1** [comment]
Does this mean that surface fluxes would be calculated in the atmosphere? Or would the surface component models still own these calculations?

**Comment by tcclevenger** [comment]
From what I see so far, nothing should really change from a surface model perspective. Currently inside 
`scream/src/mct-coupling/atm_comp_mct.F90` function `atm_init_mct()`, we initialize the atm (`scream_init_atm()`) and then initialize the current `SurfaceCoupling` class (`scream_setup_surface_coupling()`) where we pass in data pointers from the surface model to import/export to/from. Then scream's `AtmosphereDriver` is responsible for call `do_import()` and `do_export()` before an after each atm process is called. 

All this issue would change is that we would not have a separate `SurfaceCoupling` class, and instead it would be itself an atm process, and therefore setup is taken care of in `scream_init_atm()` and calling import/export function is still done by the driver, but done by calling the atm processes, not independently calling the `SurfaceCoupling` class.
