### ISSUE TITLE
Handling non-FM variables output

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1265]
The typical suite of output variables from a full E3SM run include variables that are not, strictly speaking, needed for simulation.  As such, in our current implementation these variables would not be included in the Field Manager and would be off-limits to use for I/O.

We will want to think about how to handle providing these variables as output in our SCREAM runs.  A few considerations:

1.  These variables tend to be process dependent, meaning that they are constructed in EAM in the interface of particular processes.  So as the model matures we would expect a number of these to be added to the process interfaces.
2. These variables are not always needed.  So we can't assume that a variable added for diagnostic purposes will always be needed.

This is a v1.1 task because for now in v1 production we are still largely in control of the code and many of the variables we want to use for output are already in the field manager.

As we approach v1.1 we will want to think about how we want to empower developers to design their own diagnostics without making the field manager bloated and/or filling it with a number of unused variables.

**Comment by bartgol** [comment]
I don't understand. Why not adding a field to the field manager, if you want it in the output file? The metadata is not that big, so it's not that bad to add fields to the FM.

As a aide note, the feature discussed in #985  could be used to ensure these output-only vars are "exclusive".

**Comment by bartgol** [comment]
A quick look plus a back of the envelope calculation shows that a Field is storing about 60-70 ptrs/ints (including the ptr to the data), as well as 3 strings. I don't think this is a huge overhead from the storage point of view compared to using bare views from a buffer. And the infrastructure to output fields is already built in in our framework.

Imho, it might be easier to stick with FM variables. But I'm open to discuss alternative (simple) solutions.

**Comment by AaronDonahue** [comment]
okay cool, so we don't actually have to store the memory for the data in the field?  I guess not, we just store a pointer to the memory, but don't we lock that memory so no one else can use it?

**Comment by PeterCaldwell** [comment]
To be clear, this is an idea for v1.1. Our initial impl will definitely follow the Luca option of just stuffing everything we want to output into the FM. I think once we get experience with this simpler solution, it will become clearer whether we need a more sophisticated approach for output variables. I think the worry is that EAM has *thousands* of variables floating around which people can write out if they feel like, but are usually ignored. Keeping all these potential variables around will have a bit of memory impact, but also just clutters the code up. Keeping the FM lean and easy to query might end up being prudent. But let's wait for it to become a problem before we fix it.

**Comment by AaronDonahue** [comment]
Do we want to keep this issue open?  @bartgol , @PeterCaldwell ?  I think the only thing left to consider (or at least keep track of) is the wishlist desire to have all diagnostics share the same memory buffer.  We could create a separate issue just for that.

**Comment by bartgol** [comment]
I think we can close for now. If Peter disagrees, he can reopen.

**Comment by PeterCaldwell** [comment]
Agreed. This discussion feels pretty stale at this point.
