### ISSUE TITLE
Add test for correctness of grid data views

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1287]
We need to have a test that guarantees that the grid data views stored in the grid structures are correct, regardless of the number of MPI ranks.

A while ago we had an issue with the DynamicsDrivenGridsManager building grids with the wrong dof numbering (discovered by @singhbalwinder ). Ever since, a couple of sizable PRs were merged, addressing issues related to phys/dyn grids dofs ids/coords. But we never created a test that ensures dofs information is accurate, for single and multi rank runs.

Note: the test should be done when homme is building the grid (a full cubed sphere grid). It should run in serial, then in parallel, and compare information (e.g., by saving to a nc file and using cprnc).

**Comment by AaronDonahue** [comment]
Have we addressed this @bartgol ?

**Comment by bartgol** [comment]
No, we never implemented such a test. However, we do save lat/lon/area in our NC files. And we do run tests with different number of ranks, so we definitely test (indirectly) that geometry data is rank-independent. I also think the geo data is likely correct, since all the eval time constantly uses lat/lon in postprocessing (I assume), and there hasn't been anyone raising a brow. Granted, that's not a perfect test, but I'm willing to close this for now.
