### ISSUE TITLE
P3: Changes to microphysics needed

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#130]
There are a series of variables present in both P3 and MG microphysics that should be changed or added.  This is a list of those tasks:

1) Introduce diagnostic output variables that record the rate of conversion between water phases.  This should address issue #122 
    a) vapor_liquid_exchange, all conversion to/from vapor (qv) from/to liquid (qc+qr)
    b) vapor_ice_exchange, all conversion to/from vapor from/to ice (qitot)
    c) liquid_ice_exchange, all conversion to/from liquid from/to ice
    d) vapor_snow_exchange, all conversion to/from vapor from/to snow (qs), *MG Only*

2) Audit the calculation of precipitation efficiency in MG.
3) Add a calculation of precipitation efficiency in P3.
4) Remove qcheti as a source term for rimed ice (qirim), see issue #123 .

**Comment by AaronDonahue** [comment]
@hassanbeydoun , is it true that all of these changes have been made?  Are they still needed?

**Comment by bartgol** [comment]
@AaronDonahue @hassanbeydoun Can we close this?

**Comment by AaronDonahue** [comment]
I don't think have all been made, but they may no longer be needed, now a year later.  I'll ping Hassan to see if we can close this issue.

**Comment by hassanbeydoun** [comment]
@bartgol @AaronDonahue we can close this.
