### ISSUE TITLE
For AtmosphereInput, allow reading into host views without pre-building them.

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1320]
When using an AtmosphereInput class to read into host views (rather than Fields from a FM), we still need to create views and layouts beforehand. This seems silly, since the information about the field extents is already in the nc file. Allowing to not precompute views, would turn code like

```
std::map<std::string,host_view_1d> views;
std::map<std::string,FieldLayout> layouts;
for (auto& name : field_names) {
   views[name] = host_view_1d("",dim0,..,dimN);
   layouts[name] = FieldLayout({tag1,...,tagN},{dim0,...,dimN});
}
AtmosphereInput atm_in (comm,params,grid,views,layout);
atm_in.read_variables();
```
into something like
```
AtmosphereInput atm_in (comm,params,grid); // Still need grid, so we know which dofs are read on this rank
atm_in.read_variables();
views = atm_in.get_host_views();
```

Note: code like [this](https://github.com/E3SM-Project/scream/blob/71ec97dc328e6faf47910eb5471fca322749aa9b/components/scream/src/physics/spa/spa_functions_impl.hpp#L486) in SPA could be turned from 30+ lines to 3 lines.

**Comment by AaronDonahue** [comment]
@bartgol , is this still a wishlist item?
