### ISSUE TITLE
Improve register_physics.hpp logic

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1322]
Right now, the header pulls in all the physics packages. So far, except for unit testing, it's fine, since we don't have multiple choices for each parametrization. But if/when the SCREAM AD becomes the main atm driver for e3sm, this might make `register_physics.hpp` unusable.

**A possible approach**

First, rename all files avoiding the generic prefix `atmosphere`. E.g., `atmosphere_macrophysics.*pp` -> `shoc_atm_process.*pp`. Then, make the inclusion and registration of processes guarded by ifdefs:
```
#ifdef SCREAM_HAS_SHOC
#include "physics/shoc/shoc_atm_process.hpp
#endif
#ifdef SCREAM_HAS_CLUBB
#include "physics/clubb/clubb_atm_process.hpp
#endif
#ifdef SCREAM_HAS_P3
#include "physics/p3/p3_atm_process.hpp
#endif
...
void register_physics () {
  auto& proc_factory = AtmosphereProcessFactory::instance();
#ifdef SCREAM_HAS_SHOC
  proc_factory.register_product("shoc",&create_atmosphere_process<SHOCMacrophysics>);
#endif
#ifdef SCREAM_HAS_CLUBB
  proc_factory.register_product("clubb",&create_atmosphere_process<CLUBBMacrophysics>);
#endif
...
}
```
Now, in order to be able to call `register_physics()` from the test setup, we need to forward the macros we want, so that they are defined when `register_physics.hpp` is parsed. The naive approach would be to add the compile definitions when building the tests. A much more powerful (and less intrusive) method is to have the libraries define the macro. So

Inside p3's CMakeLists.txt:
```
add_library(p3 ...)
target_compile_definitions (p3 PUBLIC SCREAM_HAS_P3)
```
Inside the test (or lib) CMakeLists.txt:
```
# use scream's macro to create test
CreateUnitTest (my_test ... LIBS "p3;share;...")

# create a library for mct
add_library (atm ...)
target_link_libraries (atm PUBLIC p3)
```
Done. Nothing else is required, since `target_link_libraries(<target> PUBLIC p3)` already propagates the PUBLIC (and INTERFACE) compile definition (and more) of the `p3` library target to the exec/lib currently built. So when building the `atm` library, `SCREAM_HAS_P3` _will_ be defined, so that `register_physics.hpp` is registering P3 in the factory.

This approach has the advantage of leaving the downstream code as lightweight as possible. Moreover, in CIME optic, one could change a parametrization name in the case, and have SCREAM's cmake machinery do everything. E.g., in the mct_coupling folder, we might have

```
if ("${SCREAM_MACROPHYSICS_PKG}" STREQUAL "SHOC")
  target_link_libraries (atm PUBLIC shoc)
elseif ("${SCREAM_MACROPHYSICS_PKG}" STREQUAL "CLUBB")
  target_link_libraries (atm PUBLIC clubb)
endif()
```
or even
```
target_link_libraries (atm PUBLIC ${SCREAM_MACROPHYSICS_PKG})
```
(assuming we know (or already checked) that it expands to a valid/supported macrophysics pkg name), without having to change implementation of the `atm` lib source code.

**Comment by AaronDonahue** [comment]
May be related to #2225
