### ISSUE TITLE
IO input silently continues when the nc file has the wrong dimensions

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1329]
You can read an IC file with N columns while running a grid with M columns, and IO never complains. We need to figure out why the code does not crash, and then make it crash if the dimensions of a file in the nc file do not match the dimensions of the scream field.

**Comment by AaronDonahue** [comment]
@bartgol , will #2802 solve this?

**Comment by bartgol** [comment]
No, it wouldn't. But I am adding some extra checks inside AtmosphereInput, to ensure dims match. So if you use AtmosphereInput, you should get the right checks. However, if you use the raw scorpio interfaces, there is no check. I.e., you will be able to do 
```
scorpio::register_file("my_file", scorpio::FileMode::Read);
std::vector<double> data (100);
scorpio::read_var("my_file","my_var",data.data());
```
Notice that there's no guarantee that the var in the file has size 100. It's not that bad though: 
 - if the var has size larger than 100, this will crap out (you'll write out of bounds in the data pointer),
 - if the var has size smaller than 100, only a portion of the data vector will be written on.

**Comment by AaronDonahue** [comment]
@bartgol , thank you for the explanation.  Do we still consider this issue an issue?  Do we have enough checks in place to feel pretty comfortable?  If I recall, this issue came up when it was fairly easy to manipulate the number of column arbitrarily.

**Comment by bartgol** [comment]
We can close it when the pioc PR gets merged then.
