### ISSUE TITLE
Introduce cmake logic to create baselines for scream

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#133]
Currently, the homme standalone test is considered 'passed' if it runs. We should add some bfb checks via cprnc (like in homme) to also check correctness.

The way homme creates baselines is a bit involved, and perhaps we can do a bit better and avoid bash scripts, staying 100% in the cmake realm.

Possible steps:
- have a 'SCREAM_BASELINES_DIR` variable. If this is 'master', do not set the variable, otherwise, set it to the build dir of master (or whatever blessed version we have)
- create a cmake script that runs the test and runs cprnc upon completion.
- if baselines are present, run cmake script (run+cprnc), otherwise simply run (and save baselines)

**Comment by PeterCaldwell** [comment]
@bartgol - is this issue still relevant?

**Comment by bartgol** [comment]
I think it goes together with the baseline test macro issue we closed earlier today. This will make sense only once we have scorpio output working in scream. I'll close for now.
