### ISSUE TITLE
Default write geo data to output file

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1331]
This task is to set up the output class to write all geo data to the output file by default.

This will require some work on the output class:

- [ ] Expose the geo data map to the output class.  Note, this will make it simpler to write all geo data that is available without creating an extra list in the output class.
- [ ] Make it possible for the output class to write raw data.  Currently the output class writes using only field managed data.
- [ ] Make writing the geo data ON by default? Do we want to allow runtime option to suppress it?  Is it even big enough in a relative sense to matter?

**Comment by PeterCaldwell** [comment]
@AaronDonahue - by geo data, are you talking about the lat and lon for each data point? And are we just talking about the centers of the cells, or also all 4 corners of the grid? Also, why did you decide we need to do this now? I kind of agree this is a good idea, but part of me has always thought that E3SM should create a library of grid info for each grid we create and just expect users to link to that file whenever they do a run. It seems wasteful to include static info in every output file. What do other folks think?

**Comment by bartgol** [comment]
On one hand, Peter is right that is a wast to write stuff that is static in every output file. OTOH, it might make some post processing scripting easier, since all info is in one nc file.

I really have no preference here.

**Comment by AaronDonahue** [comment]
@PeterCaldwell, yes that's what I was referring to. This issue came out of chatting with Ben who was doing some post-processing on SCREAM runs and wanted the lat and lon. 

I don't want to do a bunch of extra effort that isn't needed, but I was under the impression that typical EAM output provides this info by default and as Luca said there may be post-processing scripts which assume it's available. 

Does E3SM-diags need geo data in the raw output?

**Comment by PeterCaldwell** [comment]
Closed via https://github.com/E3SM-Project/scream/pull/2128
