### ISSUE TITLE
SHOC interface (cpp code) surface flux index bug

### ISSUE THREAD

**Issue by bogensch** [E3SM-Project/scream#1333]
https://github.com/E3SM-Project/scream/blob/4b5842e40bc0108a765e405c932087279a542e58/components/scream/src/physics/shoc/atmosphere_macrophysics.hpp#L162-L165

When computing the surface fluxes in the SHOC cpp interface there appears to be a index bug when attempting to use the interface level density (rho_i) at the surface.  Instead of "rrho_i(i,nlev_v)[nlev_p]" this needs to be "rrho_i(i,nlevi_v)[nlevi_p]" for the lines referenced.  The current cpp implementation is at odds with the F90 implementation and using density at the wrong level.

Of course, with my ignorance of cpp code, there is the possibility I am misreading something?...

**Comment by bartgol** [comment]
I think you're right. Tagging @tcclevenger who worked on this stuff.

**Comment by tcclevenger** [comment]
You are exactly right.
