### ISSUE TITLE
Make U_10M and V_10M model outputs

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1335]
Currently we only have WINDSPEED_10M, UBOT, and VBOT (10m wind *speed* and bottom level winds) as outputs. This screws things up when we want 10m wind speed interpolated to coarser resolution (because obs typically has U10M and V10M at that coarser resolution already and interpolating a vector then computing its magnitude gives a different answer than interpolating the average speed). We can back out U10M and V10M from all 3 outputs, but it would be better to just output U10M and V10M directly. My understanding is that this isn't that hard, but also isn't trivial. So we will save it for v1.1.

**Comment by bartgol** [comment]
This is now possible via the `X_at_Ym` diagnostic output. See #2513
