### ISSUE TITLE
Write output on coarser grid

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1339]
It would be convenient/cool if we could write ne1024 output out to file after remapping it to coarser horizontal resolution. This would save disk space and therefore allow us to write out more variables. Likewise, it would be cool to only write out a subset of vertical levels (e.g. don't bother writing levels in the sponge layer).

**Comment by AaronDonahue** [comment]
Solved by #2051 , at least for coarser horizontal.  Still need different vertical.

**Comment by bartgol** [comment]
Aren't we able to vertically reinterpolate? I guess it would be preferable to do interpolation after coarsening, but other than that, it should be possible no? I mean, if one asks for the vertically remapped field diagnostic, and specifies a remapper file, the AD should already do both vertical and horiz interpolation (in that order), no?
