### ISSUE TITLE
adjust_ps=.false. is not tested in cxx code

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/scream#1343]
SCREAM v0.1 (Fortran code) runs with adjust_ps=.false.
CXX code has only been tested with adjust_ps=.true.  

E3SM should also migrate to adjust_ps=.false., but this is on hold in order to preserve buggy V2 behavior.  

Current CXX vs Fortran bfb tests are in the E3SM repository using standalone HOMME.   The CXX code for adjust_ps=.false. needs to be tested.  In order to test this in the E3SM repository, we need a way to turn on adjust_ps=.false.  in standalone HOMME.  some options:

1. control this feature with a namelist variable.  We dont want namelist variables that turn on bugs, so we then have a second PR to remove this once the V2 freeze is lifted and the fix makes it into e3sm.      
2.  Test the CXX code by hand, until the V2 code freeze is lifted and this change makes it into E3SM
3.  Test this feature with in the SCREAM repo
4.  Add a #define to allow tests to turn this bugfix on in the E3SM repo

**Comment by bartgol** [comment]
@mt5555 we are still hard-coding `adjust_ps=true` in Hommexx. Do we need to start making this a configurable param in hommexx?

**Comment by mt5555** [comment]
Fortran code has:

#ifdef SCREAM
     adjust_ps=.false.  ! Lagrangian case can support adjusting dp3d or ps                                                 
#else
     adjust_ps=.true.   ! Lagrangian case can support adjusting dp3d or ps                                                 
#endif

And thus hommexx should also have adjust_ps=false - not sure how it can pass BFB C++ vs Fortran if adjust_ps=-true?

**Comment by PeterCaldwell** [comment]
Can you remind me what adjust_ps means?

**Comment by mt5555** [comment]
adjust_ps=false:   mass fluxes from physics are applied locally (removing the mass from the layer it came from)

adjust_ps=true:   mass fluxes are smeared over the whole column and removed from the surface pressure

adjust_ps=true preserves buggy behavior of E3SM.   it has minor impacts, so we never attempted to get this into v3

**Comment by mt5555** [comment]
this is one of these nuisance bug fixes.  it should have been fixed a long time ago, but the hassle of evaluating it combined with the small impact means it's always a low priority. 

It looks like it is in SCREAM v0.1, but the bugfix never made it into SCREAM v1.  

We shouldn't try and get this into CESS, since there are already too many PRs trying to make it in for CESS.

But lets fix this once the CESS runs have started and master is open again

**Comment by ndkeen** [comment]
I would think that changes that are not expected to cause a problem would be OK. We don't need to be BFB right now with previous runs. But will let others decide.  Yea I was hoping to never see `adjust_ps` again.

**Comment by AaronDonahue** [comment]
@tcclevenger , was this issue fixed by your PR https://github.com/E3SM-Project/E3SM/pull/6063?

**Comment by tcclevenger** [comment]
@AaronDonahue I should be, CIME cases in EAMxx require `dt_remap_factor>1` which as of that PR means `adjust_ps=false`. @mt5555 are you good with closing?
