### ISSUE TITLE
Issue with interface between MCT and SCREAM

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1357]
There is an issue when running the F2000SCREAMv1 compset where the coupling between MCT and SCREAM isn't working.  In particular, the fluxes passed into SCREAM are uniformly zero.  Note, the fluxes passed out of SCREAM to MCT are non-zero.

There may still be some settings in the mct coupling code `atm_comp_mct.F90` from when we were treating the atmosphere as a "dead" model.

This issue is most certainly contributing to the instability we are observing in the SCREAMv1 runs that forms after about a day.

**Comment by AaronDonahue** [comment]
We have already found one obvious issue.  The line `call seq_infodata_PutData(infodata, atm_prognostic=.true.)` is missing from the `atm_comp_mct.F90` code in SCREAM.  Adding that line in fixes the issue with only zero fluxes coming into the atmosphere.  But exposes a new issue, an error between ATM and ELM
```
 check_downscale_consistency ERROR: column-level forcing differs from gridcell-l
 evel forcing for urban point
 c, g =         3119         201
 ENDRUN:
 ERROR in atm2lndMod.F90 at line 440
 ```

**Comment by bartgol** [comment]
Looks like #1358 fixed this. @AaronDonahue , please reopen if I'm wrong.
