### ISSUE TITLE
SHOC property tests are still calling F90 code

### ISSUE THREAD

**Issue by bogensch** [E3SM-Project/scream#1376]
It appears that most (if not all... I haven't examined every test file) SHOC property tests are still calling the F90 code and not the cpp implementation.  This should be modified before the F90 code is abandoned to ensure property tests are being called on the relevant cpp code.

**Comment by bartgol** [comment]
@tcclevenger is this still the case?

**Comment by tcclevenger** [comment]
@bartgol Looks that way, we just need to transpose the input data and call the `shoc_*_f()` function. Should be easy. I can find some time this week to put a PR together if you want.

**Comment by bartgol** [comment]
I don't think it's a priority. I was just going through our issues to see what v1 dev issues were still a thing, trying to find some suitable ones for a new eamxx dev.

**Comment by PeterCaldwell** [comment]
Agreed this isn't urgent, but it will mean that once DP can be run in C++ mode and we get rid of F90 support, all of our SHOC testing will disappear unless we fix this. So worth keeping open and doing, but not worth putting ahead of anything else we're already doing or is urgent.

**Comment by AaronDonahue** [comment]
@jgfouca , I suspect that your upcoming work on dropping F90 support for SHOC will also address this issue.  Can you tag this as fixed when that PR goes in?

**Comment by jgfouca** [comment]
@AaronDonahue , yep! I am addressing this exact issue.

**Comment by jgfouca** [comment]
Fixed.
