### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [E3SM-Project/scream#1379]
I suggest adding the topics `climate`, `atmosphere` in the About section.

**Comment by bartgol** [comment]
> I suggest adding the topics `climate`, `atmosphere` in the About section.

@Beliavsky could you articulate more? What "About section" are you referring to?

**Comment by Beliavsky** [comment]
You can topics such as `climate` in the About section on the right at https://github.com/E3SM-Project/E3SM . GitHub describes how to add topics at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by bartgol** [comment]
Ah, ok, so you were talking about the github repo. I'll ping @PeterCaldwell  for this kind of "front page" issues. :)

**Comment by PeterCaldwell** [comment]
Ok, done. Thanks for the suggestion!
