### ISSUE TITLE
Spa remap file and data file are not fetched with the GetInputFile macro

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1420]
All our init files are in `${SCREAM_INPUT_ROOT}/inputdata/atm/scream/`, while the spa remap/data files are in `${SCREAM_INPUT_ROOT}/inputdata/scream/`. I'm not sure if we should move them to `${SCREAM_INPUT_ROOT}/inputdata/atm/scream/data` or keep them where they are. I would vote for moving them. That way, we could keep the `GetInputFile` macro as is, with no mods whatsoever.

On testing platform, these files are present because we had manually added them, but they should put in the e3sm input data server(s), and downloaded if needed.

@jgfouca I assigned this to you, cause you wrote the infrastructure and I thought this might be a quick fix for you. If you're swamped, let me know, and I can take a stab at it.

**Comment by jgfouca** [comment]
@bartgol , yes, I can do this.
