### ISSUE TITLE
Add newline after warning message

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1434]
In `src/physics/spa/atmosphere_prescribed_aerosol.cpp`, can we add a newline to the warning messages?

```
  if (m_spa_remap_file == no_filename) {
    printf("WARNING: SPA Remap File has been set to 'NONE', assuming that SPA data and simulation are on the same grid - skipping horizontal interpolation");
```

Either add `\n` or change to cout.

**Comment by bartgol** [comment]
Yeah, lack of `\n` at the end of a printf can be annoying. I would also split that very long message over 2-3 lines...

**Comment by ndkeen** [comment]
Resolved
