### ISSUE TITLE
Unable to build with compiler other than GNU

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1444]
I wanted to try the nvidia compiler on Perlmutter, but the `-Weffc++` is not a valid flag for that compiler.

I see in `externals/ekat/extern/yaml-cpp/CMakeLists.txt`

```
target_compile_options(yaml-cpp
  PRIVATE
    $<${not-msvc}:-Wall -Wextra -Wshadow -Weffc++ -Wno-long-long>
```

Are we going to honor the machine/compiler settings that are set up in CIME?

**Comment by bartgol** [comment]
For now, scream cleans the flags cmake vars, and sets them itself. Yes, at some point we should make scream append to whatever CIME already set.

As for this case, we should modify yaml-cpp/CMakeLists.txt and add that flag only for GCC. You can try this hack, and see if it works. If it does, we can open up a PR in ekat
```
target_compile_options(yaml-cpp
  PRIVATE
    $<$<AND:${not-msvc},$<CXX_COMPILER_ID:GNU>>:-Wall -Wextra -Wshadow -Weffc++ -Wno-long-long>
```

**Comment by ndkeen** [comment]
OK I think that gets further.  I now hit

```
NVFORTRAN-W-0155-MODULE PROCEDURE not defined: shr_infnan_isnan_double (/pscratch/sd/n/ndk/wacmy/s12-mar1/share/util/shr_strconvert_mod.F90: 166)
NVFORTRAN-W-0155-MODULE PROCEDURE not defined: shr_infnan_isnan_real (/pscratch/sd/n/ndk/wacmy/s12-mar1/share/util/shr_strconvert_mod.F90: 166)
```

which I might have encountered before and need to remember what I did

**Comment by bartgol** [comment]
I've hit that in the past too. IIRC, the problem was the lack of `CPRXYZ` in the compiler definitions. The top of the file, uses those to set HAVE_IEEE_ARITHMETICS.

**Comment by ndkeen** [comment]
Yep, I needed some of the same flags used in cime_config to build scream. Once I did that and made a few hacks to get around some other issues, I can build with nvidia compiler `nvidiagpu`. However, the run hits runtime fail due to a known issues I've been working with NERSC about in other apps.

**Comment by bartgol** [comment]
That's great! I think we can close this issue then (since we can build), and possibly open new ones for run issues?

**Comment by ndkeen** [comment]
Sure... but there are still several issues that need to be better addressed to build with nvidia. Some of the issues I hit will require changes to build. Conditional building based on compiler. Some of which is already in cime_config and if we are trying to merge... So OK to close this generic issue and make more specific ones?

**Comment by bartgol** [comment]
Ah, right. We can make a PR with the changes, and make that PR close this issue when it's merged.

**Comment by ndkeen** [comment]
Closing old issue.
