### ISSUE TITLE
Process Name vs. Process Type

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1449]
This thought occurred to me during our conversation about runtime options, yaml parsing, xml parsing, etc.

Currently when subcycling we use a process group if we want to subcycle 2+ processes together.  One of the entries is "Process Name", which has to be "Group".  If we have multiple groups of tightly subcycled processes they will all have the name "Group".  Which makes it difficult for something like `yamlchange` to find the proper named process and change the sub-category.

See #1371 for an example.

Can we have something like `Process Name` which can be any unique string and `Process Type` which would be "Group", "SHOC", etc.

**Comment by bartgol** [comment]
Yeah, that's doable.
