### ISSUE TITLE
A test for p3 main consistently fails on blake

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1452]
For the single precision build, with the proper random number generator seed, we can consistently reproduce a fail on blake.

To reproduce:

-  run `scripts/test-all-scream -m blake -t sp --baseline-dir AUTO --config-only`
-  run `eval $(scripts/scream-env-cmd blake)`
- `cd ctest-build/full_sp_debug/src/physics/p3/tests`
- `make -j64`
- `ctest -R setup` (to pre-build p3 tables)
- ./p3_tests --rng-seed 4126930317`

You should see an error of the form

```
/ascldap/users/e3sm-jenkins/blake/workspace/SCREAM_NightlyTests_Blake/scream/components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp:218: FAILED:
  REQUIRE( isds_fortran[i].qi[k] == isds_cxx[i].qi[k] )
with expansion:
  0.0f == 0.0f
```

This might just be an unlucky input, but the fact that it produces actual number (rather than NaN) that are non-bfb between f90 and cxx makes me a bit suspicious, that some operation in p3 uses something like `1.0` instead of `sp(1.0)` to create a floating point constant.

**Comment by bartgol** [comment]
@jgfouca @tcclevenger I tagged you guys cause I know you were involved with P3 development. If you can't work on this, please, let me know.

**Comment by tcclevenger** [comment]
@bartgol I'll try and look at this today.

**Comment by tcclevenger** [comment]
@bartgol I can also trigger it on my workstation with 1 thread, so I'm guessing it is something that can be fixed.

**Comment by jgfouca** [comment]
@bartgol , I don't think we've seen this failure in a long time. Is this issue close-able?

**Comment by bartgol** [comment]
Well, it only failed with a certain seed. Let me try it again first.

**Comment by bartgol** [comment]
@jgfouca I still see the same error with the rng seed reported in the message. Although it's probably just a bad luck input, I'd like to keep this open, in case someone stumbles on this again in the future.

**Comment by AaronDonahue** [comment]
I think we have a few of these fails due to a particular seed.  It may be good to have an open issue that records them all.

**Comment by AaronDonahue** [comment]
Actually, it looks like we might: https://github.com/E3SM-Project/scream/issues/1506
