### ISSUE TITLE
Spa unit tests fail in release mode

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1463]
The spa_main_test fails in release mode, due to roundoff diffs:

```
  REQUIRE( ccn3_h(dof_i,kpack)[kidx] == ccn3_beg(dof_i,kpack_pad)[kidx_pad] )
with expansion:
  3.9652588367 == 3.9652588367
```

The test also failed in the PR unit test. It's worth to point out that, if the AT encounters a fail in standalone tests, it sill proceeds to run CIME tests. However, on the PR page, the standalone tests result are hidden, and one might miss info regarding standalone tests output.

@AaronDonahue I'm gonna assign you, since you are the spa wizard.

@jgfouca we should improve jenkins output, so that standalone fails are not hidden. To be fair,
```
+ [[ 100 != 0 ]]
+ fails=1+1
+ [[ 2 > 0 ]]
+ exit 1
```
is showing that 2 commands failed (and in this case they are standalone and v1 testing), but we could have the script state things clearly at the end.

**Comment by AaronDonahue** [comment]
@bartgol , thanks! I'm on it
