### ISSUE TITLE
Improve Jenkins output

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1464]
Right now, only mappy can do tests other than standalone (test-all-scream). In particular, it can do v0/v1 tests and scripts tests (PR and nightlies), as well as valgrind tests (nightlies only). However, in case of, say, v1 tests, the results of test-all-scream are so far back in the log, that the snipped reported by the Autotester does not include them.

If all tests are expected to pass, then this is fine, since a FAIL on mappy will trigger investigations. However, in case of expected diffs, it might be easy to miss the lines

```
+ [[ 2 > 0 ]]
+ exit 1
```
which state that 2 test suites failed (e.g., test-all-scream and v1 tests).

It would be much easier if our jenkins scripts stored some incremental message whenever a testsuite fails, and print it at the end, to make it clear to the reader what testing failed. E.g., we could do something like

```
failed_testsuites=""
...
  # Run scream stand-alone tests (SA)
  if [ $test_SA -eq 1 ]; then
    ./scripts/gather-all-data "./scripts/test-all-scream --baseline-dir $BASELINES_DIR \$compiler -c EKAT_DISABLE_TPL_WARNINGS=ON $AUTOTESTER_CMAKE -p -i -m \$machine $SUBMIT" -l -m $SCREAM_MACHINE
    if [[ $? != 0 ]]; then
      fails=$fails+1;
      failed_testsuites += "test-all-scream"
   fi
...
      if [[ $test_v0 == 1 ]]; then
        ../../cime/scripts/create_test e3sm_scream -c -b master
        if [[ $? != 0 ]]; then
          fails=$fails+1;
          failed_testuites += ", SCREAMv0"
        fi
      fi
...
  if [[ $fails > 0 ]]; then
      echo "Failed testsuites: $failed_testsuites"
      exit 1
  fi
```

Ideally, it would be great if we could also print which testsuites in test-all-scream had a fail, and in what tests, but that's more of a convenience feature. This issue is trying to prevent merging failing PRs just because we were expecting diffs in v0/v1...

**Comment by jgfouca** [comment]
Good idea. I can take this one.
