### ISSUE TITLE
EAMxx should gather the timestep from the component coupler in CIME builds

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1468]
Creating this issue based on a conversation in Slack:

Currently, the only way to control the timestep in EAMxx is through the `scream_input.yaml` file, which makes it possible for a user to change the EAMxx timestep without updating the actual atmosphere timestep.  And vice versa.  This task is two-fold:

1. We should hide the Time Step option in `scream_input.yaml` in CIME based runs, so as to not confuse the user into thinking this is where we change the timestep.
2. We should have EAMxx gather the timestep in CIME based runs, possibly following the EAM-F90 approach.  Which can be traced here:

https://github.com/E3SM-Project/E3SM/blob/master/components/eam/src/utils/time_manager.F90#L680

using this module

https://github.com/E3SM-Project/E3SM/blob/master/share/esmf_wrf_timemgr/ESMF.F90

[ESMF.F90](https://github.com/E3SM-Project/E3SM/blob/master/share/esmf_wrf_timemgr/ESMF.F90)

**Comment by bartgol** [comment]
Actually, we are already using the timestep from the coupler. The `Time Stepping` section is only used for standalone runs. Coupled runs grab dt precisely doing what you described (see [here](https://github.com/E3SM-Project/scream/blob/3dd1358d081a9799af8c826d1200b0fa22700b6b/components/scream/src/mct_coupling/atm_comp_mct.F90#L199)).
