### ISSUE TITLE
Field alloc prop should store alloc size as a size_t

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1480]
Currently, `FieldAllocProp` uses `int` for all sizes. While this is ok for stuff like `m_last_extent` or `m_pack_size_max`, it is clearly not ok for the allocation size, since large arrays can easily lead to more than 2GB allocations.

**Comment by ndkeen** [comment]
Yes I'm pretty sure what Luca is doing here would change the integer types for certain vars to avoid the integer overflow in the allocations.

**Comment by bartgol** [comment]
@PeterCaldwell well, it is a priority if we need to fit _large_ cases on a _small_ number of MPI ranks. But I guess I can take this on now, since it should be quick (famous last words).

**Comment by ndkeen** [comment]
I verified that with these changes, I can run a couple of the the same ne4 cases that I could before (no surprise).
And that with ne30 and 1 MPI, it now goes beyond where it was stopping (with whacky allocation error) and now stops at the same location as it does with 2 MPI's. So I think you fixed it!
