### ISSUE TITLE
For screamv1 cime cases, encountered "requested too large team size" in DEBUG

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1485]
With `SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.perlmutter_gnugpu`

```
0: CalcWorkPerBlock: Total blocks:          1 Ice blocks:          1 IceFree blocks:          0 Land blocks:          0
0: Atmosphere step = 0; model time = 0001-01-01 00:00:00
0: terminate called after throwing an instance of 'std::logic_error'
0:   what():  /pscratch/sd/n/ndk/wacmy/ndk_scream_PM-update/components/scream/src/dynamics/homme/atmosphere_dynamics.cpp:417: FAIL:
0: false
0: Kokkos::Impl::ParallelFor< Cuda > requested too large team size.
0: Traceback functionality not available
0:
```
Luca suggested we make a change to `components/homme/src/share/cxx/RemapFunctor.hpp` as a work-around for this issue and that's what I've been using for PM runs. In fact, I found I also needed this for certain non-DEBUG runs.
The change involves:
```
  template<typename Tag>
  using TeamPolicyType = Kokkos::TeamPolicy<ExecSpace,Kokkos::LaunchBounds<512,1>,Tag>;
```

Should we make a work-around PR or investigate more what's happening?

Note to build with gnu v10 on Perlmutter, need a new flag that is in here https://github.com/E3SM-Project/scream/pull/1484

**Comment by bartgol** [comment]
This has happened way too many times in Homme. I think we need to start offering a (cmake-configurable) way in homme for making all team policies have the `LaunchBounds` template argument. I can work on that, but I'm busy this week, and off next week.

**Comment by ndkeen** [comment]
Verified I still see this with master of May9th using `SMS_D_Ld1_P4x1.ne4_ne4.F2000SCREAMv1.perlmutter_gnugpu`.

**Comment by ndkeen** [comment]
@AaronDonahue this is the issue I made a couple of months ago regarding team size too large. I've only seen this on PM gpu's. But I know that a similar work-around was used in the past on other machines.

**Comment by ambrad** [comment]
@jgfouca in case you haven't seen this issue, here's at least one spot that needs modification.

**Comment by jgfouca** [comment]
Thanks @ambrad !

**Comment by ambrad** [comment]
Fixed by E3SM PR 5046
