### ISSUE TITLE
Initial runs with SMS_D_Ld1_P1x1.ne4_ne4.F2000SCREAMv1.perlmutter_gnugpu.scream-5min_ts (ie ATM_NCPL=288)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1488]
In https://github.com/E3SM-Project/scream/issues/1443, I was testing with incorrect timestep (was using current default of ATM_NCPL=12). We want to use NCPL=288 or 5 min. The testname `SMS_D_Ld1_P1x1.ne4_ne4.F2000SCREAMv1.perlmutter_gnugpu.scream-5min_ts` has a modifier that doesn't exist right now, but it's to be clear that to repeat this test, need to `xmlchange ATM_NCPL=288` or create the test modifier (or make it default).

With both `F2000SCREAMv1` and `F2000-SCREAMv1-AQP1`, in DEBUG (and with GPU) it appears OK -- ran out of time after completing 4 days each.

With OPT builds:

With `F2000SCREAMv1`, using 4 MPI & 4 GPU, and OPT build I see:
```
0: Atmosphere step = 19; model time = 0001-01-01 01:35:00
2: Negative (or nan) layer thickness detected, aborting!
```

With `F2000-SCREAMv1-AQP1`, using 1 MPI & 1 GPU, and OPT build I see:
```
0: Atmosphere step = 20; model time = 0001-01-01 01:40:00
0: Negative (or nan) layer thickness detected, aborting!
```

And just like with my tests using incorrect NCPL, if I build OPT, but set Kokkos cmake debug vars, I can get the tests to complete 5 days. That's with either compset and with 1 or 4 MPI's (on GPUs).

**Comment by bartgol** [comment]
I'm trying to figure out why opt would cause negative thickness, but can't think of any good reason.

**Comment by ndkeen** [comment]
With todays master of March 23rd (which includes upstream merge), I'm able to run this ne4 test with GPU and CPU for 5 days without error.  With DEBUG and OPT*.

**Comment by PeterCaldwell** [comment]
Is this with or without output?

**Comment by PeterCaldwell** [comment]
Note also @tcclevenger 's comment on #1443 (why the heck do we have 2 almost identical issues?) that it looks like pressure profiles weren't getting assigned on GPUs on Summit for some reason... Maybe relevant for your current error?

**Comment by ndkeen** [comment]
All of these recent ne4 tests do include output.  This issue is different in that it is using 288 steps per day.

**Comment by tcclevenger** [comment]
I think there is an issue with the `columnops::column_scan()` when packsize=1. I have fully found out the reason yet. But this would affect only GPU runs.

**Comment by ndkeen** [comment]
Conrad: you might try again with updated master as I'm no longer seeing the errors in the first comment.

**Comment by ndkeen** [comment]
As it was suggested that we might not be running on the gpu's of PM, I did basic profiling and I see time spent in cuda calls:

```
 Time(%)  Total Time (ns)  Num Calls   Avg (ns)   Med (ns)   Min (ns)  Max (ns)   StdDev (ns)            Name          
 -------  ---------------  ---------  ----------  ---------  --------  ---------  -----------  ------------------------
    53.8      23644457214     246351     95978.7    17053.0      1683   35741665     480979.4  cudaStreamSynchronize   
    15.3       6708764225     132521     50624.2     6603.0      2815   35173703     253268.2  cudaMemcpyAsync         
    13.3       5828014396      62039     93941.1    16531.0       190   34104025     239517.9  cudaMemcpy              
     5.8       2548251125     517359      4925.5     4408.0      3336   38876894      79105.7  cudaLaunchKernel        
     2.6       1157302712     336386      3440.4     2525.0      1653   35179093     151286.3  cudaDeviceSynchronize   
     1.7        750077206      11073     67739.3     7856.0      2555    2554663     115013.6  cudaMalloc              
     1.7        742159646          8  92769955.8   155799.5    129870  741035543  261938853.9  cudaHostRegister        
     1.5        675687286     781254       864.9      481.0       390   35096394      89890.3  cudaEventQuery          
     1.3        558268087     122407      4560.8     3737.0      2866   26546392     104807.9  cudaMemcpyToSymbolAsync 
     1.1        461438647      11073     41672.4     6824.0      3617    2021016      67695.4  cudaFree                
     1.0        438906320     187210      2344.5     2135.0       601   35737968     131634.7  cudaEventRecord         
     0.8        333966092     122407      2728.3     2114.0      1522   31332626     117611.7  cudaEventSynchronize    
```

**Comment by tcclevenger** [comment]
@ndkeen With the fixes in https://github.com/E3SM-Project/scream/pull/1526 (which should automerge soon) I was able to run on Summit for 1/2 a month (It only timed out, so should go farther). Not sure if this will fix the issue you are seeing, but it might.

**Comment by ndkeen** [comment]
I wasn't seeing any issues?

**Comment by ndkeen** [comment]
Closing this generic issue as I think we've squared away all of the obvious problems and can make more specific issues.
