### ISSUE TITLE
Need useful error message when initial condition file has inconsistent # of levels with value in env_build.xml

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1490]
Noel spent a bunch of time chasing down a failure in HOMME that was ultimately caused by using an atm initial condition file with 128 levels but having built assuming the model had 72 layers. It seems like it would be trivial to add a REQUIRE statement that checks the size of the vertical dimension in the initial condition netcdf file and throws an error if it isn't right.

**Comment by bartgol** [comment]
This can be generalized, probably. Our grids have already been built when we feed the IC file to the AD. So we could also check that the number of columns is the right one. In general, we should check as many dimensions as possible.

**Comment by AaronDonahue** [comment]
@bartgol has this been resolved?

**Comment by bartgol** [comment]
We do get an error message as the input file is read, since the layout of the FM field does not match the one from the NC file. I don't recall the exact error message, but I think it clearly shows what the issue is. I'm going to close.
