### ISSUE TITLE
Integer overflow with variables holding sizes with ne30 (perhaps change some int to size_t)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1492]
With ne30, there is at least one location where we need a long instead of int to represent memory size.

`components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp`

Printing value of mem during this function:
```
0: ndk RRTMGPRadiation::init_buffers mymem=   395814688 after 2d
0: ndk RRTMGPRadiation::init_buffers mymem=   594499664 after 3d arrays
0: ndk RRTMGPRadiation::init_buffers mymem= -2110987824 after 3d nswbands
0: ndk RRTMGPRadiation::init_buffers mymem= -1202713648 after 3d nlwbands
0: ndk RRTMGPRadiation::init_buffers mymem= -1191826800 after 3d surf alb
0: ndk RRTMGPRadiation::init_buffers mymem=   431868816 after 3d aero -- all
0: ndk RRTMGPRadiation::init_buffers used_mem=431868816
```

And then there is an assert that is OK because *both* locations are integer overflowing:

```
  int used_mem = (reinterpret_cast<Real*>(mem) - buffer_manager.get_memory())*sizeof(Real);
  EKAT_REQUIRE_MSG(used_mem==requested_buffer_size_in_bytes(), "Error! Used memory != requested memory for RRTMGPRadiation.");
```

This may or may not be impacting other things

**Comment by PeterCaldwell** [comment]
I think @bartgol is on vacation all this week and @jgfouca is on vacation today (monday) so we might not get a quick answer, but this is the 2nd time we've seen integer overflow in assigning memory size and I'm wondering whether we need a campaign to find and upgrade *all* integer memory references to 64B...

**Comment by ndkeen** [comment]
I can make a branch with these changes -- it's all pretty straight-forward (especially for authors), but I suspect there will be some opinions on how best to do it.  It may also be what's causing the failure with GPU as may need to be consistent with the gators.

**Comment by PeterCaldwell** [comment]
That would be great. I'd actually suggest you not just make a branch, but make a WIP PR (i.e. start the title of the PR with "[WIP]: " which causes the autotester to not try to test or integrate it. That way we can easily poke through the code modifications you propose and comment on them...

**Comment by ndkeen** [comment]
I made a branch here `ndk/scream/use-size_t-for-allocation-vars` that attempts to use `size_t` in a few places associated with storing a size.

**Comment by ndkeen** [comment]
I thought of the branch as an experiment which I can verify gets me beyond an issue. I can make a PR, but it might be someone would prefer re-working. Should I add `[WIP]:` to the title?

**Comment by PeterCaldwell** [comment]
Yeah, why don't you make a PR with [WIP]: in the title and we can contemplate it for a day or two to decide whether we want to change things...

**Comment by AaronDonahue** [comment]
@ndkeen , We also have a "label" that is "WIP".  I think on one of our calls we decided to move towards using the label rather than the string in the PR title.  The label is a guarantee that the AutoTester will treat it as WIP, while the string has to be just right to get caught.

**Comment by ndkeen** [comment]
I was trying to reproduce this issue with clean clone and I think the error I get (with cpu, DEBUG, and only 1 MPI) is below, which I realize doesn't exactly sound like an integer overflow problem, but when I make the size_t changes, it does allow the run to complete 2 steps.

```
0: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
0:
0: Backtrace for this error:
0: #0  0x14ac486e83df in ???
0: #1  0x2f23179 in operator()
0:      at /pscratch/sd/n/ndk/wacmy/s15-mar22/components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp:348
0: #2  0x2f27028 in parallel_for_cpu_serial<scream::rrtmgp::rrtmgp_sw(int, int, GasOpticsRRTMGP&, real2d&, real2d&, real2d&, real2d&, GasConcs&, real2d&, real2d&, real1d&, OpticalProps2str&, OpticalProps2str&, FluxesByband&, scream::Real, bool)::<lambda(int, int, int)> >
0:      at /pscratch/sd/n/ndk/wacmy/s15-mar22/externals/YAKL/YAKL_parallel_for_fortran.h:662
0: #3  0x2f26a06 in parallel_for<scream::rrtmgp::rrtmgp_sw(int, int, GasOpticsRRTMGP&, real2d&, real2d&, real2d&, real2d&, GasConcs&, real2d&, real2d&, real1d&, OpticalProps2str&, OpticalProps2str&, FluxesByband&, scream::Real, bool)::<lambda(int, int, int)>, 3, false>
0:      at /pscratch/sd/n/ndk/wacmy/s15-mar22/externals/YAKL/YAKL_parallel_for_fortran.h:880
0: #4  0x2f23ed9 in _ZN6scream6rrtmgp9rrtmgp_swEiiR15GasOpticsRRTMGPRN4yakl5ArrayIdLi2ELi1ELi2EEES6_S6_S6_R8GasConcsS6_S6_RNS4_IdLi1ELi1ELi2EEER16OpticalProps2strSC_R12FluxesBybanddb
0:      at /pscratch/sd/n/ndk/wacmy/s15-mar22/components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp:346
0: #5  0x2f2284a in _ZN6scream6rrtmgp11rrtmgp_mainEiiRN4yakl5ArrayIdLi2ELi1ELi2EEES4_S4_S4_R8GasConcsS4_S4_RNS2_IdLi1ELi1ELi2EEES4_S4_S4_S4_RNS2_IdLi3ELi1ELi2EEESA_SA_SA_S4_S4_S4_S4_S4_SA_SA_SA_SA_SA_db
0:      at /pscratch/sd/n/ndk/wacmy/s15-mar22/components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp:246
0: #6  0x2f06f6f in _ZN6scream15RRTMGPRadiation8run_implEi
```
