### ISSUE TITLE
The netcdf output files written by scream v1 may need different format

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1494]
When I try to run ne30 with SPA, I get an error similar to:

```
0: ndk check_netcdf() file=SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np8.0001-01-01.001000.nc status=0
0:  ndk calling PIO_enddef with file=SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np8.0001-01-01.001000.nc or=SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np8.0001-01-01.001000.nc
0: ndk check_netcdf() file=SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np8.0001-01-01.001000.nc status=-62
0: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (/pscratch/sd/n/ndk/wacmy/s14-mar12/externals/scorpio/src/clib/pioc_support.c: 3376)
0: Obtained 10 stack frames.
```

Note the addition of prints to write the netcdf code is interacting with. It *might* be because the output
files we write aren't in preferred format?

```
cori10% ncdump -k SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np4.0001-01-01.001000.nc 
classic
```

I can verify that turning off output will allow the job to complete 2 steps, but that doesn't mean the issue is the netcdf format.

```
In data/scream_input.yaml comment following:
  # The parameters for I/O control
  Scorpio:
    Output YAML Files: ["data/scream_output.yaml"]
```

**Comment by jayeshkrishna** [comment]
@ndkeen this error is most likely due to the NetCDF format used for the runs. You need to change the output NetCDF format to 64bit_data (cdf5).
```
./xmlchange PIO_NETCDF_FORMAT=“64bit_data”
```

**Comment by ndkeen** [comment]
Currently, a scream v1 cime case will have:

```
login26% xmq PIO_NETCDF_FORMAT
        PIO_NETCDF_FORMAT: ['CPL:64bit_offset', 'ATM:64bit_offset', 'LND:64bit_offset', 'ICE:64bit_offset', 'OCN:64bit_offset', 'ROF:64bit_offset', 'GLC:64bit_offset', 'WAV:64bit_offset', 'IAC:64bit_offset', 'ESP:64bit_offset']
```

And as we aren't fully hooked up to cime, not surprising that this setting may not be honored right now.
Aaron made the following issue which may solve: https://github.com/E3SM-Project/scream/issues/1495

Ben noted: "I wouldn't have thought we would need different format (like cdf5) for ne30, I would think that should certainly fit into the constraints of the netcdf3/classic format"

Which may also be true. Certainly in the past we didn't run into trouble until using ne256 or ne512. 

I also wanted to clarify that I can currently write output of the form `SCREAMv1_output_hydrostatic.INSTANT....npX.0001-01-01.001000.nc` when I run without SPA, which is how I verified the `classic` format above.  But with SPA, there is something else happening as this file is present, but is only 32 bytes.

**Comment by ndkeen** [comment]
Fixed with https://github.com/E3SM-Project/scream/pull/1500
