### ISSUE TITLE
PIO_NETCDF_FORMAT flag not making into EAMxx interface

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1495]
There is an environment field in CIME named `PIO_NETCDF_FORMAT` which controls the output format of PIO files.  This flag is meant to be passed into individual models so that they can create PIO files with the appropriate format.  This is not happening in EAMxx, so it defaults to 32bit

We need to update the interface so gather this information and pass it appropriately to the PIO initialization.  In this case, as a flag to `pio_createfile`.

This will probably require looking at how EAM gathers the PIO format from MCT, and then recreating that in EAMxx.

**Comment by bartgol** [comment]
This should have been fixed by #1534 .
