### ISSUE TITLE
HommeDynamics::set_computed_group_impl is called after prim_init_data_structures_f90 returns

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1497]
HommeDynamics::set_computed_group_impl, which sets qsize in both C++ and F90 theta-l(_kokkos) code, is called after prim_init_data_structures_f90 returns, and thus in particular after prim_init1_buffers. That means prim_init1 code that uses qsize to initialize data structures uses qsize_d rather than qsize, since qsize defaults to qsize_d in control_mod.

One can work around this lack of delayed information in a number of ways, but I'm posting this as an issue in case it's viewed as a design issue.

**Comment by bartgol** [comment]
Ok, I think this can be solved by moving the call to `prim_init1_buffers` out of the `prim_init_data_structures_f90`. Unfortunately, unless we turn the AD upside down, there's no way for Homme to know qsize at construction time. Therefore, any initialization routine that needs the exact tracers count (qsize) must be delayed until the call to initialize_impl.

I will issue a small PR to fix this.

**Comment by bartgol** [comment]
Fixed by #1517
