### ISSUE TITLE
Clean up redundant flags in scream_scorpio_interface.F90

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1504]
scream_scorpio_interface.F90 has preprocessor directive `CIME_BUILD` and input variable `local` which both seem to do the same thing: use CIME-specified values if this is a CIME build and use a set of hard-coded values if not. @AaronDonahue created the `local` flag and @bartgol created the preprocessor. The resulting code is really hard to understand. We should clean this up, but the existing code works so this isn't a high priority.

https://github.com/E3SM-Project/scream/blob/673c02c8ce702198f579166870dfda67a5754e6d/components/scream/src/share/io/scream_scorpio_interface.F90#L692

**Comment by bartgol** [comment]
Fixed by #1534
