### ISSUE TITLE
Use -DRRTMGP_EXPENSIVE_CHECKS by default in debug builds

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1518]
I'm a bit embarrassed I don't know how to do this. When we compile a CIME v1 run in debug mode, we'd like to add the `-DRRTMGP_EXPENSIVE_CHECKS` flag to make sure we catch out-of-bounds variables and other nastiness. Is there an easy wan to do this?

**Comment by ndkeen** [comment]
This flag helped us find a FP issue higher up. I started a branch, but then realized there are several ways to go about this.
For example:
a) we could add the flag to our CXX builds (or even just in radiation) for DEBUG.
b) we could add source change to simply define this var when NDEBUG is not set.
c) could come up with a CMAKE var to do it, which might still end up needing to do (a)

I did verify that for the ne30 tests, I can build OPT with and without this flag and not see a measurable diff in performance.

**Comment by jgfouca** [comment]
@bartgol , i like that approach too

**Comment by ndkeen** [comment]
Another reminder that I think it would be great for each component/package/module to have its own debug macro -- whatever its called, but NOT rely on the compiler generated `NDEBUG`.  Such that we could have cmake macros that can toggle debug for each one.  That is, I can build OPT, but turn on the radiation debug checks -- no problem.  Also, as noted before, it could make reading the code easier as we could do
```
#ifdef SCREAM_DEBUG
  // code under debug
```

Ben says radiation package already uses that macro for this purpose, so it could be the same (or renamed).

**Comment by PeterCaldwell** [comment]
Update: @brhillman pointed out that RRTMGP_EXPENSIVE_CHECKS just implements the same "check variables before and after radiation is called" functionality that SCREAM has in precondition and postcondition checks. So it makes more sense to NOT make these checks the default and instead to expand pre- and post-condition checks to the radiation interface (which @wlin7 is already working on). 

Thus I'm going to close this issue.
