### ISSUE TITLE
Allow passing cpu affinity to test-all-scream 

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1519]
This is more of a wish list issue, but I think it would help a lot on mappy, where there seems to always be someone running tests.

Premise: on mappy, when jenkins (or other users) are running CIME tests, the CPU is not fully loaded, usually. It's common to see free PUs (e.g., 12-31,44-63,76-95,108-127). In that case, running `test-all-scream` (TAS) will cause CPU overload, since TAS always runs on PUs [0,$make_parallel_level) (for make, and similarly for testing), clashing with any other test currently running.

My proposal is to add a new flag to TAS: `--cpu-affinity` (or something like that), which tells TAS which PUs to use. So doing
```
./scripts/test-all-scream --cpu-affinity 12-31,44-63 -m mappy -p
```
would only use the specified PUs. TAS will still use taskset internally, to place different builds on different PUs, but will make sure to only use PUs _within_ the affinity mask passed in. Internally, TAS would have ot build an array of ints, specifying the PUs ids that it can use. If running with `-p`, TAS will partition this array across builds. Finally, when running ctest via taskset, TAS will specify as affinity mask `-c arr[0],...,arr[$this_test_parallel_lev-1]`.

Note: if this option is used, then make parallel level is automatically set to the total number of PUs provided by the mask. If running on CPU machines, this should also set the test parallel level (for GPU machines, the cpu affinity should not impact the test || level, since tests run on different resources).

**Comment by jgfouca** [comment]
Now that we have slurm on happy, we can switch test-all-scream over to using srun (and expecting test-all-scream to run as a batch submission).
