### ISSUE TITLE
Fix time-hog IO routines

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1522]
As of now, IO is a time hog for two reasons:

- We tally the averages on host, instead of doing it on device
- We tally the averages also for INSTANT output on non-write steps (a complete waste of time)

Edit: I'm adding another reason, still part of being a time-hog. @ndkeen reported that a 2.5GB file takes about 20s to write, which is very slow. We should make sure that 1) we use scorpio correctly (e.g., set up rearrangers, sub-communicator, and whatnot), and 2) we waste as little time as possible in our interface layer to scorpio.

**Comment by PeterCaldwell** [comment]
Thanks for checking into this Luca! Are these things easy to fix?

**Comment by bartgol** [comment]
> Thanks for checking into this Luca! Are these things easy to fix?

Credit to @ndkeen for profiling our runs, and zeroing out on the bottle necks.

As for the 2 points above, the 2nd is a quick fix (just add an if statement at the beginning). The first one might take more rework of the output class, but hopefully not too hard.

**Comment by bartgol** [comment]
@AaronDonahue I think it's time we get our hands dirty with PIO_STRIDE in scream...
