### ISSUE TITLE
Need to implement/test restart for CIME cases

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1530]
We do have a `model_restart` test for standalone SCREAM, but nothing for CIME cases. I suspect we still need to add some code to our mct interface layer to trigger a restart.

One extra item to keep in mind, which came up in #1526 : make sure the export fields that we init to 0 are _not_ set to 0 in a restarted run, where (presumably) the cpl will take care of loading their initial values.

**Comment by PeterCaldwell** [comment]
@ndkeen just did an ne30 CIME run for me yesterday where he had output every other step and restarted. I didn't do a super-in-depth analysis, but the output looks smooth across the restart (and the restart didn't crash). Not saying we don't need a CIME restart test (which should be a single line to add, right? Just ERS or ERP followed by the stuff we've been using for our other CIME tests?

**Comment by bartgol** [comment]
Did the input yaml file for the restarted run contain
```
   Initial Conditions:
      Restarted Run: true
```
? If not, then the AD did a normal initialization of the model. But I find it cumbersome to have to hack scream_input.yaml to tell the driver that this is a restarted run. I assume MCT already provides this sort of information to the atm component, so we should be able to handle things without any hack of the input yaml file.

**Comment by PeterCaldwell** [comment]
^^That's a question for @ndkeen
