### ISSUE TITLE
Sync ftype2 in scream and EAM+hommexx code

### ISSUE THREAD

**Issue by oksanaguba** [E3SM-Project/scream#1533]
In EAM F, for ftype=2 tracers forcing is applied in dp_coupling layer, while for all other cases, forcings are applied in homme. For simplicity, when i put new forcing code for runs EAM+hommexx, i only placed code in homme, see

https://github.com/E3SM-Project/E3SM/blob/8d33109bccd67635bd84153b8c003844734585f2/components/homme/src/share/cxx/prim_driver.cpp#L109

```
    // Apply forcing.
#if defined(CAM) || defined(SCREAM)
    //CAM and SCREAM, support only ftype0 and 2
    if (params.ftype == ForcingAlg::FORCING_0){
         apply_cam_forcing_tracers(dt_remap);
    }
    if (params.ftype == ForcingAlg::FORCING_2 && params.nsplit_iteration == 1 ){
         apply_cam_forcing_tracers(dt_remap*params.nsplit);
    }

    apply_cam_forcing_dynamics(dt_remap);
    
```

Now, in EAMxx (hommexx+new AD), there is still a call to tracers forcing from dp_coupling layer, see https://github.com/E3SM-Project/scream/blob/5de80e0f08c87c0d5039e23600b302f0435aeee9/components/scream/src/dynamics/homme/atmosphere_dynamics.cpp#L582 

This way, ftype2 is not usable in SCREAM at the moment. I suggest removing the call from the last link.

**Comment by oksanaguba** [comment]
I assigned it to Luca, but i probably can do it, including adding ftype2 tests (if they are not there).

**Comment by bartgol** [comment]
Is this as simple as removing the line
```
       ff.tracers_forcing(dt,n0,n0_qdp,true,params.moisture);
```
?

**Comment by oksanaguba** [comment]
i think so, but i'd also add a test for ftype2, if there are none.

**Comment by bartgol** [comment]
Ok, makes sense.

**Comment by ambrad** [comment]
This was fixed.
