### ISSUE TITLE
SMS_D simulations die on quartz in ELM

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1537]
We are having an issue with SMS_D simulations on the Livermore Computing quartz machine with the SCREAM codebase.  We tracked this down to an upstream merge on March 22, see: https://github.com/E3SM-Project/scream/pull/1499.  The stacktrace of the error points to ELM initialization, see

```
forrtl: error (182): floating invalid - possible uninitialized real/complex variable.
Image              PC                Routine            Line        Source
e3sm.exe           0000000007207DF4  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AAAB8A7D630  Unknown               Unknown  Unknown
e3sm.exe           00000000038DE84A  fatesinterfacemod         923  FatesInterfaceMod.F90
e3sm.exe           0000000000A71B9F  elmfatesinterface         494  elmfates_interfaceMod.F90
e3sm.exe           0000000000970B6D  elm_initializemod         557  elm_initializeMod.F90
e3sm.exe           00000000008BA478  lnd_comp_mct_mp_l         284  lnd_comp_mct.F90
e3sm.exe           000000000048E34B  component_mod_mp_         257  component_mod.F90
e3sm.exe           0000000000436B65  cime_comp_mod_mp_        1431  cime_comp_mod.F90
e3sm.exe           0000000000484CE8  MAIN__                    122  cime_driver.F90
```

and a little hunting pointed to the `photo_temp_acclim_timescale` variable being used in `FatesInterfaceMod.F90`  during the `InitTimeAveragingGlobals()` routine.  This variable is NaN in our simulations, which leads to the FPE exception above.  Looking at this variable in the FATES code I found the following comment:

```
   real(r8),protected, public :: photo_temp_acclim_timescale ! Length of the window for the exponential moving average (ema)
                                                             ! of vegetation temperature used in photosynthesis
                                                             ! temperature acclimation (NOT YET IMPLEMENTED)
```

and also the following parameter setting:

```
components/elm/src/external_models/fates/parameter_files/fates_params_default.cdl:1472: fates_photo_temp_acclim_timescale = 30 ;
```

Is it true this parameter isn't implemented yet?  If so why would we call a function that uses it?
Or is supposed to be set to 30 and for some reason the `quartz` builds are not picking that up?

**Comment by AaronDonahue** [comment]
Could this be an error detected by a specific compiler?  quartz is running intel.

**Comment by AaronDonahue** [comment]
I also looked at the `lnd.log` and saw these two lines which make me think we shouldn't be calling FATES code at all...

``` 
Number of External Models =            0
   Is BeTR present?      F
   Is FATES present?     F
```

```
 Albedo over melting lakes will approach values (visible, NIR):
  0.100000000000000       0.100000000000000
 as compared with 0.60, 0.40 for cold frozen lakes with no snow.
     use_fates =  F
```

**Comment by rljacob** [comment]
what version of intel?

**Comment by bartgol** [comment]
The module loaded on quartz is `intel/19.0.4`.

**Comment by AaronDonahue** [comment]
```
>> git diff
diff --git a/cime b/cime
--- a/cime
+++ b/cime
@@ -1 +1 @@
-Subproject commit 4f9ce69d21ba937af397412f6435c2429289f8ab
+Subproject commit 4f9ce69d21ba937af397412f6435c2429289f8ab-dirty
diff --git a/components/elm/src/main/elm_initializeMod.F90 b/components/elm/src/main/elm_initializeMod.F90
index 49ad12841e..67985a09f3 100644
--- a/components/elm/src/main/elm_initializeMod.F90
+++ b/components/elm/src/main/elm_initializeMod.F90
@@ -554,7 +554,9 @@ contains
     ! ------------------------------------------------------------------------
     ! Pass model timestep info to FATES
     ! ------------------------------------------------------------------------
-    call ELMFatesTimesteps()
+    if (use_fates) then
+      call ELMFatesTimesteps()
+    endif
     
     ! ------------------------------------------------------------------------
     ! Initialize daylength from the previous time step (needed so prev_dayl can be set correctly)
```

This change fixes the problem.   As far as I can tell, there are parts of the ELM initialization that check `use_fates` and do something, and others that call FATES code without the check.  Presumably because it causes no harm to, for example, initialize the fates timestep, even if we won't use it.  But perhaps for the compiler in quartz this will cause the code to snag on a NaN that we are not seeing with other compilers.  

@rljacob or others... Is there any reason we are not checking `use_fates` whenever there is a call to FATES code?  Are there FATES structures that are used even if FATES isn't?  Again, totally new to the ELM code...

**Comment by rljacob** [comment]
That "19.0.4" version looked familiar and there's a discussion in this old report about how we could not get compy with 19.0.4 to give correct answers:  https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1037697292/2019-10+Infrastructure+Quarterly+Report  .   So that version is suspect and you may want to upgrade.

**Comment by AaronDonahue** [comment]
Okay, I'll see if I can upgrade compilers.  Thanks for your help @rljacob

**Comment by AaronDonahue** [comment]
@rljacob , switching to `intel/19.1.2` didn't fix the problem.  Do you recall how far of an upgrade was needed?  Was it just intel/19 that was the problem?  I can also access intel/2021 or intel/2022 but I'll have to have the netcdf and pnetcdf modules remade so I only want to have that done if we are confident we need the higher compiler version.

**Comment by AaronDonahue** [comment]
Just did some digging and it looks like `compy` uses `intel/19.0.5` and Cori-KNL uses `intel/19.0.3.199`.  `sandiatoss3` even appears to be using `intel/17.0`.  These all appear to be working on CDash.  Or maybe I'm reading `cime_configs/machines/config_machines.xml` incorrectly...

**Comment by rljacob** [comment]
That's right.  And Chrysalis is using intel/20.0.4.

I would try a version known to work on another machine like the ones you list.  If you still get this error that no one else does, are you using the same compiler flags as E3SM?

I agree that the fix is odd in that every compiler should flag that.

**Comment by rgknox** [comment]
@AaronDonahue I think you got it right: https://github.com/E3SM-Project/scream/issues/1537#issuecomment-1096995944

A use_fates conditional should be there and it looks like an oversite that it was not added.

**Comment by AaronDonahue** [comment]
@rgknox , thanks for checking on that.  Would it be possible to create a ninja-fix PR in ELM so I can bring the fix up into the SCREAM repo?

**Comment by rgknox** [comment]
I'd be happy to whip up a PR if anyone hasn't already

**Comment by AaronDonahue** [comment]
@rgknox , excellent, thanks.  I found one other place in the initialize code where Fates is called but `use_fates` isn't checked.  The complete change looks like:
```
--- a/components/elm/src/main/elm_initializeMod.F90
+++ b/components/elm/src/main/elm_initializeMod.F90
@@ -292,7 +292,9 @@ contains
     ! to allocate space, determined in this routine)
     ! ------------------------------------------------------------------------
 
-    call ELMFatesGlobals()
+    if (use_fates) then
+      call ELMFatesGlobals()
+    end if
 
 
     ! ------------------------------------------------------------------------
@@ -554,7 +556,9 @@ contains
     ! ------------------------------------------------------------------------
     ! Pass model timestep info to FATES
     ! ------------------------------------------------------------------------
-    call ELMFatesTimesteps()
+    if (use_fates) then
+      call ELMFatesTimesteps()
+    end if
```

of course, if `ELMFatesGlobals()` is needed then by all means keep it as is.  Just wanted to ping you since you were fixing one already.

**Comment by rgknox** [comment]
I "think" we may have an internal check in the ELMFatesGlobals(), but will verify and change if not.

**Comment by rgknox** [comment]
I check that call/routinge and we are ok, there. We actually do have to enter that routine for all non-fates runs too, so that FATES can pass back info that helps set some array allocations, and when FATES is not on it sets allocation to trivial.

**Comment by AaronDonahue** [comment]
ok cool, so it's just the one fix then.
