### ISSUE TITLE
Link fail on Cori with Intel -- undefined reference to `for_abort'

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1539]
Using master of Apr12th, can reproduce with: `SMS_D_Ld1_P16x4.ne4_ne4.F2000SCREAMv1.cori-knl_intel`

I can work-around by commenting out the abort in `components/eam/src/physics/cam/scream_abortutils.F90`

Luca suggests:
in scream/src/physics/share/CMakeLists.txt you can try to add
```
if (${CMAKE_VERSION} VERSION_LESS "3.15.0")
  target_link_libraries (physics_share PUBLIC
    $<$<COMPILE_LANGUAGE:Fortran>:$<$<Fortran_COMPILER_ID:Intel>: ifport>>)
else ()
  target_link_libraries (physics_share PUBLIC
    $<$<COMPILE_LANG_AND_ID:Fortran,Intel>: ifport>)
endif()
```

**Comment by bartgol** [comment]
I think that's fine. Though we would have to ensure we are linking against the csmshare lib. Currently, rrtmgp builds that lib (if we're not in a CIME build). I think we should always build it and be done with it. I can fix our cmake logic for that.

**Comment by ndkeen** [comment]
This seems to no longer be an issue
