### ISSUE TITLE
atm.log file finishes with "?" character in CIME based runs

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1541]
It looks like when a run completes in CIME now the filename finishes with `?`.  Rather than `gz` like the rest of the log files from the run.

This isn't a critical issue, but it may cause confusion to typical users who may see anything but a `.gz` extension as representing a failed run.  For a concrete example, here are the log files from a recently finished run:

```
run/atm.log.9188398.220412-143103?    run/e3sm.log.9188398.220412-143103.gz	  run/ice.log.9188398.220412-143103.gz	run/ocn.log.9188398.220412-143103.gz
run/cpl.log.9188398.220412-143103.gz  run/homme_atm.log.9188398.220412-143103.gz  run/lnd.log.9188398.220412-143103.gz	run/preview_run.log.9188398.220412-143103.gz
```

Notice how all but the `atm.log` file end in `gz`.

**Comment by bartgol** [comment]
@ndkeen also noticed something odd with log files. His PR #1538 fixed the problem for him. If your branch does not have that commit, you might want to update the branch and try again.

**Comment by AaronDonahue** [comment]
oh right, I saw that PR go in.  It's not critical, I'll wait till the PR goes in and then take another look and close the issue if it ends up getting resolved.

**Comment by bartgol** [comment]
@AaronDonahue did that PR fix your issue?

**Comment by AaronDonahue** [comment]
#1538 fixed this
