### ISSUE TITLE
Internal error with default Intel compiler (version 19.1.2.254) on Cori using OPT build

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1543]
Using a scream master of Apr12th, can reproduce with `SMS_Ld1_P16x1.ne4_ne4.F2000SCREAMv1.cori-knl_intel` (ie OPT build) after commenting out abort as noted here https://github.com/E3SM-Project/scream/issues/1539. The test will buidl with DEBUG.

```
[ 95%] Linking CXX executable p3_tables_setup
cd /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.intel.12s.n011b64x1.nospa.RECe.N576.ts150.s8.opt1/bld/cmake-bld/scream/src/physics/p3 && /global/common/software/nersc/cori-2022q1/spack/cray-cnl7-haswell/cmake-3.22.1-zdiyyvt/bin/cmake -E cmake_link_script CMakeFiles/p3_tables_setup.dir/link.txt --verbose=1
python3 /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.intel.12s.n011b64x1.nospa.RECe.N576.ts150.s8.opt1/Tools/e3sm_compile_wrap.py  /opt/cray/pe/craype/2.6.2/bin/CC  -traceback -DRRTMGP_EXPENSIVE_CHECKS -restrict -Wall -diag-disable=remark -O3 -DNDEBUG -O3 -qopenmp-simd -Wl,-rpath,/opt/cray/pe/atp/3.14.9/lib -Wl,--undefined=__libAtpSigHandler_ctor -L/opt/cray/dmapp/7.1.1-7.0.3.1_3.7__g93a7e9f.ari/lib64 -DKOKKOS_DEPENDENCE -fopenmp -xMIC-AVX512 CMakeFiles/p3_tables_setup.dir/p3_tables_setup.cpp.o -o p3_tables_setup  libp3.a ../share/libphysics_share.a ../../share/libscream_share.a ../../../../externals/ekat/src/ekat/libekat.a ../../../../externals/kokkos/containers/src/libkokkoscontainers.a ../../../../externals/kokkos/core/src/libkokkoscore.a ../../../../externals/yaml-cpp/libyaml-cpp.a ../../../../externals/spdlog/libspdlog.a /opt/cray/pe/libsci/20.09.1/INTEL/16.0/x86_64/lib/libsci_intel_mpi_mp.a /opt/cray/pe/libsci/20.09.1/INTEL/16.0/x86_64/lib/libsci_intel_mp.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libiomp5.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libiomp5.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a -lhdf5hl_fortran_parallel -lhdf5_fortran_parallel -lnetcdff -lmpichf90_intel -lifcore 
": internal error: 010101_13941
```

Originally noted here, https://github.com/E3SM-Project/scream/issues/1540, but I now see this is a diff issue and fails to build this file: `components/scream/src/physics/shoc/shoc_assumed_pdf.cpp`

I tried several compiler flag changes, and other module changes (including different Intel compiler version), but was unable to get beyond the error. 

However, I had been able to successfully build Intel optimized with a clone from a few weeks ago.

What about first bisecting to find which PR might have introduced a change?
And then if that's not successful, I have several modifications in the clone that does allow Intel optimized build that I can look at one-by-one (already tried the obvious changes, such as compiler flags) ?

**Comment by PeterCaldwell** [comment]
shoc_assumed_pdf.cpp is ~10 lines but is probably a placeholder for shoc_assumed_pdf_impl.hpp which is 360 lines... which is still not very much code. Are you sure the problem is in this file, @ndkeen ? ie is the fail in this file repeatable? Do we have a line number (I know you would have mentioned if so, but one can hope)? If so, I'm tempted to ask someone to just to read through the code looking for sketchy stuff. I skimmed it and didn't see anything. If we don't see anything, I think we could easily break the code into pieces and comment out pieces chunk by chunk to find the offending line.

**Comment by ndkeen** [comment]
I get same error (as above) with each build, and I think it's same as what Chris T found.  What about my suggestion?

```
What about first bisecting to find which PR might have introduced a change?
And then if that's not successful, I have several modifications in the clone that does allow Intel optimized build that I can look at one-by-one (already tried the obvious changes, such as compiler flags) ?
```

**Comment by bartgol** [comment]
When out of ideas (esp for ICE's), bisection is a great idea. That is, assuming we know that there used to be _no_ error at some point.

**Comment by ndkeen** [comment]
Great, I was hoping someone would agree it's a good idea, because I already did it.

**Comment by PeterCaldwell** [comment]
@jgfouca - is this the same internal compiler error you're seeing? I guess not because you had problems with DEBUG and Noel is having probs with OPT? Are you having errors in the same file though? Maybe you could create a similar git issue?

**Comment by jgfouca** [comment]
@PeterCaldwell , no, different file. I have since switched from conrad's branch to master and I'm not seeing the internal compiler error anymore.

**Comment by bartgol** [comment]
Are you building with flags that throw FPEs? If so, that would explain why the ekat's invalid function was a problem. If not, I'm not really sure why that's an issue. It might be that cuda 11 defines macros for NaN slightly differently?

**Comment by PeterCaldwell** [comment]
Don't we know the error is in shoc_assumed_pdf? And further, that it is related to invalid values in packs? It seems like it should be easy to look through that code and find the offending line.

Or can we reproduce the problem in the unit test for shoc_assumed_pdf? I note that the case Noel reports the problem in is an ne4 case, so we shouldn't have to increase the resolution to find it?

**Comment by PeterCaldwell** [comment]
I'm also curious whether the internal compiler error in opt builds on cori is the same thing that causes really hot temperatures for Perlmutter opt builds.

**Comment by PeterCaldwell** [comment]
Another dumb question: if the problem is related to invalid values in packs, do we still have it if we set packsize to 1? I'm not sure how to do that in a CIME build...

**Comment by PeterCaldwell** [comment]
> Don't we know the error is in shoc_assumed_pdf? And further, that it is related to invalid values in packs? It seems like it should be easy to look through that code and find the offending line.

I just asked @bogensch to bisect shoc_assumed_pdf by commenting out stuff until the error goes away.

**Comment by ndkeen** [comment]
Typically with internal compiler errors (ie an error with the compiler itself), it's a bug and you can work to find a small reproducer to give to vendor in hopes they will fix it. And sometimes you can find a slight tweak to the code to work-around it (which I think I found). It's not usually something obvious (or makes much sense). I do see that NERSC has an even newer intel compiler version `intel/19.1.3.304` which I just tried and it seem to build. So that may be all we need. Will test more, but I would not waste anyone else's time.

**Comment by bartgol** [comment]
Agreed. ICEs are a pain, never related to actual algorithmic bugs, and their solution is seldom logical.

**Comment by jgfouca** [comment]
For what it's worth, pack size can be tweaked by editing the cmake machine file for the current machine (components/scream/cmake/machine-files/$machine.cmake). Set the cached SCREAM_PACK_SIZE to 1.

**Comment by ndkeen** [comment]
I also test a ne120 cases with `intel/19.1.3.304` and it built (and runs), which is not necessarily much more of a test, but at least we know it wasn't just luck last night.

I cloned a e3sm master, updated to `intel/19.1.3.304` and trying e3sm_developer. Then we can decide how best to upgrade to this newer compiler version.

**Comment by ndkeen** [comment]
Whoops. When I make a new clone and try the new compiler version, I'm still getting internal compiler error for OPT builds. So that means there is still something in my local changes that are tweaking things just enough to avoid the error. Will keep working on it.

**Comment by ndkeen** [comment]
I basically had a typo in my quick macros to turn on/off the work-around which meant my testing with new compiler was actually still using at least a portion of the work-around. I'm still testing, but verified the work-around still works with recent repo.

**Comment by ndkeen** [comment]
@AaronDonahue this is the issue regarding internal compiler error with Intel in optimized. I would say cori-knl, but that's only place I've tested with Intel.  You noted:

```
Cori-KNL had build errors for SCREAMv1 the ERS test, looking at the logs it looks like an internal error related to src/physics/shoc/shoc_calc_shoc_varorcovar.cpp
```

which is indeed in a different file.

**Comment by ambrad** [comment]
Does the SCREAM build system permit file-dependent flags? Looks like -O1 and no higher resolves the issue for shoc_assumed_pdf.cpp.

**Comment by bartgol** [comment]
Yes, it works. File-specific compiler flags are appended _after_ global and target flags. So one can change opt flags on a per-file basis inside CMakeLists.txt.

**Comment by ndkeen** [comment]
Typically we do this with a file like `cime_config/machines/Depends.cori-knl.intel.cmake`, but I tried adding something and it doesn't seem to be used.

**Comment by ambrad** [comment]
Thanks Luca. I'm trying your suggestion in `components/scream/src/physics/shoc/CMakeLists.txt` and will report back. Not clear to me whether this cmake file is used in the CIME build, so I'm just taking a guess.

**Comment by bartgol** [comment]
It is used. Scream CMake build system is invoked by e3sm's cmake build system.

**Comment by ambrad** [comment]
Yep, and the fix works. I'm going to add
```cmake
if ("${SCREAM_MACHINE}" STREQUAL "cori-knl")
  set_source_files_properties (shoc_assumed_pdf.cpp PROPERTIES COMPILE_FLAGS "-O1")
endif()
```

**Comment by ndkeen** [comment]
Wait, if `cime_config/machines/Depends.cori-knl.intel.cmake` *is* used, then we should make the change there?

**Comment by ambrad** [comment]
I think @bartgol meant that components/scream/src/physics/shoc/CMakeLists.txt is used.

**Comment by ndkeen** [comment]
ok. then yea let's make that change.

**Comment by bartgol** [comment]
Yeah, sorry, I should have quoted the msg I was replying to.

Good to know that it works.
