### ISSUE TITLE
Unpredictable fails in radiation code with screamv1 cime cases -- eg: gas_optics(): array tsfc has values outside range `RRTMGP_EXPENSIVE_CHECKS`

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1547]
Originally noted here https://github.com/E3SM-Project/scream/issues/1479

I build with `-DRRTMGP_EXPENSIVE_CHECKS` which adds some extra tests in radiation and I think is where these type of errors are printed -- without the macro, I will see other type of errors, so we think this is earlier indication of problem. I verified that it's not actually any slower to have this check with optimized/debug builds.

Common error message:
```
 3: FATAL ERROR:
 3: gas_optics(): array tsfc has values outside range
```

I see the error at ne30 and at least 3 times with ne4. I've seen it with Intel/GNU built code and on Perlmutter/cori-knl. It also has the nice property of not crashing on the same step every time. So even in same case, running 3 times, I've seen it fail at different steps. On PM, I  have hit the issue using GPU and in CPU-only attempts.

With ne30, some of my runs have gone beyond a day, eg up to 679 steps, before hitting issue.

I've also seen `GasConcs::set_vmr(): concentrations should be >= 0, <= 1`
as well as `gas_optics(): array tlay has values outside range`

With ne120, I get a related error (may or may not should be included in this issue?):

```
rte_sw: sfc_alb_dir out of bounds [0,1]
```

For ne120, I'm seeing it fail on the first step with this error pretty reliably (on cori-knl).

**Comment by ndkeen** [comment]
I added some prints at some of those error sites.  For ne120:

```
 630: ndk sfc_alb_dir=         0.000000000000000e+00 ncol=    -66496 nlay=         7 ngpt=        72 nband=       224
 630: FATAL ERROR:
 630: rte_sw: sfc_alb_dir out of bounds [0,1]
```

```
 int ncol  = atmos.get_ncol();
  int nlay  = atmos.get_nlay();
  int ngpt  = atmos.get_ngpt();
  int nband = atmos.get_nband();
```

This is in
```
void rte_sw(OpticalProps2str const &atmos, bool top_at_1, real1d const &mu0, real2d const &inc_flux,
            real2d const &sfc_alb_dir, real2d const &sfc_alb_dif, FluxesType &fluxes, real2d const &inc_flux_dif) {
```

`components/eam/src/physics/rrtmgp/external/cpp/rte/mo_rte_sw.h`

Obv the ncol value looks odd, but it went past here:

```
if (size(sfc_alb_dir,1) != nband || size(sfc_alb_dir,2) != ncol) { stoprun("rte_sw: sfc_alb_dir inconsistently sized"); }
```

**Comment by PeterCaldwell** [comment]
I suspect this is the same problem as #1575

**Comment by ndkeen** [comment]
Sure. I would say that if we don't "trust" the additional checks that are engaged when `RRTMGP_EXPENSIVE_CHECKS` defined, then this can be closed. I know that the details of the checks (in general) are changing. And it may be that we can one day try again (or not).

**Comment by PeterCaldwell** [comment]
Ah, you remind me that @brhillman  had a PR which was supposed to provide better details about what was going wrong when these checks failed. Maybe he has a comment on whether we should try turning on these new checks, or whether they're already on and aren't catching anything?

**Comment by brhillman** [comment]
> 
Sure. I would say that if we don't "trust" the additional checks that are engaged when RRTMGP_EXPENSIVE_CHECKS defined, then this can be closed. I know that the details of the checks (in general) are changing. And it may be that we can one day try again (or not).

Actually, I would say that we *do* trust the checks, we just wanted to implement checks of our own further up in the code to catch these issues before RRTMGP saw them and just aborted the run. That way we would have a chance to catch problems and repair fields/clip values/print more useful messages. That's what the "extra checks" are supposed to be doing; when compiled with the CIME DEBUG=TRUE flag, or for standalone tests in debug mode, we should be triggering these checks, which will report min/max when fields go out of bounds. Possible that I missed some though...are you still seeing these errors, and NOT getting better reporting?
