### ISSUE TITLE
Post-condition check failure with ne30/ne120 cime attempts

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1554]
Starting with branch `bartgol/scorpio-mods` and using ` --res ne120_r0125_oRRS18to6v3 --compiler gnugpu --compset F2000SCREAMv1`, I see the error below after a small number of timesteps. Some cases have failed at different step count (somewhere between 5 and 15?), but I've not verified if a single case fails at exactly the same place each time.

I also see same type of error with certain ne30 attempts, so it's not specific to ne120.

This is on PM and cori and is without SPA.

```
 75: terminate called after throwing an instance of 'std::logic_error'
 75:   what():  /global/cfs/cdirs/e3sm/ndk/bio-apr11/components/scream/src/share/atm_process/atmosphere_process.cpp:275: FAIL:
 75: false
 75: Error! Failed post-condition check (cannot be repaired).
 75:   - Atm process name: Macrophysics
 75:   - Property check name: T_mid within interval [140, 500]
 75:   - Atmosphere process MPI Rank: 75
```

These are builds without `RRTMGP_EXPENSIVE_CHECKS`.

Verified same errors when I added in recent changes to use omega.

**Comment by PeterCaldwell** [comment]
@ndkeen - is this just with optimized builds? Is this still a problem now that we have qv<0 bumpers in master? Can we close this issue? I can run hundreds of steps at ne30 now on quartz (before eventually crashing).

**Comment by ndkeen** [comment]
We can close this since we have reworked the checks.
