### ISSUE TITLE
pbl_depth out of bounds

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1560]
Running an ne30 case on quartz using master post bounds checking and SPA memory management PRs, I immediately fail with the error:

```
Error! Failed post-condition check (cannot be repaired).
  - Atm process name: Macrophysics
  - Property check name: pbl_height within interval [0, 3000]
```

- Chris Terai verified that he gets the same error when he runs on Perlmutter.
- Peter B pointed out that 3000m isn't that high of a max BL height and suggested that we increase the upper bound to 10,000m. The code still crashes after I make that fix. 
- Turning off shoc postcondition checks in namelist_scream.xml allows the model to run for at least 10 steps. 
- ne4 does not fail in this way.

**Comment by PeterCaldwell** [comment]
I'm unclear whether pbl_height is getting huge or whether it's going slightly negative. Runs with the "hot" problem have BL depth of 8 km or so, but that might be expected if your surface layer is 400K. Ben's PR which provides more useful info when bounds checks fail will be useful to clarify this.

**Comment by PeterCaldwell** [comment]
Writing output every timestep shows that pbl_height is huge in the first timestep of the run, then plummets to reasonable values. This is kind of annoying - a bad value in init is tolerable except that it prevents us from checking bad vals later. I think these weird values are on the tip of Tierra Del Fuego. Peak value is almost 20K m.
[ne30_opt_pbl_height.pdf](https://github.com/E3SM-Project/scream/files/8542792/ne30_opt_pbl_height.pdf)

**Comment by PeterCaldwell** [comment]
ne4 does not have this weird spin-up issue.

**Comment by bartgol** [comment]
Would it help to add the possibility to "skip" property checks during the first N time steps (to allow adjustment during spinup)? Or even more generally, to ramp the check from a coarse one to a tight one? The former should be not too hard to impl, while the latter (of which the former is a limit case) might be complicated, and I don't know if we need it now.

**Comment by PeterCaldwell** [comment]
we might eventually give up and skip the check for the first N steps, but first I'd like to try to fix it for a bit longer.

**Comment by singhbalwinder** [comment]
Would generating new initial conditions from a spun up model  and using them help?
