### ISSUE TITLE
Memory growth with cime screamv1 case with output (PM and cori-knl)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1565]
For the ne30 case I'm running on Perlmutter, I can run ~14 days before hitting error. I noticed that the memory is increasing every day. It may or may not be the cause of the error I hit, but surely something we don't want to see.

```
 memory_write: model date =   00010101       0 memory =   27451.52 MB (highwater)       5145.58 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010102       0 memory =   35597.93 MB (highwater)       5508.42 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010103       0 memory =   36976.55 MB (highwater)       6157.80 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010104       0 memory =   37596.70 MB (highwater)       6807.18 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010105       0 memory =   38288.41 MB (highwater)       7456.54 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010106       0 memory =   38976.57 MB (highwater)       8105.90 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010107       0 memory =   39728.24 MB (highwater)       8755.27 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010108       0 memory =   40367.88 MB (highwater)       9404.63 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010109       0 memory =   41017.59 MB (highwater)      10210.34 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010110       0 memory =   41526.06 MB (highwater)      10846.37 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010111       0 memory =   42285.31 MB (highwater)      11512.64 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010112       0 memory =   42949.02 MB (highwater)      12149.94 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010113       0 memory =   43650.26 MB (highwater)      12839.20 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)
 memory_write: model date =   00010114       0 memory =   44274.87 MB (highwater)      13476.22 MB (usage)  (pe=    0 comps= cpl ATM LND ICE OCN GLC ROF WAV IAC ESP)

/pscratch/sd/n/ndk/e3sm_scratch/perlmutter/bio-apr11/f30.F2000SCREAMv1.ne30_ne30.bio-apr11.gnugpu.1m.n008a4x16.Hremap512.K00.N576.ts150.S1.s8.36sb.OMEGA.gnu11

/pscratch/sd/n/ndk/e3sm_scratch/perlmutter/bio-apr11/f30.F2000SCREAMv1.ne30_ne30.bio-apr11.gnugpu.1m.n008a4x16.Hremap512.K00.N576.ts150.S1.s8.36sb
```

This a branch from Apr11, and uses OMEGA and gnu v11.  But I've also confirmed same memory growth before with gnu v10 (which is what we normally use) and without the OMEGA change. This is a debug-like build. It includes SPA and writes snapshots every 36 steps.

**Comment by PeterCaldwell** [comment]
It would be good to check whether we see this memory growth on all machines. Is this memory_write something that you added to your code? Should we have it in master?

**Comment by ndkeen** [comment]
Those lines are included in cpl.log* files.

**Comment by bartgol** [comment]
Do we know how the cpl gets this numbers? I wonder if there is a way to squeeze a bit more information out of this, to help us track down things.

Another thing to try would be to eliminate one (or more) atm processes from the atm input list, and see if the memory still increases or not. It may be that it's one (or more) atm procs that cause the leak, but it might be that the infrastructure is responsible.

**Comment by ndkeen** [comment]
Can also see mem growth with ne4 and confirmed it seems related to the output. 

To set the frequency of snapshots:
```
Output Control:
  Frequency: 36
  Frequency Units: Steps
```

And I found that for ne30 and beyond, it's nice to have 1 file per snapshot:
`Max Snapshots Per File: 1`


![mem](https://user-images.githubusercontent.com/5684727/165339558-f094ea82-711c-47bb-9616-a12626634812.png)

**Comment by bartgol** [comment]
The fact that 1file/ss is worse suggests we might be leaving scorpio structs (like pio file stuff) in memory even if they can be discarded already. I thought they were relatively small structs, but maybe I'm wrong.

**Comment by ndkeen** [comment]
I also ran a 1 month case with output every 36 steps (into sep snapshot files), but only asked to write 1 variable. The memory growth is still present, but at a much slower pace. Suggesting that whatever is happening is likely per variable.
I could add another line to the plot.

**Comment by AaronDonahue** [comment]
I think that PR #1643 will address the issue with 1SS/file.  I'm still investigating the "all SS on 1 file case".

**Comment by ndkeen** [comment]
I just ran a case for 420 days on alvarez (same as pm-cpu). This is ne30 on 43 nodes and I think we have snapshots only writing once per month. I still see a memory growth that is likely happening with each file write. Note the big jumps there are the restart file writes which are set at 210 days (one in the middle and one at end).

![stampmemdata2](https://user-images.githubusercontent.com/5684727/179803861-e065c3fb-838b-4d1c-842a-bce7e41f9d6d.png)

**Comment by AaronDonahue** [comment]
So it looks like we are not freeing the decomp (or some other chunk of memory) when we write restarts.  Thanks for investigating this @ndkeen .  I will do some digging around our code to see if we are treating the end of a restart write differently than when its a 1SS/File output.

I'll note that I'm not surprised that a restart would have a big jump in memory, it needs to write everything that is needed for a clean restart, which is probably more than our relatively small set of default outputs.

**Comment by ndkeen** [comment]
Just to clean up the issue the restart write frequency, I ran the 420 days again. I copied the case to here:
`/global/cfs/cdirs/e3sm/ndk/dump/ne30_ne30.F2010-SCREAMv1.alvarez_gnu.420d.PACK1.n043a128x1ci2b`

And the memory plot looks about the same (or conveys same message)

![stampmemdata2](https://user-images.githubusercontent.com/5684727/179820417-feb5032b-fd2b-4360-ba87-b419236c14e5.png)

**Comment by AaronDonahue** [comment]
@ndkeen , do you know if we are still seeing memory growth with our output like this?  Is it something you could add to your planned performance analysis of the YAML output options?

**Comment by ndkeen** [comment]
I tried a case `ne30pg2_ne30pg2.F2010-SCREAMv1` on 45 CPU nodes for 6 months with cess-style yaml outputs.
It completed without showing any increase in memory, if we can trust what's written to cpl.log.
So perhaps we can close.

Note that I had to run without the following yaml file as it otherwise had a problem the team size too large

```
scream_output.test.3hourlyINST_ne30tone4.yaml
```
