### ISSUE TITLE
Possible incorrect  initialization/restart of fields in coupled runs

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1571]
I was going over stale PRs, and stumbled upon [this](https://github.com/E3SM-Project/scream/pull/1400#issuecomment-1032063170) comment I made:

"[...] we do print a correct DAG, including the surface coupling, but when we check which fields need an Initial Condition ([here](https://github.com/E3SM-Project/scream/blob/32ffa4b57f28591ad208b9aa61198c7e7ccd43a0/components/scream/src/control/atmosphere_driver.cpp#L557)), we do not keep into account the surface coupling..."

I think this may still be an issue. I'm using the conditional, since it might be that the surface coupling class still puts everything back in place when it runs the 1st time step. But now knowing how the SC fields are potentially used by the atm procs, this can potentially be a bug (e.g., if some atm proc uses a surface flux field during initialization).

Furthermore, I _think_ the current implementation is _requiring_ that the surface fluxes fields are in the IC/restart file, which is conceptually not right.

Possible solutions:
- run the SC import phase after init-ing the fields, but before initializing the atm procs. This is the easy approach, which would ensure the fields contain the correct values, but still require these fields to be in the IC/restart file.
- reinforce the logic for IC/restart fields, by also inspecting the SC outputs.
- long term, @tcclevenger is working on turning SC into an atm proc, which should make the current AD implementation work correctly.

The latter is the best solution, but more time consuming. As a stopgap, the first one might be enough (though it will still require/generate larger IC/restart files).

**Comment by bartgol** [comment]
@PeterCaldwell there is a slim chance that this might be causing model crashes, although i find it hard to believe, since everything was working for a while, and this has been an issue in the AD for a while.

**Comment by PeterCaldwell** [comment]
> i find it hard to believe, since everything was working for a while, and this has been an issue in the AD for a while.

I've been saying for a while that something is not quite right in surface coupling and we know that pbl_height is really wacky for our first timestep, so I wouldn't be so confident. 

I'm afraid I don't understand what isn't being done right. My understanding is that at the beginning of each timestep, we import vars from the surface to the atm and at the end of each step we export atm vars to the surface. This seems like it is guaranteed to provide surface models with good atm exports to work with. If the surface schemes are themselves saving the data in restarts which we import for atm to use, then everything should be good, right? Or are you saying that we might be using data from the surf schemes in our init step, but we don't have access to that data yet?

**Comment by bartgol** [comment]
Yeah, that's why I said "it might be that the surface coupling class still puts everything back in place when it runs the 1st time step."

The issue is that after initialization, and before we run the 1st time step, we might be having wrong surf fluxes. We should not read them from the init or restart file, but rather, we should run the SC, and _then_ init the atm procs (assuming any of them uses a surf flux field in any way). It might be that no atm proc uses surf fluxes during initialization, and if that's the case, _in practice_ we're ok. That said, the logic might be confusing, so eventually it will have to be fixed.

The "high priority" label is more for the double checking that this is not causing bad values. If it's not, we can bump priority down to low.

**Comment by PeterCaldwell** [comment]
So how do we check that this isn't giving bad values? It seems like we could either implement the fix or look through all the init functions for each proc?

**Comment by bartgol** [comment]
I'll think about it.

**Comment by PeterCaldwell** [comment]
I think we decided that no SCREAM procs are using surface fluxes in init, so we can close this issue?
