### ISSUE TITLE
On nodes with N gpu, make AD use (N+1)th rank to handle IO  

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#158]
Writing this down to keep track of the idea.

Rough idea: on systems like summit, spawn 7+ MPI ranks per node: 6 to handle computations (assuming 1 rank per GPU), and 1+ to handle I/O. The I/O rank(s), should access GPU data directly (bypass MPI/aggregation), then call PIO(2), or whatever aggregation+I/O library to be used.
Advantage: calculations on GPU can continue while the I/O rank(s) handle I/O stuff.

**Comment by ndkeen** [comment]
I *think* this means trying to respect the `PIO_STRIDE` variable that we typically set to be the number of MPI's per node (ie to get 1 IO writer per node).

**Comment by bartgol** [comment]
Well, if I understand correctly PIO, the ranks that do I/O _also_ do a piece of the calculations. In this issue, I was proposing having a rank (on host only) do _all_ the I/O  without the need to ship data to the IO rank via MPI at all (it can access it directly from the GPU), and _no_ calculations. This assumes that IO takes a non-negligible amount of time, so that having a rank handling _only_ IO might allow GPUs to resume calculations more quickly.

Alas, I think this would be a _very_ disruptive change, with lots of tricky issues.

**Comment by ndkeen** [comment]
OK. Should we make another issue to note that we are currently ignoring `PIO_STRIDE` ?

**Comment by bartgol** [comment]
Yes, that's a separate topic, and we should address it ASAP.

**Comment by bartgol** [comment]
This seems to be non-realistic. Closing.
