### ISSUE TITLE
Higher-res initial conditions

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1594]
For ne256, ne512, and ne1024.

**Comment by sarats** [comment]
I see a ne512 file at https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/scream/init/
Is that ready to use?

**Comment by PeterCaldwell** [comment]
- ne512 setup exists but was crashing in first step on NERSC machines. It would be worth trying this on summit, but don't hold your breath.
- ne256 setup was created at the end of last weeks. See https://github.com/E3SM-Project/scream/issues/1699 for initial attempt to get it working.

**Comment by AaronDonahue** [comment]
Based on all the runs we are doing now I'm going to say this is fixed.
