### ISSUE TITLE
WARNING - Albedo repair HACK needs to be reversed!

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1605]
PR #1600 is a hack to repair albedos coming in from surface coupling inside radiation.  But this is a temporary hack which will need to be reversed when surface coupling becomes an atmosphere process.

**Comment by whannah1** [comment]
Aaron, can you clarify what you mean by "_when surface coupling becomes an atmosphere process_"?

**Comment by bartgol** [comment]
Short story: he's just referring to an implementation detail inside EAMxx.

Long story: the "AtmosphereProcess" abstract class has already some capabilities to run checks pre/post run phase. The "SurfaceCoupling" class is an unrelated class, but we're thinking of making it inherit from the atm proc one, to make other parts of the code easier. By doing that, we could move these checks/repairs inside the SC class.

**Comment by ambrad** [comment]
@AaronDonahue was this fixed?

**Comment by bartgol** [comment]
@AaronDonahue is this still an issue? It'd be nice to not have a "WARNING! ..." open issue... :)

**Comment by AaronDonahue** [comment]
https://github.com/E3SM-Project/scream/blob/master/components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp#L93

https://github.com/E3SM-Project/scream/blob/master/components/eamxx/src/control/atmosphere_surface_coupling_importer.cpp#L129

I think so...
