### ISSUE TITLE
First attempt to run with ne512

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1607]
To try with ne512, all I did was change the IC file and the `ne` value in the dynamics section.
Attempted on cori-knl (without SPA) with 256 nodes (and again with 1024 nodes) using master of April27 with a handful of minor changes:

```
4048: PIO: FATAL ERROR: Aborting... An error occured, Reading variable (T_mid, varid=9) from file (/global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220405.nc, ncid=17) failed with PIO_IOTYPE_PNETCDF iotype. The low level (PnetCDF) I/O library call fa$

cori10% ls -l /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220405.nc
-rw-rw---- 1 bhillma e3sm 654223463252 Apr  6 08:29 /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220405.nc
cori10% ncdump -k /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220405.nc
cdf5

```

As this is using 128 levels, is there something else that needs to change?

When I try the p3 stand-alone (`bld/tests/uncoupled/p3`) on PM, I can run with ne30 and ne120 files. But with ne512:

```
 0: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: Index exceeds dimension bound (file = /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220405.nc) (/global/cfs/cdirs/e3sm/ndk/se02-apr27/externals/scorpio/src/clib/pio_darray_int.c: 1505)
```

Relevant changes to input.yaml:  
```
Grids Manager:
  Type: Mesh Free
  Reference Grid: Point Grid
  Mesh Free:
    #Number of Global Columns:   218
    #Number of Global Columns:   48602
    #Number of Global Columns:   777602
    Number of Global Columns:   14155778
    #Number of Vertical Levels:  72  # Will want to change to 128 when a valid unit test is available.
    Number of Vertical Levels:  128

# The name of the file containing the initial conditions for this test.
Initial Conditions:
  Point Grid:
    #Filename: /global/cfs/cdirs/e3sm/inputdata/atm/scream/init/p3_init_ne2np4.nc
    #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne30np4L72_20220503.nc
    #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne120np4L72_20220503.nc
    Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220405.nc
```

**Comment by bartgol** [comment]
The obvious: the error `Index exceeds dimension bound` we saw it before when `ncol` and `lev`/`ilev` were swapped. Are they correct in the ne512 input file?

**Comment by PeterCaldwell** [comment]
Good question, Luca. ncdump says `float T_mid(time, lev, ncol)`, which I think is the correct order, right? I also confirm that `Number of Global Columns:   14155778` is correct for ne512.

**Comment by PeterCaldwell** [comment]
@brhillman - Any chance we can make a 128 level ne4 or ne30 initial condition? It would be good to figure out whether it's the number of horiz or vertical levels that's causing indigestion.

**Comment by bartgol** [comment]
@PeterCaldwell  That's not the correct order. In that format, ncol strides faster, while we need lev to stride faster.

**Comment by PeterCaldwell** [comment]
Ok, it looked like all of the variables in our ne512 IC use that order. Calling @brhillman !!!

**Comment by bartgol** [comment]
you can simply do
```
ncpdq -a ncol,lev -O $filename
ncpdq -a ncol,ilev -O $filename
```
and that should fix it.

**Comment by ndkeen** [comment]
What about 
```
ncpdq -a ncol,lev -O a.nc b.nc
ncpdq -a ncol,ilev -O b.nc c.nc
```
where a.nc is input and c.nc is output?

**Comment by PeterCaldwell** [comment]
Yeah I was going to suggest what Noel said, or to make a copy of $filename, then do what Luca said. Not corrupting the original file seems like the way to go (even though it is unusably wrong). Noel - can you make the new file and try it?

**Comment by ndkeen** [comment]
I first copied the file to my project space, and tried:
```
ncpdq -a ncol,lev -O screami_ne512np4L128_20220405.nc screami_ne512np4L128_20220405b.nc
ncpdq -a ncol,ilev -O screami_ne512np4L128_20220405b.nc screami_ne512np4L128_20220405c.nc
```
however, the first ncpdq command is still running (it's been about 1.5 hours).

**Comment by bartgol** [comment]
I guess nco tools might not be very effective on very large files... :)

**Comment by ndkeen** [comment]
The first ncpdq ran for 5.5 hours before I lost connection, so it's likely it did not complete, though I don't know how to verify. So I started 2 more attempts: the first assuming (b) was written ok and the second assuming it was not.

```
nohup ncpdq -a ncol,ilev -O screami_ne512np4L128_20220405b.nc screami_ne512np4L128_20220405c.nc &
nohup ncpdq -a ncol,lev -O screami_ne512np4L128_20220405.nc screami_ne512np4L128_20220405b2.nc &
```

**Comment by ndkeen** [comment]
So the command to do `-a ncol,ilev` completed in only 1.5 hours, while the command to retry `-a ncol,lev` is still running. I have a completed file that should be ready and I just tried it with a cime case on cori.

```
1440: PIO: FATAL ERROR: Aborting... An error occured, Reading variable (horiz_winds, varid=19) from file (/global/cfs/cdirs/e3sm/ndk/sida/screami_ne512np4L128_20220405c.nc, ncid=17) failed with PIO_IOTYPE_PNETCDF iotype. The low level (PnetCDF) I/O library call failed to read the variable (Number of region$
```

**Comment by PeterCaldwell** [comment]
dimensions for horiz winds are `float horiz_winds(time, dim2, ncol, lev)`. Is that wrong?

**Comment by bartgol** [comment]
Good call Peter. Yes, that's wrong. The ncpdq command I gave works for scalar quantities. For vector quantities (like horiz_winds), we need `ncpdq -a ncol,$vecdim,lev $file`.

**Comment by bartgol** [comment]
Yeah, if he's already working on it, then yes. Sorry for the poor advice. :/

**Comment by ndkeen** [comment]
This is what I did:
```
ncpdq -a ncol,lev -O screami_ne512np4L128_20220405.nc screami_ne512np4L128_20220405b.nc 
ncpdq -a ncol,ilev -O screami_ne512np4L128_20220405b.nc screami_ne512np4L128_20220405c.nc 
ncpdq -a ncol,dim2,lev -O  screami_ne512np4L128_20220405c.nc screami_ne512np4L128_20220405d.nc
```

I'm not sure if the resulting `screami_ne512np4L128_20220405d.nc` will be the same as what @brhillman  is doing or not.

**Comment by ndkeen** [comment]
Trying Ben's new ne512 IC, I ran on cori-knl and it fails without useful error mesg.  Presumably reading the file, but I don't know for sure.

```
   0:  ndk subroutine atm_init_mct Initialize atm
   0: Rank 0 [Fri May  6 10:20:28 2022] [c0-1c0s0n0] application called MPI_Abort(MPI_COMM_WORLD, 115989908) - process 0
```

Same error with OPT/DEBUG.  Trying with more nodes.

**Comment by ndkeen** [comment]
A case using 1024 nodes (and 8 MPI's per node) also failed in the same way (ie just MPI_Abort). So I think there is a problem somewhere as I would think that should be enough memory.

**Comment by ndkeen** [comment]
Trying again with Intel, it fails in same place, but I get better (or diff?) error mesg:

```
   0:  var,nvars:           3          12
   0:            1  ABORTING WITH ERROR: NaNs detected in repro sum input
   0: Rank 0 [Fri May  6 15:02:24 2022] [c1-1c0s8n3] application called MPI_Abort(MPI_COMM_WORLD, 45) - process 0
   0: forrtl: error (76): Abort trap signal
   0: Image              PC                Routine            Line        Source             
   0: e3sm.exe           0000000008DC870B  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000006D2B920  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000008F2FFA0  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000009378E71  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000006E5FFD2  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000006E2E2EB  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000006E34885  Unknown               Unknown  Unknown
   0: e3sm.exe           000000000774C0E8  parallel_mod_mp_a         310  parallel_mod.F90
   0: e3sm.exe           000000000773D927  global_norms_mod_         857  global_norms_mod.F90
   0: e3sm.exe           00000000074534F1  prim_state_mod_mp         356  prim_state_mod.F90
   0: e3sm.exe           00000000073682ED  prim_init_model_f         215  homme_driver_mod.F90
   0: e3sm.exe           00000000072C28D9  _ZN6scream13Homme         378  atmosphere_dynamics.cpp
   0: e3sm.exe           0000000008B91F56  _ZN6scream17Atmos          44  atmosphere_process.cpp
   0: e3sm.exe           0000000008BAE44A  _ZN6scream22Atmos         140  atmosphere_process_group.cpp
   0: e3sm.exe           0000000008B91F56  _ZN6scream17Atmos          44  atmosphere_process.cpp
   0: e3sm.exe           0000000006FE2FE9  _ZN6scream7contro         876  atmosphere_driver.cpp
   0: e3sm.exe           00000000008591F6  _ZZ15scream_init_         195  scream_cxx_f90_interface.cpp
   0: e3sm.exe           0000000000859FF7  _ZN12_GLOBAL__N_1          51  scream_cxx_f90_interface.cpp
   0: e3sm.exe           0000000000858091  scream_init_atm           169  scream_cxx_f90_interface.cpp
   0: e3sm.exe           000000000084D2B5  atm_comp_mct_mp_a         177  atm_comp_mct.F90
   0: e3sm.exe           000000000046DAF9  component_mod_mp_         263  component_mod.F90
   0: e3sm.exe           0000000000415AEF  cime_comp_mod_mp_        1435  cime_comp_mod.F90
   0: e3sm.exe           0000000000464263  MAIN__                    177  cime_driver.F90
```

**Comment by bartgol** [comment]
That error happens in homme, when computing max/mins/sums of quantities, during the print_state calls. I think the NaN usually points to un-inited vars. I gotta check what nvar=12 was...

**Comment by ndkeen** [comment]
Just realized my ne512 cime attempts have been using the wrong resolution:
`--res ne120_r0125_oRRS18to6v3 --compset F2000SCREAMv1`

where I thought had changed it to use `--res ne512_r0125_oRRS18to6v3`, but that is not valid.

**Comment by PeterCaldwell** [comment]
> When I try --res ne512pg2_r0125_oRRS18to6v3

Recall that EAMv1 can't use pg2 grids. 

@brhillman - what grid did you use to create the ne512 IC?

**Comment by ndkeen** [comment]
Peter C suggested using resolution: `ne512np4_360x720cru_oRRS15to5`
Which did work (built, submitted).  But failed with:

```
Attempting to read ldomain from /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.r0125_oRRS18to6v3.200212.nc 
```

(at end of land log)

```
cori01% ll /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.[r0125_oRRS18to6v3.200212.nc](http://r0125_orrs18to6v3.200212.nc/)
-rw-rw-r--+ 1 taylorm taylorm 414722012 Feb 13  2020 /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.r0125_oRRS18to6v3.200212.nc
cori01% ncdump -k /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.r0125_oRRS18to6v3.200212.nc
classic
```

**Comment by PeterCaldwell** [comment]
Looks like the invalid memory reference is in homme.

**Comment by bartgol** [comment]
Usually, the error in the repro sum points to uninited memory (or memory containing garbage). I suspect there may still be issues with the grid and/or IC files.

**Comment by PeterCaldwell** [comment]
Update from yesterday: I'm pretty sure the ne512 initial condition is corrupted. See https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/3359047685/Peter+s+v1+evaluation+blog#%5Bdate%5D-Is-ne512-crash-due-to-corrupted-initial-condition-file%3F . 

I still wonder whether we will have problems with 128 level output since all our previous CIME cases have used 72 layers. Ben created 128 level ICs for ne4 and ne30: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne4np4L128_20220512.nc and /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne30np4L128_20220512.nc . 

I just tried the ne4 case (/global/cscratch1/sd/petercal/e3sm_scratch/cori-knl/F2010-SCREAMv1.ne4_ne4.16x1.128L/; just took a vanilla ne4 case and changed the IC and vertical coordinates file in namelist_scream.xml)
which failed with
```
1: PIO: FATAL ERROR: Aborting... An error occured, Reading variable (hyam, varid=10) from file 
(/global/cfs/cdirs/e3sm/inputdata/atm/scream/init/spa_file_unified_and_complete_ne30_20220428.nc, ncid=20) 
failed with PIO_IOTYPE_PNETCDF iotype. The low level (PnetCDF) I/O library call failed to read the variable (Number of 
regions = 1, iodesc id = 513, Bytes to read on this process = 128). NetCDF: Start+count exceeds dimension bound 
(err=-57). Aborting since the error handler was set to PIO_INTERNAL_ERROR... 
(/global/u1/p/petercal/gitwork/scream/externals/scorpio/src/clib/pio_darray_int.c: 1133)
```
This is the error listed at the very top of this page, which was due to thinking we were using ne512 when we configured the case as ne120. I don't think that's the problem here, but maybe I screwed something else dumb.

**Comment by PeterCaldwell** [comment]
I think we should close this issue and open a new ne512 issue because we've fixed a lot of problems since this page. Nice to get a clean start.
