### ISSUE TITLE
v0 diagnostic ice cloud fraction needs to be ported to v1

### ISSUE THREAD

**Issue by bogensch** [E3SM-Project/scream#1609]
The diagnostic ice, precipitation, and total cloud fractions introduced in PR #1307 for v0 were never converted to v1.  This has no effect on the model solution thus is currently low priority given the current v1 campaign, but v1 will eventually want to have this for diagnostic purposes.  In addition, corresponding PR #1334 will also need to be converted.

**Comment by AaronDonahue** [comment]
Are these different than the variables `cldfrac_tot`, `cldfrac_ice` and `cldfrac_liq` we have in SCREAM?

**Comment by bogensch** [comment]
cldfrac_liq is the same as the liquid cloud fraction diagnostic added in PR #1307, though cldfrac_tot and cloudfrac_ice are different than the definition added in that PR.

**Comment by AaronDonahue** [comment]
I feel like this has been done right?  @bogensch ?  If so can we close?  If not, are we happy with ice frac in v1?

**Comment by bogensch** [comment]
yeah, dishes are done
