### ISSUE TITLE
PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints with ne120 cime case

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1614]
This is the error I see when trying to write output with ne120 on cori-knl. This is with a repo from April27, while I was able to write with my repo from April11.

```
0: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np4096.0001-01-01.000500.nc) (/global/cfs/cdirs/e3sm/ndk/se02-apr27/externals/scorpio/src/clib/pioc_support.c: 3921)
```

Previously we hit an error like this (if not same) that was resolved after the PR that used the settings in XML files for CIME cases.

**Comment by whannah1** [comment]
Have you tried adding `./xmlchange PIO_NETCDF_FORMAT="64bit_data"` to your run script?

**Comment by ndkeen** [comment]
I can try that, but I've only seen that needed for ne512/ne1024. Currently it's set to `64bit_offset`

**Comment by bartgol** [comment]
Didn't we say that this error pointed to an issue with the input file? Or did you use the same input nc file for both runs (apr11 and apr27 repos)?

P.s: I like the bit `file = SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np4096.0001-01-01.000500.nc` in the output error. Is that a recent improvement in scorpio, or did you add that mod in your repo?

**Comment by ndkeen** [comment]
Indeed our ne120 cases are now using new IC files, but my understanding is that they are only different in that we added `p_int` (I think) as a variable so that certain stand-alone tests could use the same file. 

The filename in mesg is not my addition, so must be something from scorpio.

**Comment by bartgol** [comment]
> Indeed our ne120 cases are now using new IC files, but my understanding is that they are only different in that we added `p_int` (I think) as a variable so that certain stand-alone tests could use the same file.

Right, but didn't we see that `p_int` was added with the wrong layout? Namely, the incorrect `ilev,ncols` instead of the correct `ncols, ilev`. I should look in slack, but I'm quite sure something like that happened. I also thought we fixed it, but maybe that convo was for the ne30 file, and the buggy layout is still in the ne120 file?

> The filename in mesg is not my addition, so must be something from scorpio.

Nice!

**Comment by PeterCaldwell** [comment]
> Didn't we say that this error pointed to an issue with the input file?

I think there's a critical difference between the issue reported here and the dimension order problem we've been dealing with in the last few days: this issue is related to writing output after running a few steps and the dimension-ordering problem in IC files caused us to crash in init.

**Comment by ndkeen** [comment]
Using `./xmlchange PIO_NETCDF_FORMAT="64bit_data"` seems to be working (thanks Walter).
Though I suspect something isn't quite right such that we need to use that format with ne120.
The snapshots are ~40GB each. Can see them here:

`/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/se02-apr27/f120cpu.F2000SCREAMv1.ne120_r0125_oRRS18to6v3.se02-apr27.gnu.24s.n0128b32x1.N576.ts75.2sb.s8.nospa.PR1596-1600.64bitdat`

**Comment by PeterCaldwell** [comment]
Is there a reason why we don't just set 64bit_data as the default for all v1 runs?

In terms of why we need 64bit_data for ne120 in v1 but didn't in v0 - is this maybe because horiz_winds and surf_mom_flux include both u and v directions in 1 variable in v0 (and thus are 2x bigger)? I'm not asserting that's the case, just noting that v1 has slightly bigger variables.

**Comment by ndkeen** [comment]
It may be fine to always use `64bit_data`, but I'm not sure of the finer details. I just know that we don't normally need that for ne120 and could easily point to an issue.  If it's easy, can someone look at the data files in the case above to make sure nothing is obviously wrong?

**Comment by bartgol** [comment]
@ndkeen I looked at the folder you posted. I see it still uses the old xml format (our first iteration of xml defaults and buildnml). But other than that, it should be ok.

**Comment by PeterCaldwell** [comment]
Yeah, I'm looking at the output from the most recent ne120 run now. It's clear that we're going to need to change the way we analyze v1 data at higher resolution - it's freezing up my machine. I'll try to work on that this afternoon. 

The simulation doesn't look that wacky, though TKE and particularly momentum eddy diffusivity has a lot of fine scale noise - I don't think SHOC is operating correctly. I don't think this run includes the shoc lengthscale fix (judging by SHF and LHF decreasing over time), so probably not worth analyzing in a ton of detail yet.

**Comment by PeterCaldwell** [comment]
![Screen Shot 2022-05-06 at 2 26 47 PM](https://user-images.githubusercontent.com/8432529/167218660-5dad5a7a-adda-41a0-92dd-79d125cc56a5.png)

eddy_mom_diff

**Comment by ndkeen** [comment]
Right this is still with master of ~Apr27th. OK thanks, was hoping looking at the data might reveal if there is an issue as it still seems odd that we needed `PIO_NETCDF_FORMAT="64bit_data"`.

**Comment by ndkeen** [comment]
So here is something is strange. For runs using ne120 with April 11th repo, I did not need `64bit_data` and the sizes of the snapshot files were about 16G.  Now we do need them, and sizes are 40GB.

```
cori05% ls -lh bio-apr11/f120cpu.F2000SCREAMv1.ne120_r0125_oRRS18to6v3.bio-apr11.gnu.12s.n0128b32x1.nospa.N576.ts75.12sb.s8.nosurf.nocheck/run/SCREAMv1_output_hydrostatic.INSTANT.Steps_x12.np4096.0001-01-01.003000.nc
-rw-rw-r-- 1 ndk ndk 16G Apr 18 20:22 bio-apr11/f120cpu.F2000SCREAMv1.ne120_r0125_oRRS18to6v3.bio-apr11.gnu.12s.n0128b32x1.nospa.N576.ts75.12sb.s8.nosurf.nocheck/run/SCREAMv1_output_hydrostatic.INSTANT.Steps_x12.np4096.0001-01-01.003000.nc
cori05% 
cori05% ls -lh se02-apr27/f120cpu.F2000SCREAMv1.ne120_r0125_oRRS18to6v3.se02-apr27.gnu.24s.n0128b32x1.N576.ts75.2sb.s8.nospa.PR1596-1600.64bitdat/run/SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np4096.0001-01-01.000500.nc
-rw-rw-r-- 1 ndk ndk 40G May  6 09:38 se02-apr27/f120cpu.F2000SCREAMv1.ne120_r0125_oRRS18to6v3.se02-apr27.gnu.24s.n0128b32x1.N576.ts75.2sb.s8.nospa.PR1596-1600.64bitdat/run/SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np4096.0001-01-01.000500.nc
```

**Comment by bartgol** [comment]
Did we start adding more vars to the output? Otherwise, I wonder if the different format can cause the 2.5x bloating? Seems hard to believe...

**Comment by PeterCaldwell** [comment]
Yeah, that’s weird. We might have added a few new variables, but definitely not 2.5x more! Can we check an ne30 case with and without 64bit_data to see if format causes bloat?

**Comment by ndkeen** [comment]
For ne30 cases, the sizes of the snapshot files seem about the same from Apr11 to Apr27 repo.

**Comment by ndkeen** [comment]
`Max Snapshots Per File: 1` in both of those.

**Comment by ndkeen** [comment]
OK, Ben helped me to remind myself that when trying without SPA I also need to modify the output vars (to not write certain ones).

Here is a diff between the `ncdump -h` outputs:
```
cori01% diff ndump.out-bio-apr11 ndump.out-se02-apr27
1c1
< netcdf SCREAMv1_output_hydrostatic.INSTANT.Steps_x12.np4096.0001-01-01.003000 {
---
> netcdf SCREAMv1_output_hydrostatic.INSTANT.Steps_x2.np4096.0001-01-01.000500 {
6a7
>       lwband = 16 ;
7a9
>       swband = 14 ;
158a161,175
>       double aero_g_sw(time, ncol, swband, lev) ;
>               aero_g_sw:units = "1" ;
>               aero_g_sw:long_name = "aero_g_sw" ;
>       double aero_ssa_sw(time, ncol, swband, lev) ;
>               aero_ssa_sw:units = "1" ;
>               aero_ssa_sw:long_name = "aero_ssa_sw" ;
>       double aero_tau_lw(time, ncol, lwband, lev) ;
>               aero_tau_lw:units = "1" ;
>               aero_tau_lw:long_name = "aero_tau_lw" ;
>       double aero_tau_sw(time, ncol, swband, lev) ;
>               aero_tau_sw:units = "1" ;
>               aero_tau_sw:long_name = "aero_tau_sw" ;
>       double PotentialTemperature(time, ncol, lev) ;
>               PotentialTemperature:units = "K" ;
>               PotentialTemperature:long_name = "PotentialTemperature" ;
```

**Comment by brhillman** [comment]
I think you'll get the same problem *with* SPA too, really we just want to remove these variables from output in all cases I think. I think the only time they will be useful is in debugging, since they should just be remapped versions of the inputs.

**Comment by ndkeen** [comment]
Confirmed that when I remove those `aero_` cars from the output, I can write ne120 snapshot data without the need to `64bit_data` and the filesizes are back to ~16G each.  

I can close the issue, or leave open until we remove those vars from default output altogether?
