### ISSUE TITLE
p3_standalone fail with latest ne512 IC file (Error! Temperature has NaN values)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1622]
Using `p3_standalone` in the dir: `tests/uncoupled/p3`
I was trying to test reading in the new ne512 file.
I am trying on PM with a debug exe 

Rank0 output is here:
```
 0: [EAMXX] initialize_fields ... done!
 0: [EAMXX] initialize_output_managers ...
 0: [EAMXX] initialize_output_managers ... done!
 0: [EAMXX] initialize_atm_procs ...
 0: [EAMXX] initialize_atm_procs ... done!
 0: Start time stepping loop...       [  0%]
 0: Atmosphere step = 0
 0:   model time = 2021-10-12 12:30:00
 0: 
 0: 
 0: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 0: p3_standalone is a Catch v2.13.8 host application.
 0: Run with -? for options
 0: 
 0: -------------------------------------------------------------------------------
 0: p3-stand-alone
 0: -------------------------------------------------------------------------------
 0: /global/cfs/cdirs/e3sm/ndk/se02-apr27/components/scream/tests/uncoupled/p3/p3_standalone.cpp:16
 0: ...............................................................................
 0: 
 0: /global/cfs/cdirs/e3sm/ndk/se02-apr27/components/scream/tests/uncoupled/p3/p3_standalone.cpp:26: FAILED:
 0:   {Unknown expression after the reported line}
 0: due to a fatal error condition:
 0:   SIGTERM - Termination request signal
```

But note Rank28 is actually the first problematic message written and looks like:

```
28: ÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃÃKERNEL CHECK FAILED:
28:    !(is_nan_t_atm.any())
28:    Error!%s:%u: %s: block: [%d,%d,%d], thread: [%d,%d,%d] Assertion `%
28: KERNEL CHECK FAILED:

and in the standard error file, I see many:
28: :0: : block: [174,0,0], thread: [0,32,0] Assertion `` failed.
28: :0: : block: [174,0,0], thread: [0,33,0] Assertion `` failed.
28: :0: : block: [174,0,0], thread: [0,34,0] Assertion `` failed.

```

Relevant input.yaml lines:
```
Grids Manager:
  Type: Mesh Free
  Reference Grid: Point Grid
  Mesh Free:
    Number of Global Columns:   14155778
    Number of Vertical Levels:  128

# The name of the file containing the initial conditions for this test.
Initial Conditions:
  Point Grid:
    Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220505.nc
```

**Comment by ndkeen** [comment]
Using master of May6, I tried again on cpu and get a diff error mesg:

```
   0: Start time stepping loop...       [  0%]
   0: Atmosphere step = 0
   0:   model time = 2021-10-12 12:30:00
   0:
 981: Starting catch session on rank 981 out of 1024
 981: KERNEL CHECK FAILED:
 981:    !(is_nan_t_atm.any())
 981:    Error! Temperature has NaN values.
```

newer yaml style:
```
atmosphere_processes:
  atm_procs_list: (p3)
  p3:
    Grid: Point Grid

Grids Manager:
  Type: Mesh Free
  Reference Grid: Point Grid
  #Number of Global Columns:   218
  #Number of Global Columns:   48602
  #Number of Global Columns:   777602
  Number of Global Columns:   14155778
  #Number of Vertical Levels:  72  # Will want to change to 128 when a valid unit test is available.
  Number of Vertical Levels:  128

Initial Conditions:
  #Filename: /global/cfs/cdirs/e3sm/inputdata/atm/scream/init/p3_init_ne2np4.nc
  #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne30np4L72_20220503.nc
  #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne120np4L72_20220503.nc
  Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220505.nc
```

**Comment by PeterCaldwell** [comment]
I just checked the ne512 IC and it doesn't have any nans in T_mid or T_prev_micro_step. 

Is p3_standalone compiled in debug mode? Is packsize 1? If not, we should definitely try that in case the nan T you're getting is due to padding arrays up to the packsize.

**Comment by ndkeen** [comment]
This is in DEBUG

**Comment by bartgol** [comment]
If this is PM, pack size should always be 1 (though we should also be printing it at the very beginning).

**Comment by ndkeen** [comment]
This is PM, but using CPU-only nodes.  So not GPU

**Comment by bartgol** [comment]
Ah, then pack size should default to 16. I agree with Peter: a good start would be to enforce pack size of 1. You can hack the machine file, and set
```
set (SCREAM_PACK_SIZE 1 CACHE STRING "")
```
The other pack sizes cannot exceed this, so setting this is enough.

**Comment by ndkeen** [comment]
I tried PACK=1. But I'm now seeing that while ne2 works, even ne30 gives me trouble. It is running out of time, but that's after 29 minutes and I would expect this test to be much quicker?
This first step was 9.6 minutes -- eventhough this is DEBUG, that is too slow, right?

Is this OK input?

```
Time Stepping:
  Time Step: 1800
  Start Time: [12, 30, 00]      # Hours, Minutes, Seconds
  Start Date: [2021, 10, 12]    # Year, Month, Day
  Number of Steps: 5

atmosphere_processes:
  atm_procs_list: (p3)
  p3:
    Grid: Point Grid

Grids Manager:
  Type: Mesh Free
  Reference Grid: Point Grid
  #Number of Global Columns:   218
  Number of Global Columns:   48602
  #Number of Global Columns:   777602
  #Number of Global Columns:   14155778
  Number of Vertical Levels:  72  # Will want to change to 128 when a valid unit test is available.
  #Number of Vertical Levels:  128

Initial Conditions:
  #Filename: /global/cfs/cdirs/e3sm/inputdata/atm/scream/init/p3_init_ne2np4.nc
  Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne30np4L72_20220503.nc
  #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne120np4L72_20220503.nc
  #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220505.nc
```

**Comment by PeterCaldwell** [comment]
Yeah, we run the entire model at ne30 in the debug queue, so we should be able to run just P3. How many cores are you using though - could be slow if completely serial? Also, your values all look good to me. You could try setting packsize to 2 and see if that's faster and/or avoids the error. 

How many steps did you complete in 29 min? I think you said the first step took ~10 min by itself, so maybe you got through 3 or 4 of the 5 steps?

**Comment by ndkeen** [comment]
I was using 64 MPI's on 2 nodes. It ran out of time after the first step.

**Comment by bartgol** [comment]
For the record, for obvious reasons, pack size 1 should run _at most_ N times slower (where N is the vector length of the CPU), but in reality the speedup of packs is smaller than that. On KNL we see I think a speedup of about 3x when using packs of size 8 or larger (compared with pack size 1). Of course, that only accounts for computations, any init/setup/IO operation would have a fixed cost.

**Comment by bartgol** [comment]
But the fact that packsize 1 ran suggests we may be doing something wrong when we have nontrivial packs.

**Comment by PeterCaldwell** [comment]
This was packsize 1, but also ne30 instead of ne512. I think we could already run ne30 with default packsize? I'm embarrassed to say that I don't know what `-c 4` means in Noel's `-n 128 -c 4` comment above.

**Comment by ndkeen** [comment]
Right that was ne30. And ne120 just completed with 16 nodes. The output file is pretty big (11G). Trying ne512 (with output commented).

The -c flag is to srun which controls how the ranks bind to the cores.

**Comment by ndkeen** [comment]
With ne512 I get 
```
 11: Starting catch session on rank 11 out of 1024
  11: KERNEL CHECK FAILED:
  11:    !(is_nan_t_atm.any())
  11:    Error! Temperature has NaN values.
```

**Comment by PeterCaldwell** [comment]
We now know that the ne512 IC is corrupted, which probably explains this error.

**Comment by PeterCaldwell** [comment]
I wonder if p3_standalone works at ne512 now that we have a legit IC file? Could you check, @ndkeen ?

**Comment by ndkeen** [comment]
I still need to test these stand-alones again, but we know there was the issue of using 72 vs 128 levels and F cases with ne512 can run.

**Comment by ndkeen** [comment]
Closing this issue as we were using these tests to debug problems running ne1024 and have since resolved. We rarely test with ne512 anyway.
