### ISSUE TITLE
Clouds are too reflective/absorptive due to lack of subcolumn sampling in v1 model

### ISSUE THREAD

**Issue by crterai** [E3SM-Project/scream#1626]
v1 radiation currently does not run with subcolumn sampling and for its one column, it uses in-cloud properties to calculate radiaitive fluxes. This leads to too much reflected sunlight and not enough sunlight reaching the surface. This also impacts longwave radiation. 
A temporary fix until we get subcolumn sampling into v1 would be to use grid-mean water values to calculate radiation.

**Comment by PeterCaldwell** [comment]
Are you going to issue the PR to switch us to grid-mean quantities, @crterai ? Or is @brhillman ? Or someone else?

**Comment by crterai** [comment]
@brhillman's offered to put in a PR for this, since he had some additional thoughts to keep us from forgetting that we'll be using grid-mean values rather than in-cloud values for radiation.
