### ISSUE TITLE
shoc_cld_p3_rrtmgp fail at ne512 with PIO out of bounds array index

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1635]
Using master of May6th and building for CPU in DEBUG (with PACK=1), I can run this test with ne2, ne30, and ne120.
However at ne512 I hit this error right away.

`tests/coupled/physics_only/shoc_cld_p3_rrtmgp`

```
 645: Assertion failed...
 645: PIO: FATAL ERROR: Aborting... out of bounds array index (/global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/clib/pio_rearrange.c: 2574)
```

```
Grids Manager:
  Type: Mesh Free
  #Number of Global Columns:   218
  #Number of Global Columns:   48602
  #Number of Global Columns:   777602
  Number of Global Columns:   14155778
  #Number of Vertical Levels:  72  # Will want to change to 128 when a valid unit test is available.
  Number of Vertical Levels:  128

Initial Conditions:
  # The name of the file containing the initial conditions for this test.
  #Filename: /global/cfs/cdirs/e3sm/inputdata/atm/scream/init/shoc_cld_p3_rrtmgp_init_ne2np4.nc
  #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne30np4L72_20220503.nc
  #Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne120np4L72_20220503.nc
  Filename: /global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne512np4L128_20220505.nc
```

**Comment by PeterCaldwell** [comment]
I still think that the number of vertical levels could be the cause of this crash - I think ne512 is the first time we've tried that many vertical levels. It would be good to create a 128 level ne4 or ne30 IC. I think that should be easy to do, but only @brhillman knows how to do it :-). Alternatively, what happens if you just set the number of vertical levels to 72? Maybe it will ignore the levels above that index (in which case it would complete without failure).

**Comment by ndkeen** [comment]
I just tried that (only changing number of levels from 128 to 72) and i still get same error.

**Comment by PeterCaldwell** [comment]
Do we know which variable is going out of bounds? I'm wondering whether it is something defined on layer interfaces (so has 129 rather than 128 vertical levels). Though this doesn't explain why 72 layers was ok. 

Another idea is that maybe some index is overflowing as we move to higher resolution. Like, it is int32 but needs to be int64...

**Comment by ndkeen** [comment]
No I don't know. The assert is coming from PIO rearranger code and the full error message isn't much more useful. This is with DEBUG, so unfortunate not to see a stack.

```
 877: Assertion failed...
 877: PIO: FATAL ERROR: Aborting... out of bounds array index (/global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/clib/pio_rearrange.c: 2574)
 877: Obtained 10 stack frames.
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa7f92d]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa7faf8]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa7fb69]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa985f3]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa8a914]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa46e4a]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa4650f]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0xa475ee]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0x94c690]
 877: /global/cfs/cdirs/e3sm/ndk/se03-may6/cime/scripts/bld/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/./shoc_cld_p3_rrtmgp() [0x94bd29]
 877: MPICH ERROR [Rank 877] [job id 2156934.0] [Wed May 11 17:12:41 2022] [nid005549] - Abort(-1) (rank 877 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 877
 877: 
 877: aborting job:
 877: application called MPI_Abort(MPI_COMM_WORLD, -1) - process 877
```

**Comment by bartgol** [comment]
The int32 issue might be a good guess. At ne512 with 72 levels global arrays have about 170M entries. That's still in bound for int. But if you have stuff like spa arrays with an extra dimension with extent 15, then you get out of bound.

**Comment by ndkeen** [comment]
I'm using this was an issue with the code using 72 instead of 128 levels, but I've not tried this again. We can run ne512 F case (without SPA) on cori-knl and pm-cpu.

**Comment by ndkeen** [comment]
I'm going to close this issue. These were attempts to help debug problems getting higher resolutions working which we have addressed. And the ne512 case in particular is something we aren't testing with.
