### ISSUE TITLE
Use 64 bits for offsets in scorpio classes

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1638]
With ne512 we start seeing PIO errors, with indices out of bounds (see #1635).

A simple check on the math shows that large arrays (such as the aero_xyz ones used by rad) will overflow 32 bits bounds: 512x512x9x72x15=2.55B, which is OOB for int32.

**Comment by AaronDonahue** [comment]
@bartgol , is this still an issue?

**Comment by bartgol** [comment]
No, it was addressed in #1859 .
