### ISSUE TITLE
SPA file load error with 128 levels

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1646]
At both ne4 and ne30, CIME v1 runs using initial conditions with 128 levels fail with:
```
PIO: FATAL ERROR: Aborting... An error occured, Reading variable (hyam, varid=10) from file 
(/global/cfs/cdirs/e3sm/inputdata/atm/scream/init/spa_file_unified_and_complete_ne30_20220428.nc, ncid=20) failed with 
PIO_IOTYPE_PNETCDF iotype. The low level (PnetCDF) I/O library call failed to read the variable (Number of regions = 1, iodesc id
 = 513, Bytes to read on this process = 128). NetCDF: Start+count exceeds dimension bound (err=-57).
```
Note that this spa file always has 72 vertical levels - which is the same number of levels all previous v1 runs used. It is supposed to interpolate in the vertical to other grids, but perhaps it's not doing so?

128-level initial conditions on NERSC are: 
/global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne4np4L128_20220512.nc
/global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne30np4L128_20220512.nc

**Comment by AaronDonahue** [comment]
Ahh yes, this is a bug.  We need hyam and hybm for the interpolation, but here it looks like we are grabbing it from the wrong file.  Should be a straightforward fix.  I'll get on it.

**Comment by AaronDonahue** [comment]
I've found the problem, working on a fix, it's a little more involved just because of the order of operations in the AD, but the fix should be coming soon.

**Comment by AaronDonahue** [comment]
@PeterCaldwell , do you know if these two initial condition files are in the repository on Blues?  @brhillman ?

**Comment by PeterCaldwell** [comment]
no, they definitely aren't. They only exist on NERSC. I don't want to put them in the blues repo because I don't think we want to use them for anything except debugging. Though maybe we should use the ne4 one for a nightly?

**Comment by AaronDonahue** [comment]
I was going to add a 128 level unit test.

**Comment by PeterCaldwell** [comment]
Ok, ne4 128L added to blues server.
