### ISSUE TITLE
Create a medres unit test suite

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1650]
It would be useful to exercise some of our unit tests at higher resolution than ne2/ne4 in our nightlies. I keep meaning to create this suite, but never get around to it. Creating this issue to help remember.

**Comment by bartgol** [comment]
We do have a medres testsuite, although only for v1. See [here](https://github.com/E3SM-Project/scream/blob/6e06efce8500b4239644d6aca027070ab9dfb546/cime_config/tests.py#L457).

**Comment by PeterCaldwell** [comment]
Yeah, I know about that medres test suite. I meant we should create one for unit/standalone tests. Though now that I think about it, we should probably just *add* unit tests to the existing medres suite instead. So thanks for the reminder!

**Comment by PeterCaldwell** [comment]
I guess the obvious first thing to add would be homme_shoc_cld_spa_p3_rrtmgp. Is there an easy way to run that at ne30, or would I need to create a new test for it? 

I'm not sure whether we would also want to include single-process unit tests or other combos of procs, or whether we would trust that the combined test would fail whenever any individual test failed. One goal of adding these tests is making sure they work when we want to use them to isolate a problem in CIME runs (e.g. which proc causes perlmutter-opt builds to go wacky?) - this goal would benefit from including lots of tests. The other goal is just to allow differentiation between whether CIME fails are due to CIME or SCREAM parts of the code... This would only need a single standalone test.

**Comment by AaronDonahue** [comment]
We have this in place now right?  @bartgol , @PeterCaldwell , @ambrad ?

**Comment by bartgol** [comment]
Yes, we have a medres v1 testsuite (ne30).
