### ISSUE TITLE
v1 macmic equivalent does not work

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1663]
I believe the reason is that in the XML file one sees
```xml
<Num__Subcycle__Iterations>18</Num__Subcycle__Iterations>
```
In the emitted YAML one then sees
```yaml
Num Subcycle Iterations: 18
```
But in the C++ one sees
https://github.com/E3SM-Project/scream/blob/6adad54bdc6bb95ed3463719d36ebdb765dd00d6/components/scream/src/share/atm_process/atmosphere_process.cpp#L27-L29
If this last is switched to "Num Subcycle Iterations", then the macmic behavior works.

If I've gotten this right, I have a suggestion to help prevent this kind of mistake in the future. In the YAML parser, keep a table of queries for specific entires. At the end of initialization, output a warning if there are entries in the input YAML that have not been queried by any process. This isn't necessarily an error, so it shouldn't end the simulation, but an informative warning would be helpful. In the opposite direction, one might also output a list of fields processes have queried that do not have entires in the input YAML.

**Comment by bartgol** [comment]
Good catch!
