### ISSUE TITLE
ne30 F2010-SCREAMv1 CPU pack size default vs pack size 1

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1670]
With the subcycling fix and the P3 WSM fix, I find that ne30 F2010-SCREAMv1 runs out of the box on the CPU fine, but when I add `./xmlchange --append SCREAM_CMAKE_OPTIONS="SCREAM_PACK_SIZE 1"`, it fails immediately on the CPU with both negative values and NaNs in dp, leading to the negative layer thickness message.

ne4 runs with pack size 1, so it seems we can't use ne4 as a reproducer.

In a couple of days, once all the current bug-fix PRs go into the main branch, it would be good to check that this situation still holds.

**Comment by ambrad** [comment]
I'm running on Chrysalis, 320 ranks, Intel compiler.

**Comment by bartgol** [comment]
It's interesting that GPU runs also use pack size 1, but don't seem to generate negative dp (that we can tell, so far). While packsize=1 is likely part of these crashes, it should not be 100% of the story. There has to be also something peculiar to the exec space currently being used (perhaps related to host mirrors, or some enable_if switch).

When you say "fails immediately" does that mean the 1st timestep? Homme is the first atm process to run, so if that's the case we can exclude bugs (at least for the sake of this crash) in the whole physics folder.

**Comment by ambrad** [comment]
homme_atm.log shows:
```
nstep=           2  time=   600.000000000000       [s]
```
e3sm.log shows (with my additional print statements in check_source_thickness just before the "Negative (or nan) layer thickness..." msg in RemapFunctor gets emitted):
```
  0: Atmosphere step = 0
  0:   model time = 0001-01-01 00:00:00
  0:
290: amb> RemapFunctor <0: 1 0 0 -1.313436e+00
```
atm.log is empty.

**Comment by bartgol** [comment]
Ok, so this was during 1st timestep, before any physics parametrization is ever run. That should narrow down the possible set of buggy code.

**Comment by ambrad** [comment]
I've updated to today's master branch and run with GNU debug on Chrysalis and no longer see this issue. I'm not going to close it yet, though, until I'm comipletely convinced it's gone.

**Comment by ndkeen** [comment]
I have also been running ok with packsize=1 on CPU's.

**Comment by ambrad** [comment]
Closing as I can do nontrivial GNU-debg runs for the PE-layout issue with pack size 1 with today's master branch.
