### ISSUE TITLE
Suppress io_perf output in all our tests - low priority

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1688]
I'm just making a note of a wishlist for me, that would be to suppress the io performance summary statistics from SCORPIO in all of our tests.  When debugging I usually run the same test multiple times in a row and my directory ends up getting cluttered with the io_perf_*.txt files which I have to delete before I can see the other files in the directory.  I think we can just suppress these with one line, so this is a simple task for a time when we are cleaning up the code...

**Comment by PeterCaldwell** [comment]
Yeah, @ndkeen and I have also complained about this in the past. I think the fix is easy, but I never figured it out.

**Comment by sarats** [comment]
IIRC these files should be bundled up under spio_stats.tar.gz and cleaned up automatically at the end of a job. Are you folks using the recent Scorpio release (around a month or 2 ago). If you still see this, I can follow up.

**Comment by jayeshkrishna** [comment]
@AaronDonahue : Please let us know if you have issues with the latest release of SCORPIO and also include info on the test that you run (if its still an issue either me or Danqing can take a look at it)

**Comment by jayeshkrishna** [comment]
Also note that you can turn off SCORPIO I/O stats (the performance summary files etc) by configuring SCORPIO with ```-DPIO_ENABLE_IO_STATS:BOOL=OFF (default is ON).```

**Comment by PeterCaldwell** [comment]
@AaronDonahue - can I assign you to make the above change the default behavior for SCREAM? Not a high priority, but should be trivial so worth doing soon? Creating all these files could become a bottleneck for higher resolutions...

**Comment by AaronDonahue** [comment]
@PeterCaldwell , I'm happy to take this task on.  I'll note that I don't think it will be a major issue for higher resolution.  In a typical run there are only 2 files created, so not too much clutter, and they are stored in `run/spio_stats`.

I was mainly focused on when I'm running the unit tests inside scream.  If any of those tests use SCORPIO then a new set of io_perf_summary files is created.  When debugging I'm making changes and running the same test in the same directory dozens of times.

@jayeshkrishna , the unit tests won't be running through SCREAM, so this is most likely just a needed cmake flag in our unit test infrastructure.  Probably just the cmake line you pointed to above should do it.

**Comment by PeterCaldwell** [comment]
Maybe I don't understand the issue then. I thought there was a pio_log_*.txt file created for each MPI, which is a ton of files for big runs... I see now that you're talking about io_perf_*.txt which I guess is different.

**Comment by AaronDonahue** [comment]
right, it's a pretty low-priority thing.  And maybe just something that I'm focused on.

**Comment by bartgol** [comment]
It's not the same think as `io_perf_xyz.txt`, but It is a very related thing though: turning off `pio_log_N.txt` would still be helpful, and it also consists of turning off a PIO cmake option.

**Comment by sarats** [comment]
As Aaron mentioned, this only impacts the scenario where someone reuses the same run directory for a lot of tests. There are just 2 io_stats files created per run.  

So it's okay to disable for such testing but we definitely should retain this capability for normal SCREAM runs as they get archived to PACE etc.

**Comment by PeterCaldwell** [comment]
Ok, disregard my task then (unless someone wants to turn off pio_log_N.txt).

**Comment by PeterCaldwell** [comment]
@jayeshkrishna - could spio_stats.<run_name>.tar.gz be put in the run/spio_stats directory rather than in the run directory in a future PIO release? That would solve Aaron's complaints and simultaneously be more rational...

**Comment by jayeshkrishna** [comment]
We could move the I/O stats gz file to spio_stats directory, but typically for E3SM runs the other provenance info like timing info (timing*.tar.gz) etc are stored directly in the run directory. If I/O stats and logging are turned off during SCORPIO configure you should not see the files at all.
@AaronDonahue are you still having issues with SCORPIO stat files crowding up the run directory?

**Comment by sarats** [comment]
My inclination is not to move the location of the stats files. This is now baked into CIME provenance logic as well as PACE parsing backend. 

Aaron's scenario is a niche case and hopefully turning off stats entirely for his runs is a good workaround.

**Comment by PeterCaldwell** [comment]
Ok, sounds good. Thanks Jayesh and Sarat. I think we should close this issue before I come up with another hare-brained idea.
