### ISSUE TITLE
Timing files: Misc issues

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/scream#1692]
Starting this thread as I think SCREAM handles timing files a bit differently. 

I see HommeTime.0 and HommeTime_stats files but we don't have the corresponding 
e3sm_timing and e3sm_timing_stats that are written out by default E3SM.

I have various jobs that sometimes appeared to hang while writing timing checkpoints as well as the directory `timing/checkpoints` does not exist. 

Other jobs print an error at the end and perhaps related cause a job to not release resources even after successful completion. Just a guess, there might be an issue with post-run provenance as well.
```
No timing file found in run directory
ERROR: /gpfs/alpine/cli115/scratch/sarat/repos/scream/cime/scripts/ne30-64nodes/timing/e3sm_timing_stats.2093349.220527-191932 does not exists
```

**Comment by PeterCaldwell** [comment]
This issue is in some sense an extension of https://github.com/E3SM-Project/scream/issues/1610

**Comment by sarats** [comment]
Reposting my prev comment here:

I'm not sure if you folks still have this issue: GPTLstopf thread 0: timer for a_f:Total had not been started

Typically, this is because the corresponding timer start is either conditional (which wasn't met) or removed while refactoring etc.

With the prefix you identified, do you have a t_startf('Total') somewhere corresponding t_stopf('Total') for the finalization stuff?

**Comment by bartgol** [comment]
I tried to track this down earlier, but I was grepping "a_f" instead of "Total" for the timer name. Grepping the right name quickly showed the guilty file:

```
components/scream/src/dynamics/homme/interface/homme_driver_mod.F90:255:    call t_stopf('Total')
```
Do you think this is responsible for hangs or it simply causes a warning message on screen? We can fix this in a blink, if it helps.

**Comment by PeterCaldwell** [comment]
It would probably be easiest to just make the fix and see if it helps. Can you do that, @bartgol ?
