### ISSUE TITLE
Failure in post-condition for nr with ne120 on pm-gpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1698]
I have tried several PE layouts with ne120 (and ATM_NCPL=288), noted here:
https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/3363831838/Initial+performance+measurements+of+SCREAMv1+cime+cases+on+Perlmutter+pm-gpu+and+pm-cpu

Several cases run this problem for 1 day, including 256 nodes with 4x1. But when I try 256 nodes and 4x16, I see the following error after step 186:

```
 308: terminate called after throwing an instance of 'std::logic_error'
 308:   what():  /global/cfs/cdirs/e3sm/ndk/se06-may27/components/scream/src/share/atm_process/atmosphere_process.cpp:245: FAIL:
 308: false
 308: Error! Failed post-condition check (cannot be repaired).
 308:   - Atm process name: Microphysics
 308:   - Property check name: nr within interval [0, 1e+09]
 308:   - Atmosphere process MPI Rank: 308
 308:   - Error message: Check failed.
 308:   - check name: nr within interval [0, 1e+09]
 308:   - field id: nr[Physics GLL] <double:COL,LEV>(765,72) [kg^-1]
 308:   - minimum:
 308:     - value: 0
 308:     - entry: (183530,1)
 308:     - lat/lon: (-6.83454, 129.207)
 308:   - maximum:
 308:     - value: 1.04502e+09
 308:     - entry: (187900,1)
 308:     - lat/lon: (-3.96426, 133.5)
```

**Comment by AaronDonahue** [comment]
Is `1e+09` an extreme value for `nr` already?  Or can we bump this threshold up on this value?  @PeterCaldwell ?

**Comment by AaronDonahue** [comment]
Note, this still points to non-BFB behavior, which should also be addressed.  See issue #1676

**Comment by PeterCaldwell** [comment]
> Is 1e+09 an extreme value for nr already?

If I did my math right, 1e+9 #/kg is ~1000 drops per cubic centimeter. That seems high but not outlandish. I think we could increase this number to 1e+10.

**Comment by ndkeen** [comment]
I'm going to close this as I'm no longer seeing this type of problem with ne120 on pm-gpu.
