### ISSUE TITLE
Non-BFB PR's shouldn't be able to Automerge

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1708]
Would it be possible to deactivate the AUTOMERGE label if a PR also has the Non-BFB label?  Or just deactivate the AUTOMERGE ability?

Typically, we wouldn't expect both labels to be attached to the same PR, but in the edge case where they are and a PR we expect to be non-BFB ends up passing all tests, if it has been approved and has the AUTOMERGE label it will go in.  If a PR is labeled non-BFB we would expect it to fail the AT, so all tests passing should be a red-flag that holds up the PR until we figure out whats going on.

An example where this might happen would be
```
if (some_conditional_we_expect_to_trigger) {
  DO SOME NON BFB STUFF
}
```
if the conditional doesn't actually trigger than all tests may pass and it gets merged.  Other users may assume the new change has actually taken effect when in fact it hasn't.

**Comment by AaronDonahue** [comment]
I'm happy to bench this to wishlist as well.  But I think it is worth thinking about.  I added this issue after the wet/dry MMR PR went in.  It was supposed to be non-BFB but it passed the AT and automerged.  We probably would have caught that something was up if it passed and was labeled non-BFB.  Honestly, I think the simplest approach would be to have the `non-BFB` label suppress automerge, if possible.  Any non-BFB PR would theoretically need a manual merge anyways.

**Comment by bartgol** [comment]
There's no automerge in E3SM, and AT1 has been retired. Closing.
