### ISSUE TITLE
Check if rad super cycling and restart frequencies can be independent

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1712]
We observed some ERP failures withs some resolutions where REST_N and rad super cycling were such that restarts did not coincide with a rad step. We should verify that this is indeed a problem, and, if so, add checks (possibly at config time or even buildnml time) to enforce this.

**Comment by crterai** [comment]
I don't know how to enforce that REST_N falls on a rad step, but I've verified that the COMPARE_base_rest will PASS if the REST_N (and final timestep when the data is written) falls on a timestep that radiation runs.
Test that passed was `ERS_Ln10.ne30_ne30.F2010-SCREAMv1.chrysalis_intel`. `REST_N` is  `$STOP_N / 2 + 1` for ERS tests, so `Ln10` ensures that REST_N and STOP_N fall on an even timestep, when radiation runs on ne30 (`rad_frequency=2`). 
```/lcrc/group/e3sm/ac.terai/scratch/chrys/ERS_Ln10.ne30_ne30.F2010-SCREAMv1.chrysalis_intel.20220603_133759_tvapc9```

**Comment by AaronDonahue** [comment]
This looks a lot like #2201 , closing this one since that one is newer.
