### ISSUE TITLE
atmchange: comparison with an empty string?

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/scream#1713]
I get an error the first time I run this and the second time it works! 
Perhaps it might be comparing the new setting to the old (an empty string?)

Opening an issue so that it can be closed by a PR later ;)

```
[sarat@login5 ne4-t2 ]$ ./atmchange Frequency__Units=nsteps Frequency=99999999
/gpfs/alpine/cli115/scratch/sarat/repos/scream/components/scream/scripts/atm_manip.py:138: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if s is '':
[sarat@login5 ne4-t2 ]$ ./atmchange Frequency__Units=nsteps Frequency=99999999
Works!
```

**Comment by jgfouca** [comment]
@AaronDonahue , no. That line of code has been fixed and I confirmed the command works.
