### ISSUE TITLE
Friendly reminder: Semantic version for tagging releases

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/scream#1718]
You may have planned this already. Once you are ready to tag v1, please use semantic versioning similar to E3SM conventions.
Consider using a prefix (SCREAM/scream) to help easily differentiate from E3SM releases as this version tag gets archived in PACE etc.

Example: scream-v1.0.0

You can mark alpha, beta, release candidates (rc) etc. as suffixes. e.g., scream-v1.0.0-alpha.0.1.

**Comment by bartgol** [comment]
Since we are working in main e3sm repo, this seems irrelevant now.
