### ISSUE TITLE
P3 does not conserve water

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1756]
P3 does not conserve water.  This is true for both C++ and F90 implementations.  The overall error looks to be approximately .5% of the overall precipitation.  See this plot produced by @crterai for more details.
![image (2)](https://user-images.githubusercontent.com/11351562/175393326-62df1b25-ced1-4d45-bf2b-1c3bb9deefd2.png)

**Comment by AaronDonahue** [comment]
Note, due to #1755 , it is critical to set the number of subcycles in P3 to 1 when running screamV1

**Comment by AaronDonahue** [comment]
@crterai , when you have a chance to rerun the analysis can you close this issue if it is no longer relevant?

**Comment by crterai** [comment]
Okay, I've verified that the P3 water leak is much smaller now. 
For completness, I re-created the plot after the water fix PRs went in and it shows the water leak in P3 to be smaller than SHOC (and the overall water leak is an order of magnitude smaller). 

![image](https://user-images.githubusercontent.com/12244479/183502943-b661b2e7-42f2-42a3-9ffd-e1467b6e183d.png)
