### ISSUE TITLE
seg fault on Ascent

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1778]
@jgfouca reports in https://github.com/E3SM-Project/scream/pull/1777 that the tests seg fault on Ascent. SCREAM runs on Summit as late as last week without a problem. I'm wondering if the difference is due to the different modules that get loaded in cime_config/machines/config_machines.xml for ascent and summit-gpu.

summit-gpu:
```
      <modules compiler="gnugpu">
        <command name="load">gcc/7.5.0</command>
        <command name="load">cuda/10.1.168</command>
      </modules>
```

ascent:
```
      <modules compiler="gnugpu">
        <command name="load">cuda/11.0.3</command>
      </modules>
      <modules compiler="gnu.*">
        <command name="load">gcc/9.1.0</command>
      </modules>
```

spectrum-mpi is the same, so the seg fault is unlikely to be related to passing GPU pointers to MPI calls.

**Comment by ambrad** [comment]
From today's cdash I see that the seg fault is here:
```
1: 26: #11  0x130abe1f in _ZN5Homme16BoundaryExchange13pack_and_sendEv
1: 26: 	at /gpfs/wolf/cli115/proj-shared/testing/scream/components/homme/src/share/cxx/mpi/BoundaryExchange.cpp:508
```
Thus, it in fact looks like an issue with GPU pointers passed to MPI calls.

Possibly the cause of this is that, again in config_machines.xml, the ascent entry for gnupgu is missing these environment settings that the summit-gpu gnugpu entry has:
```xml
      <env name="PAMI_ENABLE_STRIPING">1</env>
      <env name="PAMI_IBV_ADAPTER_AFFINITY">1</env>
      <env name="PAMI_IBV_DEVICE_NAME_1">mlx5_3:1,mlx5_0:1</env>
      <env name="PAMI_IBV_DEVICE_NAME">mlx5_0:1,mlx5_3:1</env>
```
@jgfouca when you get a chance, would you add these to the ascent gnugpu env vars section and see if that gets the tests passing?

**Comment by ambrad** [comment]
Another missing things in the ascent xml w.r.t. the summit-gpu xml to try adding:
```xml
<arg name="smpiargs">--smpiargs="-gpu"</arg>
```

**Comment by ambrad** [comment]
test comment for slack channel

**Comment by oksanaguba** [comment]
smpiargs is probably responsible to crash.

**Comment by brhillman** [comment]
@jgfouca in the closed PR that this convo originated in, it looked like you had gotten a little further by disabling the YAKL pool allocator, but then ran into a error in radiation due to not being able to allocate memory. Can we update the conversation here, and get an up to date status report?

**Comment by jgfouca** [comment]
@brhillman , with current master and this patch:

```
--- a/cime_config/machines/config_machines.xml
+++ b/cime_config/machines/config_machines.xml
@@ -3762,6 +3762,7 @@
         <arg name="latency_priority">--latency_priority $ENV{LTC_PRT}</arg>
         <arg name="stdio_mode">--stdio_mode prepended</arg>
         <arg name="thread_vars">$ENV{JSRUN_THREAD_VARS}</arg>
+        <arg name="smpiargs">--smpiargs="-gpu"</arg>
       </arguments>
     </mpirun>
     <module_system type="module" allow_error="true">
@@ -3791,10 +3792,8 @@
         <command name="load">xl/16.1.1-10</command>
       </modules>
       <modules compiler="gnugpu">
-        <command name="load">cuda/11.0.3</command>
-      </modules>
-      <modules compiler="gnu.*">
-        <command name="load">gcc/9.1.0</command>
+        <command name="load">gcc/7.5.0</command>
+        <command name="load">cuda/10.1.168</command>
       </modules>
       <modules>
         <command name="load">spectrum-mpi/10.4.0.3-20210112</command>
@@ -3840,7 +3839,7 @@
     </environment_variables>
     <environment_variables compiler="pgigpu">
       <env name="RS_PER_NODE">6</env>
-      <env name="CPU_PER_RS">3</env>
+      <env name="CPU_PER_RS">7</env>
```

And also adding `export GATOR_DISABLE=1` to my current env, I get these errors:

```
source_func_lw%alloc: not initialized so can't allocate

optical_props::alloc: spectral discretization hasn't been provided
```

when running case `SMS_Ln22.ne30_ne30.F2010-SCREAMv1.ascent_gnugpu` on ascent.

**Comment by ambrad** [comment]
Completed long ago.
