### ISSUE TITLE
warning GPTLinitialize: has already been called is written too often (once per MPI)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1791]
`GPTLinitialize: has already been called`
It doesn't take a very large problem for this to become really annoying to see in e3sm.log.
A job with 85 nodes using 128 MPI's per node means we get this 10880 times.

In `share/timing/gptl.c`

```
  if (initialized)
    return GPTLerror ("%s: has already been called\n", thisfunc);
```

For some cases I can change this to `return 0;` to avoid the messages, but this causes trouble for other cases when it tries to do timing summary work at end of run and crashes.

**Comment by bartgol** [comment]
This is a known issue. GPTL does not offer a function like `is_initialized()` to check if GPTL was already inited, so the AD runs `GPTLinitialize` to "check" if it was (a return code different from 0 is interpreted as "it was already inited").

In standalone runs, we do have to manually init GPTL. I suppose we could just check whether we're in a standalone or CIME run, and just use that info to determine whether to init/finalize GPTL (do it in standalone, don't do it in CIME runs).

**Comment by ambrad** [comment]
Can the SCREAM CPP symbol SCREAM_CIME_BUILD be used around the call to GPTLinitialize in AtmosphereDriver::init_scorpio?

**Comment by ndkeen** [comment]
like this?  
```
void init_gptl (bool& was_already_inited) {
  //ndk try this as suggested by AMB                                                                                                                                                                                                                                              
#ifdef SCREAM_CIME_BUILD
#else
  auto ierr = GPTLinitialize();
  was_already_inited = (ierr!=0);
#endif
}
```

**Comment by ndkeen** [comment]
Hmm, when I try that, I'm still getting the warnings.  I see that maybe I should be using 
`#ifdef SCREAM_CONFIG_IS_CMAKE`
which _does_ work.

I had grabbed `#ifdef SCREAM_CIME_BUILD` from a grep and found it in C++:
```
./src/share/io/scream_scorpio_interface.F90:625:#ifdef SCREAM_CIME_BUILD
./src/share/io/scream_scorpio_interface.F90:642:#ifdef SCREAM_CIME_BUILD
./src/share/io/scream_scorpio_interface.F90:880:#if !defined(SCREAM_CIME_BUILD)
./src/share/io/scream_scorpio_interface.F90:903:#if !defined(SCREAM_CIME_BUILD)
```

and perhaps that should be changed to `SCREAM_CONFIG_IS_CMAKE`

`SCREAM_CIME_BUILD` is used in cmake files.

**Comment by bartgol** [comment]
Uhm, `SCREAM_CIME_BUILD` _should_ be a valid CPP symbol. It is the first symbol `cmakedefine`d in `scream_config.h.in`.

**Comment by ndkeen** [comment]
OK, I can just make PR to add a guard for the warning.  I was just guessing the other location was a mistake, but was going to test before making a PR -- we can make a diff issue for the macros in that file.
