### ISSUE TITLE
SCREAM_CIME_BUILD macro being used, but not set 

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1796]
Might want to change something about this situation.  When building a CIME case, the `SCREAM_CIME_BUILD` macro is used in cmake, but not set in source files.  Only place found was here:

```
./src/share/io/scream_scorpio_interface.F90:625:#ifdef SCREAM_CIME_BUILD
./src/share/io/scream_scorpio_interface.F90:642:#ifdef SCREAM_CIME_BUILD
./src/share/io/scream_scorpio_interface.F90:880:#if !defined(SCREAM_CIME_BUILD)
./src/share/io/scream_scorpio_interface.F90:903:#if !defined(SCREAM_CIME_BUILD)
```

**Comment by bartgol** [comment]
It is cmakedefine-d in `scream_config.h.in`, so it is available in the generated `scream_config.h` file (and its analogue `scream_config.f` for fortran).

Any code that needs a different behavior in CIME builds than it does in standalone builds should include `scream_config.h` (or the `.f` if in a fortran source file), and use the macro.

**Comment by ndkeen** [comment]
Are you saying that no change is needed here? 

I'm not sure how different the stand-alone build is, but it kinda looks like `SCREAM_CIME_BUILD` will never be defined for that file.

**Comment by ndkeen** [comment]
So for this file, it currently *does* use `SCREAM_CIME_BUILD`, so you are suggesting we include `scream_config.h` which, would then change the behavior of those functions (if they are used) for our CIME builds.

**Comment by bartgol** [comment]
Yes, that's correct.

**Comment by ndkeen** [comment]
I do see `#include "scream_config.f"`
Which I cannot find -- is that auto-generated or a typo?

**Comment by bartgol** [comment]
Yes, that's auto-generated. But it should be only included by Fortran files.

**Comment by bartgol** [comment]
Yeah, that's a fairly standard paradigm: have a `config.h.in`  in the src folder, and use CMake (or autotools) to generate a `config.h` in the bld dir.

**Comment by ndkeen** [comment]
Yep, that variable is being set via the auto-generated `.f` include correctly. I now see it's all fine the way it is.
Closing.
