### ISSUE TITLE
SHOC: pref_mid should be computed and not read from file

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1806]
It's basically `a*ps0 + b*ps_ref`. Right now it appears that pref_mid in the ne3 and ne30 IC files is wrong, leading to npbl=1 (hence the "bug" label in addition to "infrastructure"). But rather than fix those IC files, it would be better to follow the approach in EAM and compute pref_mid.

**Comment by bartgol** [comment]
About `ps_ref`: is it the initial ps from the IC file? Is it ps as computed by dynamics at every step? Or something else?

**Comment by ambrad** [comment]
It's just a typical surface pressure ref value.

**Comment by ambrad** [comment]
One can follow EAM's dyn_grid_get_pref.

**Comment by tcclevenger** [comment]
From `eam/src/utils/hycoef.F90` (called from `dyn_grid_get_pref()`), 
```
pref_mid(k) = hypm(k) = hyam(k)*ps0 + hybm(k)*psr,       ps0 = psr = 1e5
```

It looks like both Homme and SPA both load variables called `hyam` and `hybm` from file, but they come from different files. 
```
Homme: screami_unit_tests_ne4np4L72_20220718.nc,   SPA: spa_file_unified_and_complete_ne4_20220428.nc
```

`pref_mid` is only used in shoc, so should these coords again be load from file there? Or should we grab these values once in the driver/process group from file, and then SPA, SHOC, and Homme reference these values and do their computations from there?

**Comment by bartgol** [comment]
SPA needs hybrid coords _on the mesh where the SPA data is defined_. Those could potentially be different (definitely if SPA data is on a grid with less/more levels).

OTOH, SHOC and Homme need the hybrid coordinate of the mesh where the simulation is being run on.

**Comment by tcclevenger** [comment]
Ok that makes sense. Then maybe we should just load in `hyam/hybm` in `atmosphere_macrophysics` like home does.

**Comment by ambrad** [comment]
You can grab the hyam/hybm values from HybridVCoord data structure from Hommexx rather than read them in again.

**Comment by tcclevenger** [comment]
> You can grab the hyam/hybm values from HybridVCoord data structure from Hommexx rather than read them in again, in case you were thinking about doing the latter.

Yeah, that will be the easiest.

**Comment by tcclevenger** [comment]
Does it make sense that `ps0 = psr`? Or am I missing one of those being updated?

**Comment by ambrad** [comment]
No, ps0 is the TOM pressure. psr should be reference surface pressure, something like 1013 hPa. Check EAM's procedure for details.

**Comment by bartgol** [comment]
I'm a bit hesitant to have SHOC access Homme's stuff, since we make SHOC dependent on Homme. However, we should be able to stuff the hyam/hybm views in the grid, along other geometry data, during the grids construction.

**Comment by PeterCaldwell** [comment]
Yeah, I agree that SHOC should not use HOMME's functions or data because we want people to be able to use SHOC in other models or in standalone mode. That said, I'm less opposed to using HOMME data structures/functions in the SHOC interface layer. Ideal would be to pass ps_ref out of HOMME init into some structure known to physics.

**Comment by ambrad** [comment]
Right, the idea is to make a utility routine that any dycore must provide to make pref_mid. What I meant above was that SHOC's interface would call this routine, and this routine would be impl'ed using Hommexx's HybridVCoord data structure. This follows EAM's approach to providing dyn_grid_get_pref.

**Comment by tcclevenger** [comment]
@ambrad I'm attempting to follow the `ps0,psref` trail through eam, but I'm a bit confused. 

Following `pref_mid` from `eam/src/physics/cam/shoc_intr.F90 - shoc_init_e3sm()`:

In shoc_intr.F90: `use ref_pres, only: pref_mid`
In ref_pres.F90:                                   `call dyn_grid_get_pref(pref_edge, pref_mid, num_pr_lev)`
In eam/src/dynamics/.../dyn_grid.F90: `pref_mid(k)  = hypm(k)`
In eam/src/utils/hycoef.F90:                  `hypm(k) = hyam(k)*ps0 + hybm(k)*psr`
                                                             `ps0 = 1.0e5_r8    ! Base state surface pressure (pascals)`
                                                             `psr = 1.0e5_r8    ! Reference surface pressure (pascals)`

The only other definition of reference pressure I'm finding is in `eam/src/dynamics/sld/grmult.F90` where they calculate
```
pref = hyam(k)*ps0 + hybm(k)*psref,    ps0 = hycoef.F90::ps0, psref = 101325
```

**Comment by ambrad** [comment]
@tcclevenger yes, you're right. Sorry, wasn't thinking hard enough about ps0 yesterday. ps0 = psref is fine. 1e5 is a fine value for psr.
