### ISSUE TITLE
SHOC: calculate_dx_from_area assumes radian lat but gets degree lat input

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1807]
I suspect this doesn't really matter because it just contributes to a small ellipsoid correction to the sphere, but it would be better to do the calculation correctly or just switch to a sphere assumption.

**Comment by PeterCaldwell** [comment]
I'd like @bogensch comment on whether we should just delete this correction. 

If it is needed (or maybe even if it is just easier to switch radian->deg), I think this might be a good task for Hannah (whose git handle I can't find).

**Comment by bogensch** [comment]
I will say that I have extensively verified the v0 version of this calculation (which also uses degree lat) produces very reasonable and representative values of dx input to SHOC for a variety of ne resolutions (and RRM) that I would expect.  Aaron and I also verified this when in v1 when he made PR #1598, so I'm very comfortable with the values currently being produced from this routine.  Thus, I don't think this is super critical for September 1st.... but of course, I think it should probably eventually be corrected to be consistent...  In summary, fixing this will likely have negligible impact on the model solution.
