### ISSUE TITLE
Output field not initialized error when adding LiqWaterPath output and related fields

### ISSUE THREAD

**Issue by crterai** [E3SM-Project/scream#1810]
The ability to add vertically integrated cloud liquid, vapor, ice, and rain water paths was added with PR#1761. With master `35de2d4`, when `LiqWaterPath` is requested as an output, the following error results in a crash. Although note tested, I suspect it also affects `VapWaterPath`, `IceWaterPath`, and `RainWaterPath`.
```
5376: terminate called after throwing an instance of 'std::logic_error'
5376:   what():  /global/u1/t/terai/SCREAM/scream/master/components/scream/src/share/io/scorpio_output.cpp:193: FAIL:
5376: field.get_header().get_tracking().get_time_stamp().is_valid()
5376: Error! Output field 'LiqWaterPath' has not been initialized yet
5376: .
```

**Comment by bartgol** [comment]
I see the issue. I can fix it quickly.

**Comment by crterai** [comment]
Great, thanks @bartgol!

**Comment by ndkeen** [comment]
I can show how to reproduce if it helps

**Comment by bartgol** [comment]
Thanks. I was able to reproduce in standalone mode, by asking for `VapWaterPath` in the homme standalone test. And I verified that this branch fixes it.
