### ISSUE TITLE
calculate_z_int use in diagnostics causes error on weaver cuda_mem_check

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1813]
There are three tests that are failing the `cuda_mem_check` test suite on the GPU machine `weaver`.  The three failed tests are

- dry_static_energy
- vertical_layer_interface
- vertical_layer_midpoint

All three of which are diagnostics tests.  The one thing they all have in common is that they must calculate the vertical_layer_interface, `z_int`, as a step or as the final product. 

The error message looks like:

```
========= Invalid __global__ read of size 4
....
```

and I have tracked the offending line down to the calculation of `z_int` within the diagnostics definitions.  See the lines:

https://github.com/E3SM-Project/scream/blob/master/components/scream/src/diagnostics/dry_static_energy.cpp#L87
https://github.com/E3SM-Project/scream/blob/master/components/scream/src/diagnostics/vertical_layer_interface.cpp#L74
https://github.com/E3SM-Project/scream/blob/master/components/scream/src/diagnostics/vertical_layer_midpoint.cpp#L76

I still am not sure what the issue is, although I suspect it has something to do with the use a local view_1d defined above and maybe an issue with host vs. device access.

**Comment by AaronDonahue** [comment]
@bartgol or @ambrad I feel like I'm probably abusing HOST vs DEVICE in these diagnostics. Maybe the issue is more clear to you both because you have more experience.

**Comment by ambrad** [comment]
I think one issue is that you're using m_num_levs inside a kernel, which is a class var. You need to make a local copy for the lambda to capture.
