### ISSUE TITLE
Issue with CheckAndRepairWrapper

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1834]
I think Homme's use of CheckAndRepairWrapper (CARW) is wrong. And I'm also wondering if that class should exist at all.

Originally, the intent of CARW was to allow different tolerances during check and repair phases. The goal was, say for a LB check, to crap out if field F is "significantly below LB", and repair values "just below LB". But that's not what's happening. So long as CARW stores a PropCheck repair object, the check method will never cause the overall CARW to fail, and the repair object will always clip to LB.

I think I have to change the concept of [CheckResult](https://github.com/E3SM-Project/scream/blob/2e0f5dcf50dac46ebff6c26b4fd6cd03c99b79a3/components/scream/src/share/property_checks/property_check.hpp#L45): rather than storing a `bool pass;`, it should store an enum, with possible values along the line of `Pass, CatastrophicFail, RepairableFail`. PC classes like FieldWithinIntervalCheck should then store two LB/UB, to determine if something is within reasonable distance from the bound (and therefore fixable) or completely off.

E.g., Homme could use a FieldLowerBoundCheck with LB1=-1e-17, LB2=0. If min(F)<LB1, return `CatastrophicFail`, if LB1<min(F)<LB2, return `RepairableFail`, otherwise return `Pass`.

**Comment by PeterCaldwell** [comment]
Uh oh. Does this mean that our runs are all catastrophically bad, but are held together by incessant large repairs?

**Comment by bartgol** [comment]
> Uh oh. Does this mean that our runs are all catastrophically bad, but are held together by incessant large repairs?

Not necessarily. Our infrastructure still prints the values that are "bad" before repairing them. We would see "very bad" neg values printed if that happened.

**Comment by ambrad** [comment]
I suspect we don't have catastrophically bad out-of-bounds values, but @bartgol, a 90-day ne30 simulation produces something like >1 GB of postcondition warnings in the log file, so the chance that anybody spots a really bad value is quite low.

**Comment by bartgol** [comment]
Yeah, that's true. We still haven't fixed the amount of warnings printed when fields are fixed.
