### ISSUE TITLE
Negative (or nan) layer thickness detected with ne30pg2 on cori-knl/intel with PACKSIZE=1

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1847]
Using scream master of Aug5th, I've been trying pg2 on pm-cpu with GNU. I recently tried on cori-knl with intel and I see runtime error below with PACKSIZE=1:

```
   0: Atmosphere step = 0
   0:   model time = 0001-01-01 00:00:00
   0:
1350: Negative (or nan) layer thickness detected, aborting!
1350: Exiting...
```

The same test does work with GNU (on cori-knl and pm-cpu) using PACKSIZE=1.

The following tests seem to be working (which use default PACKSIZE):
```
SMS.ne30pg2_ne30pg2.F2010-SCREAMv1-noAero.cori-knl_intel
SMS_D.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_intel

SMS_D.ne30pg2_ne30pg2.F2010-SCREAMv1-noAero.cori-knl_gnu
SMS_D.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_gnu
```

**Comment by ambrad** [comment]
It's possible that -noAero is doing it. Note that ERS_Ln22.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_intel passes stably in the nightlies.

**Comment by ambrad** [comment]
Based on your updated issue description, my guess is this case is another instance of #1726.

**Comment by ndkeen** [comment]
Yes, I was looking for that issue. I can close this one.
