### ISSUE TITLE
EAMxx_tests_IC_FILE_72lev needs to be updated

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1851]
During some separate work I noticed that the default test initial condition file is for an ne4 initial condition, but the tests are all set to be ne2.  So the initial condition file for our tests in the `components/scream/tests` directory needs to be updated.

This means a remap of the ne4 IC file for testing to an ne2 file version.
then make the change in `components/scream/tests/CMakeLists.txt`

Making this issue so I don't lose sight of this bugfix.

**Comment by bartgol** [comment]
Our IC files for unit tests are now ne2.
