### ISSUE TITLE
replay.sh does not have quotations

### ISSUE THREAD

**Issue by oksanaguba** [E3SM-Project/scream#1856]
this is probably very minor, but when using replay.sh, it does not have quotation marks,

```
./xmlchange SCREAM_CMAKE_OPTIONS=SCREAM_NP 4 SCREAM_NUM_VERTICAL_LEV 128 SCREAM_NUM_TRACERS 10
```

vs

```
./xmlchange SCREAM_CMAKE_OPTIONS="SCREAM_NP 4 SCREAM_NUM_VERTICAL_LEV 128 SCREAM_NUM_TRACERS 10"
```

**Comment by AaronDonahue** [comment]
I'm guessing this was fixed when the above 4361 went in.  @oksanaguba feel free to repopen if I'm wrong about that.
