### ISSUE TITLE
Tests reported on cdash for cori-knl failing with Intel

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1868]
Both `ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1` and `PEM_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1` are failing with COMPARE. Might not be same root cause, but just starting an issue.

They are using Intel compiler.

The ne30pg2 case is only using 1 node and we should bump that to using more nodes on this machine, though I'm not sure that's the reason for the fail here.
(`PEM_P2048_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_intel` also fails compare)
the DEBUG case is also fail compare:
`PEM_D_P2048_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_intel`

For both tests, looks like they pass with GNU (ie the following all pass):
```
ERP_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.cori-knl_gnu
ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.cori-knl_gnu

PEM_P2048_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_gnu (note using more nodes)
```

I see that `PEM_D_P2048_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_gnu` fails with floating-point exception, but no stack
```
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s56-aug16/PEM_D_P2048_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-knl_gnu.20220816_174124_lrp708
```

**Comment by ambrad** [comment]
I'm investigating the PEM case.

**Comment by ndkeen** [comment]
I tested these 2 cases on the intel-based GCP which has `intel-oneapi-compilers/2021.3.0`. The following all passed:

```
PEM_P720_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.gcp_intel

ERP_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.gcp_intel
ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.gcp_intel
```

**Comment by ndkeen** [comment]
Since it's easy and I'm curious about the newer versions of Intel compiler installed on cori, I tried the two failing tests with 2 newer versions.

```
intel/19.0.3.199 currently used in master
intel/19.1.2.254 the machine default
intel/19.1.3.304 highest version installed on machine
```

Will update results here:
```
fail compare -- ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.cori-knl_intel.intel1912 
```

**Comment by ndkeen** [comment]
I also tried these tests using the same Intel compiler, but on cori-haswell.  They both passed.

```
ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.cori-haswell_intel
PEM_P2048_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.cori-haswell_intel
```

Pointing to an issue with Intel and KNL. Can try modifying compiler flags.

**Comment by ndkeen** [comment]
cdash shows these are passing and I just tried them myself -- PASS. I had been slowly trying different compiler flags -- indeed to make scream files have similar flags as cime. But I was still seeing fails. I can only guess the passing started with the PR to use same flags in scream as cime. Will just close.
