### ISSUE TITLE
Add calendar (no leap year) info in the metadata of time output for v1

### ISSUE THREAD

**Issue by crterai** [E3SM-Project/scream#1872]
In the v1 output, the time dimension should include information that denotes that there are no leap years in the SCREAMv1 model. Including this info will avoid any confusion down the road when analyzing data (where the timestamp on the output file doesn't match up with what `time` gives when using analysis software like xarray. 
What the `time` variable metadata shows in v1:
```
	double time(time) ;
		time:units = "days since 2010-01-01 00:00:00" ;
		time:long_name = "time" ;
```
For reference, here is what the v0 (EAM) output of time gives:
```
	double time(time) ;
		time:long_name = "time" ;
		time:units = "days since 1979-01-01 00:00:00" ;
		time:calendar = "noleap" ;
		time:bounds = "time_bnds" ;
```

**Comment by bartgol** [comment]
Btw, I think the default in scream is to use leap year:
```
option(SCREAM_HAS_LEAP_YEAR "Whether scream uses leap years or not" ON)
```
Perhaps this default has to be changed too then.

**Comment by crterai** [comment]
Oh, interesting. Based on the offset that I was seeing (output file time stamp said 2013-01-06 and xarray thought it was 2013-01-05), I'd assumed that it was running with no leap year but perhaps worth testing around a Feb 29th date. 
Either way, it would be good to have the output indicate with the `calendar` metadata whether it's one or the other and have it be consistent with what the model is actually running.

**Comment by crterai** [comment]
Okay, I ran the test, and it looks like SCREAMv1 skips the leap-day. It would be good to make everything consistent and make them all indicate no leap years. 

```
/pscratch/sd/t/terai/e3sm_scratch/pm-gpu/ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.leapyeartest.20220817master/run

ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.leapyeartest.20220817master.scream.hi.AVERAGE.nsteps_x48.2012-02-28-00000.nc
ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.leapyeartest.20220817master.scream.hi.AVERAGE.nsteps_x48.2012-03-01-00000.nc
ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.leapyeartest.20220817master.scream.hi.AVERAGE.nsteps_x48.2012-03-02-00000.nc
ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.leapyeartest.20220817master.scream.hi.AVERAGE.nsteps_x48.2012-03-03-00000.nc
```

**Comment by bartgol** [comment]
Interesting. I have to check if something is amiss in the TimeStamp update.
