### ISSUE TITLE
Need to seriously speed up memcheck build

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1883]
The build as a whole is taking about 1h45m to complete. This is too much, especially considering it's only one fraction of what mappy needs to run every night (scream standalone dbg/sp/fpe/opt, scream standalone coverage, scream standalone memcheck, e3sm_master, e3sm_next, cldera-e3sm).

One test currently takes 1h40m to run (basically slowing down the whole build):
```
homme_shoc_cld_spa_p3_rrtmgp_128levels_np1 ... 1h 40m 42s 310ms
homme_shoc_cld_spa_p3_rrtmgp_128levels_np2 ...    55m 22s 440ms
homme_shoc_cld_spa_p3_rrtmgp_128levels_np3 ...    44m 12s 950ms	
homme_shoc_cld_spa_p3_rrtmgp_128levels_np4 ...    44m 12s 130ms
```
The same test, on 72 levels takes ~40% less time to run.

Things to consider when thinking about a solution:
- Testing np4 is probably enough. If we have no memory errors in ||, we can be fairly confident we won't have any in serial.
- We do want to test nlev%packsize=0 as well as nlev%packsize>0. We could run nlev=72 with packsize=16 and packsize=8.
- Increasing compiler optimization (keeping -g) might give some improvement in performance, bringing down overall test time.
- If we address #1882 we might get memcheck build to start while other builds are still running (sp build is very fast). Since the long tests are few (after removing np1,np2,np3), it might be beneficial to start memcheck as soon as sp is over, even if we get fewer cores than running memcheck by itself. Or maybe not. But worth checking.
- We might not have to test all omp threads from 1 to 16. Even though tests that use omp threads are fast, ompN with large N uses a good chunk of the machine, reducing concurrency. And p3_tests_omp3 still takes 11m, so not peanuts. Perhaps we can run with SCREAM_TEST_THREAD_INC=7 (omp1, omp8, omp15), which will still test both ends of the spectrum.

Note: all of this is for the memcheck build only. Other builds can keep doing what they do, since they're fast enough (longest test, homme_shoc_cld_spa_p3_rrtmgp_128levels_np1, takes about 8m for the full_debug build).

**Comment by jgfouca** [comment]
@bartgol , it looks like things have improved since you filed this ticket. Some combination of srun managing resources better and/or better use of the SCREAM_TEST_SIZE=SHORT mechanic. The nightlies report that the mem-check run of test-all-scream is taking about 50m now, which I think is reasonable, especially now that mappy's throughput has improved with the srun changes.
