### ISSUE TITLE
History Checkpointing should automatically sync with restart writing

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1887]
We currently ask the user to specify the frequency and units for writing output checkpoints.  This is controlled by the `Checkpoint Control` field in the output control yaml file.  It makes more sense to synchronize the writing of checkpoints to correspond with writing a restart file, since we are not likely going to need an output checkpoint unless we are also restarting the run.

**Comment by bartgol** [comment]
The user is no longer able to specify checkpoint frequency. Instead, the AT sets the specs based on restart freq/option. Closing.

**Comment by bartgol** [comment]
The user is no longer able to specify checkpoint frequency. Instead, the AT sets the specs based on restart freq/option. Closing.
