### ISSUE TITLE
Error when trying cudatoolkit 11.7 on pm-gpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1896]
Currently, we are using `cudatoolkit/11.5` on pm-gpu, but the machine default is now `cudatoolkit/11.7`. When I tried using newer version, I get an error with standard ne30pg2 case:

```
 0: Atmosphere step = 0
 0:   model time = 0001-01-01 00:00:00
 0: 
 0: terminate called after throwing an instance of 'std::logic_error'
 0:   what():  /global/cfs/cdirs/e3sm/ndk/se17-aug24/components/scream/src/dynamics/homme/atmosphere_dynamics.cpp:486: FAIL:
 0: false
 0: cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /global/cfs/cdirs/e3sm/ndk/se17-aug24/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:151
 0: 
 0: Program received signal SIGABRT: Process abort signal.
```

This also included updates to other modules (now machine default):
`cray-mpich/8.1.17 cray-hdf5-parallel/1.12.1.5 cray-netcdf-hdf5parallel/4.8.1.5 cray-parallel-netcdf/1.12.2.5`
but if I only reduce version of cudatoolkit back to 11.5, run completes.

**Comment by ambrad** [comment]
Would you write exact instructions (e.g., a repo diff) to do the module swap(s)?

**Comment by ndkeen** [comment]
With `ndk/se18-aug25` I have pm-gpu using cuda 11.7

I also have commented out what you could do to update other modules (cray-mpich and netcdf).

And then I have 3 tests in `/global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se18-aug25`

```
perlmutter% lr */run/e3sm*
-rw-rw-r-- 1 ndk e3sm 33233 Aug 25 13:13 SMS_Ln5.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.cuda117/run/e3sm.log.3050031.220825-131245
-rw-rw-r-- 1 ndk e3sm 33233 Aug 25 13:23 SMS_Ln5.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.cuda117modup/run/e3sm.log.3050047.220825-132306
-rw-rw-r-- 1 ndk e3sm  5803 Aug 25 13:52 SMS_Ln5.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.cuda115modup/run/e3sm.log.3050106.220825-135159.gz
```

**Comment by ndkeen** [comment]
I tried this again with Nov 16th repo.  That is, updating `cudatoolkit/11.5` to `cudatoolkit/11.7` and trying
`SMS_Ln5.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu` 
The case completed. So either the above error was not reproduceable, or something has changed.

I will try a few more cases and then close.

**Comment by ndkeen** [comment]
I also tried it with ne256 case on 48 pm-gpu nodes for 1 day.

Will close
