### ISSUE TITLE
Support for both monolithic and many small kernels to address Crusher/Frontier challenges.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1903]
The AMD compilers for the AMD GPUs, e.g. hippcc, are having a hard time with large kernels, SHOC in particular. Error modes include spurious segmentation faults, hanging, and two types of failures to allocate registers during compilation. Right now we have a workaround for SHOC, but it makes SHOC very slow, much slower than the dycore for example.

Fortunately, our column-physics s/w design accommodates both monolithic (LK) and many small kernels (SK). Recall that LK is generally best on the CPU because it encourages good caching, it minimizes memory footprint due to temporaries, and it has been fine on Nvidia GPUs; thus we have favored it so far. LK is also harder to design for, so it's good to design it in up front and retreat to SKs as needed with optional configuration flags. Here I outline what we should do to help SCREAMv1 run well on Crusher/Frontier.

The keys to accommodating both LK and SK are:

1. function decomposition and
2. the workspace manager.

Consider shoc_main_internal as an example. In the LK approach, the workspace manager manages nslot work slots for the ncol columns. On the GPU, it's possible by design (to decrease the memory footprint) for nslot < ncol. shoc_main_internal acts on one column at a time, calling a long sequence of subroutines on the same column data, with the work slots holding temporary data.

In the SK approach, we will set nslot = ncol always. Each subroutine call in shoc_main_internal will be replaced by a top-level Kokkos loop (KOKKOS_LAMBDA, a kernel dispatch) over ncol. Work slots will hold data persistently between kernel dispatches.

To enable both LK and SK, we need to do the following:

1. Introduce a new SCREAM CMake variable, SCREAM_MONOLITHIC_KERNELS (or something like that), defaulting to ON.

2. Introduce a new EKAT CMake variable, EKAT_WORKSPACE_NSLOT_EQ_NCOL (or something like that), defaulting to OFF.

3. In SCREAM, if SCREAM_MONOLITHIC_KERNELS is OFF, force EKAT_WORKSPACE_NSLOT_EQ_NCOL to be ON.

4. In shoc_main, ifdef SCREAM_MONOLITHIC_KERNELS, do what is currently done; else, add new code to call an alternative version of shoc_main_internal.

5. In the alternative shoc_main_internal, replace each subroutine call with a dispatch loop calling the subroutine. The local scalars should be stored in an extra work slot.

6. Optionally, make each dispatch its own subroutine and put it in its own cpp file. This will have two benefits: (1) shorter compilation time (many small translation units to build in parallel) and (2) if there is an internal compiler error (ICE), it will be immediately obvious what bit of code is triggering the ICE. To support this capability, the CMake code will have to add a bunch of cpp files to the source file list if SCREAM_MONOLITHIC_KERNELS is OFF.

We should start with SHOC because it is the problem at the moment, but P3 should eventually support SCREAM_MONOLITHIC_KERNELS, too.

**Comment by ambrad** [comment]
This is for SCREAMv1.1, but I've marked the priority as high because of internal and external interest in Crusher/Frontier.

**Comment by jgfouca** [comment]
I will take this on and bring in additional help if/when needed.

**Comment by bartgol** [comment]
+1 for option 6, if possible. The build time of shoc and p3 on GPU is quite large (up to 5min for a couple of files). For those doing lots of mod-compile-test cycles on GPU, using SK config might be a good way to increase productivity.

**Comment by tcclevenger** [comment]
Re 6: shorter compilation time AND easier identifiable ICEs? Yes.
