### ISSUE TITLE
Build error on pm-gpu after PR to use CIME flags 

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1905]
After `[#1895 Propagate flags set by CIME to scream](https://github.com/E3SM-Project/scream/pull/1895)`, a test worked (built/ran) on pm-cpu, but failed on pm-gpu.

```
cd /global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se20-aug29/f30.F2010-SCREAMv1.ne30_ne30.se20-aug29.gnugpu.5d.n004a4xX14444/bld/cmake-bld/scream/src/dynamics/homme/homme/composec++ && /global/cfs/cdirs/e3sm/ndk/se20-aug29/externals/ekat/extern/kokkos/bin/kokkos_launch_com$
In file included from /global/cfs/cdirs/e3sm/ndk/se20-aug29/externals/YAKL/src/YAKL.h:4,
                 from /global/cfs/cdirs/e3sm/ndk/se20-aug29/externals/YAKL/src/YAKL.cpp:2:
/global/cfs/cdirs/e3sm/ndk/se20-aug29/externals/YAKL/src/YAKL_header.h:26:10: fatal error: mpi.h: No such file or directory
   26 | #include <mpi.h>
      |          ^~~~~~~
compilation terminated.
```

I see that for the compilation of YAKL.cpp, there are some flags used in previous repo, that are not here now. But I'm not yet sure if that's actually the issue or not. For example, I don't see these flags thrown for YAKL.cpp: `-DGPU -DHAVE_MPI -DLinux -DMCT_INTERFACE  -DNO_R16 -D_PNETCDF` in older version.

Note also that YAKL.cpp is the only file built with nvcc.

One hack that allows the build to complete for me is to change 2 sources to force not having MPI. We probably need to do something like: change the compiler used for that YAKL.cpp, change only the flags passed to that one file, allow HAVE_MPI by also adding a `-I`, etc

**Comment by ndkeen** [comment]
I see tests on ascent are building, so might be something specific to machine.

**Comment by bartgol** [comment]
I think this is related to the fact that `common_setup.cmake` adds `HAVE_MPI` to the CPP defs. This makes YAKL include `mpi.h`, but we never link MPI to YAKL, so YAKL can't find it. Notice that we _do_ link MPI to `ekat`, which is linked to all scream, so the rest of scream is fine. We can try to link it to YAKL too, if HAVE_MPI is on. I'll try a ninja branch to fix this.
