### ISSUE TITLE
Homme interface: n0_qdp vs np1_qdp in homme_post_process

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1916]
This is a cosmetic issue, but I think it would help make the code clearer. Right now, this block of code https://github.com/E3SM-Project/scream/blob/7b2ecc1d469ecf397872e1304b5ecebf7a316e5b/components/scream/src/dynamics/homme/atmosphere_dynamics.cpp#L634-L644 seems to do something strange for the tracers: it uses np1_qdp rather than n0_qdp. The reason is that tl.update_tracers_levels hasn't been called. If it is, then n0_qdp will work. Moreover, subsequent calls to update_tracers_levels will be idempotent, making code less dependent on whether or not update_tracers_levels has been called.

@bartgol agree?

**Comment by bartgol** [comment]
Yeah, I have never liked the fact that n0 is the right level for states, but np1 is the one for tracers. I am not sure if this should be fixed in Homme or scream though. It might have to do with what Homme internally thinks the up to date state/tracer level is...

**Comment by ambrad** [comment]
The dycore makes a call to update_tracers_levels immediately before doing anything with qdp. So it's really just a scream-side issue in restart, where it wants to do something with qdp before the next dycore time step updates the pointers. Anybody is free to update them prematurely, though, as subsequent calls are idempotent since nstep is the data.

Thus, we can add a tl.update_tracers_levels call at the end of prim_subcycle_c if we want, but even if we do, we need to update the scream side, too (np1_qdp -> n0_qdp). I propose making a PR for scream to rationalize this and then, later, we could optionally change the dycore, too.

**Comment by ambrad** [comment]
Let's drop this. Way too low of a priority.
