### ISSUE TITLE
Write a 2d output slice from a 3d variable

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1929]
For our Sept production run, we really need to be able to write 2d slices from some of our field-managed 3d variables. Some use cases (with item 1 being necessary, item 2 being important, and item 3 being wishlist):
1. write 2d outputs from the lowest or highest model levels of a 3d variable to allow us to write TOA (top of atmosphere) or bot (surface) output. It would be slightly more useful and very easy to extend this to write output on any particular level. For example, we might write LW_flux_up(:,:,0) out as LW_flux_up_TOA (or LW_flux_up_0lev).
2. write a variable interpolated to a particular pressure level (e.g. `LW_flux_up_500mb`). 
3. write a variable interpolated to a particular geometric height above sea level (e.g. `LW_flux_up_10m`).

Note that this task includes a subtask of writing a 2d slab and another subtask of appending the level as a string on the end of the variable name. 

We can implement this either as a general capability that allows us to extract a 2d slice from any variable or we can make a hack for this specific set of simulations which adds derived diagnostics for the 10 or so variables we want to write out.

**Comment by AaronDonahue** [comment]
This has been addressed in recent PRs
