### ISSUE TITLE
Hang on pm-gpu at specific location in LND init when using fewer than 24 nodes at ne120

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1939]
For the ne120pg2 case I have been testing, I started to see it hang pretty consistently on pm-gpu (not other machines) on 11 nodes. I found that it would not hang with different node count, but not convinced it's solely dependent on PE layout.

I was just noting this hang as it does not happen with ne30/ne256/ne1024.  Except when it did -- I had a hang in the same location for ne256 and then just now with a ne1024 run (using same PE layout, etc that I normally use).

It happens during init, last lines of cpl.log:
```
(seq_mct_drv) : Initialize each component: atm, lnd, rof, ocn, ice, glc, wav, esp, iac
(component_init_cc:mct) : Initialize component atm
(component_init_cc:mct) : Initialize component lnd
```

End of lnd.log:
```
 Attempting to read soil color, sand and clay boundary data .....
 (GETFIL): attempting to find local file surfdata_0.125x0.125_simyr2010_c191025.nc
 (GETFIL): using /global/cfs/cdirs/e3sm/inputdata/lnd/clm2/surfdata_map/surfdata_0.125x0.125_simyr2010_c191025.nc
 Opened existing file /global/cfs/cdirs/e3sm/inputdata/lnd/clm2/surfdata_map/surfdata_0.125x0.125_simyr2010_c191025.nc          28
 Attempting to read organic matter data .....
 organicrd                       /global/cfs/cdirs/e3sm/inputdata/lnd/clm2/surfdata_map/surfdata_0.125x0.125_simyr2010_c191025.nc
 (GETFIL): attempting to find local file surfdata_0.125x0.125_simyr2010_c191025.nc
 (GETFIL): using /global/cfs/cdirs/e3sm/inputdata/lnd/clm2/surfdata_map/surfdata_0.125x0.125_simyr2010_c191025.nc
```

Example of hanging ne120 case: `/global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se28-sep8/f120.F2010-SCREAMv1-noAero.ne120pg2_r0125_oRRS18to6v3.se28-sep8.gnugpu.1d.n011a4x1`

Example of hanging ne256 case:
`/global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se28-sep8/f256.F2010-SCREAMv1-noAero.ne256pg2_r0125_oRRS18to6v3.se28-sep8.gnugpu.1d.n024a4x16ci2.ICjun6/`

Actually, for the ne1024 case, the hang was NOT in same location as it looks like it completed init and is maybe on the first step.  So for ne1024 case, might be a different issue.
`/global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se29-sep11/f1024.F2010-SCREAMv1-noAero.ne1024pg2_ne1024pg2.se29-sep11.gnugpu.1d.n0384a4xX18888c2.t100`

**Comment by ambrad** [comment]
Does intermittent mean that if you run ./case.submit in the same case directory, the next run might not hang?

**Comment by ndkeen** [comment]
Ah, no, I suppose not. Right now I can only say that the ne120 case hangs every time I try it with 11, 16, or 22 nodes.  And does not hang with the 32 or 43 node attempts. I know that the ne120 case will run with as few as 6 nodes of pm-cpu.

**Comment by ndkeen** [comment]
A few more tests show that the hanging with the ne120 cases appears dependent on the number of pm-gpu nodes used.  It hangs with 11,16,20,22 nodes, but does not hang with 24,30,32,43 nodes. This points to the amount of memory available, but I'm skeptical that this is the root issue here as there should be enough memory.

**Comment by ndkeen** [comment]
If these issues are related, I'm sure we can simplify and better describe conditions causing hang (and not sure they are same flavor of hang), but noting in this issue https://github.com/E3SM-Project/scream/issues/1920 I can run when I request that no `elm.h0` files be written.

**Comment by ndkeen** [comment]
I might just close this as it looks like any job with 24 or more nodes will not show this. It's still disturbing to me that a failure mode is to "hang".

**Comment by ndkeen** [comment]
Using the same set of libfabric env vars that allow us to write restarts without hanging on another issue, I can run ne120 with as few as 8 nodes. Also tried 11 and 22 nodes.  So I think the following env vars could be a work-around for this specific issue, which could easily be just a variation of the other issues and was triggered by different PE layout.

```
setenv FI_CXI_DEFAULT_CQ_SIZE 71680
setenv FI_CXI_CQ_FILL_PERCENT 90
setenv FI_CXI_REQ_BUF_SIZE 12582912
setenv FI_UNIVERSE_SIZE 4096
```

**Comment by ndkeen** [comment]
We think we have a work-around for this issue that also seems to work for other hanging issues on PM.  It will need to be upstreamed to scream, of course.  https://github.com/E3SM-Project/E3SM/pull/5291
