### ISSUE TITLE
Slowdown related to PR 1931

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1942]
I ran PEM_Ln90.ne30pg2_EC30to60E2r2.F2010-SCREAMv1-MPASSI with and without PR #1931 and see the following:

With PR:
```
"CPL:INIT"                             168 1.680000e+02   8.273370e+03    49.595   48.960  // init looks fine
"CPL:RUN_LOOP"                         168 1.512000e+04   7.863434e+03    46.905   46.802  // time stepping is fine
"a_f:EAMxx::finalize"                  168 1.680000e+02   2.965438e+04   176.573  176.457  // big slowdown ...
"a_f:PIO:syncfile"                     168 1.680000e+02   2.953458e+04   175.905  175.714
"a_f:PIO:PIOc_sync"                    168 1.680000e+02   2.953458e+04   175.905  175.714
"a_f:PIO:write_total"                  168 3.360000e+02   2.953458e+04   175.905  175.714
"a_f:PIO:flush_buffer"                 168 6.720000e+02   2.953457e+04   175.905  175.714
"a_f:PIO:PIOc_write_darray_multi"      168 6.720000e+02   2.953456e+04   175.905  175.714
"a_f:PIO:write_darray_multi_serial"    168 6.720000e+02   1.475772e+04   175.801    0.633  // ... with this as the lowest-level timer
```

Without PR:
```
"CPL:INIT"                             168 1.680000e+02   6.430998e+03    38.748 37.862
"CPL:RUN_LOOP"                         168 1.512000e+04   8.028902e+03    47.879 47.787
"a_f:EAMxx::finalize"                  168 1.680000e+02   1.556985e+02     1.114  0.916
"a_f:PIO:syncfile"                     168 1.680000e+02   3.616856e+01     0.414  0.146
"a_f:PIO:PIOc_sync"                    168 1.680000e+02   3.616827e+01     0.414  0.146
"a_f:PIO:write_total"                  168 3.360000e+02   3.617823e+01     0.416  0.146
"a_f:PIO:flush_buffer"                 168 6.720000e+02   3.545426e+01     0.289  0.146
"a_f:PIO:PIOc_write_darray_multi"      168 6.720000e+02   3.544924e+01     0.289  0.146
```

In the latter case, there is no write_darray_multi_serial timer. Thus, I suspect that something in the PR, perhaps only in the single-precion output case, has switched the scorpio write mode to being serialized in parts.

**Comment by bartgol** [comment]
Ah, I think Summit shows the same behavior. I launched the runs, and didn't bother watching them until a while later, so I did not notice that they took a long time to finish, stuck in write phase. 

Double:
```
timer                        wall max
--------------------------------------------------
"a_f:PIO:syncfile"                   1463.450
"a_f:PIO:PIOc_sync"                  1463.450
"a_f:PIO:write_total"                1463.450
"a_f:PIO:flush_buffer"               1463.450
"a_f:PIO:PIOc_write_darray_multi"    1463.450
"a_f:PIO:rearrange_comp2io"          0.001
"a_f:PIO:pio_swapm"                  0.001
"a_f:PIO:write_darray_multi_serial"  1463.426
```
```
timer                        wall max
--------------------------------------------------
"a_f:PIO:syncfile"                   907.684
"a_f:PIO:PIOc_sync"                  907.684
"a_f:PIO:write_total"                907.684
"a_f:PIO:flush_buffer"               907.684
"a_f:PIO:PIOc_write_darray_multi"    907.684
"a_f:PIO:rearrange_comp2io"          0.002
"a_f:PIO:pio_swapm"                  0.001
"a_f:PIO:write_darray_multi_serial"  907.652
```

**Comment by bartgol** [comment]
I grepped for RUN timers, but should have looked at the others too.

**Comment by bartgol** [comment]
Standalone scream tests on weaver do not exhibit this behavior:

right after PR merged (with double precision output):
```
PIO:write_total                6.401
PIO:PIOc_write_darray          1.291
PIO:flush_buffer               3.680
PIO:PIOc_sync                  3.686
PIO:PIOc_write_darray_multi    2.974
PIO:rearrange_comp2io          0.265
PIO:write_darray_multi_serial  1.882
```
right before PR merged:
```
PIO:write_total                6.737
PIO:PIOc_write_darray          1.290
PIO:flush_buffer               3.968
PIO:PIOc_sync                  3.975
PIO:PIOc_write_darray_multi    3.108
PIO:rearrange_comp2io          0.257
PIO:write_darray_multi_serial  1.873

```
Which is surprising, since Andrew is not seeing the `multi_serial` timer without the PR. Perhaps we're doing unwise things in setting up PIO defaults in CIME cases... Still, not sure why that PR would create any issue, given that PIO setups are identical, and nothing should change with double output precision...

**Comment by ambrad** [comment]
I double checked and definitely am not seeing multi_serial with the PR reverted. Is it possible the standalone test has always used a bad PIO mode, so it's not a good test for this particularly issue?

**Comment by bartgol** [comment]
Ah, that's def a possibility. In standalone we pick some values for io type, mode, rearranger, etc. Might be that the combination we pick always cause the multi serial routine to run.

I'm still not sure why multi serial would run with double data type after the merge but not before the merge. The code does the same thing. Though maybe something changed at setup time, perhaps some extra pio setting for the var. I'll keep digging.

**Comment by ambrad** [comment]
Just a random guess, but is it possible a switch from the F90 to the C++ PIO interface (as I interpret the mods based on a quick glance at the PR) has dropped some settings the F90 interface automatically provides?

**Comment by bartgol** [comment]
We did not switch from F90 to C++ in the PR. We still go through scorpio's flib.

**Comment by ambrad** [comment]
Oh, OK. I was basing this guess on the addition of pioc to the scream_io target.

**Comment by bartgol** [comment]
Yeah, I added explicit dep on pioc only because I needed to read some `PIO_XYZ` macro value directly from cxx.

**Comment by ambrad** [comment]
This was fixed.
