### ISSUE TITLE
Post condition fail with low T_mid at ne1024/ne256

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1950]
There may already exist an issue for this error.

With ne1024, cases on summit and pm-gpu have hit the same error. And now I'm able to reproduce the error with ne256 case on pm-gpu. This is error with the ne256 case after it ran for just over 2 months (model date `00010305`).

```
367: terminate called after throwing an instance of 'std::logic_error'
367:   what():  /global/cfs/cdirs/e3sm/ndk/se29-sep11/components/scream/src/share/atm_process/atmosphere_process.cpp:266: FAIL:
367: false
367: Error! Failed post-condition check (cannot be repaired).
367:   - Atmosphere process name: Dynamics
367:   - Property check name: T_mid within interval [130, 500]
367:   - Atmosphere process MPI Rank: 367
367:   - Message: Check failed.
367:   - check name: T_mid within interval [130, 500]
367:   - field id: T_mid[Physics PG2] <double:COL,LEV>(2048,128) [K]
367:   - minimum:
367:     - value: 123.764
367:     - entry: (1494334,1)
367:     - lat/lon: (65.9676, 223.161)
367:   - maximum:
367:     - value: 291.196
367:     - entry: (1494336,1)
367:     - lat/lon: (65.849, 222.864)

/global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se29-sep11/f256.F2010-SCREAMv1-noAero.ne256pg2_r0125_oRRS18to6v3.se29-sep11.gnugpu.3m.n192a4x16ci2.IC914a.so288n1.noew
```

To get around the issue with ne1024, we have been increasing guard rails on T to allow 100 increase of 130. I also tried this with ne256, but it has only run 1 month and now I see I need to run longer (a 3-month attempt failed with `cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered` so submitting again)
I did run this case with 

Using a repo from Sep 11th that includes a team_barrier bugfix.  Also, for the ne256 case, I'm using Ben's latest IC file from Sep 14th, and setting qc, qi, nc, ni to zero. For ne120 (and presumably ne256), I had some troubling issues where the job would hang while writing `elm.h0` files. It seems to continue if I ask that those files not be written:
```
cat <<EOF >> user_nl_elm
hist_nhtfrq = -99999999
hist_mfilt = 1
hist_empty_htapes = .true.
EOF
```

**Comment by ndkeen** [comment]
Trying ne256 again without guard rails and it is running beyond the point it failed above.

```
/global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se29-sep11/f256.F2010-SCREAMv1-noAero.ne256pg2_r0125_oRRS18to6v3.se29-sep11.gnugpu.3m.n192a4x16ci2.IC914a.so288n1.t100.w500.noew
```

I will try to let it run longer still

**Comment by ambrad** [comment]
Here's the location (red x), mask, and topo, the latter two assuming these inputdata are correct:
* share/domains/domain.lnd.ne256pg2_oRRS18to6v3.200212.nc
* atm/cam/topo/USGS-gtopo30_ne256np4pg2_16xdel2_20200213.nc
![ne256pg2_lowTmid_0](https://user-images.githubusercontent.com/3401413/190879446-343e25b0-e4e8-4f33-8c8c-176aa0a24df4.png)
Much less interesting than the ne1024pg2 case we've looked at previously:
* share/domains/domain.lnd.ne1024pg2_ICOS10.211018.nc
* atm/cam/topo/USGS-gtopo30_ne1024np4pg2_16xconsistentSGH_20190528_converted.nc
![ne1024pg2_lowTmid_0](https://user-images.githubusercontent.com/3401413/190879466-31c1d9bc-498a-4580-abe1-c150bd3ccad0.png)

**Comment by ambrad** [comment]
I recommend bringing this 13 Sep commit into your repo if you don't have it: https://github.com/E3SM-Project/scream/commit/ab6fa9767d161608747faa80f66fcf981a781793 This is the commit that finished fixing issue #1917.

**Comment by ndkeen** [comment]
I do have the fix adding the team_barrier in this repo.

**Comment by ndkeen** [comment]
The case that uses wider guard rails for T & wind reached `model date =   00010630` before crashing with negative layer thickness error.

We also see negative layer error with ne120 cases https://github.com/E3SM-Project/scream/issues/1951

**Comment by ndkeen** [comment]
Still using Sep 19th repo, I tried some suggestions by others to look at the ne256 issues.

1) Use `dt_remap_factor=2` -- I simply ran the same case (including wider guard rails) but with this change. It ran 1 month and about 27 days to `model date =   00010227` at expected performance (~2.2 sypd) and then for some reason, suddenly slowed down to about 0.3 sypd (getting this from the reported time per day in cpl.log).  I'm assuming there's no reason for the code to do this and it must be something happening on the machine. I let it continue anyway and it reached `model date =   00010405` before stopping with a "Bus error".  So it did not reach the point at which it was hitting negative layer thickness as reported above (at ~6 months).  I can run it again?

```
f256.F2010-SCREAMv1-noAero.ne256pg2_r0125_oRRS18to6v3.se30-sep19.gnugpu.1y.n192a4x16c2.IC914a.so288n1.t100.w500.noew.dtr2
```

2) Try `Ckh_s_max = 0.25` instead of `Ckh_s_max = 0.1` (for several vars named similarly).
This run also hit a generic "Bus error" after only 23 days. The performance woudl be about 1.3 sypd which, unless these changes are known to impact performance, could point to more machine performance issues.

```
/global/cfs/cdirs/e3sm/ndk/e3sm_scratch/pm-gpu/se30-sep19/f256.F2010-SCREAMv1-noAero.ne256pg2_r0125_oRRS18to6v3.se30-sep19.gnugpu.1y.n096a4x16c2.IC914a.so288n1.t100.w500.noew.ck25
```

In general, I do see "Bus errors" (as well as other generic errors) for runs on PM where simply resubmitting is OK.  Counting these via grep, since Aug24th, I have about 250 jobs that have tried to run on pm-gpu and 15 of them stopped with Bus error.

**Comment by ambrad** [comment]
Sorry I wasn't clear. I meant dt_remap_factor=1, not 2.

**Comment by ndkeen** [comment]
Oh ok -- that experiment was actually with `dt_remap_factor=1`, but I see I misnamed the case to be `dtr2` and meant to name it `dtr1`.

**Comment by ndkeen** [comment]
I'm finally able to get decent performance again on pm-gpu -- not sure what was happening before. 
```
48 nodes for 1 day (no IO) 0.7 sypd
96 nodes for 1 day (no IO) 1.2 sypd
```
I've submitted longer cases using `dt_remap_factor=1` as well as `Ckh_s_max = 0.25` at ne256.

**Comment by AaronDonahue** [comment]
Are these results both ne256?

**Comment by ndkeen** [comment]
yes -- did you think it might be ne1024?

**Comment by AaronDonahue** [comment]
No, I thought it would be a little high, but better to check then assume 😀

**Comment by ndkeen** [comment]
With a Sep29th repo, I tried ne256 using `dt_remap_factor=1` 
This case only ran 13 days before hitting a cold T.

```
184: terminate called after throwing an instance of 'std::logic_error'
184:   what():  /global/cfs/cdirs/e3sm/ndk/se32-sep29/components/scream/src/share/atm_process/atmosphere_process.cpp:274: FAIL:
184: false
184: Error! Failed post-condition check (cannot be repaired).
184:   - Atmosphere process name: Dynamics
184:   - Property check name: T_mid within interval [130, 500]
184:   - Atmosphere process MPI Rank: 184
184:   - Message: Check failed.
184:   - check name: T_mid within interval [130, 500]
184:   - field id: T_mid[Physics PG2] <double:COL,LEV>(4096,128) [K]
184:   - minimum:
184:     - value: 127.96
184:     - entry: (1507626,127)
184:     - lat/lon: (61.7833, 219.166)
184:   - maximum:
184:     - value: 283.149
184:     - entry: (1507627,124)
184:     - lat/lon: (61.5632, 219.206)

/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se32-sep29/f256.F2010-SCREAMv1-noAero.ne256pg2_r0125_oRRS18to6v3.se32-sep29.gnugpu.1y.n096a4xXc2.so288n1.noew.dtr1
```

**Comment by ndkeen** [comment]
Using same Sep29th repo, but after long PM maintenance, I tried another case to run for only 16 days after adjusting the guards to allow for colder T.  Job completed 16 days without issue.

**Comment by ndkeen** [comment]
As discussed on the telecon today, I'm running another case using Nov 9th repo. One difference is that I'm now running _with_ SPA.  I'm also using a fix to the problem of hanging while writing restarts.
I do not have any changes in place to avoid cold T by widening guard rails.

The case is running here: `/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se41-nov9/f256.F2010-SCREAMv1.ne256pg2_r0125_oRRS18to6v3.se41-nov9.gnugpu.3m.n096a4xX.so1n18.modup.MCS`
