### ISSUE TITLE
Vertical slices of Diagnostic output

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1960]
The way vertical slicing is currently implemented it is expected that whatever we are vertically slicing is itself a Field in the field manager.  Since diagnostics are not stored in the Field Manager per se they are not candidates for vertical slicing.  But there may be applications where we want a diagnostic at a certain level.  For example:

```
VerticalLayerThickness@bot
```
which is equivalent to `z_mid` at the bottom.  `z_mid` is not explicitly a Field Managed variable so we have it set up as a "diagnostic" for output.

**Comment by bartgol** [comment]
To be clear, I don't think FieldAtLevel assumes anything about the provenance of the input field. In the IO class, we grab the 3d field with `get_field(fname)`, which should still allow it to be provided by a diagnostic.

I suspect what you are saying is that you would like to write `z_mid` instead of `VerticalLayerThickness`. That's fine, and it basically boils down to register the diagnotic with a different name. That is, in register_diagnostic.hpp, replace
```
diag_factory.register_product("VerticalLayerThickness",&create_atmosphere_diagnostic<VerticalLayerThicknessDiagnostic>);
```
with
```
diag_factory.register_product("z_mid",&create_atmosphere_diagnostic<VerticalLayerThicknessDiagnostic>);
```
Adding the second line, keeping the first, would still work, though I suspect few would use 'VerticalLayerThickness' if 'z_mid' is available...

Am I correct? Or are you saying that `VerticalLayerThickness@bot` is not currently working?

**Comment by PeterCaldwell** [comment]
I don't think we care what the variable is called. Aaron told me that FieldAtLevel wouldn't work with diagnostic variables. If it does work, I think we are good to go. If it doesn't work, I don't think it's a high enough priority to fix (unless it's super easy).

**Comment by AaronDonahue** [comment]
I'm going to have to confirm, but I recall changing the name to the proper VerticalLayerThickness@bot and having that fail. Maybe I misspelled it, it is a long name.

**Comment by AaronDonahue** [comment]
```
/ascldap/users/asdonah/sandbox_1/scream/components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/homme_shoc_cld_p3_rrtmgp.cpp:31: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  /ascldap/users/asdonah/sandbox_1/scream/components/scream/src/share/io/
  scorpio_output.cpp:653: FAIL:
  false
  Field VerticalLayerMidpoint not found in output field manager or diagnostics
  list
```

This is the error I get when adding `- VerticalLayerMidpoint@bot` to the output.yaml file for a standalone test.  When I remove the `@bot` it runs fine.  Which seems to indicate that the `VerticalLayerMidpoint` is working just fine.  When the run ends I see in the output file the following.  (NOTE:  This is when I remove `@bot`)

```
...
		sfc_flux_sw_net:long_name = "sfc_flux_sw_net" ;
	float VerticalLayerMidpoint(time, ncol, lev) ;
		VerticalLayerMidpoint:units = "m" ;
		VerticalLayerMidpoint:long_name = "VerticalLayerMidpoint" ;

// global attributes:
		:source = "E3SM Atmosphere Model Version 4" ;
...
```

**Comment by bartgol** [comment]
I see what the problem is. Likely, the `FIeldAtLevel` diag is set _before_ `VerticalLayerMidpoint`, so when calling `get_field("VerticalLayerMidpoint")`, we don't find it yet.

@PeterCaldwell I think it's an easy fix, so I might just go ahead and fix it.

**Comment by AaronDonahue** [comment]
@bartgol , another question about FieldAtLevel.  Should it work for fields that have more than 2 dimensions.  Like for example `horiz_winds`?  So would we expect to be able to do `horiz_winds@bot`?

**Comment by bartgol** [comment]
I don't see why not.
