### ISSUE TITLE
Strange behavior on summit

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1973]
This issue is just to document any strange behavior I see on Summit in case it is relevant to other issues we may encounter.

1. CIME RESUBMIT option does not work, even when runs finish and write a restart.  If I submit a job with RESUBMIT=1 and it finishes and exits cleanly I don't see a resubmitted job put in the queue.
2. Jobs will sometimes hang when an error is thrown.  Often if I run a job that encounters some error printed to the e3sm log, so for all intent an purposes the run is finished I still have to kill the job in the queue before it will finish.  Could it be that scream errors are not making it back to the main model and so it is stuck in some sort of limbo?

**Comment by AaronDonahue** [comment]
Note, for the RESUBMIT behavior, I see in the case directory that `CONTINUE_RUN` does switch to be true.

**Comment by PeterCaldwell** [comment]
@jgfouca ^^^: Are you the person who would know about CIME_RESUBMIT?

**Comment by PeterCaldwell** [comment]
Regarding hangs: would it make sense/would it be hard to add some code to EAMxx that would detect hangs and abort? Like maybe if no log messages get written in 5 min? I suspect it would be hard because if a job is hung in radiation (for example), it would never get back to the code that checks if it is hung. Maybe we'd have to create a separate process that monitors and sends slurm the kill signal if triggered?

**Comment by AaronDonahue** [comment]
I would note that the hangs are after an error has been thrown, stacktrace and everything.

**Comment by whannah1** [comment]
Summit has always hung on error for me. It's actually been a huge problem where my job will stay in the queue for hours after getting a random CFL error in the CRM. I've reached out to various people about this at OLCF and elsewhere and no one seems to understand it or think that it's worth fixing. I've just gotten used to monitoring my jobs more frequently so I can manually kill things when I catch them hanging. Shortening the jobs can also help.

**Comment by PeterCaldwell** [comment]
OMG that's so frustrating Walter. It blows my mind that OLCF wouldn't care if users are wasting tons of time not computing anything. That should be included in their Linpack timing!

**Comment by AaronDonahue** [comment]
@whannah1 , thanks for that info.  So I can at least scratch this one off as a scream-related issue.

**Comment by whannah1** [comment]
I recall someone at OLCF telling me that my allocation wasn't actually being spent after a run had crashed, but I'm not sure whether to believe that or not... I might be able to dig that up in an email.

**Comment by AaronDonahue** [comment]
> I recall someone at OLCF telling me that my allocation wasn't actually being spent after a run had crashed, but I'm not sure whether to believe that or not... I might be able to dig that up in an email.

Seems like a weird thing to say, presumably the scheduler still thinks those nodes are busy... so at the very least you are holding up other peoples jobs.

**Comment by PeterCaldwell** [comment]
Yeah: "Summit is the fastest computer in the world. We use half of it for science, and the other half is used waiting for failed jobs to time out"

**Comment by jgfouca** [comment]
@AaronDonahue , @PeterCaldwell , CONTINUE_RUN indicates where a case should resume from its most recent restart checkpoint or start over. RESUBMIT>0 should be all you need to ensure a resubmission. There are race conditions in CIME when xmlchanging things while a CIME process is already running, so it's possible you just got very unlucky. We've run into similar issues in the past with users like Chris Golaz in this ticket https://github.com/ESMCI/cime/issues/3338 . I believe that has all been resolved and is tested in CIME's standalone testing.

**Comment by AaronDonahue** [comment]
@jgfouca , ahh okay.  I am for sure changing RESUBMIT before I do case setup and case submit.  And I feel like I've confirmed that RESUBMIT is 1 when the run starts.  But it is in fact 0 when it finishes.  I might put in a quick test with RESUBMIT=2 and see if it drops to 1 but doesn't resubmit.

**Comment by jgfouca** [comment]
@AaronDonahue , are you setting RESUBMIT before the initial submission or while it's running?

**Comment by AaronDonahue** [comment]
before

**Comment by AaronDonahue** [comment]
I just changed it again and submitted a debug job.  I'll see if that successfully resubmits.  Maybe my script is messing things up...

**Comment by AaronDonahue** [comment]
Does CIME drop RESUBMIT by 1 when the run starts?  or at case.submit?  I changed resubmit to 1 and did `case.submit` and now the run is going and I see `RESUBMIT` is 0.

**Comment by jgfouca** [comment]
@AaronDonahue , ok, so that eliminates the race condition possibility entirely. This is routine CIME stuff so it seems like there must be something going on on the user side. You can paste your script here if you want.

**Comment by AaronDonahue** [comment]
Oh wait, I think I've got it.  It looks like from the std output in the case_scripts directory that it tried to resubmit but couldn't because this was a debug job and summit only allows one debug job at a time.  So since the job is still technically running summit kills the job.

**Comment by jgfouca** [comment]
@AaronDonahue , nice find. That explains why this works everywhere else.

**Comment by jgfouca** [comment]
Should I close ticket with the "solution" that you just can't do resubmits on summit debug, or do you want a real solution that would likely take some CIME re-work?

**Comment by AaronDonahue** [comment]
No, I think it's okay to not resubmit on debug.  It's a pretty edge case.  I'm testing my theory on batch, once I confirm I'll close the issue.

**Comment by AaronDonahue** [comment]
Confirmed that resubmit works if the queue on summit is batch.  Closing this issue.

**Comment by jgfouca** [comment]
@AaronDonahue , that's a big relief, thanks.
