### ISSUE TITLE
Change implementation of get_vector_dim in FieldLayout

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1996]
Right now, it returns the _index_ of the `CMP` tag. Compare this with the method `int dim(const FieldTag t)`, which returns the extent of the dimension with the given tag (assuming there's only one). This is confusing. On top of that, in all the places where we call `get_vector_dim` we're actually interested in the _extent_ of that dimension.

Hence, we should change the impl to return the extent of the `CMP` dimension. Basically, replace impl with `return dim(FieldTag::Component);`.

**Comment by mjs271** [comment]
closed by #2746
