### ISSUE TITLE
When not using threads, don't build with openmp flags (and maybe use serial kokkos backend)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1997]
I found that for cases not using threads, there is a very small perf improvement to use the serial kokkos backend rather than our current openmp backend.  I also see that openmp flags are used with openmp backend builds, but not with serial (not sure if those are already tied together).  E3SM will only use openmp flags if any component requests threads.

Here are some results (tables at bottom)
https://acme-climate.atlassian.net/wiki/spaces/EPG/pages/3532849992/SCREAM+ne30pg2+results+on+pm-cpu+and+pm-gpu

Note these also use the ZEN3 kokkos target, but other experiments shows that ZEN3 target performs about same as current ZEN2 target

Can we query if threads are being used for a given case and build appropriately?

**Comment by ndkeen** [comment]
Noting comments from Luca B:
"We should be able to do it, yes. I'm assuming cime passes info to the model regarding threading? If so, scream needs to adjust the Kokkos cmake options values, based on it. A clean solution might require some better design, but a quick way to do it should be

```
if (NOT USE_THREADS) #<- or whatever cime's cmake var for enabling threading is
  set (Kokkos_ENABLE_OPENMP OFF)
  set (Kokkos_ENABLE_SERIAL ON)
endif()
```
somewhere at the top of scream's CMakeLists.txt.
this will, of course, only disable OpenMP. If we need/want to support multiple host backends (e.g. Kokkos::Threads ), this has to be adjusted. Hence my comment about needing to think about a long-term clean solution"

**Comment by bartgol** [comment]
One minor obstacle to a clean solution: right now, scream standalone _preloads_ the mach file into the cache, while CIME _includes_ the mach file. The difference is that, when preloading in the cache, the only valid statements in the mach file are
```
set (VAR value CACHE TYPE "doc string")
option (VAR "docstring" value)
```
Any other cmake operation is not valid. OTOH, including the file, we can ping other cache vars, and do conditional behaviors.

In short, if we moved scream to _always_ include the file (like e3sm does), inside our mach files, we could do
```
include (${EKAT_MACH_FILES_PATH}/kokkos/amd-zen3.cmake)
if (USE_THREADS)
  include (${EKAT_MACH_FILES_PATH}/kokkos/openmp.cmake)
else()
  include (${EKAT_MACH_FILES_PATH}/kokkos/serial.cmake)
endif()
```

Pinging @jgfouca in case he has some thought on this.

**Comment by jgfouca** [comment]
@bartgol let me investigate this use case.

**Comment by ndkeen** [comment]
This seems to be working for me.

```
if (${SMP_PRESENT})
  include (${EKAT_MACH_FILES_PATH}/kokkos/openmp.cmake)
else()
  include (${EKAT_MACH_FILES_PATH}/kokkos/serial.cmake)
endif()
```

**Comment by jgfouca** [comment]
@ndkeen , where did you put that?

**Comment by ndkeen** [comment]
`components/scream/cmake/machine-files/pm-cpu.cmake`

**Comment by jgfouca** [comment]
@ndkeen , OK, that will work for CIME cases but not SCREAM standalone due to issues @bartgol brought up.

**Comment by ndkeen** [comment]
```
if ("${PROJECT_NAME}" STREQUAL "E3SM")
  if (${SMP_PRESENT})
    include (${EKAT_MACH_FILES_PATH}/kokkos/openmp.cmake)
  else()
    include (${EKAT_MACH_FILES_PATH}/kokkos/serial.cmake)
  endif()
else()
  include (${EKAT_MACH_FILES_PATH}/kokkos/openmp.cmake)
endif()
```

**Comment by jgfouca** [comment]
@ndkeen , I'd be fine with that as a temporary workaround.

**Comment by bartgol** [comment]
Also, FYI, when doing a conditional in CMake, it's recommended to not dereference a variable. That is, do `if (SMP_PRESENT)` rather than `if (${SMP_PRESENT})`. The latter might generate some warnings from CMake.

**Comment by ndkeen** [comment]
How about this?  `ndk/scream/use-serial-kokkos`
Should I just make a PR to make it easier to look at?
I should probably run a few tests on each machine.

**Comment by bartgol** [comment]
Yeah, if you test it on those machines and it works, then we can quickly merge a PR.
