### ISSUE TITLE
regression test fails

### ISSUE THREAD

**Issue by xyuan** [E3SM-Project/scream#201]
There is one P3 regression test fails, see below:

-------------------------------------------------------------------------------
p3_cloud_water_autoconversion_test
-------------------------------------------------------------------------------
/ccs/home/yuanx/scream/components/scream/src/physics/p3/tests/p3_unit_tests.cpp:215
...............................................................................

/ccs/home/yuanx/scream/components/scream/src/physics/p3/tests/p3_unit_tests.cpp:168: FAILED:
  REQUIRE( cwadc[s].qcaut == cwadc_host(s).qcaut )
with expansion:
  0.0000002235 == 0.0000002235

===============================================================================
test cases:    21 |    20 passed | 1 failed
assertions: 77654 | 77653 passed | 1 failed

**Comment by ambrad** [comment]
Thanks. What is the platform and build configuration?

**Comment by xyuan** [comment]
It was run on summit with gcc and llvm, both are failed.

**Comment by ambrad** [comment]
There are requirements on the build to make BFB pass. @jgfouca would you point @xyuan to the BFB configurations in your testing infrastructure; thanks.

**Comment by xyuan** [comment]
This information was from my debuging run of the unit test, ctest -V also show similar information about this case. There are 21 BFB tests because I added additional 3 test cases. I used nvcc_wrapper to compile the code with cuda support, but mpicxx to compile the code for only openmp and pthread support.

**Comment by jgfouca** [comment]
@xyuan , I will take a look at this as soon as i can.

**Comment by xyuan** [comment]
awesome, thanks very much.
