### ISSUE TITLE
New runtime warnings on pm-gpu (and other GPU machines) command line argument '--kokkos-num-devices' is deprecated.

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2026]
With Nov 9th repo, which includes update to kokkos to 3.7, I'm seeing these warning messages in e3sm.log:

```
Warning: command line argument '--kokkos-num-devices' is deprecated. Use '--kokkos-map-device-id-by=mpi_rank' instead. Raised by Kokkos::initialize().
```
Looks like one warning per MPI.  And only happens on pm-gpu, not pm-cpu.

@bartgol mentioned he also noticed them

**Comment by ndkeen** [comment]
I can get rid of warnings if I do this:

`components/homme/src/share/cxx/ExecSpaceDefs.cpp`

```
-  ss << "--kokkos-num-devices=" << nd;
+  ss << "--kokkos-map-device-id-by=mpi_rank";
```

and

`externals/ekat/src/ekat/ekat_session.cpp`

```
-  ss << "--kokkos-num-devices=" << nd;
+  ss << "--kokkos-map-device-id-by=mpi_rank";
```

**Comment by bartgol** [comment]
Yes, this are known warnings, that need to be fixed in EKAT. They are not yet at the level of error, and are still gracefully handled by kokkos. But this may change in future releases of kokkos, so we'll have to address this at some point.

**Comment by ndkeen** [comment]
I think this is resolved now. Thanks Jeff.
