### ISSUE TITLE
Build error on an enum type defined in scream/share/timing/private.h

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/scream#2048]
This issue was reported by @oksanaguba when building a scream test on Crusher with
machine crusher-gpu and compiler crayclang.

Steps to reproduce

1. Checkout latest scream master branch and update crayclang_crusher-gpu.cmake as below:
```
--- a/cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake
+++ b/cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake
@@ -1,9 +1,9 @@
-#if (compile_threaded)
-#  string(APPEND CFLAGS " -fopenmp")
-#  string(APPEND FFLAGS " -fopenmp")
-#  string(APPEND CXXFLAGS " -fopenmp")
-#  string(APPEND LDFLAGS " -fopenmp")
-#endif()
+if (compile_threaded)
+  string(APPEND CFLAGS " -fopenmp")
+  string(APPEND FFLAGS " -fopenmp")
+  string(APPEND CXXFLAGS " -fopenmp")
+  string(APPEND LDFLAGS " -fopenmp")
+endif()
```
2. Create the following scream test with machine crusher-gpu and compiler crayclang:
```
cd scream/cime/scripts
./create_test --machine crusher-gpu --compiler crayclang ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv
```
Build errors:
```
In file included from /gpfs/alpine/cli133/proj-shared/wuda/scream/share/timing/gptl.c:36:
/gpfs/alpine/cli133/proj-shared/wuda/scream/share/timing/private.h:47:15: error: expected identifier
typedef enum {false = 0, true = 1} bool;  /* mimic C++ */
              ^
/opt/cray/pe/cce/14.0.0/cce-clang/x86_64/lib/clang/14.0.0/include/stdbool.h:17:15: note: expanded from macro 'false'
#define false 0
              ^
In file included from /gpfs/alpine/cli133/proj-shared/wuda/scream/share/timing/gptl.c:36:
/gpfs/alpine/cli133/proj-shared/wuda/scream/share/timing/private.h:47:26: error: expected identifier
typedef enum {false = 0, true = 1} bool;  /* mimic C++ */
                         ^
/opt/cray/pe/cce/14.0.0/cce-clang/x86_64/lib/clang/14.0.0/include/stdbool.h:16:14: note: expanded from macro 'true'
#define true 1
             ^
In file included from /gpfs/alpine/cli133/proj-shared/wuda/scream/share/timing/gptl.c:36:
/gpfs/alpine/cli133/proj-shared/wuda/scream/share/timing/private.h:47:35: error: expected ';' after enum
typedef enum {false = 0, true = 1} bool;  /* mimic C++ */
                                  ^
                                  ;
```
In scream/share/timing/gptl.c, the following code block is used to mimic the bool type of C++:

```
#ifndef __cplusplus
typedef enum {false = 0, true = 1} bool;  /* mimic C++ */
#endif

```
On Crusher, stdbool.h might be implicitly included by Cray Clang compiler wrappers
before compiling this code block, which expands true/false macros like below (causing build errors):
`typedef enum {0 = 0, 1 = 1} bool;
`

@ambrad has a proposed fix by checking whether the macro true has already been defined (e.g. by stdbool.h):
```
#ifndef __cplusplus
# ifndef true
typedef enum {false = 0, true = 1} bool;  /* mimic C++ */
# endif
#endif
```

**Comment by dqwu** [comment]
@ambrad 
You can update share/timing/private.h for scream first, and then for E3SM.
I will also update this file in the internal GPTL lib of SCORPIO.

**Comment by ambrad** [comment]
Great. I'll create a PR for E3SM, and then we'll get it in SCREAM through an upstream merge. This is how we handle most changes outside of components/scream.

**Comment by dqwu** [comment]
After this fix, the original test still has some build errors inside SCORPIO, which can also be reproduced with a standalone SCORPIO build, see https://github.com/E3SM-Project/scorpio/issues/496. It will be fixed on SCORPIO side later with a patch provided by @ambrad

**Comment by ambrad** [comment]
I'll merge 5323 to upstream master tomorrow. Closing as this will be resolved in the next upstream merge.
