### ISSUE TITLE
Crusher: ELM reports a very large number of "Ball-Berry" errors.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2057]
Now that SCREAMv1 is running deterministically on Crusher, I'm starting to look at some anomalies in the runs. The most prominent is a huge number of lines of this sort in e3sm.log:
```
7:  Ball-Berry error check - stomatal conductance error:
7:  0.,  52577.053632404488
```
A 10-day ne30pg2 run has a 421M e3sm.log file essentially 100% due to lines of this type.

**Comment by ambrad** [comment]
@amametjanov @grnydawn have you ever seen the above warning from ELM in your Crusher runs? This is with crayclang, and LND is running with no OpenACC on the CPU. I'm wondering if you've disocvered some F90 flags that might solve this issue. Thanks.

**Comment by ambrad** [comment]
I've confirmed an identical run on Ascent does not have this warning in e3sm.log.

**Comment by ambrad** [comment]
`-O0` does not solve the issue. The build line with the `-O0` modification and excluding irrelevant inclusion stuff, is this:
```
python3 /autofs/nccs-svm1_home1/ambradl/crusher/ne30pg2_ne30pg2.F2010-SCREAMv1.1/Tools/e3sm_compile_wrap.py \
 /opt/cray/pe/craype/2.7.16/bin/ftn -DCNL -DCPRCRAY -DFORTRANUNDERSCORE -DHAVE_MPI -DHAVE_SLASHPROC -DLINUX -DMCT_INTERFACE -DMODAL_AER -DNDEBUG -DNO_R16 -D_PNETCDF \ 
... \
-I/autofs/nccs-svm1_home1/ambradl/repo/SCREAM/components/elm/src/utils -I/autofs/nccs-svm1_home1/ambradl/repo/SCREAM/components/elm/src/cpl -I/gpfs/alpine/cli133/proj-shared/ambradl/e3sm_scratch/crusher/ne30pg2_ne30pg2.F2010-SCREAMv1.1/bld/lnd/obj -I/opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/include \
-em -J.   -f free -N 255 -h byteswapio -em -M1077 -hnoacc -I/opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/include \
-L/opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/lib -lmpi -L/opt/cray/pe/mpich/8.1.16/gtl/lib -lmpi_gtl_hsa -O0 \
-hnoacc -hzero -hfp0 -hipa0   -DUSE_CONTIGUOUS=contiguous,  \
-c /autofs/nccs-svm1_home1/ambradl/repo/SCREAM/components/elm/src/biogeophys/PhotosynthesisMod.F90 -o CMakeFiles/lnd.dir/__/__/elm/src/biogeophys/PhotosynthesisMod.F90.o
```

**Comment by ambrad** [comment]
I suspect that in the lines
```
7:  Ball-Berry error check - stomatal conductance error:
7:  0.,  52577.053632404488
```
the first 0 in the second line points to a s/w type bug rather than a numerical one. I suspect the value is not meant to be 0.

**Comment by ambrad** [comment]
These warnings occur in the nightly tests, e.g., ERS_Ln22.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-gpu_crayclang.

**Comment by oksanaguba** [comment]
I have seen those too.

**Comment by ambrad** [comment]
I checked the E3SM Crusher nightlies and see (excluding -I items) these two build lines:

From SMS_Ln5.ne30pg2_r05_EC30to60E2r2.BGCEXP_LNDATM_CNPRDCTC_1850.crusher_amdclang:
```
/opt/cray/pe/craype/2.7.16/bin/ftn -DCNL -DCPRAMD -DFORTRANUNDERSCORE -DHAVE_MPI -DHAVE_SLASHPROC -DLINUX -DMCT_INTERFACE -DMODAL_AER -DNDEBUG -DNO_R16 -D_PNETCDF
-DUSE_CONTIGUOUS=  -c /gpfs/alpine/cli133/proj-shared/testing/E3SM/components/elm/src/biogeophys/PhotosynthesisMod.F90 -o CMakeFiles/lnd.dir/__/__/elm/src/biogeophys/PhotosynthesisMod.F90.o
```

SCREAMv1 crusher-gpu_crayclang
```
/opt/cray/pe/craype/2.7.16/bin/ftn -DCNL -DCPRCRAY -DFORTRANUNDERSCORE -DHAVE_MPI -DHAVE_SLASHPROC -DLINUX -DMCT_INTERFACE -DMODAL_AER -DNDEBUG -DNO_R16 -D_PNETCDF
-I/opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/include -em -J.   -f free -N 255 -h byteswapio -em -M1077 -hnoacc
-I/opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/include -L/opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/lib -lmpi -L/opt/cray/pe/mpich/8.1.16/gtl/lib -lmpi_gtl_hsa
-O0 -hnoacc -hzero -hfp0 -hipa0
-DUSE_CONTIGUOUS=contiguous,  -c /autofs/nccs-svm1_home1/ambradl/repo/SCREAM/components/elm/src/biogeophys/PhotosynthesisMod.F90 -o CMakeFiles/lnd.dir/__/__/elm/src/biogeophys/PhotosynthesisMod.F90.o
```

I'm going to work on making the SCREAMv1 line match the E3SM one.

**Comment by ambrad** [comment]
The relevant configuration code is this, in cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake:
```
if (NOT DEBUG)
string(APPEND CFLAGS " -O2 -hnoacc -hzero -hfp0 -hipa0")
string(APPEND FFLAGS " -O2 -hnoacc -hzero -hfp0 -hipa0")                                                                                                                                                                                           
endif()
```
Based on my previous observation that the Ball-Berry message does not appear in debug builds, I guessed that this configuration code is they key. It turns out that the `-hzero` option makes the difference. Without it, the Ball-Berry message does not appear. `man crayftn` shows this:
```
     -h arg The -h arg option enables you to access various  compiler  func-                                                                                                                                                                        
          tions.  Some of these options duplicate -O arg options.                                                                                                                                                                                   

          zero   Initializes all undefined local stack variables to 0 (ze-                                                                                                                                                                          
                 ro).  If a user variable is of type character, it is ini-                                                                                                                                                                          
                 tialized to NUL.  The variables are initialized upon each                                                                                                                                                                          
                 execution of the procedure.  This option is identical  to                                                                                                                                                                          
                 the -e0 option.                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
                 · Default: disabled
```

**Comment by ambrad** [comment]
Visual inspection suggests that `kn` is set at PhotosynthesisMod.F90:681-685 but is already used at lines 596 and 639.

**Comment by ambrad** [comment]
Zero-setting `kn` with `-hzero` removed does not reproduce the problem, so some other uninitialized variable seems to be the cause.

**Comment by ambrad** [comment]
Using `-hzero` on every F90 file except `PhotosynthesisMod.F90` fixes the problem, implying something in `PhotosynthesisMod.F90` is the cause.

**Comment by ambrad** [comment]
Ok, got it. The issue is `intent(out) :: gs_mol` in `brent`. `brent` can exit early without assigning `gs_mol` a value. `-hzero` 0-inits `gs_mol`, whereas otherwise it would have the value from the calling scope. Retaining the value from the calling scope is the desired behavior, so the fix is to make it `intent(inout) :: gs_mol`.

**Comment by ambrad** [comment]
I think I'm also going to remove `-hzero` from our configuration. E3SM does not conventionally 0-init its stack variables.

**Comment by ambrad** [comment]
@oksanaguba, @amametjanov: In both SCREAM and E3SM, I see various commits from each of you apply `-hzero` (0-init stack variables, including `intent(out)` arguments) and `-hipa0` (no function inlining) to optimized crayclang builds on Crusher. I'm guessing `-hipa0` may be a compiler workaround. But what is the motivation for `-hzero`? I believe E3SM does not conventionally 0-init its stack-allocated variables.

**Comment by ambrad** [comment]
Closing. SCREAM PR  #2066 removes `-hzero`, and upstream PR 5334 will fix the ELM issue. Either one of these resolves the problem for SCREAM.
