### ISSUE TITLE
Questions about nonhydrostatic pressure

### ISSUE THREAD

**Issue by jli628** [E3SM-Project/scream#2062]
Hi,

I found the outputs of geopotential height, temperature, and other state variables at specific pressure levels (e.g., 850 hPa and 700 hPa) were done by interpolating these state variables using state%pmid. Is state%pmid always equal to hyam(k)*ps0 + hybm(k)*ps(i)? We outputted total pressure before in WRF to analyze variables associated with convective systems. However, SCREAM doesn't provide similar output variables except for dynamic non-hydrostatic pressure. We found DYN_PNH was unequal to hyam(k)*ps0 + hybm(k)*DYN_PS(i). Does anyone know the relationships between DYN_PNH and state%pmid? How is DYN_PNH connected to physics? Is state%pmid the correct variable for our analysis if we want to interpolate geopotential height, temperature, and other state variables to specific pressure levels? Thanks.

**Comment by oksanaguba** [comment]
If you are using Fortran code (scream v0), then DYN_PNH is nonhydro pressure from the dycore and it won't match state%pmid, which is based on hydrostatic pressure per your formula with hyam... above. Also, DYN_PNH is not connected to physics.

**Comment by oksanaguba** [comment]
Yes, physics uses only hydrostatic pressure.

**Comment by jli628** [comment]
I see. Thank you, @oksanaguba
