### ISSUE TITLE
Small-kernels version of P3.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2069]
Issue to track this item.

**Comment by ndkeen** [comment]
Just noting that I ran into this on Tioga at LLNL, which is similar AMD-GPU-based machine.
What seems to be happening is that with GNU compiler, I see build fail in `eamxx/src/physics/p3/atmosphere_microphysics_run.cpp`

```
error: ran out of registers during register allocation
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
```

And then if I do something like:

```
#ifdef NDK_HOLD

  P3F::p3_main(prog_state, diag_inputs, diag_outputs, infrastructure,
               history_only, lookup_tables, workspace_mgr, m_num_cols, m_num_levs);
#endif
```

I am able to create e3sm.exe.

**Comment by bartgol** [comment]
Closing, since p3 small kernels was added around July 2023.
