### ISSUE TITLE
MassAndEnergyColumnConservationCheck: Implicit capture of 'this'

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2099]
`this` is being captured in several lambdas because class methods are being called inside the lambdas. One possible solution is make those methods static. Here are the line numbers in mass_and_energy_column_conservation_check.cpp that have the problem: 93, 123, 173, 207.

**Comment by tcclevenger** [comment]
I'll take a look. What exactly breaks because of this?

**Comment by ambrad** [comment]
Have you ever run this on the GPU? It will likely seg fault on at least some systems. (It _should_ seg fault on _all_ GPUs, but we know from experience that implicit `this` capture doesn't always cause a seg fault. It will cause a cuda memcheck error, though.)

**Comment by tcclevenger** [comment]
Yeah, there should be an AT test on weaver, but I guess we are getting lucky there. I'll verify any fix with cudamemcheck

**Comment by tcclevenger** [comment]
So no AT test (or even CIME test) uses this. I'll add one in my fix.
