### ISSUE TITLE
Crusher: "srun: error: Unable to create step for job ...: More processors requested than permitted"

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2112]
At first I thought this was associated with node count, but it's not. It seems that 8 tasks by 8 threads, 1 thread/core, stopped working on 29 Dec. I've tried various things of this sort to no avail:
```
export SLURM_JOB_CPUS_PER_NODE=64
srun  -l -K -n 8 -N 1  --gpus-per-node=8 --gpu-bind=closest -c 8 --cores-per-socket=64 --sockets-per-node=1 --ntasks-per-core=1 ...
```
`-c 7` works, however. I'll use this to work around the problem, but I probably need to email with some systems folks to get to the bottom of this.

**Comment by ambrad** [comment]
I submitted a support ticket to OLCF to see if the system experts have any ideas.

**Comment by oksanaguba** [comment]
they mentioned this in the email (you prob have seen):
```
After the outage, the default number of cores available to each GCD on a node will be 7.
```

**Comment by ambrad** [comment]
@oksanaguba thanks. I must have deleted that email without seeing that message.

**Comment by ambrad** [comment]
Found it. Here's the full message:
```
Slurm’s core specialization value (`--core-spec` or `-S`) was set to 8.
    This will provide a symmetric distribution of cores per GCD to the application and will reserve one core per L3 cache region.
    After the outage, the default number of cores available to each GCD on a node will be 7.
    To change from the new default value, you can set `-S` in your job submission.
    To make all 64 cores available to the job step (the behavior before the outage), you can use `-S 0` in your job submission.
```
I'll look into using this -S option.
