### ISSUE TITLE
HOMMEXX-side doubly periodic capability

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2118]
Do everything in HOMMEXX necessary to make a HOMMEXX equivalent of thetanh-moist-bubble.cmake pass C++-vs-F90 comparison.

**Comment by ambrad** [comment]
In progress. Dev here: https://github.com/E3SM-Project/E3SM/compare/master...ambrad:E3SM:ambrad/hommexx/dpdev

**Comment by ambrad** [comment]
PR: https://github.com/E3SM-Project/E3SM/pull/5481

**Comment by bartgol** [comment]
DP is now running in EAMxx unit tests, so I believe this task is completed. @ambrad feel free to reopen if I'm wrong.
