### ISSUE TITLE
DY1 non-BFBness: Run ERS_Ln362.ne30pg2_ne30pg2.F2010-SCREAMv1 through gprof

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2124]
We discovered that the second 20-day run of the DY1 simulation was not run-to-run BFB within the first half day. The project-wide evidence implies that this non-BFBness instance is exceptional:
* Two previous ne1024pg2 simulations were shown to be run-to-run BFB.
* We have ERS/P nightlies on Ascent, Crusher, and PM-GPU with scream.hi output, and these nightlies have been solidly green for months.
* Noel ran the following two configs twice each with 6 Jan 22 master and found them to be run-to-run BFB by diffing HOMME diagnostic output:
  * ne120 for 4 months
  * ne256 for 1 month.

Additional anecdotal and other grinding-script-based evidence collected during the BFBness campaign from mid Sep to early Dec supports BFBness in all cases examined.

One guess is that this instance is a result of an exceptional (and probably physically unrealistic) atmosphere state that is triggering code that rarely runs.

Given how exceptional this instance is and the fact that we don’t want to run an ne1024pg2 case repeatedly, we need to be careful in debugging this. The first concrete task is implementing #2122. Another, the focus of this github issue, is to run ERS_Ln362.ne30pg2_ne30pg2.F2010-SCREAMv1 (as SMS is fine) through gprof to isolate sections of code that aren't exercised (e.g., that run only in an physically unrealistic atmosphere state) in our tests.

**Comment by PeterCaldwell** [comment]
@ambrad - I think we decided not to work on this. Should we close this issue? Or reduce the priority?

**Comment by ambrad** [comment]
Either closing or wish-listing is fine.

**Comment by PeterCaldwell** [comment]
Closing because we have no intention of pursuing this unless it comes up again (at which time we'll create a new issue).
