### ISSUE TITLE
One Hommexx cxx_vs_f90 test fails on master on Weaver

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2126]
I find that the following test fails the cxx_vs_f90 phase on Weaver:
```
ctest -R theta-f1-tt10-hvs1-hvst0-r2-qz10-nutopoff-GB.*-ne13-nu1.2e16-ndays1.* -E -sl- -V
```
The Q, Q2, Q3, Q4 fields diff.

I tested this using the SCREAM repo, but there is extremely little reason to believe this is any different in upstream. All of the other theta cxx_vs_f90 tests pass with the `nightly` test profile. I configured the tests to run with 24 cores; I don't know whether that detail matters for this failure.

Attn: @oksanaguba @bartgol @tcclevenger

**Comment by oksanaguba** [comment]
Did you request 6 weaver nodes or just changed mpiexec -n 24 on 1 node?

so far i got from the default, mpiexec -n 4 on 1 node:
nmax=2, qsize=1, ne13 bfb
nmax=4, qsize=1, ne13 bfb

1 node but mpiexec -n 24 ..., nmax=4, qsize=4, ne13 bfb

**Comment by ambrad** [comment]
Short answer: mpiexec -n 24 on 1 node

Longer answer: I did another complete run overnight and still see this one fail:
```
Test #178: theta-f1-tt10-hvs1-hvst0-r2-qz10-nutopoff-GB-ne13-nu1.2e16-ndays1_cxx_vs_f90 ...***Failed 
```

Following are details of my configuration:

My machine file vs what's in cmake/machineFiles:
```
$ diff weaver.cmake ~/climate/scream/components/homme/cmake/machineFiles/weaver.cmake 
53c53
< set(USE_NUM_PROCS 24 CACHE STRING "Num mpiprocs to use")
---
> set(USE_NUM_PROCS 4 CACHE STRING "Num mpiprocs to use")
75d74
< SET (HOMMEXX_CUDA_MAX_WARP_PER_TEAM "8" CACHE STRING  "")
80c79,80
< set(CMAKE_CXX_COMPILER mpic++ CACHE STRING "")
---
> ######## CHANGE THAT
> set(CMAKE_CXX_COMPILER "/home/onguba/acme-master/externals/kokkos/bin/nvcc_wrapper" CACHE STRING "")
```

My module setup:
```
$ cat source-hxx-standalone.sh
source /etc/profile.d/modules.sh
module purge
module load git/2.10.1 python/3.7.3 cmake/3.23.1 cuda/11.2.2/gcc/8.3.1 openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 netcdf-c/4.8.1/gcc/8.3.1/openmpi/4.1.1 netcdf-cxx/4.2/gcc/8.3.1/openmpi/4.1.1 netc\
df-fortran/4.5.4/gcc/8.3.1/openmpi/4.1.1 parallel-netcdf/1.12.2/gcc/8.3.1/openmpi/4.1.1 openblas/0.3.18/gcc/8.3.1
export OMPI_CXX=/ascldap/users/ambradl/climate/scream/externals/kokkos/bin/nvcc_wrapper
```

After the rhel8 and Cuda 11 changes, I seem only to be able to build on rhel8 nodes. If you're using the Cuda 10 setup, perhaps the upgrades explain the new C++-vs-F90 diff.

**Comment by oksanaguba** [comment]
yes, i am using `cuda/10.1.105`.

**Comment by bartgol** [comment]
Dumb question: 24 ranks on one node is overloading the GPU, right? Besides the fact that I recalled kokkos or cuda rte not allowing this (but you guys ran, so it must have been something else I'm thinking of), we do not really care about that scenario, right? Is it worth chasing a non-bfb issue when running in a non-standard setting (i.e. 2+ ranks per GPU)?

**Comment by ambrad** [comment]
I used 24 because the F90 tests are extremely slow otherwise. 24 is fine for the GPU. The Ascent nightlies run with I think 7 ranks/GPU (42 ranks/node), for example. The large platforms sometimes disable that capability (MPS) by default, but even then you can turn it on when allocating the nodes. It's not the most performant way to run, but my experience is the performance degradaition in the case of many elements/GPU is not very large.

That aside, it's true that if 4 ranks/node doesn't lead to this diff, then we don't necessarily need to examine it. However, I'm curious if others find the F90 runs to be super slow with 4 ranks/node. Some of the Held-Suarez tests in particular take a really long time even with 24.

**Comment by tcclevenger** [comment]
Looking at the namelist for this test, doesn't look like this uses `pgrad_correction=1`, so there should be no issues from that change (or the tref_lapse_rate change).

**Comment by oksanaguba** [comment]
yes, F code is slow on weaver. I usually do not even run anything except ne2 (maybe i should). we can switch to nmax=something small, instead of using nday=1 in those tests.

**Comment by oksanaguba** [comment]
i think it would be better to find what causes nonbfb (even if it is the case of overloading gpus), but i would not know how if the change is from cuda11 (unless we do brute force and start disabling chunks of code).

**Comment by ambrad** [comment]
Yes, it's possible that only I have developed the fine-grained exclusive-or hashing technique sufficiently to find the cause of the diff. I don't have time right now to take this task on, however. We can leave it as "help wanted" with "priority:low" for a while.

**Comment by oksanaguba** [comment]
closing for now (one would have to rerun to confirm that the test still fails)
