### ISSUE TITLE
Cloud fraction outputs use wrong ice cloud fraction

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2132]
The 3d cldfrac_tot field and the 2d cldhgh, cldmed, and cldlow fields are all based on the "internal ice cloud fraction" which needs to be 1 whenever any ice is present in the cell at all in order for microphysics to act at all. As a result, our cloud fraction variables are 100% almost always whenever qi is present. People evaluating models want ice cloud fraction to mean that there's enough ice in the cell to be visible (or something like that). We have an output field "ice_cloud_mask" which uses the diagnostic definition. We need all the total (liquid+ice) cloud fractions output by the model to use this "evaluation" ice cloud fraction rather than the "internal" ice cloud fraction. 

In addition, we should change our default output request to output the 3d *liquid* cloud fraction and the total cloud fraction rather than the total cloud fraction and ice_cloud_mask since ice will always be 0 or 1 in a snapshot while liquid is generally less than 1. Thus we can reconstruct the ice cloud fraction from the total and the liquid... but we can't recover reasonable cloud fractions from what we have for the 4 season runs. @AaronDonahue - can you make this change?

My understanding is that ice_cloud_mask is a "diagnostic output" so it is calculated then immediately written out rather than being available as an ingredient for other output, particularly those calculated within physical processes and passed via the field manager to the output process. At least some of these other cloud outputs (e.g. cldhgh) need to be calculated within radiation because that's where we have the overlap calculator. I think the natural solution is to compute ice_cloud_mask within the ice cloud fraction process and to make it available to the AD. Maybe we could call it ice_cloud_fraction_4OUTPUTONLY or something to make sure people don't try to use it in calculations in the future?

**Comment by AaronDonahue** [comment]
Would it make sense to instead change the name of what we are calling `ice_cloud_frac` to `ice_cloud_mask`?  to mean there is either some ice or none, and then use `ice_cloud_frac` to have the higher threshold currently used in the diagnostic?

**Comment by AaronDonahue** [comment]
I ask in response to the suggestion we call one variable `ice_cloud_fraction_4OUTPUTONLY` or something like that.  Or, at the risk of inviting feature creep we could add a group type to the field manager that is output only, which would bar it from be registered as "REQUIRED" or something like that.

**Comment by PeterCaldwell** [comment]
I'd rather the variable name has a clearly alarming name so when someone uses it inappropriately I can ask "Why did you expect  ice_cloud_fraction_4OUTPUTONLY to be useful for internal calculations?" instead of having to say "well, if you look on line 1582 of obscurus.hpp, you'll see a the number 1e-12... you should have interpreted this as...". 

I think switching frac -> mask isn't clear enough, since in actuality both the output version and the internal versions are zero or one and could therefore better be described as masks. 

And I'd rather the name describe the situation rather than having people be confused why they can't assign a reasonable-looking variable to be required...

**Comment by AaronDonahue** [comment]
If IceCloudMask is essentially recreated in what will be the new field managed variable should I remove this as a diagnostic in the code?

**Comment by PeterCaldwell** [comment]
> If IceCloudMask is essentially recreated in what will be the new field managed variable should I remove this as a diagnostic in the code?

Yes.
