### ISSUE TITLE
Clean up SCREAM repo for merge to upstream.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2136]
In prep for a cleaner version of https://github.com/E3SM-Project/E3SM/pull/5416

Issues to resolve:

- [x] HOMME standalone works (@ambrad)
- [x] homme_integration passes on Chrysalis (@ambrad); PR https://github.com/E3SM-Project/scream/pull/2150 (merged)
- [x] SCREAM Crusher config stuff is orthogonal to upstream Crusher work (@ambrad) - PR #2138 (merged), https://github.com/E3SM-Project/E3SM_test_scripts/pull/62 (merged); CDash reports again for the new entires
- [ ] P3 issues addressed (@brhillman)
- [ ] README and .gitignore fixed; can be fixed in PR (@brhillman)
- [ ] ... ?

**Comment by brhillman** [comment]
Rather than fix the README and gitignore, I added those fixes to a PR to address the other minor issues. I was worried that we would have to deal with the conflict every time we merged back and forth. I think if we want a SCREAM-specific README, that should go in components/scream anyways. See #2139

**Comment by ambrad** [comment]
@brhillman I was running some tests this weekend and saw that homme_integration fails in the SCREAM repo. I must have mistakenly run the tests with the E3SM repo when I reported homme_integration is fine. I'll work on this on Monday.

**Comment by ambrad** [comment]
Ok, I found and fixed the discrepancy here: https://github.com/E3SM-Project/scream/pull/2150

**Comment by ambrad** [comment]
PR 2150 is merged, so now homme_integration passes when using the SCREAM repo.

**Comment by AaronDonahue** [comment]
@brhillman , just doing some cleanup - has this issue been resolved?  I know we've merged SCREAM into the upstream E3SM so I am guessing yes.

**Comment by ambrad** [comment]
Closing as completed.
