### ISSUE TITLE
Subcycle number of iterations should not have to divide the physics time step

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2145]
Example:
```
 3: Backtrace for this error:
 5: terminate called after throwing an instance of 'std::logic_error'
 5:   what():  /gpfs/fs1/home/ac.ambradl/SCREAM/components/eamxx/src/share/atm_process/atmosphere_process.cpp:85: FAIL:
 5: (dt % m_num_subcycles)==0
 5: Error! The number of subcycle iterations does not exactly divide the time step.
 5:   - Atm proc name: mac_aero_mic
 5:   - Num subcycles: 7
 5:   - Time step    : 900
```
Unlike in other situations where division constraints are imposed for fairly substantial reasons, this division constraint is, if I'm not mistaken, completely cosmetic and easily removed just by using doubles internally. (Note that in the case of meaningful constraints, they are based on real values and so are as least constraining as possible. Example: VR time step divides tracer transport time step or vice versa.) We should remove this constraint so that modelers can use the number of subcycles they want.

**Comment by PeterCaldwell** [comment]
It took me a while to understand what you're saying, but I think I agree. If (dt % m_num_subcycles) !=0, then substep_dt won't be a whole number... but if substep_dt is double precision anyways, who cares?

**Comment by bartgol** [comment]
To be clear: this requires changing dt to be double pretty much in all the atm process related interfaces. It's not a big amount of work, but I don't think it can be avoided.

**Comment by PeterCaldwell** [comment]
Ok. Yeah, I think dt should be a double, but I also don't think this is a high priority. Wishlist it?

**Comment by ambrad** [comment]
I'd advocate for making it a somewhat higher priority than "wishlist". It's reasonable for people to want to be able to specify whatever subcycle value they want, and rather unreasonable that they can't. Consider that someone might have to run a simulation slower just to get a configuration that works, simply because of a scalar data mistype.

**Comment by bartgol** [comment]
I'll take this one. After all, I changed it to `int` (after initialiiy using `double`). I think I changed it to int while working on mct coupling, since EAM used dtime as an integer in that layer.

**Comment by ambrad** [comment]
Great. Just to be clear (I'm pretty sure you're saying this): The _subcycle_ time step should be double, but the physics time step can remain int.

**Comment by bartgol** [comment]
Is there any issue with making _all_ timesteps double?

**Comment by ambrad** [comment]
None that I can think of. But what time step other than the physics time step and the subycle step is int? I agree we can make the physics one double and just match the int value the cpl'er has in the usual case of physics step == cpl step.

**Comment by ambrad** [comment]
One point, though: _Don't_ accumulate a double time. That can lead to time errors in long simulations. My advice is to look at each layer of EAM and think about why it chooses int vs real in each layer.

**Comment by bartgol** [comment]
We have fixed this at some point in the last 10 months. Closing.
