### ISSUE TITLE
WaterPath diagnostic outputs have incorrect units

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2164]
LiqWaterPath, IceWaterPath, RainWaterPath, RimeWaterPath, VapWaterPath should have units of kg m^-2 instead of m

**Comment by AaronDonahue** [comment]
I think this has already been solved.  Looking at the units for all of these diagnostics they are kg/m2.

```
  // Construct and allocate the diagnostic field
  const auto m2 = m*m;
  FieldIdentifier fid (name(), scalar2d_layout_mid, kg/m2, grid_name);
```

Are we seeing the units as incorrect somewhere else?

**Comment by PeterCaldwell** [comment]
I think the units are wrong in all of our 4 seasons runs. If they've been fixed since then - great!!!! Does anyone have a recent simulation to confirm empirically?
