### ISSUE TITLE
Add ability to write output on GLL nodes

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2165]
Add ability to write output on GLL nodes

**Comment by AaronDonahue** [comment]
@tcclevenger , you are planning to take this task on after rough-topo right?

**Comment by tcclevenger** [comment]
@AaronDonahue Yes. I'll update progress here.

**Comment by tcclevenger** [comment]
This is done in https://github.com/E3SM-Project/scream/pull/2322 and a PG2 standalone test outputting on GLL nodes introduced in https://github.com/E3SM-Project/scream/pull/2344.

**Comment by tcclevenger** [comment]
This is done in https://github.com/E3SM-Project/scream/pull/2322 and a PG2 standalone test outputting on GLL nodes introduced in https://github.com/E3SM-Project/scream/pull/2344.
