### ISSUE TITLE
Incorrect `dz` calculation in P3

### ISSUE THREAD

**Issue by quantheory** [E3SM-Project/scream#2167]
I mentioned this on Slack late (for me) yesterday, but I'm more confident now that this is a bug. The value of `dz` passed to P3 is calculated [by this call](https://github.com/E3SM-Project/scream/blob/f90b4e036706f1a7fbd6a67080771862d5f79074/components/eamxx/src/physics/p3/atmosphere_microphysics.hpp#L110)

```C++
        dz(icol,ipack) = PF::calculate_dz(pseudo_density(icol,ipack), pmid_pack, T_atm_pack, qv(icol,ipack));
```

where `pseudo_density` and `pmid_pack` [are set to the "dry" values](https://github.com/E3SM-Project/scream/blob/f90b4e036706f1a7fbd6a67080771862d5f79074/components/eamxx/src/physics/p3/atmosphere_microphysics.cpp#L229-L230) and `calculate_dz` [uses virtual temperature](https://github.com/E3SM-Project/scream/blob/f90b4e036706f1a7fbd6a67080771862d5f79074/components/eamxx/src/share/util/scream_common_physics_functions_impl.hpp#L303). But the virtual temperature is only correct if "wet" values are being input.

If we denote dry pseudo-density by $\Delta \widetilde{p}_d$ and dry density as $\rho_d$, then my understanding is that for each grid cell $\Delta \widetilde{p}_d = \rho_d g \Delta z$ by definition. The dry pressure can also be expressed in terms of dry density $p_d = \rho_d R_d T$. So $\Delta z = (R_d T \Delta \widetilde{p}_d) / (p_d g)$, i.e. the same formula as `calculate_dz` uses, but with actual rather than virtual temperature. (Maybe this is obvious, but I'm not used to writing things in terms of pseudo-density, so wanted to be explicit about it.)

There are a few possible ways to fix this, but the easiest would be to just pass zero rather than `qv` to `calculate_dz`:

```C++
        dz(icol,ipack) = PF::calculate_dz(pseudo_density(icol,ipack), pmid_pack, T_atm_pack, 0.);
```

All that said, I don't know that this bug would cause cause mass conservation problems. An incorrect `dz` would lead to an incorrect value calculated for `rho`, which means that the process rate and fall speed calculations will generally be off in P3. But in nearly every case, this would simply mean an error in the amount of mass transferred between categories (e.g. cloud to rain) or in the magnitude of fluxes between vertical levels, neither of which affects total mass.

In the sedimentation code, the conversion of fluxes to a change in `qc`/`qr`/`qi` relies on both `dz` and `rho`. However, in this case the errors in `dz` and `rho` should cancel each other, so this does not seem to cause problems for conservation either.

**Comment by PeterCaldwell** [comment]
Yeah, I agree that the relationship between dry density and dry pressure should use temperature instead of virtual temperature... the whole point of virtual temperature is to account for the mass of water while still using Rd!

@onguba - I think you said this fix didn't solve the P3 water leak (but that P3's water leak is much smaller than SHOC's?). Is this all correct?

In terms of a a fix - I'd rather rename calculate_dz to calculate_dry_dz and delete qv as an input for it. I think we should figure out our big-picture strategy (e.g. for https://github.com/E3SM-Project/scream/issues/2169) before making any changes though.

**Comment by oksanaguba** [comment]
I do not think there should be such thing as "dry dz"? We can transfer everything to dry pressure levels, but it seems to be this will only complicate things without benefits. And yes, giving calculate_dz 0 for qv did not help with conservation.

The latest discovery is that dry/wet conversion is using qv in shoc/p3 interfaces (that is, an updated qv at the end of their time step), which makes it inconsistent with wet mmrs as seen by the AD.

**Comment by PeterCaldwell** [comment]
Sorry, my function name "calculate_dry_dz" was misleading. I don't think anybody wants to define a new "dry dz" variable. Instead, I was trying to convey that we can calculate the correct dz using dry mixing ratio and pdel_dry. Maybe call it "calculate_dz_dryvars"?

I don't understand your "latest discovery" comment, but maybe I don't need to. We designed the AD to only know about wet mmrs which get converted to dry mmr in the interfaces for p3 and shoc. The whole point of conversion is that inside p3 and shoc routines, qv should be defined as a dry mixing ratio.

**Comment by quantheory** [comment]
@PeterCaldwell I think your suggestion is good. Maybe the routine should be called `calculate_dz_from_dry` or something? But it doesn't matter as long as it conveys in some way that the inputs are intended to be dry variables.

I think the "latest discovery" that @oksanaguba was referring to is just the problem noted in #2169, which is more likely to be the the cause of the water mass conservation issues (as opposed to this issue, which I think is an unrelated problem that just happens to also involve wet/dry unit confusion).

**Comment by PeterCaldwell** [comment]
So I think the plan here is to replace `calculate_dz` with `calculate_dz_from_dry` which takes in dry pressure, dry pseudo density, and normal T (and removes qv as an input variable) and returns dz. Does anyone disagree? Does anyone want to take this on?
