### ISSUE TITLE
ERROR: NetCDF: One or more variable sizes violate format with ne256 on pm-gpu while writing scream.r restart

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2175]
With Feb13th repo, I'm trying to run a case that has different output (I will try my usual ne256 script to test restart writes next) and see a fail while trying to write `scream.r` restart.  I can reproduce after just 1 day.  I don't see the problem with ne30.

```
  0: MCT::m_Router::initp_: GSMap indices not increasing...Will correct
  0: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = ./t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr.scream.r.0001-01-02-00000.nc\
) (/global/cfs/cdirs/e3sm/ndk/repos/se53-feb13/externals/scorpio/src/clib/pioc_support.c: 4351)
 84: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = ./t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr.scream.r.0001-01-02-00000.nc\
) (/global/cfs/cdirs/e3sm/ndk/repos/se53-feb13/externals/scorpio/src/clib/pioc_support.c: 4351)
160: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = ./t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr.scream.r.0001-01-02-00000.nc\
) (/global/cfs/cdirs/e3sm/ndk/repos/se53-feb13/externals/scorpio/src/clib/pioc_support.c: 4351)
188: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = ./t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr.scream.r.0001-01-02-00000.nc\
) (/global/cfs/cdirs/e3sm/ndk/repos/se53-feb13/externals/scorpio/src/clib/pioc_support.c: 4351)
144: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = ./t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr.scream.r.0001-01-02-00000.nc\
) (/global/cfs/cdirs/e3sm/ndk/repos/se53-feb13/externals/scorpio/src/clib/pioc_support.c: 4351)
 68: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = ./t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr.scream.r.0001-01-02-00000.nc\
) (/global/cfs/cdirs/e3sm/ndk/repos/se53-feb13/externals/scorpio/src/clib/pioc_support.c: 4351)
  0: Obtained 10 stack frames.

/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se53-feb13/t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr

```

Potentially same issue as we saw with ne1024.  https://github.com/E3SM-Project/scream/issues/2042
The work-around was to use more nodes, and I will try that here with ne256.

**Comment by dqwu** [comment]
@ndk Could you please check the format of "t.se53-feb13.F2010-SCREAMv1.ne256pg2_ne256pg2.pm-gpu.1d.n048t4xX.dailyoutb.wr.scream.r.0001-01-02-00000.nc" with "ncdump -k" command?

Maybe you need set PIO_NETCDF_FORMAT with 64bit_data instead of classic or 64bit_offset in env_run.xml.

**Comment by ndkeen** [comment]
The filesize is zero for that `scream.r` file.

I also tested a simpler ne256 script for 1 day with restarts and it worked with 48 pm-gpu nodes.  So will try to see what exactly is causing the fail.

**Comment by dqwu** [comment]
> The filesize is zero for that `scream.r` file.
> 
> I also tested a simpler ne256 script for 1 day with restarts and it worked with 48 pm-gpu nodes. So will try to see what exactly is causing the fail.

What is the "ncdump -k" result of the restart files output by the simpler ne256 script for 1 day with 48 pm-gpu nodes?

**Comment by ndkeen** [comment]
Normally, I always add `./xmlchange PIO_NETCDF_FORMAT="64bit_data"` to my scripts, but the one I was testing from Chris G did not have this. Adding it seems to be allowing the restarts to be writing on pm-gpu with 48 nodes. At least after 1 day.
