### ISSUE TITLE
On model error, flush output before exiting.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2185]
That way we get all output in files at a model crash.

**Comment by bartgol** [comment]
In #2174 , part of the output fixes were to add a call to `eam_pio_closefile` when the OutputManager is destroyed, to ensure any open file is flushed at the end of the run. I suspect this is not enough in case there's an exception/error thrown. In that case, however, I think we could still get correct behavior simply registering via `atexit` a util function that calls `ScreamContext::singleton().clean_up()`. The destructor of the driver would call the dtor of the output managers, which would call `eam_pio_closefile`.
