### ISSUE TITLE
Write CMIP-standard output variable names

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2186]
This is a modern incarnation of https://github.com/E3SM-Project/scream/issues/968 . The idea is that it would be nice to have EAMxx output use the standard variable names expected of CMIP contributions because then analysis packages which are meant for processing CMIP output could operate directly on our output and our output could (hopefully) be uploaded directly to CMIP-like intercomparisons rather than needing to go through the dreaded CMORization step.

One recent realization which makes this task less odious is noting that CMIP names are shorter and more rational than CF-conventions long_names, which are really long and awful. The CF names are the first column and the CMIP names are the 2nd column of https://pcmdi.llnl.gov/mips/cmip3/variableList.html . 

One caveat is that in addition to CMIP names, we would also need to make sure output had CMIP-standard output *units*. I don't think we're ready to tackle that task yet, though I think CMIP-standard is mks conventions (meter, kg, sec), which is what we use internally, so maybe this isn't a problem). 

This task seems to be conceptually easy, but require some drudgery. Steps:
1. Add a `cmip_name` attribute to the FM (or hijack `long_name` if it already exists?)
2. Modify output so it uses the cmip_name rather than the variable name when it writes to netcdf
3. Go through each instance where a variable is added to the FM and add its `cmip_name` attribute. 

One note on task 2: we originally thought there should be a namelist flag allowing users to choose whether their output was written in cmip style or native style. @brhillman pointed out, however, that it would be a mess if some simulations used one naming convention for their output and others used a different one. I think we agreed (or at least Peter C did) that we should *always* use cmip output names if/when we complete this task.

**Comment by golaz** [comment]
This would be a very valuable feature to have and it would save the E3SM project a lot of resources long term. (Obviously, there is a non-negligible short term cost).

Implementation is likely to be spread over some time, so while we in transition, I would still suggest to have an option for selecting between native and cmip naming convention so as to not constantly break existing post-processing workflows. That option could eventually be sunset.

A few more questions regarding implementation:

1. We probably want to be able to specify the cmip name in the output yaml file, not just the native name (which would be really confusing for new users).
2. There may not always be a 1:1 mapping between native and cmip variables. Some cmip variables might have to be derived (for example top-of-model and surface radiation by adding _@tom_ or _@bot_ to 3d radiation variables, or constructed by simple combination of variables).

**Comment by PeterCaldwell** [comment]
Great points, Chris. I like in particular your item 2, which reframes a problem I was struggling with (what to do when our variables are in different units than CMIP requires) in a way which is solvable: We need to be able to have a cmip name associated with derived variables. Then if we want precip in mm/day for CMIP output (for example), but we store it in kg/m2/s internally, we would ask for derived variable <CMIP-precip-varname> and it would be converted before being written. 

This brings up another question though - what do we do about variables that don't have a CMIP name? I think years ago when we were hooked on CF-long-names, we planned on making names that were what we guessed CF would call them if they were added to CF list. I'm somewhat inclined to do the same for CMIP names, but we could also just use the native output name when a CMIP name doesn't exist.

**Comment by golaz** [comment]
Yes, there will likely be many variables for which there are no CMIP names. I don't see any problem with either making one up, or just reverting to native names.

I believe there is also a mechanism to _submit_ new names for CMIP approval. But that might be more than we are willing to take on.

**Comment by bartgol** [comment]
> This would be a very valuable feature to have and it would save the E3SM project a lot of resources long term. (Obviously, there is a non-negligible short term cost).
> 
> Implementation is likely to be spread over some time, so while we in transition, I would still suggest to have an option for selecting between native and cmip naming convention so as to not constantly break existing post-processing workflows. That option could eventually be sunset.

I like this. So long as we force to CMIP for _all-or-none_ of the variables, this should not be too complicated. Mix and match might be more of a headache. Note: if a var does NOT have a CMIP name, then it's fine to mix its name with CMIP vars; I was more concerned to mix eamxx and CMIP names for vars that have both.
 
> 1. We probably want to be able to specify the cmip name in the output yaml file, not just the native name (which would be really confusing for new users).

If, as mentioned above, we force an all-or-nothing approach for CMIP vars, then I think we can definitely handle this in an easy way.

> 2. There may not always be a 1:1 mapping between native and cmip variables. Some cmip variables might have to be derived (for example top-of-model and surface radiation by adding _@tom_ or _@bot_ to 3d radiation variables, or constructed by simple combination of variables).

We do have the possibility to compute derived quantities at IO time, so that's fine. We currently have a plethora of diagnostics which are used exclusively for IO. Making those CMIP compliant should be even easier than handling CMIP-compliance for the regular model variables.

**Comment by AaronDonahue** [comment]
This has been addressed, we now add `standard_name` metadata to our output
