### ISSUE TITLE
Livermore Computing machines can't build CIME cases

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2192]
After the latest commit of #2190 the Livermore Computing machines `quartz` and `syrah` can't get past the `cmake` config step when building a new CIME based E3SM case.

LC machines have, in the past, had issues owing to the fact that rather than `mpiexec` they use `srun` to run multi-core jobs.  I'm not sure how this is related, if at all, to the changes made in #2190 but I note it here in case it helps us figure out what is going wrong.

Here's the cmake error that may be relevant.

```
CMake Error at /g/g17/donahue5/Code/e3sm/scream/scream_sandbox/externals/ekat/extern/kokkos/cmake/kokkos_functions.cmake:40 (MESSAGE):
  Given deprecated option list KOKKOS_ARCH.  This must now be given as
  separate -D options, which assuming you spelled options correctly would be:

    -DKokkos_ARCH_BDW=ON

  Remove CMakeCache.txt and re-run.  For a list of valid options, refer to
  BUILD.md or even look at CMakeCache.txt (before deleting it).
  ```

**Comment by AaronDonahue** [comment]
Shortly after making this issue I noted that only `quartz` and `syrah` actually use the `KOKKOS_ARCH` command in the machine file.  I've commented that out and am rerunning to see if it fixes the issue.

**Comment by AaronDonahue** [comment]
@jgfouca , do you have any thoughts?

**Comment by AaronDonahue** [comment]
```Configuring with cmake cmd:
 /usr/bin/time -p cmake -DCIME_MODEL=e3sm -DSRC_ROOT=/g/g17/donahue5/Code/e3sm/scream/scream_sandbox  -Dcompile_threaded=FALSE  -DINSTALL_SHAREDPATH=/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l/bld/intel/mpich/nodebug/nothreads/mct  -DUSE_KOKKOS=FALSE  -DCOMP_NAMES='driver;scream;elm;cice;docn;srof;sglc;swav;siac;sesp' -DCASEROOT="/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l" -DCASETOOLS="/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l/Tools" -DCIMEROOT="/g/g17/donahue5/Code/e3sm/scream/scream_sandbox/cime" -DSRCROOT="/g/g17/donahue5/Code/e3sm/scream/scream_sandbox" -DCOMP_INTERFACE="mct" -DCOMPILER="intel" -DDEBUG="FALSE" -DEXEROOT="/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l/bld" -DRUNDIR="/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l/run" -DINCROOT="/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l/bld/lib/include" -DLIBROOT="/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l/bld/lib" -DMACH="quartz" -DMPILIB="mpich" -DNINST_VALUE="c1a1l1i1o1r1g1w1i1e1" -DOS="LINUX" -DPIO_VERSION="2" -DSHAREDLIBROOT="/p/lustre2/donahue5/e3sm_scratch/quartz/SMS_Lm1_P96x1.ne4_ne4.F2010-SCREAMv1.quartz_intel.20230227_102119_v7op0l/bld" -DSMP_PRESENT="FALSE" -DUSE_ESMF_LIB="FALSE" -DUSE_MOAB="FALSE" -DCOMP_LND="elm" -DCOMPARE_TO_NUOPC="FALSE" -DUSE_TRILINOS="FALSE" -DUSE_ALBANY="FALSE" -DUSE_PETSC="FALSE"  -DCMAKE_C_COMPILER_WORKS=1 -DCMAKE_CXX_COMPILER_WORKS=1 -DCMAKE_Fortran_COMPILER_WORKS=1  -DSCREAM_NP=4 -DSCREAM_NUM_VERTICAL_LEV=72 -DSCREAM_NUM_TRACERS=10 -DSCREAM_DYN_TARGET=theta-l_kokkos -DSCREAM_CIME_BUILD=ON /g/g17/donahue5/Code/e3sm/scream/scream_sandbox/components
```

**Comment by bartgol** [comment]
I see that our `intel-bdw.cmake` file in EKAT is obsolete. It has
```
  set(KOKKOS_ARCH BDW CACHE STRING "")
```
instead of the new syntax. However, I don't see that file being included by the quartz mach file (it is using the new syntax, and so is the syrah mach file).

**Comment by AaronDonahue** [comment]
```
include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)
common_setup()

# Load all kokkos settings from Ekat's mach file
set(Kokkos_ENABLE_SERIAL TRUE CACHE BOOL "")

# Enable Broadwell arch in Kokkos
option(Kokkos_ARCH_BDW "" ON)

...
```

**Comment by AaronDonahue** [comment]
even still, commenting out the `Kokkos_ARCH` line doesn't seem to fix the problem.

**Comment by AaronDonahue** [comment]
maybe the KOKKOS_ARCH thing is a red-herring

**Comment by bartgol** [comment]
AH, no, sorry, I was looking at an old master. We _do_ include that bad file for quartz. I will fix it in ekat. I am not sure what the deal is for syrah though.

**Comment by AaronDonahue** [comment]
maybe syrah is fine.  Let me confirm...

**Comment by bartgol** [comment]
Wait, syrah seems to build fine on cdash

**Comment by AaronDonahue** [comment]
yes, and 2190 didn't go in until today, so cdash doesn't reflect it.  I found this by trying to build from master myself today.

**Comment by bartgol** [comment]
I don't see a v1 build on syrah. Is there one (perhaps not reporting to cdash)? Tbh, I don't think we need one there; it's an old arch anyways, and I don't think there's any target production machine still using it. I think it's good to have some v1 teting on LC machines, but since we already have quartz...

**Comment by AaronDonahue** [comment]
We don't build syrah for CIME nightlies.  Since quartz and syrah are so similar we decided to stick with just the one.

**Comment by bartgol** [comment]
Ok. I was sidetracked by your initial comment.

THe mach file fix is in EKAT. Then we'll need a submodule update to fix quartz nightlies.

**Comment by AaronDonahue** [comment]
I see that EKAT has new entries for `quartz.cmake`

**Comment by AaronDonahue** [comment]
see: https://github.com/E3SM-Project/scream/pull/2190/files#diff-7979fcbdb371b5b7e6d1782f48bedbdf9003be5474a3af48844269c865daba2c

**Comment by bartgol** [comment]
EKAT does not have a mach file for syrah, so no changes needed for syrah. The CIME tests there should not fail, from what I can tell.

**Comment by AaronDonahue** [comment]
@bartgol and @jgfouca , I grabbed Luca's EKAT branch and tried to build again and was successful.

**Comment by jgfouca** [comment]
@AaronDonahue , great! I'm going to double check a couple more machines and then I will update EKAT submodule.

**Comment by AaronDonahue** [comment]
syrah still doesn't work.
