### ISSUE TITLE
Add ordered list of variable names included in 'tracers' in scream.r files 

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2194]
In scream.r files (i.e. our restarts), advected quantities are bundled in a variable called `tracers`. It is occasionally useful to analyze or use data from the restart file, so it would be nice if scream.r listed the order in which variables are contained in the `tracers` array. Ideally, this would occur as an additional attribute of the tracers array, but I have some vague recollection that adding an attribute for a single variable in a netcdf file is hard. In that case, making a global attribute with this info would be fine. Note that there's also a bit of trickery here in that different simulations may have different number or order of tracers in the future (e.g. with prognostic aerosol), so we need to get the list of tracers online rather than hardcoding it.

**Comment by AaronDonahue** [comment]
This is addressed in PR #2204
