### ISSUE TITLE
Surface pressure (ps) output appears to be double the correct size.

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2195]
Branched off from Issue #2160 , Here is the original text submitted by @golaz .

I ran a short test (1 month) on chrysalis with the latest code (b6314dad6440c284e8121cc402f9e723c5ec7640, COMPSET="F2010-SCREAMv1", RESOLUTION="ne30pg2_ne30pg2", 128 levels). Thanks to @crterai for helping me configure this run.

I noticed some issues with output variables.

**ps**

The surface pressure magnitude is way off, topping around 2052 hPa. 

![ps](https://user-images.githubusercontent.com/15743046/217918712-141f3cf6-0ed3-4626-90f2-9736da9563d5.png)

But the lowest model p_mid looks fine (topping at 1024 hPa), so this must be a diagnostic issue.

![p_mid-127](https://user-images.githubusercontent.com/15743046/217918798-d4884b0c-f925-4736-8e65-7e68948a5783.png)

**Comment by AaronDonahue** [comment]
Bringing in comments from #2160 relevant to this issue:

Aaron Donahue:
Re: ps, have we been able to recreate this effect? I'm looking at a number of my recent ne30 runs and ps always seems to be right in the 100hPa 1000hPa range. @crterai , @golaz ?

Chris Terai:
One of my recent test shows relatively okay looking ps values so @golaz is better positioned to chime in here.

**Comment by AaronDonahue** [comment]
I reran this case w/ all four output types:  AVERAGE, INSTANT, MAX, MIN and here are the results for the largest value that `ps` takes:
```
In [8]: np.amax(favg["ps"][:])
Out[8]: 205140.17

In [9]: np.amax(fins["ps"][:])
Out[9]: 103572.484

In [10]: np.amax(fmin["ps"][:])
Out[10]: 101642.055

In [11]: np.amax(fmax["ps"][:])
Out[11]: 104350.78
```

Based on these results it looks like something make be wrong with how we are handling the AVERAGE flag.  My first concern was that maybe we hit a large `ps` peak that when averaged out looks like 2x the normal values.  But the MAX output proves that over the entire simulation we don't go over a reasonable value.

@bartgol , you might have some insight.  Do you see any chance there is a bug in AVERAGE flag?  I would think our unit tests would catch this, but it might be worth noting that `ps` is a homme variable that is remapped to physics maybe just for writing as output.

**Comment by AaronDonahue** [comment]
okay a little more digging and I found another variable with the same behavior:
```In [11]: for v in favg.variables:
    ...:   if v != "time_bnds":
    ...:     avg_v = np.amax(favg[v][:].data)
    ...:     ins_v = np.amax(fins[v][:].data)
    ...:     min_v = np.amax(fmin[v][:].data)
    ...:     max_v = np.amax(fmax[v][:].data)
    ...:     if (avg_v>max_v):
    ...:       print("%36s: %e,\t%e,\t%e,\t%e\t" %(v,avg_v,ins_v,min_v,max_v))
    ...: 
    ...: 
                                            AVERAGE                INSTANT                  MIN                         MAX
                                  ps: 2.051402e+05,	1.035725e+05,	1.016421e+05,	1.043508e+05	
                               qv_2m: 4.043704e-02,	2.302467e-02,	1.801977e-02,	3.011429e-02
```

so `qv_2m` also has the same issue where the average is larger than the max

**Comment by PeterCaldwell** [comment]
We're computing averages by accumulating then dividing by the number of samples included in that accumulation, right? I bet the count is getting tallied wrong. It'd be easy to print it out to confirm.

**Comment by AaronDonahue** [comment]
Yes, that's my theory too, but we have tests that confirm that average output is correct.  So I am trying to figure out why these two variables might show the problem while others don't.  Current hypothesis is that it is related to variables that are in `homme` only.  At least that is the case w/ `ps` which is only used in homme.

**Comment by bartgol** [comment]
Good find Aaron! This is definitely a trackable issue. As Peter said, it's likely an issue with our tally count. If you don't find it by the end of week, let me know and I can take a look.

**Comment by AaronDonahue** [comment]
Update, still not exactly sure what is going on but I it appears I cannot recreate this error with the "standalone" homme+physics unit test.  I am going to try to run a CIME test w/ surface coupling suppressed to see if the issue goes away.

**Comment by AaronDonahue** [comment]
Okay, I figured it out... And it would be a good face-palm emoji time.  In the output control yaml file that recreates the problem the fields `ps` and `qv_2m` are listed twice.   So for averaging we call `combine` twice.  Instant, min and max are all correct because there is nothing cumulative about their values, thus calling combine more than once has no impact.  I'm surprised our interface let us register the same variable name twice, but it would be an easy fix to throw an error if something is listed twice.  Alternatively I could just trim the second entry and display a WARNING.

@PeterCaldwell, @golaz , @bartgol any preference on how to handle it when a user specifies the same field twice?

**Comment by PeterCaldwell** [comment]
I think it's best to be as permissive as possible so long as doing so doesn't confuse users or make our code more complicated. Thus I don't think we should error out, just ignore outputs that have already been registered and print a warning. If its harder to do that then error out, however, we should just error out.

**Comment by bartgol** [comment]
I vote for erroring out. I can see this happening when someone wants to add `var_1`, `var_2`,..,`var_N`, so they hack the file with a good old copy-paste, but forgot to edit some of the entries. Their field is never saved, and they might have burned cpu hours for no reason.

Erroring out at init time might be better. Even better (though it might take some work) would be to error out in buildnml, which happens before getting the job submitted to the Q...

**Comment by AaronDonahue** [comment]
It is essentially the same amount of work for either ERROR or WARN.  Here are my pro/cons for ERROR vs. WARNING debate.

ERROR:
1) The user may have meant a different field with a similar name, think `p_mid` vs. `p_int`, or `cldfrac_ice` vs. `cldfrac_liq`.  If we just issue a WARNING and then burn through the whole run and provide less output that could be annoying.
2) If we error out then the job fails for essentially a typo which can be annoying if you had been waiting on the run to get through the queue for awhile and you would have rather just had the extra entry removed.

WARNING:
1) It lets the job continue even with a likely common typo.
2) No one ever looks at the e3sm.log for warnings, so the user will probably never know what happened and will continue using a bad yaml control file.

I have a branch in the wings that has the solution either way, we should put it to a vote and go from there.  Then I can post a bugfix PR.

**Comment by PeterCaldwell** [comment]
Luca makes a good argument. I change my vote to "what he said" (i.e. erroring out).

**Comment by golaz** [comment]
@AaronDonahue : amazing debugging work! Very sorry that I let you go down the path of a wild goose chase by listing `ps` twice in my yaml file.

I think an error in that case would be warranted.

Thanks for all the hard work on this.
