### ISSUE TITLE
reorg moved kokkos_generated_settings.cmake 

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#22]
#17 changed the place kokkos_generated_settings.cmake is expected to be found from ${KOKKOS_DIR} (which is, I think where cmake was called to build kokkos) to ${KOKKOS_INSTALL_DIR} (which at least for me is ${KOKKOS_DIR}/install). Is this what we want? If so, we should change README.md to tell folks to configure/compile kokkos from the KOKKOS_INSTALL_DIR location.

The impact of this change is that building tests following MAKEFILE.md currently fails because it can't find kokkos_generated_settings.cmake...

**Comment by ambrad** [comment]
@jgfouca may I ask you to look at this? Thanks.

**Comment by jgfouca** [comment]
@PeterCaldwell , please use the "develop" branch of Kokkos and make sure it's up-to-date.

**Comment by bartgol** [comment]
@PeterCaldwell I don't think #17 changed where it looks for kokkos stuff. I also had that error, and jim pointed out to me that I had to use kokkos develop (up to date). That fixed it for me, so maybe it's the same for you.

**Comment by PeterCaldwell** [comment]
Ok. I've also been able to build/run tests by switching to the develop branch of kokkos. Should we add the step of switching to the develop branch of kokkos to README.md, or is this change going to get to kokkos master in the next week or so?

**Comment by jgfouca** [comment]
@PeterCaldwell , looking at the master branch of Kokkos, it is difficult to decipher what their integration policy is. The last time they updated master was in May; before that, they were doing it quite frequently.

**Comment by PeterCaldwell** [comment]
Ok, I'll make a PR adding a line to README.md saying to checkout develop

**Comment by jgfouca** [comment]
Sounds good, sorry for the confusion.
