### ISSUE TITLE
Insist on including ave type and freq in output filename

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2202]
Currently, users can elect to omit output frequency or averaging type from filenames. If they did so, changing freq or ave type wouldn’t start a new output stream. It would also result in name conflicts between (for example) attempts to output daily max and daily min T. Thus, we will disable the option to suppress freq and ave type in output filenames.

**Comment by AaronDonahue** [comment]
@bartgol , have you taken this task on with your work on being able to reopen a history stream that hasn't reached the max nsnaps?

**Comment by bartgol** [comment]
Yes, that branch will take away the possibility of not having avg/freq in the filename.
