### ISSUE TITLE
Be able to write ALL fields with a single argument

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2213]
For debugging purposes it might be nice to have an argument that one can pass through the output control yaml file that just flags all fields available fields to be outputted.  Something like:

```
Fields:
  Physics ${PHYSICS_GRID_TYPE}:
    Field Names:
      - ALL
```

That way users don't need to list every field they can think of.

**Comment by PeterCaldwell** [comment]
It seems like it would be hard to get this to output derived variables since the FM doesn't know about them?

**Comment by bartgol** [comment]
I think we should instead allow to ask for a group of vars (e.g., STATE, or TRACERS, or RESTART, or...), and we can query the FM for either a field or a group. Something like
```
get_field (const std::string& name, const FieldManager& fm) {
  if (fm.has_field(name)) {
    ...
  } else if (fm.has_group(name)) {
    ...
  } else if (is_diag(name) {
    ...
  }
}
```
And I guess we can make the FM add all fields to the macro group "ALL".

**Comment by PeterCaldwell** [comment]
This sounds nice, but would we ever use it? I'm having a hard time seeing this as a high priority but maybe if either of you personally wanted it for some debugging you're doing I could see it as being worth doing...

**Comment by bartgol** [comment]
Oh, I don't think it's a priority (one can always list the fields explicitly). Just pointing out a more flexible approach if one ever decides to implement this.

**Comment by AaronDonahue** [comment]
Re: Would we ever use this?  For debugging probably.  I find myself curious about the full state of the field manager and having to manually go through all processes to check if I've gotten all fields listed.  I like Luca's suggestion about turning the request into a group of fields and allowing users to request said group.

**Comment by bartgol** [comment]
I'm closing since this seems like a "we-will-probably-never-imp-this" kind of issue. If it's _needed_, we can reopen.
