### ISSUE TITLE
change `atmosphere_<name>` to `eamxx_<name>`

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2225]
For each process, the interface files connecting the AD and FM to the actual parameterization have been named `atmosphere_<name>.Xpp`. This is confusing and we decided to change these file names to `eamxx_<name>.Xpp` instead.

**Comment by bartgol** [comment]
Also, change <generic_name> to <pkg_name>, right? So e.g., `atmosphere_microphysics.hpp`->`eamxx_p3.hpp`.

**Comment by PeterCaldwell** [comment]
Yeah, Luca's correct. ^^^^

**Comment by AaronDonahue** [comment]
When addressing this we should look at #1322 to make sure it isn't possible to fix both with the same PR.
