### ISSUE TITLE
qv@bot not working right

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2230]
@crterai and Yunyan report that qv@bot looks really weird in our recent Oct 1 ne1024 simulation - it has values of 1e7. Looking at the bottom layer of the full 3d qv variable looks normal though. Chris reports that T_mid@bot looks fine for this run. There's also a possibility that there was a bug in our code in Dec when we did this run that we fixed in recent months (but I don't remember one).

Bad values from qv@bot:
<img width="920" alt="image001" src="https://user-images.githubusercontent.com/8432529/224188625-68dbe622-98a1-438f-adca-d2b187f46507.png">

Reasonable values from qv[127]:
<img width="920" alt="image002" src="https://user-images.githubusercontent.com/8432529/224188643-2c2090b3-bd02-448a-8d41-df528cc6f2ce.png">

**Comment by bartgol** [comment]
This might be a bug related to packing. I can check.

**Comment by bartgol** [comment]
Yes, in `field_at_level.cpp` we were using a dangerous/power-user method of `Field`, which is not safe if the field is a subfield. I will correct it.
