### ISSUE TITLE
Issues introduced by C++17

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/scream#2241]
This issue is a catch-all that we can use to track C++17-related things. It seems like it's a bit early for us to expect C++17 to work on all our target machines.

* [2240: Compile error in spdlog's version of fmt library on Crusher](https://github.com/E3SM-Project/scream/issues/2240)
* Our configuration on Ascent uses GCC 9.1, which is old and probably should be updated

**Comment by bartgol** [comment]
@jgfouca is currently testing a branch that may fix the crusher issue (we replicated a fix implemented in the fmt lib, which has not made its way into spdlog yet) :crossed_fingers:
