### ISSUE TITLE
Check output streams yaml files at buildnml time

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2246]
It is annoying if a job waits in the Q for hours just to find out that the list of vars requested is wrong (maybe just b/c of a typo). It would be preferable if buildnml inspected the yaml files, to detect any issue.

Possible checks:

- Ensure the list of fields contains no duplicates. See #2195 for an example of what went wrong before we put a runtime check for this.
- Ensure all fields in the list are indeed available. This would require some help from the parametrizations, providing some file (yaml,xml,python,...) containing a list of required/computed fields that one is allowed to request in I/O. Then, buildnml would parse these files, according to the list of atm procs currently enabled, to verify they are indeed available. It should also consider possible diagnostics, including blah@levN. NOTE: currently, the yaml file for output lists the fields under a list named after the grid they are defined on. So all these yaml/xml/python files listing valid fields should probably do a similar formatting, so that buildnml does not need to know anything about grids names.

**Comment by AaronDonahue** [comment]
Probably a naive idea, but are there ways to instruct the compiler to log info about the inner workings of the code? like when compiling "add_field" to also log that field in a text file or something?

**Comment by bartgol** [comment]
Closing, I don't think the 2nd bullet is realistically possible anyways.
