### ISSUE TITLE
Bad dphi error with ne120 using vtheta-thresh=100 on pm-cpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2252]
This case on pm-cpu does not fail with cold T like the others (https://github.com/E3SM-Project/E3SM/issues/6818) have on pm-gpu (at model dat 6/30). However, at `model date =   00020706`, it does hit a bad dphi error.

```
 6678: Bad dphi, dp3d, or vtheta_dp; label: 'CaarFunctorImpl::run TagPreExchange'; see hommexx.errlog.10880.6678
 6678: Exiting...

/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se59-mar13/t.se59-mar13.F2010-SCREAMv1.ne120pg2_ne120pg2.pm-cpu.n085t128x1cX.L128
```

**Comment by ambrad** [comment]
Would you put the output of hommexx.errlog.10880.6678 into a comment in this issue?

**Comment by ndkeen** [comment]
[hommexx.errlog.10880.6678.txt](https://github.com/E3SM-Project/scream/files/11023104/hommexx.errlog.10880.6678.txt)

**Comment by ambrad** [comment]
@mt5555 see above for the hommexx.errlog file. Looks like the problem is at the surface.

**Comment by ndkeen** [comment]
I'll close this issue as I don't have a clean reproducer here and we haven't had issues with ne120 on pm-cpu recently.
