### ISSUE TITLE
Missing scream init file on ANL server

### ISSUE THREAD

**Issue by elynnwu** [E3SM-Project/scream#2253]
`map_ne4np4_to_ne2np4_mono.nc` is missing from the public e3sm site:

```
  Could not download scream/init/map_ne4np4_to_ne2np4_mono.nc, output was:
  WARNING:root:wget failed with output: and errput --2023-03-20 22:50:46--
  https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/scream/init/map_ne4np4_to_ne2np4_mono.nc


  Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)...  140.221.70.30

  Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.70.30|:443...
  connected.

  HTTP request sent, awaiting response...  404 Not Found

  2023-03-20 22:50:47 ERROR 404: Not Found.
```

**Comment by AaronDonahue** [comment]
That file should be in the /maps/ subdirectory not in /init/. @elynnwu can you search for where that file is being requested as in /init and change it to /maps and see if that fixes the issue?

and then post here what file has to be changed?

**Comment by AaronDonahue** [comment]
https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/scream/maps/

You can see the correct file here.
