### ISSUE TITLE
Monthly restart skips Feb. when restarting from the end of the month

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2260]
This issue is an extension of the issue detailed in #2110.  @ndkeen did some more stress testing and found another case where the restarts that are written do not match the other components.  In this case, when 

1. writing monthly restarts, and
2. starting a run from a restart at the end of a non-February month.

The logic of how EAMxx checks if it is time to write a restart when the frequency is nmonths is to compare the current timestamp against the reference timestamp and write a restart if the following conditions are met.

1. The difference in the months is a multiple of the restart frequency.
2. The days match.  

The latter condition is to ensure that we only write a monthly restart on the proper day of the next month, in case we start a run mid-month and still want consistent monthly restarts.  This is a problem when we hit February for any start date that has a day >28, and an issue for other months when the start date has a day of 31. 

It appears that the other components default to writing a restart at the end of the month.  So if the start date is on day 30, when we hit February a restart is written on day 28.

**Comment by AaronDonahue** [comment]
A little more context.  

First, I don't see this as more than an edge case.  We don't often request monthly restarts for a simulation that starts mid-month, let alone on day 29,30 or 31. 

That being said, considering that it is possible what behavior do we want from EAMxx?  Do we skip a month that doesn't have that day?  Do we do as the other components do and write an output on day 28 of Feb for example.

**Comment by AaronDonahue** [comment]
Adding as a separate text-box because it pertains to how other components respond to this edge case.

It looks like they default to writing output to Feb. 28th, but then something strange happens, they switch to always writing restarts on the 28th.  Is this behavior what we want, albeit for this edge case?  @rljacob do you have any thoughts?

Note: with REST_OPTION=nmonths, REST_N=2, restart from 0003-12-30-00000 we get the following:
```
run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.cice.r.0003-12-30-00000.nc
run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.cice.r.0004-02-28-00000.nc
run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.cice.r.0004-04-28-00000.nc

run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.cpl.r.0003-12-30-00000.nc
run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.cpl.r.0004-02-28-00000.nc
run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.cpl.r.0004-04-28-00000.nc

run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.elm.r.0003-12-30-00000.nc
run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.elm.r.0004-02-28-00000.nc
run/SMS_Lm1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.monthly_restart_check_PR2256.elm.r.0004-04-28-00000.nc
```

**Comment by bartgol** [comment]
@AaronDonahue If I understand correctly, this is a corner case problem which may have no solution: when Feb 28th is picked, when computing the next monthly output timestamp, the infrastructure has no other option than picking Mar 28th.

Imho, this is a true corner case, which users simply need to be aware of, but that we do not need to cover (meaning, we don't need to have Jan 30th, Feb 28th, Mar 30th in our restart sequence). I'm closing, but feel free to add more comments (or even reopen if you want it fixed).
