### ISSUE TITLE
Output files should contain _FillValue attribute associated with output fields

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/scream#2262]
Netcdf files use the _FillValue attribute for missing data by convention. EAMxx output has the potential to write fill values for missing data (i.e., for the zeroth timestep output), but the _FillValue attribute is not added to output fields. Thus, missing data in output files ends up looking like garbage rather than masked data.

**Comment by brhillman** [comment]
I think PR #2174 should have fixed this, but I'm still not seeing valid FillValues in netcdf output files. For example, in our baselines on mappy:
```
ncmax sfc_flux_sw_net /sems-data-store/ACME/baselines/mappy/gnu9/master/SMS_D_Ln9.ne4_ne4.F2010-SCREAMv1-noAero.mappy_gnu9/scream.hi.0001-01-01-00000.nc.base
3.40282e+33 
```
We get the large value for the max because there is not a fill value attribute associated with the output field:
```
ncdump -h /sems-data-store/ACME/baselines/mappy/gnu9/master/SMS_D_Ln9.ne4_ne4.F2010-SCREAMv1-noAero.mappy_gnu9/scream.hi.0001-01-01-00000.nc.base | grep sfc_flux_sw_net
        float sfc_flux_sw_net(time, ncol) ;
                sfc_flux_sw_net:units = "s^-3 kg" ;
                sfc_flux_sw_net:long_name = "sfc_flux_sw_net" ;
```
So while we might be "masking" these fields as the AD is concerned, we are not propagating that information to the netcdf files for the user (and post-processing/analysis toolchains) to be able to use intelligently.

**Comment by bartgol** [comment]
Yeah, that PR uses a FillValue, but I did not store it in the nc file. The suggestion to do so came after the PR was merged.

**Comment by bartgol** [comment]
This was done in #2436
