### ISSUE TITLE
Discussion of how we handle restart frequency (and output frequency in general)

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2264]
Given the recent set of issues discovered by @ndkeen this issue is meant to serve as a single location to discuss how EAMxx will handle writing restarts, rather than have that conversation spread over the few issues already open, namely #2260 and #2263.

In summary of those two issues - 
1. Late month start-dates when the day of the data >=29 can lead to incorrect behavior for monthly output and restarts.  see #2260 
2. It now appears that when we run monthly restarts we are missing the first month of output, see #2263 

I think both stem from the same issue, how we determine if output needs to be written.  So I want to invite a discussion of the correct approach, rather than continue making changes that lead to more problems and/or need to be revised further down the road.  Note, I had already "fixed" this once but that seems to have caused other issues.  

_Current Approach:_
Each output stream stores a "reference" start date that is used to determine if the appropriate amount of steps/time have passed in order to write output or a restart.  With my current fix the reference date defaults to overall simulation campaign startdate for output and current run start for restarts.

**Comment by AaronDonahue** [comment]
My first pass through what the other components do seems to indicate that they calculate the number of steps until the next output.  Then they reassess that value after the next output is written.  That last step being necessary for monthly output.  This leads, however, to strange behavior when the startdate is >=29.  As I point out in #2260 , You might see a set of files with timestamps like this:
```
20221230 - Dec 30
20230130 - Jan 30
20230228 - Feb 28
20230328 - Mar 28
```
and so on.  So there is logic to account for Feb. not having 30 days, but it also resets the actual day to 28 from then on.  

So the first question is, is this okay behavior for admittedly an edge case?  Do we think EAMxx should adopt this approach?

Follow-up, am I characterizing what the other components do correctly?

**Comment by golaz** [comment]
Regarding monthly averaged output. Is the intent for EAMxx to 

1. support restarts in the middle of the month and still produce correct monthly averaged files, 
2. or only support restart at month boundaries.

(2) is obviously much simpler to implement and is something users could live with if the limitation is known. EAM supports (1), but it writes out additional files to make that possible.

**Comment by bartgol** [comment]
> Regarding monthly averaged output. Is the intent for EAMxx to
> 
> 1. support restarts in the middle of the month and still produce correct monthly averaged files,
> 2. or only support restart at month boundaries.
> 
> (2) is obviously much simpler to implement and is something users could live with if the limitation is known. EAM supports (1), but it writes out additional files to make that possible.

Yes, EAMxx _should_ support restarting in the middle of an avg window, and still get the correct average. Our ERS/ERP tests in the nightlies are testing this.

**Comment by bartgol** [comment]
> My first pass through what the other components do seems to indicate that they calculate the number of steps until the next output. Then they reassess that value after the next output is written. That last step being necessary for monthly output. This leads, however, to strange behavior when the startdate is >=29. As I point out in #2260 , You might see a set of files with timestamps like this:
> 
> ```
> 20221230 - Dec 30
> 20230130 - Jan 30
> 20230228 - Feb 28
> 20230328 - Mar 28
> ```
> 
> and so on. So there is logic to account for Feb. not having 30 days, but it also resets the actual day to 28 from then on.
> 
> So the first question is, is this okay behavior for admittedly an edge case? Do we think EAMxx should adopt this approach?

Assuming you characterization is correct, I would vote for doing the same thing in EAMxx. Not that I like it, but a) replicating EAM's behavior seems to make for a smoother transition to EAMxx, and b) restoring to original day can be a mess from the impl point of view (notice that it's not just a Feb issue, since if first output is on, say, Mar31st, you'd have to switch back/fort to 30-31 almost every month).
