### ISSUE TITLE
How to handle supercylced fields so that AVG output is correctly restarted?

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2276]
PR #2269 exposed an issue concerning radiation supercycling and non-instantaneous output. What happened was the following:

1. ERS run with AVERAGE output, including some fields that RAD computes (LW_flux_dn, LW_flux_up, SW_flux_dn, SW_flux_up, cldhgh, cldlow, cldmed, cldtot).
2.  eamxx ran for N timesteps, wrote a model restart file.
3. upon restart, those RAD fields were not restarted (they are not needed by the model, since RAD simply computes them).
4. upon restart, the first step did _not_ include a RAD update
5. the first IO output step after restart used some garbage (in this case, I think we were "lucky" and had all zeros) values for these fields to update the averages.

I discussed with @brhillman , and our stopgap solution was to add these fields to the RESTART group. That should fix the ERS tests (we'll see when AT runs, but that should be what will happen). However, it raises a bigger issue: how to handle supercycled fields when we have non-instantaneous output?

One solution would be to upgrade (add it to the list...) our I/O, so that, on top of an averaging window (which is currently specified by frequency and frequency units), the user can specify a "sampling frequency". The idea would be that you pick a sample for your average every N step, and we'd make sure that the snapshot is taken when rad is updated (we could handle this by better handling the fields timestamps in radiation, and making IO check that timestamps are equal to model timestamp when taking a snapshot).

I had this idea in the past, but I didn't think it was _that_ useful. Radiation might be the only case where it is. Although, one may also wonder if "supercycling" I/O could in general be useful for AVERAGE output: if you compute daily averages or even 6h averages, do you really need snapshots at the model timestep (which for ne1024 is 100s=1m40s, from what I can see), or is it enough to take snapshots every 15min (that is, 10x less averaging work)? I don't know if these are actual use cases though, so maybe this scenario is not relevant, and the only issue is RAD avg output on restart...

Pinging @AaronDonahue and @PeterCaldwell as well.

**Comment by PeterCaldwell** [comment]
I thought (but am probably wrong) that radiative fluxes are held constant over all the timesteps between radiation calls. Or maybe held constant except for an adjustment to account for changes in zenith angle. If either of these is true, then including steps other than when radiation is called in our averaging wouldn't cause problems.

I guess the other option would be for radiation output during non-radiation calls to be zero or NaN. Averaging over that would certainly be a problem. 

@brhillman - how are radiation variables handled in between radiation steps?

**Comment by bartgol** [comment]
I believe you are right, but the issue is that those fields are _not_ restarted (since they are not inputs to anything). Therefore, if the first step after restart is not a RAD step, we have no value for that field.

In other words, the issue is a restart one. I floated the idea of subsampling output, since that would fix the RAD issue (just pick only snaps where RAD _is_ updated). But that's just a way to solve the issue of not having any value for those fields upon restart if RAD is not called at the first step.

**Comment by PeterCaldwell** [comment]
> if the first step after restart is not a RAD step, we have no value for that field.

Oh ok. Don't we need rad variables in the restart file in order to stay BFB in this case though? In which case we'd have them for output as well? Are we just talking about diagnostic output variables from radiation? Do we even have any of those?

**Comment by bartgol** [comment]
From what I understand, those 8 quantities are diagnostic output of RAD. They are computed based on other stuff, but never "updated" (meaning we never do var += blah). That means that we do not need them for BFB restarts. Put it another way, those vars have zero effect on the state (since the ERS test shows diffs for the output only in those vars, not the state), so having them in the output only serves the purpose of plotting some intermediate quantities.

@brhillman is probably better suited to clear your doubts though. Mine is just speculation based on observed output shenanigans.

**Comment by PeterCaldwell** [comment]
Ah, got it. I hadn't paid attention to the "8 variables" in your original message. The 4 cloud fraction variables are definitely output-only. We can actually delete them if it makes our life easier since they end up using the ice cloud fraction needed to trigger the microphysics at all rather than what analysts would actually use. I'm a bit surprised the 3d radiative flux info isn't what the model uses internally, but I guess I can see it.

**Comment by bartgol** [comment]
I think we can close this issue. We are now enforcing restarts to coincide with rad actual steps (that is, `rad_frequency` perfectly divides `REST_N`). If anything related to this comes up again, we can reopen (or open a new one).
