### ISSUE TITLE
Select 2D variable coarsening output not supported

### ISSUE THREAD

**Issue by elynnwu** [E3SM-Project/scream#2284]
We're not able to coarsen `surf_mom_flux_U`, possibly other variables too. Here's a list of 2D variables we're trying to coarsen:

```
filename_prefix: output.scream.remapped_output.2d
Averaging Type: Average
Max Snapshots Per File: 56 #one file per week
vertical_remap_file: /usr/gdata/climdat/eamxx-ml/maps/map_ne120pg2_to_ne30pg2_20230328_vert_enhanced.nc
horiz_remap_file: /usr/gdata/climdat/eamxx-ml/maps/map_ne120pg2_to_ne30pg2_20230328_vert_enhanced.nc
Fields:
  Physics PG2:
    Field Names:
    - sfc_flux_dir_nir
    - sfc_flux_dir_vis
    - sfc_flux_dif_nir
    - sfc_flux_dif_vis
    - sfc_flux_sw_net
    - sfc_flux_lw_dn
    - PrecipLiqSurfMassFlux
    - PrecipIceSurfMassFlux
    - ps
    - surf_sens_flux
    - surf_evap
    - surf_mom_flux_U
    - surf_mom_flux_V
    - SW_flux_dn@bot
    - SW_flux_up@bot
    - LW_flux_dn@bot
    - LW_flux_up@bot
    - SW_flux_up@tom
    - SW_flux_dn@tom
    - LW_flux_up@tom 
output_control:
  Frequency: 3
  frequency_units: nhours
  MPI Ranks in Filename: false 
```
And the error:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  /g/g20/wu62/E3SM/EAMxx/code/20230328/scream/components/eamxx/src/share/grid/remap/vertical_remapper.cpp:236: FAIL:
src_layout.rank()>1 || src.get_header().get_alloc_properties().get_padding()==0
Error! vert_remap:do_bind_field:check_src:surf_mom_flux_U, We don't support 2d scalar fields that are padded.
```

**Comment by PeterCaldwell** [comment]
Ok. Try removing surf_mom_flux_U, surf_mom_flux_V. I suspect you will also have to remove U and V from the 3d file. These 2 variables are unique in that the model internally considers them to be arrays called surf_mom_flux and horiz_winds which have u and v components. It seems that this special output handling doesn't work with coarsening. 

Not to say this behavior isn't a bug we should fix, just trying to isolate the problem. Outputting horiz_winds and surf_mom_flux might be a temporary workaround.

**Comment by bartgol** [comment]
As Peter suggested, requesting the "parent" field (of which they are simply a slice) is a good workaround.

Looking at the code, I think this assertion can probably be easily removed. I can try to take a look at some point, but my todo list is already quite long, so ... I hope the workaround works! :)

**Comment by bartgol** [comment]
This is not an I/O issue, per se, but given that the vertical remapper is only used in I/O, we can consider it as such.

**Comment by elynnwu** [comment]
Confirmed that writing out the parent fields worked.
