### ISSUE TITLE
Add OCNFRAC And LANDFRAC to imported variables

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2295]
Ocean and land fraction are two variables made available to the ATM by the CPL.  We currently do not use these in EAMxx so they are not imported, but they are valuable for post-processing.

This task is to simply create two new imported atm. fields `ocnfrac` and `landfrac` and then include those fields into the set of imported variables from CPL.

**Comment by AaronDonahue** [comment]
@golaz I made this issue to track your request for these variables.

@tcclevenger , I assigned to both of us since I think either one of us is pretty well suited to make this change.  Once one of us has a couple free cycles to tackle it we can just ping the other that we are taking it on.

**Comment by tcclevenger** [comment]
I'm going to submit a PR for this soon. What are the units on each `ocnfrac` and `landfrac`?

**Comment by PeterCaldwell** [comment]
They're a fraction. They can be between 0 and 1.

**Comment by tcclevenger** [comment]
Thanks @PeterCaldwell.

**Comment by tcclevenger** [comment]
See https://github.com/E3SM-Project/scream/pull/2302. `ocnfrac` and `landfrac` can be requested on physics grid in output manager when merged.
