### ISSUE TITLE
Switch `atm_procs_list` in EAMxx control file to a vector of strings

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2305]
Currently EKAT is set to parse the `atm_procs_list` namelist variable in EAMxx as a single string, which is then further parsed internally into a list of processes.  This can be counterintuitive to users who likely think of this as a list that needs to be changed as a list would be.  Similar to how the `output_yaml_files` namelist parameter is changed.

The task is to update the parsing of the EAMxx namelist file to treat `atm_procs_list` as a vector of strings.

**Comment by bartgol** [comment]
There is a potential minor problem with this task (though I suspect it's no longer a problem).

In my original XML implementation, I allowed the `atm_proc_list` entry to describe nested groups. E.g., one could have had `(homme,(shoc,p3))`, do denote that shoc-p3 would form an atm proc group, whose name would be `shoc_p3` (basically `"_".join(p for p in atm_proc_list)`, in pythonese). I wanted this feature to be able to allow users to change atm proc list at will. E.g., I wanted to allow
```
$ ./atmchange atm_proc_list=(homme,(p3,shoc))
```
This was also the reason why I added EKAT's util [parse_nested_lists](https://github.com/E3SM-Project/EKAT/blob/c7dec6634c09c58d39538d139ca351a4df5dba33/src/ekat/util/ekat_string_utils.hpp#L152).

If we limit ourselves to array of strings, then the input arg cannot contain nested strings. This may limit our ability to do runtime changes to the atm proc list without changing namelist_defaults.xml. For instance (this may be non-realistic, but just to explain the issue), our current atm proc list is defined by the following XML snippets (cutting irrelevant stuff):

```
   <atm_procs_list locked="true">(sc_import,homme,physics,sc_export)</atm_procs_list>
    <physics inherit="atm_proc_group">
      <atm_procs_list>(mac_aero_mic,rrtmgp)</atm_procs_list>
    </physics>
    <mac_aero_mic inherit="atm_proc_group">
      <atm_procs_list>(shoc,cldFraction,spa,p3)</atm_procs_list>
      <atm_procs_list COMPSET=".*SCREAM.*noAero">(shoc,cldFraction,p3)</atm_procs_list>
    </mac_aero_mic>
```
Let's say one wanted to replace spa with a subcycling of `(spa,zm)` (again, forget the fact that it may make no sense from that atm modeling point of view, we're discussing infrastructure here). To do this with a vector of strings, I would have to give a name to this group, say `spazm`. But then, `spazm` would have to be an existing atm proc entry in namelist_defaults.xml, or else buildnml will not know what to do with it. With nested lists syntax, one can simply do
```
$ ./atmchange mac_aero_mic::atm_procs_list="(shoc,cldFraction,(spa,zm),p3)
$ ./atmchange spa_zm::num_subcycles=3
```

Now, this was to explain what the current  syntax allows that the vector of strings doesn't. Of course, if we agree that the use case above is too much of a corner case or very unlikely to ever happen, then we're good, and can replace the string with a vector of strings. Each user desiring to experiment with atm procs will have to add their new atm procs lists to namelist_defaults.xml.
