### ISSUE TITLE
test-all-scream may be doing the wrong thing when handling PRs from forks

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#231]
During PR testing, the first thing we do is to merge `origin/master`, to make sure the repo will be good _after_ the PR is merged.

However, due to how the AT works, the `origin` in `origin/master` is the same repo where the branch of the PR is. When the PR comes from a fork, this may *not* be the same as the master branch on E3SM-Project/scream.git.

Possible solutions:

-  manually add a second remote, pointing to E3SM-Project/scream.git (which may be the same as origin if PR branch is on main scream repo), then merge master from this second remote
- always get the main scream repo rather than the one where the branch resides, then check out the PR branch with the (very cool and very little known) git syntax: `git fetch origin pull/PR_ID/head:BLAH && git checkout BLAH`, where PR_ID is the number of the pr, and BLAH is whatever name we want to give to this branch. This cool git feature allows you to checkout the branch of a PR without having to clone the repo where the branch is.

I personally like the second option very much, but I'm not sure if it requires changes to the AT framework. Remebver that we don't have access to the AT source code (well, we can hack it from the jenkins job workspace, but that's not the way to go). I have to double check.

**Comment by jgfouca** [comment]
Agree, the second option is definitely better.

**Comment by bartgol** [comment]
And given what you told me in chat, it looks like option 1 is not feasible.

**Comment by bartgol** [comment]
This has been fixed without having to change the code. That is, we did a few tweaks of the jenkins jobs, and now it seems to be working correctly. Closing.
