### ISSUE TITLE
Incorrect output variable units

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/scream#2319]
@czender first alerted me to this.

Some EAMxx output variables have incorrect units

- **RelativeHunidity**: should be '1' instead of 'K'
- **lat**, **lon**: current unit is '1'. See CF conventions for how they should be specified: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#latitude-coordinate

Also, units for radiative fluxes and surface sensible flux are correct (s-3 kg) but not very intuitive. W m-2 would be more intuitive, but maybe there was a desire to stay with SI base units only.

**Comment by bartgol** [comment]
Re: SI units. Our units framework stores everything in SI units internally. The default print string is therefore a SI units. However, we do support 'user-defined' strings, in case some units are easier to read (e.g., Pa for is easier to parse than kg m-1 s-2) or are more common in the atm field (e.g., kg/kg would be stored as '1'). We already do set user-defined strings for some units, so this is just a matter of doing the same for any other desired variable.

**Comment by bartgol** [comment]
Looking at the code, it seems this has been fixed.
