### ISSUE TITLE
BLAS in threaded land component on Frontier

### ISSUE THREAD

**Issue by oksanaguba** [E3SM-Project/scream#2335]
It was suggested that we create an issue for the problem. It is desirable to run the land component with threads, which requires using a thread-safe  blas. Previously, @ambrad had already encountered issues with threaded runs on Frontier; also, from old communication, @sarats might have created an OLCF ticket for it.

Here we summarize the most recent attempts to resolve this problem per PR https://github.com/E3SM-Project/scream/pull/2279 .

S. Abbott traced wrong libsci (not thread-safe) flags to cmake and wrong CC compiler. His suggestions https://github.com/E3SM-Project/scream/pull/2279/commits/8fcd12e4c1750177ef72fb50ad47d2772eb5fffb were tested for an ne30 run with 7 land threads and there were no crashes or blas errors in 14 runs.

We then switched to 512-node runs, but it crashed without blas messages, but right at the blas call in land
```
(gdb) bt
#0  0x0000000001524350 in banddiagonal$banddiagonalmod_ ()
#1  0x0000000000d24a42 in solvetemperature$soiltemperaturemod_ ()
#2  0x0000000000d19459 in soiltemperature$soiltemperaturemod_ ()
#3  0x000000000067477b in elm_drv$elm_driver.cray$mt$p0005 ()
#4  0x00007fffe273ff77 in _cray$mt_start_one_code_parallel () from /opt/cray/pe/cce/15.0.0/cce/x86_64/lib/libcraymp.so.1
```
So we switched to no-threads runs, but there was the same issue and the same stack in core as above.

Finally, Andrew found a raw implementation of blas calls for land, which (up to some hiccups, maybe, due to machine issues) allowed us to have a 3-day run, folder fgpu-build-apr27-r4096-replaceblas .

 Per @sarats  suggestion, tagging @grnydawn in case he is interested in separating a small reproducer.

**Comment by sarats** [comment]
As this crashes even for non-threaded runs, this seems different from requiring thread-safe libsci. Can you confirm if your run was still compiled with OpenMP using one thread or completely omits openmp flags?

Related ticket: OLCFDEV-1540 Jira during early access period on Frontier. Might need to re-submit once we have clarity as it may have fallen off their radar.

**Comment by sarats** [comment]
Is this is an intermittent failure or occurs all the time? For a successful run, how much time is typically spent in this routine/region?

**Comment by oksanaguba** [comment]
for non-threaded runs, i did not see fopenmp is land flags. i did not try too many nonthreaded 512-node runs (maybe, 2, both failed).

**Comment by oksanaguba** [comment]
Regarding how expensive the routine is -- BandDiagonal calls blas routines, timer for BandDiagonal is SoilTempBandDiag 22 sec for a run which has ATM_RUN=4422 sec.

**Comment by sarats** [comment]
If using reference blas works for all cases (threaded or otherwise), then we can put this on the back-burner as it's not computationally expensive,

**Comment by oksanaguba** [comment]
i did not try to use ref implementation in threaded runs.

**Comment by ambrad** [comment]
Oksana, I recommend running the intended production configuration -- 7 threads for LND -- with the machines/frontier branch to make sure it's ready.

**Comment by oksanaguba** [comment]
are you guys saying the ref implementation is thread-safe? for example, no need to run bfb threaded tests? i thought the plan was to use 1 land thread with it.

**Comment by ambrad** [comment]
Yes, the reference implementation is thread safe.

**Comment by bartgol** [comment]
On slack, we discussed the fact that we seem to no longer have this issue. We are currently not using the branch with the hand-rolled blas routine, and yet see no crash, possibly suggesting that the problem has been fixed by the machine maint group. Closing for now.
