### ISSUE TITLE
`PrecipLiqSurfMassFlux` and `PrecipIceSurfMassFlux` output cannot be instant

### ISSUE THREAD

**Issue by elynnwu** [E3SM-Project/scream#2353]
This output stream does not work:

```
%YAML 1.1
---
filename_prefix: output.scream.land.replaced.2d
Averaging Type: Instant
Max Snapshots Per File: 56 #one file per week
Fields:
  Physics PG2:
    Field Names:
    - PrecipLiqSurfMassFlux
    - PrecipIceSurfMassFlux
output_control:
  Frequency: 3
  frequency_units: nhours
  MPI Ranks in Filename: false
```

Error message:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  /g/g20/wu62/E3SM/EAMxx/code/scream/components/eamxx/src/share/util/scream_time_stamp.cpp:21: FAIL:
mm>=1 && mm<=12
Error! Month out of bounds. Did you call `days_in_month` with yy and mm swapped?
```

Adding `printf("Check - %s, %s\n",t_start.to_string().c_str(),t_now.to_string().c_str());` inside `components/eamxx/src/diagnostics/precip_liq_surf_mass_flux.cpp` give:

```
Check - -2147483648--2147483648--2147483648--2147483648, 2010-01-01-00000
```
It appears that `t_start` is not initialized.

If averaging type is average, no error message.

**Comment by PeterCaldwell** [comment]
Definitely a bug. As a workaround, I think `PrecipLiqSurfMass` (without the flux on the end) should work. And same for ice phase. You just need to divide the output by the timestep to convert mass per step to flux per second.

**Comment by elynnwu** [comment]
Right, this issue is actually non-blocking but wanted to report what I found so that it's documented.
