### ISSUE TITLE
Test different OMP thread counts in AT to satisfy E3SM code review?

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2359]
E3SM's code review requires that stealth features pass the "super-BFB test suite", which is defined here: https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/3438608385/E3SM+Code+Review+and+New+Feature+Process#Super-BFB-suite

I think our AT automatically tests all of these things except OpenMP threading. Could we easily add a test or two to the AT so we can check this box? I suspect E3SM's code review would include more tests if it had imagined we would be running on GPUs, but I also think(?) we have adequate coverage for GPU cases. Am I wrong?

@jgfouca - I suspect you're most up-to-date on this topic?

**Comment by jgfouca** [comment]
@PeterCaldwell , our AT runs the standalone SCREAM suite and some CIME cases. Our standalone suite does extensive thread "sweeping" (run same test with 1->N threads) so I think we can claim to cover this. Our CIME cases do not change threads though.

**Comment by PeterCaldwell** [comment]
Ok thanks. I thought we did thread sweeping so was surprised to hear that we weren't testing threading when I asked on the eamxx channel. I guess I should have been more specific. I agree that for PRs that change units, we should have adequate coverage (and including threading tests in full-model integrations is probably more expensive than we want for the AT). I'll close this issue after waiting another day or so for more comments.

**Comment by bartgol** [comment]
I still think there may be some value in doing a threaded run through CIME. There are a few things we may want to check. E.g., is EAMxx picking up the CIME thread specs correctly? And is surface coupling thread safe? (I don't think we run SC unit tests with threads).

**Comment by jgfouca** [comment]
@bartgol , we could add something (a PET test) to one of our suites. Mappy defaults to 1 thread so it would not be useful to run it there.

**Comment by PeterCaldwell** [comment]
Update on this @fouca and @bartgol ? It seems trivial to do so maybe we should before we forget?

**Comment by jgfouca** [comment]
@PeterCaldwell , yes, I will add something to our AT test suite.
