### ISSUE TITLE
Create derived output total precipitation

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2368]
To reduce output data volume, it would be useful to have a derived output of

precip_total_surf_mass_flux = precip_liq_surf_mass_flux + precip_ice_surf_mass_flux

**Comment by bartgol** [comment]
I saw there are a few derived outputs that are simply an arithmetic combination of others. Perhaps we should look into creating a general diagnostic that can do that. Ideally, parsing a simple arithmetic string and computing the result, but I would settle for something like FieldSum (f1+f2), FieldProd (f1*f2), FieldScale (f1*C), FieldDiv (f1/f2) FieldPow(f1^k)...

**Comment by PeterCaldwell** [comment]
In the past I've advocated against users being able to create new variables at run time because I fear we'll lose all provenance of what variables mean what. But now I'm conflicted - this capability may go a long way towards making EAMxx more accessible for people that just want to make small changes.

A couple details:
1. If a user is creating new variables, they will need to be able to choose new names for those variables. I think people have suggested that we should be able to change variable names in the past and this would naturally be a way to do it (just by outputting NEW_NAME = FieldIdentity(INTERNAL_NAME) ).
2. Similarly, this would allow us to write our output with whatever units we wanted (by explicitly specifying the unit conversion as an algebraic function)
3. We could largely solve my provenance concern by automatically setting the "long_name" attribute for these variables to the algebraic function we are using (e.g. long_name = 'FieldSum( precip_liq_surf_mass_flux, precip_ice_surf_mass_flux)'.
4. I still think we'd want to make variables we expect lots of people will want into derived variables rather than having our output yaml files become code in themselves.

**Comment by AaronDonahue** [comment]
> If a user is creating new variables, they will need to be able to choose new names for those variables. I think people have suggested that we should be able to change variable names in the past and this would naturally be a way to do it (just by outputting NEW_NAME = FieldIdentity(INTERNAL_NAME) ).
I've been wanting something like this for awhile.  I would be in favor of allowing users to rename variables on the fly and taking advantage of suggestion (3) in Peter's comment we could include provenance by including the original field name in the the long_name.  
> Similarly, this would allow us to write our output with whatever units we wanted (by explicitly specifying the unit conversion as an algebraic function)
Yes, we would want to make sure that the `units` entry in the variable metadata reflected this change.
> We could largely solve my provenance concern by automatically setting the "long_name" attribute for these variables to the algebraic function we are using (e.g. long_name = 'FieldSum( precip_liq_surf_mass_flux, precip_ice_surf_mass_flux)'.
Yes, i think this would be a good idea.  Note, we are not limited to `long_name`, we can add any metadata we want, so we could also include a metadata like `notes`
> I still think we'd want to make variables we expect lots of people will want into derived variables rather than having our output yaml files become code in themselves.
Yes

**Comment by AaronDonahue** [comment]
At risk of complicating things, another option we could explore for user defined variables is to be more explicit in the YAML file.  So something like a sublist of user defined fields:

```
  Physics GLL:
    Field Names:
      blah
    User Defined Fields:
      Fields Names:
        - Field_A
        - Field_B
       Field_A:
        Name: "My name is A"
        Units: unitless
        Derivation: FieldSum(precip_ice_mass,precip_liq_mass)
```

**Comment by PeterCaldwell** [comment]
Yeah, I think we'd have to do something like your last comment because we would need to allow users to set the units and possibly other field properties.

**Comment by AaronDonahue** [comment]
right, that was my thought.  And would make parsing things on EAMxx side easier.

**Comment by bartgol** [comment]
I think you are going way further than I was suggesting. All I was suggesting is a way to quickly add a variable on the fly. Changing units and properties and other stuff goes further than that, though I can see why one woult think about that. Personally, I was thinking about code reduction: this feature _could_ help to define most of our diag output in terms of a handful of diagnostic classes, which _may_ be beneficial in terms of code maintenance.

**Comment by bartgol** [comment]
@pbosler pointed out that #2180 may have already done this. @tcclevenger can you confirm?

**Comment by tcclevenger** [comment]
Yes, I think that is the same. The PR calculates
```
precip_total_surf_mass_flux = (precip_ice_surf_mass + precip_liq_surf_mass)/(rho_h2o*dt)
```

**Comment by bartgol** [comment]
Great, then I'm closing this. Feel free to reopen if we missed something.
