### ISSUE TITLE
Create 10-m U and V component wind speeds 

### ISSUE THREAD

**Issue by crterai** [E3SM-Project/scream#2380]
Currently we have the `wind_speed_10m` as an output for 10-m wind speed (U and V combined total wind speed), but some use cases require the U and V components to be separated for 10-m wind speeds. It's a larger undertaking, since 10 m wind speed is currently calculated in the coupler, but having these as available output in EAMxx would be useful for various cases (e.g., comparison with ERA5, storm analysis, renewable energy).

**Comment by bartgol** [comment]
We can currently compute any field at a certain pressure height. I suppose we can upgrade the diagnostic to compute quantities at a certain elevation.

**Comment by PeterCaldwell** [comment]
> We can currently compute any field at a certain pressure height. I suppose we can upgrade the diagnostic to compute quantities at a certain elevation.

That would be great. I think that was originally part of our plans but got sidelined. Not a huge priority though.

**Comment by crterai** [comment]
This certain elevation capability would be great. I know for the renewable energy community (wind), they're mainly interested in winds at ~100m height.

**Comment by bartgol** [comment]
To be clear, this is elevation from surface, not sea level, correct?

**Comment by PeterCaldwell** [comment]
Yes, that's right. We want elevation from surface.

**Comment by bartgol** [comment]
We took care of this in #2388

**Comment by bartgol** [comment]
Actually, even though the diagnostic was implemented, we never added the logic for requesting it to I/O. Re-opening.
