### ISSUE TITLE
Add functionality to output cloud droplet number at cloud top

### ISSUE THREAD

**Issue by susburrows** [E3SM-Project/scream#2394]
To analyze albedo susceptibilities to aerosol and calculate other ACI-related diagnostics, we (@mahf708, @jmuelmen, and myself) would like EAMxx to produce a CDNC diagnostic variable similar to that of Aerocom. This variable should provide the average cloud droplet number concentration in the first liquid cloud level (from the model top) that contains "sufficient" total cloud water (above a pre-defined threshold).  The rationale is to simulate the cloud droplet number that would be retrieved from a satellite such as MODIS.

The calculation of this diagnostic can be simplified in EAMxx (as long as we assume we’re running at 3km) compared to how it is done in EAM.  This is because at 3km, we can, to a first approximation, ignore some of the complexities related to the interpretation of cloud fractions when comparing MODIS data with the model in coarse resolution models.

The algorithm to calculate cloud-top CDNC can then be simplified to the following (the calculation is done per column):

- Iterate through model levels beginning with the second level from the top (the Aerocom procedure in EAM assumes that there is no cloud in the top level)

- The diagnostic CDNC equals the cloud droplet number concentration (grid-box mean) in the “stratocumulus cloud-top” level.  When we reach a level where three criteria are all met, we call this the “cloud top”.    The criteria are:
    1. No cloud ice is present
    2. Cloud liquid cloud water content exceeds a pre-defined threshold value
    3. Liquid cloud fraction exceeds a pre-defined threshold value

- After reaching the cloud top, exit the iteration (the computation in the coarse-resolution model also looks at levels below the cloud top and estimates the additional cloud fraction that a satellite would see there, but we can ignore that at 3km resolution).

The pre-defined threshold values have not yet been determined, but we can provide some placeholder values.  It might be useful to implement them as parameters that are accessible through the namelist.

**Comment by PeterCaldwell** [comment]
Interesting question - can/should we generalize this to provide any output variable at cloud top? Or at cloud base?

**Comment by susburrows** [comment]
> Interesting question - can/should we generalize this to provide any output variable at cloud top? Or at cloud base?

I was just about to update the issue to say that this might be helpful :)

**Comment by AaronDonahue** [comment]
What value would we assign in a clear-sky column (i.e. those 3 criteria are never met)?  A mask value?  0?

**Comment by AaronDonahue** [comment]
> Interesting question - can/should we generalize this to provide any output variable at cloud top? Or at cloud base?

I think this would be relatively straightforward to code up, ala the approach we use for X_at_lev and X_at_hPa

**Comment by bartgol** [comment]
Interesting topic for diagnostic outputs! A couple of comments.

1. We do not have a column max/min/sum/avg diagnostic. Nobody ever requested it, so we never implemented it, but if it's something we need, we can add a ticket.
2. We could add a diagnostic that computes a 2d (int) field, whose values are the cloud top level location at each column. This diag can then be piped to an upgraded version of FieldAtLevel, where the level is specified via a 2d field. This are interesting features, but again, nobody ever needed them. @mahf708 if you think it's needed, we can add a ticket.
