### ISSUE TITLE
Allow online filtering of data?

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2397]
A potentially cost-saving feature is allowing users to filter data online. Dealing with large datasets is time consuming and one ends up cleaning the data a lot to begin with. Is this doable? I am not familiar with the code base, so it could well be already available or discussed elsewhere; if so, sorry and please feel free to close.

--

A concrete example is the functionality request/wish in #2394. In practice, we end up using a tiny fraction of column–time data saved. Consider the following filters (simplified, but not far from what we likely will end up using): 
- solar zenith angle above 50
- cloud fraction above 0.90
- ice content fraction less than 0.10

These filters can leave one with less than 10% of the data saved.

--

A potential way to do this is a routine that filters each `(column, time)` point based on conditions specified by the user. That way the users will have smaller (and thus more tractable datasets) but also potentially allow the users to time-sample the data more frequently (instead of 3-hourly, 1-hourly and so on).

--

A major problem, at least for some users, would be the wildly unstructured nature of the data saved. For example, some time steps may have 10000 columns whereas others may have 20000 columns saved. However, that will be the user's problem to deal with.

--

Xrefs:
- cloud-top CDNC #2394 (recent issue inspiring this issue)
- field-at-height #2388 (recent PR with relevant workflow that could be generalized)

**Comment by AaronDonahue** [comment]
>A major problem, at least for some users, would be the wildly unstructured nature of the data saved. For example, some time steps may have 10000 columns whereas others may have 20000 columns saved. However, that will be the user's problem to deal with.

Unfortunately this may also be a major hurdle from an infrastructure perspective.  The IO libraries work off a static set of dimensions which I believe are necessary to properly store data in the netCDF format.  So when we register a variable with `ncol` as a dimension we can't change `ncol` overtime, without opening a new file.  

A solution might be to add a lighter filtering that just assigns a masked value to anything outside of the filter options, then a post-processing tool need only look for masked values and ignore them, rather than have to be defined to follow specific filters.

**Comment by bartgol** [comment]
@mahf708  To be clear, we can cook up some file format to save exactly what you want. The deeper infrastructure issue is to ensure that there are downstream tools for postprocessing. If you already know of a format that has already tools in place to parse sparse data (in the form of programs or scripts), then we can think of a strategy to incorporate them in EAMxx.

**Comment by PeterCaldwell** [comment]
I'd love to have this capability, but it is what we call a "wishlist" item - we don't have the staffing to do more than the bare essentials to get/keep the model running at this point. 

A variant of this approach that would work with a fixed grid is: in each column, accumulate (i.e. sum) all snapshots which satisfy some criterion (e.g. identified as a convective core) and increment a counter every time you add a snapshot. Then once a month or once a year, write out the accumulated values for that column divided by its counter. This would provide composited profiles over particular events without needing to save every snapshot and postprocess. If you are only interested in convective cores (for example), you could further reduce data volume by only writing output for the region where you expect tropical deep convection.
