### ISSUE TITLE
Wrong check in surface coupling unit test. Test fails when check is corrected

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2408]
[This line](https://github.com/E3SM-Project/scream/blob/26baa19dab79a4473c9fb46a71ce27ac44740184/components/eamxx/tests/uncoupled/surface_coupling/surface_coupling.cpp#L436) in the surface coupling unit test has the wrong parentheses. As is, it checks `abs(diff<tol)`, rather than `abs(diff)<tol`. Special thanks to the compiler that informed me that `taking the absolute value of unsigned type 'bool' has no effect`.

Unfortunately, once I changed this to do the correct check, the test started to fail with 2+ ranks. I tried to go through it, and fixed a few things, but it still crashes. Additional info (hopefully it can help):

- tests always pass on one rank, but fail on all others
- the fail is in the second call to `test_exports`, so I _assume_ the imports are correct.
- it's not a roundoff diff:
```
Faxa_lwdn_file: 689.000000
exprt data view: 797.999939
```

@tcclevenger I'm assigning you since you might spot right away what's wrong. I pushed the branch `bartgol/surface-coupling-test-fixes` with the MPI consistency fixes, in case you want to take a look. I can't be 100% sure that the bug is limited to the test; it may as well be in the SC itself. But the fact that tests pass on one rank, makes me think that there is still an inconsistency between ranks. Perhaps another input that is not broadcasted correctly.

**Comment by AaronDonahue** [comment]
I think I am responsible for this test since it should be using a file to prescribe the surface values. So I will check this out too

**Comment by AaronDonahue** [comment]
Got it! It was just a poor test setup on my part that didn't account for GIDs in multi-rank cases.  I've pushed a fix to the branch @bartgol if you want to open a PR.

**Comment by bartgol** [comment]
Thanks @AaronDonahue !
