### ISSUE TITLE
Remove namelist_defaults.xml file from case dir

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2412]
We now save all the issued atmchange commands in CIME env (every time atmchange runs, under the hood we call `xmlchange --append SCREAM_ATMCHANGE_BUFFER=$the_change` to store the change and redo it later if case settings change). This is however making me think that we no longer need the atm XML file in the case dir: everytime buildnml runs, we can generate scream_input.yaml, as well as namelist.nl, without any need to store the intermediate XML file.

Pros:
- less files for the user to understand (not that they _need_ to understand what `namelist_defaults.xml` did, but curious users might, and end up just more confused)
- avoid bad usage, where users modify the intermediate XML file, without seeing the new values in the output yaml/nml files

Cons:
- no power-user method, where we tell atmchange that we don't want to use the buffer in the CIME xml file, and manually change the atm XML file

Personally, I think the power-user capability is not that important. I don't even know if we ever use it. Mostly, because I think we are now capable of doing whatever mod we want using atmchange. So I think it's ok to remove the `namelist_defaults.xml` file completely.

@jgfouca @AaronDonahue @PeterCaldwell @tcclevenger @ndkeen @crterai pinging you since you are either part of the eamxx design or power-users of eamxx (or both). And feel free to ping others that are using atmchange & friends.

**Comment by bartgol** [comment]
@jgfouca I think I may withdraw this as an issue, since I _think_ we may need the intermediate XML file for atmquery (otherwise we would have to regen the XML tree from the defaults as well as the ATMCHANGE_BUFFER every time atmquery is issued).

That said, I think we should rename the file since a) these are not the defaults, b) we do not use (only) namelists, so the name is not entirely correct, and c) the name is generic (someone may think these are the params for the whole model).

**Comment by jgfouca** [comment]
@bartgol , we can keep it if there's still changes you think are needed. Maybe just edit it?
