### ISSUE TITLE
When a new atm proc is added via atmchange, regenerate the intermediate xml file, to include its defaults

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2427]
Currently, when one does something like
```
./atmchange physics::atm_procs_list=(shoc,cld,spa,p3,foo)
./atmchange foo::blah=2
```
we would get an error, since `foo::blah` is not found. That's because `atmchange` looks for the parameter in the intermediate XML file (in the case dir), which, if `foo` was not included in the current compset, would not contain the `foo` atm proc defaults. In order to re-generate the intermediate XML file (which would then contain the `foo` process section) one needs to re-run `buildnml`, e.g. via `case.setup`. This can be confusing, since it means we must run `case.setup` twice (the first time to get the atmchange script linked in the case folder, and the second to get the `foo` settings in the XML file in the case folder). The average user may be confused by this, and their productivity will be impacted.

There are a few options to fix this.

- Re-generate the intermediate XML file every time atmchange runs. This may make manual case handling a bit slower.
- When we create the intermediate XML file, we could also put the defaults for all atm procs in it, even if not currently included in the ATM ap list. Obv, we would put them in an XML section that would not be included in the final yaml input file.
- When we run atmchange, if an atm proc list is changed, we add some code that, if a new atm proc has been added, it grabs the defaults from the XML defaults file in the src tree.

I think the only use case that requires `case.setup` to be re-run is precisely the one described above. Adding a new atm proc (or even swapping one for another) is the only scenario where a new XML section needs to be added to the intermediate XML file. Therefore, I think we can handle this inside atmchange: if we detect that the entry to be changed is an `atm_procs_list`, we can scan the current XML file in the case folder, and update the sections of the atm procs. E.g., if we swap shoc with clubb, we should remove the shoc section, and add the clubb section, grabbing it from the defaults XML file in the src tree.

**Comment by elynnwu** [comment]
I found an edge case similar to this, this time I did:

```
    ./atmchange physics::atm_procs_list="(mac_aero_mic,rrtmgp,nudging)"
    ./case.setup
    ./atmchange nudging::nudging_filename=...
```

then I want to turn off nudging:

```
    ./atmchange physics::atm_procs_list="(mac_aero_mic,rrtmgp)"
    ./case.setup
```
but this leads to this error:

```
failed with error 'ERROR: nudging::nudging_filename did not match any items
```

**Comment by bartgol** [comment]
@elynnwu argh, your corner case is I think a separate issue. Namely, when turning off an atm proc (or, in general, when removing an XML node with children), we should later ignore all the atmchanges of that node, when we re-apply them from the ATMCHANGE_BUFFER xml var from cime.

@jgfouca I think Elynn's corner case is quite annoying to deal with. We can chat offline regarding how to tackle it.

**Comment by jgfouca** [comment]
@bartgol , might not be too bad. We could just ignore an errors during the re-apply.

**Comment by bartgol** [comment]
That may be risky, although one may argue that "if we did not error out when it was issued the first time, it's prob safe to ignore the error" (assuming this is the only corner case that can generate the re-apply error).

Another option: we could add a special flag to atmchange in order to add/remove/change atm processes.

**Comment by jgfouca** [comment]
@bartgol , not @elynnwu 's use case. I will make PR. The main issue is fixed.

**Comment by jgfouca** [comment]
I was mistaken, this is not fixed, but Elynn's case is with the latest PR.
