### ISSUE TITLE
regridded ne120 output lat and lon coordinates are zero

### ISSUE THREAD

**Issue by bogensch** [E3SM-Project/scream#2439]
I noticed recently that the lat and lon coordinates in the regridded ne120 v1 output are all set to zero everywhere.

**Comment by bartgol** [comment]
Ah, yes, looking at the code I see that saving the geo data (lat, lon, area, ..) only works with no remapping. I think I can probably fix this quickly.

**Comment by bartgol** [comment]
Uhm, running an ne30 case and remapping to ne4 does produce non-zero lat/lon variables (with plausible values). I will run on GPU, to see if there is an issue with dev/host syncing (since the ne120 remapped output was likely a run on GPU).

**Comment by AaronDonahue** [comment]
@bartgol , have we made any progress on this?  Did running w/ GPU produce the zero lat/lon's in the regridded data?

**Comment by bartgol** [comment]
Sorry, this fell off my radar. Thanks for pinging me.

**Comment by bartgol** [comment]
I tried to run on weaver an eamxx standalone test, with both GLL and PG2 grids, with ne=30 and ne30->ne4 output remap. In both cases, the output file contained valid lat/lon fields. While it may be that ne1024->ne120 has some peculiarity, I find it bizarre that I get _all nonzeros_, while in that case lat/lon are _all zeros_.

@bogensch @AaronDonahue @PeterCaldwell do any of you know whether this is still an issue? If so, can you point me to a case dir where this happened, so I can look at the configs/inputs, and maybe try to reproduce?

**Comment by bogensch** [comment]
Here is a case on Frontier where the lat/lon is zero in the *ne120* output.  Note that this run used the simulations/cess-v1 branch.

/lustre/orion/cli115/proj-shared/bogensch/e3sm_scratch/cess-v1-wql.002a.ne1024pg2_ne1024pg2.F2010-SCREAMv1.20230801/run

**Comment by bartgol** [comment]
Any chance you still have the original yaml files for the output? The ones listed in `namelist_scream.xml` are no longer existing...

**Comment by bartgol** [comment]
Note to self: from conversation with @PeterCaldwell , it appears that the issue is not only that lat/lon are zero, but also that they have "time" in their dimensions list.

**Comment by crterai** [comment]
Just noting that Noel has run a test with `machines/frontier` (git hash of `931a725b7005d45e90aa9d101c1092089eeee613`) with an ne30 simulation with ne30->ne4 mapping and the files there also show zeros for lat/lon:
```
/lustre/orion/cli115/proj-shared/noel/e3sm_scratch/maf-jul14/t.maf-jul14.F2010-SCREAMv1.ne30pg2_ne30pg2.frontier-scream-gpu.n001t8x1.vth200.newo.cice0.remap30to4.rforce/run/output.scream.Cess.3hourlyAVG_noremap.AVERAGE.nhours_x3.0001-01-02-00000.nc 
```
Could it be just a case where we just need to merge `master` into `frontiers/machine` and it will fix this issue?

**Comment by bogensch** [comment]
@bartgol the yaml files used for the simulation can be found in scream-docs repo commit 74c979259fe474427294dc4097bc4fc764a1e500

Below are the specific yaml files used in the simulation (taken from the script used):
```
    ./atmchange output_yaml_files=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.monthly_ne1024.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.50hourly_QcQiNcNi.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.50hourly_QrNrQmBm.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.6hourlyINST_ne30.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.6hourlyAVG_ne30.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.3hourlyAVG_ne120.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.3hourlyINST_ne120.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.3hourly_ne1024.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.hourly_2Dvars.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.ARM_sites_2D.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.ARM_sites_3D.yaml"
    ./atmchange output_yaml_files+=${SCREAMDOCS_ROOT}"/v1_output/scream_output.Cess.monthly_cosp_ne1024.yaml"
```

**Comment by bartgol** [comment]
Logging what I found:

- reproducible with ne30->ne4 on crusher
- horiz remapper seems to not run for geo data.

**Comment by bartgol** [comment]
Update

On crusher, setting SCREAM_MPI_ON_DEVICE=OFF seems to fix the issues. However, this macro is handled correctly, since things work fine on weaver with mpi on device. I am re-enabling it, and trying to see if there is something obviously amiss in how it is handled.

**Comment by bartgol** [comment]
Note: to disable mpi on device, you simply need to do `./xmlchange --append SCREAM_CMAKE_OPTIONS="SCREAM_MPI_ON_DEVICE OFF"`.

**Comment by ndkeen** [comment]
Do you have a favorite reproducer? I can try on pm-gpu

**Comment by bartgol** [comment]
A `ne30pg2_ne30pg2.F2010-SCREAMv1` case should do. You can also do
```
$ ./xmlchange STOP_N=1,STOP_OPTION=nsteps
$ ./atmchange output_yaml_files=$(pwd)/my-output.txt
```
where my-output.txt is 
```$ cat my-output.yaml 
%YAML 1.1
---
filename_prefix: latlon-debug
Averaging Type: Instant
horiz_remap_file: /lustre/orion/cli115/world-shared/e3sm/inputdata/atm/scream/maps/map_ne30pg2_to_ne4pg2_nco_conservative.20230608.nc
Fields:
  Physics PG2:
    Field Names: [p_mid]
output_control:
  Frequency: 1
  frequency_units: nsteps
```
You will of course have to change the path to the map file. The file is on the lcrc server, so if it's missing on pm, you will have to download it (sorry, we have not yet added the logic to download remap files if detected in the yaml output files, we have an issue open for that)

**Comment by bartgol** [comment]
Actually, I can no longer say that MPI_ON_DEVICE makes a difference. I re-enabled it, and I now get lat/lon correctly. I added a few print statements here and there, so I wonder if there was some issue with untouched memory before. As discussed with @crterai on slack, I will put this on hold in favor of another more pressing issue.

**Comment by ndkeen** [comment]
OK I ran it on pm-gpu, but I've forgotten how to ask if there are zeros for lat/lon.
`/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se73-aug31/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se73-aug31.gnugpu.n001.gh2439`

**Comment by bartgol** [comment]
I can check. But for the record, you can do `ncdump -v <varname> <filename>`. If you have nco installed, you can also do `ncks -d <dimname>,<dimstart>,<dimend> -v <varname> <filename>` to look at only certain slices. E.g., you could do `ncks -d ncol,1,10 lat <filename>` to look at only the first 10 cols. You can also use multiple `-d` flags, to slice along multiple dimensions.

**Comment by bartgol** [comment]
Looks like it's all non-zero on pm-gpu, and MPI on device was ON.

**Comment by ndkeen** [comment]
```
login14% ncdump -v latlon run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se73-aug31.gnugpu.n001.gh2439.cpl.ha.0001-01-01.nc 
ncdump: latlon: No such variable
```

Oh I think thats wrong file.  When I ran again for only 1 step, I only get one file.

```
login14% ncdump run/latlon-debug.INSTANT.nsteps_x1.0001-01-01-00000.nc > lo
login14% grep -A1 lat lo
netcdf latlon-debug.INSTANT.nsteps_x1.0001-01-01-00000 {
dimensions:
--
        float lat(ncol) ;
                lat:units = "1" ;
                lat:long_name = "lat" ;
                lat:_FillValue = 3.402824e+33f ;
        float lon(ncol) ;
--
 lat = -32.47379, -35.84118, -22.6296, -25.29939, -37.99874, -39.04331, 
    -27.05292, -27.92236, -39.04331, -37.99874, -27.92236, -27.05292, 
    
```

which seems ok?

Not sure whats up with p_mid values?
```    
login14% grep -A1 p_mid lo
        float p_mid(time, ncol, lev) ;
                p_mid:units = "m^-1 s^-2 kg" ;
                p_mid:long_name = "p_mid" ;
                p_mid:_FillValue = 3.402824e+33f ;
        float area(ncol) ;
--
 p_mid =
  _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 

```

**Comment by bartgol** [comment]
Looks like `p_mid` was not outputed at t=0. I am not sure why, since we should have valid values for p_mid at t=0 (homme takes care of that in the init sequence). I will dig a bit there.

**Comment by bartgol** [comment]
Update: it appears that creating some host copies and printing them is enough to get nonzeros. If I comment out those copies, then lat/lon are zeros. Classic example of an heisenbug.

**Comment by ndkeen** [comment]
re p_mid, that's fine, I just noted it.

Actually do we already know if we see the zero-latlon issue only on frontier?  Or have we also seen on pm-gpu?  I do not recall.

**Comment by bartgol** [comment]
I think we only have seen it on frontier and crusher. I was not able to reproduce it on CPU/GPU on internal snl machines.

**Comment by bartgol** [comment]
I think I may have found the issue. I think we're missing a fence.
