### ISSUE TITLE
Resume output file fill not working

### ISSUE THREAD

**Issue by elynnwu** [E3SM-Project/scream#2443]
Current master [49af9e3](https://github.com/E3SM-Project/scream/commit/49af9e3a76f5d8420e46470e43d84905b5251fd2) does not resume writing to existing output file properly, likely when it's closing the file.

This happens when `Max Snapshots Per File` has not been filled, so during restart, the existing output stream file is appended until the max snapshots are reached. 

For example, we have `ne30` run with the following output stream:
```
%YAML 1.1
---
filename_prefix: output.scream.remapped_output.3d
Averaging Type: Average
Max Snapshots Per File: 16
vertical_remap_file: /usr/gdata/climdat/eamxx-ml/maps/map_ne30pg2_to_ne4pg2_20230724_vert_enhanced.nc
horiz_remap_file: /usr/gdata/climdat/eamxx-ml/maps/map_ne30pg2_to_ne4pg2_20230724_vert_enhanced.nc
Fields:
  Physics PG2:
    Field Names:
    - T_mid
    ...
output_control:
  Frequency: 3
  frequency_units: nhours
  MPI Ranks in Filename: false
```
In the test run, we write restart with daily frequency. After the initial run, the output file only has 8 entries. During restart, the model grabs that existing file and appends to it. From the log file, it appends appropriately, but hangs once it reaches the end of the restart run (i.e., end of 2nd day). The output file is never closed because it still only has 8 entries instead of 16.

If we force the output stream to write to a new file by specifying:
```
Restart:
  force_new_file: true
```
This works fine and restart run completes without errors.

Unclear if this is related, but on [aarondonahue/20230801_add_set_get_attr_for_vars](https://github.com/E3SM-Project/scream/pull/2436/commits/1bf57d5be152fd114f55a9e16a3d61629556a783), we get the following error at the end of appending to the output file during restart:
```
munmap_chunk(): invalid pointer
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source
libpnetcdf.so.4    0000155553933A0C  for__signal_handl     Unknown  Unknown
libpthread-2.28.s  00001555482A9CF0  Unknown               Unknown  Unknown
libc-2.28.so       0000155547F1FAFF  gsignal               Unknown  Unknown
libc-2.28.so       0000155547EF2EA5  abort                 Unknown  Unknown
libc-2.28.so       0000155547F62097  Unknown               Unknown  Unknown
libc-2.28.so       0000155547F694EC  Unknown               Unknown  Unknown
libc-2.28.so       0000155547F6979C  Unknown               Unknown  Unknown
libmpi.so.12       0000155552C9457F  psm_do_unpack         Unknown  Unknown
libmpi.so.12       0000155552C6C816  psm_do_ncrecv_com     Unknown  Unknown
libmpi.so.12       0000155552C6C669  MPIDI_CH3_Request     Unknown  Unknown
libmpi.so.12       0000155552C405EE  MPIR_Request_comp     Unknown  Unknown
libmpi.so.12       0000155552BDC1F2  MPIR_Waitall_impl     Unknown  Unknown
libmpi.so.12       0000155552BDBA75  MPI_Waitall           Unknown  Unknown
libmpi.so.12.1.1   0000155552CE60F9  Unknown               Unknown  Unknown
libmpi.so.12       0000155552CE4D6C  ADIOI_LUSTRE_Writ     Unknown  Unknown
libmpi.so.12       0000155552CE113C  MPIOI_File_write_     Unknown  Unknown
libmpi.so.12       0000155552CE1942  MPI_File_write_at     Unknown  Unknown
libpnetcdf.so.4    0000155553330848  ncmpio_read_write     Unknown  Unknown
libpnetcdf.so.4.0  000015555332B673  Unknown               Unknown  Unknown
libpnetcdf.so.4.0  0000155553328F79  Unknown               Unknown  Unknown
libpnetcdf.so.4.0  0000155553326B17  Unknown               Unknown  Unknown
libpnetcdf.so.4    0000155553277032  ncmpi_wait_all        Unknown  Unknown
e3sm.exe           00000000017B4E97  Unknown               Unknown  Unknown
e3sm.exe           0000000001764875  Unknown               Unknown  Unknown
e3sm.exe           00000000016B6663  piolib_mod_mp_clo        1108  piolib_mod.F90
e3sm.exe           0000000001C011C5  scream_scorpio_in         881  scream_scorpio_interface.F90
e3sm.exe           0000000001C209C1  eam_pio_closefile         131  scream_scorpio_interface_iso_c2f.F90
e3sm.exe           0000000001C18BA0  Unknown               Unknown  Unknown
e3sm.exe           0000000001C35916  Unknown               Unknown  Unknown
e3sm.exe           0000000001C31DE8  Unknown               Unknown  Unknown
e3sm.exe           0000000001803413  Unknown               Unknown  Unknown
e3sm.exe           0000000000523DA1  Unknown               Unknown  Unknown
e3sm.exe           000000000051B814  atm_comp_mct_mp_a         220  atm_comp_mct.F90
e3sm.exe           0000000000446A62  component_mod_mp_         751  component_mod.F90
e3sm.exe           0000000000425B3B  cime_comp_mod_mp_        3105  cime_comp_mod.F90
e3sm.exe           00000000004466A0  MAIN__                    153  cime_driver.F90
e3sm.exe           0000000000422E22  Unknown               Unknown  Unknown
libc-2.28.so       0000155547F0BD85  __libc_start_main     Unknown  Unknown
e3sm.exe           0000000000422D2E  Unknown               Unknown  Unknown
```

**Comment by bartgol** [comment]
I ran F2010-SCREAMv1 with ne30pg2 grid with a non-remapped output on chrysalis, and it worked fine. I ran 1day+1day, with output every 3h. After the initial run, the nc file had 8 snapshots, and after the restarted run it had 16 snapshots.

Either the remap is the culprit, or this may be a machine-specific thing. I point out that the hang at file sync time may be a red herring. In particular, it is possible (and likely) that all but one rank are at the file-sync point, but one rank is stuck waiting on something (a file, a comm request, an infinite loop, ...) a while back. The real issue is of course the rank that is waiting (which could be anywhere in the code, up until the previous blocking barrier), and not the point where the file is closed.

**Comment by elynnwu** [comment]
Appears to be an issue related to writing to `lustre2`, cannot reproduce on other machines (chrysalis, pm) or writing on scratch instead. Closing for now

**Comment by PeterCaldwell** [comment]
@elynnwu - what machine *does* have this issue? Is it Quartz?

**Comment by elynnwu** [comment]
It was quartz and ruby. It appeared to be related to `lustre2`, and there was a maintenance note but for `lustre1` only. I was able to run the same thing w/o issues using scratch yesterday. Today it appears that `lustre2` is back to normal, no hang when writing restart or history files.
