### ISSUE TITLE
ARMSite output has incorrect longitudes

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2524]
@paullric pointed out to me that all the ARM sites seem to be located over Asia because their longitudes are wrong. At least in `/pscratch/sd/t/terai/EAMxx/shareWPaul/output.scream.Cess.ARMSite_2D.INSTANT.nmins_x15.2019-08-01-00000.nc`, which is for an ne256 run post-lat/lon=0 fix. 

I promised Paul I would make a plot demonstrating the problem and try to figure out whether we just needed to add or subtract 180 or 360 degrees or put a minus sign in front of what we have... but I'm not sure when I'll get to that.

**Comment by bartgol** [comment]
I took a quick look at the file, and noticed that the number of coarse grid points in each site varies a lot:
```
 1: 8301
 2: 8434
 3: 2847
 4: 9556
 5: 8300
 6: 8638
 7: 3177
 8: 8796
 9: 8289
10:   36  
11:   42
12:   46
13:   47
14:   56
15:   49
16:   46
```
Is it expected that one site has 8k points in it, while another has only 46? I don't know much about ARM sites, so this may be expected. But since it looked odd, I figured I asked.

**Comment by bartgol** [comment]
Is there a page where we can see where these sites are supposed to be located? I tried to google it, and found a [webpage](https://www.arm.gov/capabilities/observatories/sgp/locations), but it has way more sites than the nc file, so I don't think this is it...

**Comment by crterai** [comment]
I looked through the mapping files to see if there were any issues, and it looks to be a mapping file issue. These were maps that I'd made originally. 
I'll have a fix for the ARM and ACI region maps ready by tomorrow to test (at ne256 and updated ones for ne1024).

**Comment by crterai** [comment]
This fix in the creation of the mapping file fixed this issue: https://github.com/E3SM-Project/scream-docs/pull/175
