### ISSUE TITLE
non-bfb issues with Cess-like cases on frontier

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2534]
Starting with a sep6th checkout of machines/frontier, I have run many tests at ne30/ne256/ne1024 while debugging various issues as well as testing performance. I noticed that several cases were not BFB (looking at the hashes). Looking closer, I don't see any two ne256 or ne1024 cases that are BFB. They are all the same at 0th hash, but different at 18th.

With ne30, there is more consistency -- where I see many cases are the same, but at least 2 cases differ at hash 468. Additionally, even at ne30, using threads in ICE is not BFB and it should be (as we already compile with openmp since we use threading in LND). I just tried 2 ne30 cases without threads, and still see non-BFB.

On pm-gpu, using scream master of sep12, I have two ne256 cases that are identical after 5 days (only diff between the 2 cases is threading in ICE).

The cases on frontier are at `/lustre/orion/cli115/proj-shared/noel/e3sm_scratch/maf-sep6`

**Comment by ambrad** [comment]
This page describes options you can set to get more detailed hash output to try to isolate the source of non-BFBness: https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/3831923056/EAMxx+BFB+hashing.

**Comment by ndkeen** [comment]
Adding more detailed hashing, I see the difference here (ne30):

```
case A:
 0: exxhash> 2020-  1.85417 0 5f5130ce7ea4a04a (p3-pre-sc-0)
 0: exxhash> 2020-  1.85417 0 339641831d857825 (p3-pst-sc-0)
 0: exxhash> 2020-  1.85417 1 53ee771d592621ea (p3-pst-sc-0)
 0: exxhash> 2020-  1.85417 2                0 (p3-pst-sc-0)
 0: exxhash> 2020-  1.85417 0 d522edfc253737d6 (mac_aero_mic-pst-sc-0)
 0: exxhash> 2020-  1.85417 1  a48181d9160d9cd (mac_aero_mic-pst-sc-0)
 0: exxhash> 2020-  1.85417 2                0 (mac_aero_mic-pst-sc-0)
 0: exxhash> 2020-  1.85417 0 d522edfc253737d6 (mac_aero_mic-pre-sc-1)
 0: exxhash> 2020-  1.85764 0 3bc59afc94e6a6e6 (shoc-pre-sc-0)           qqq
 0: exxhash> 2020-  1.85764 0 667122e0d823b182 (shoc-pst-sc-0)
 0: exxhash> 2020-  1.85764 1 9c4eb50a9bba7c05 (shoc-pst-sc-0)
 0: exxhash> 2020-  1.85764 2                0 (shoc-pst-sc-0)
 0: exxhash> 2020-  1.85764 0 d2a9409a4a41a1bb (cld_fraction-pre-sc-0)
 0: exxhash> 2020-  1.85764 0 d2a9409a4a41a1bb (cld_fraction-pst-sc-0)
 0: exxhash> 2020-  1.85764 1 614904fbbfea4160 (cld_fraction-pst-sc-0)
 0: exxhash> 2020-  1.85764 2                0 (cld_fraction-pst-sc-0)
 0: exxhash> 2020-  1.85764 0 6ca81e14084d669b (spa-pre-sc-0)

case B:
 0: exxhash> 2020-  1.85417 0 5f5130ce7ea4a04a (p3-pre-sc-0)
 0: exxhash> 2020-  1.85417 0 339641831d857825 (p3-pst-sc-0)
 0: exxhash> 2020-  1.85417 1 53ee771d592621ea (p3-pst-sc-0)
 0: exxhash> 2020-  1.85417 2                0 (p3-pst-sc-0)
 0: exxhash> 2020-  1.85417 0 d522edfc253737d6 (mac_aero_mic-pst-sc-0)
 0: exxhash> 2020-  1.85417 1  a48181d9160d9cd (mac_aero_mic-pst-sc-0)
 0: exxhash> 2020-  1.85417 2                0 (mac_aero_mic-pst-sc-0)
 0: exxhash> 2020-  1.85417 0 d522edfc253737d6 (mac_aero_mic-pre-sc-1)
 0: exxhash> 2020-  1.85764 0 3bb7875ac16555f9 (shoc-pre-sc-0)         qqq
 0: exxhash> 2020-  1.85764 0 663feeba499d58d4 (shoc-pst-sc-0)
 0: exxhash> 2020-  1.85764 1 9c2b9485e0b57444 (shoc-pst-sc-0)
 0: exxhash> 2020-  1.85764 2                0 (shoc-pst-sc-0)
 0: exxhash> 2020-  1.85764 0 d2a9409a4a41a1bb (cld_fraction-pre-sc-0)
 0: exxhash> 2020-  1.85764 0 d2a9409a4a41a1bb (cld_fraction-pst-sc-0)
 0: exxhash> 2020-  1.85764 1 614904fbbfea4160 (cld_fraction-pst-sc-0)
 0: exxhash> 2020-  1.85764 2                0 (cld_fraction-pst-sc-0)
 0: exxhash> 2020-  1.85764 0 6ca81e14084d669b (spa-pre-sc-0)
```

**Comment by bartgol** [comment]
It is odd that the diff appears before running shoc for the 2nd subcycle, but there was no diff at the end of mac_aero_mic 1st subcycle. This points to some issue with the AD infrastructure. I will look at the code and see if anything stands out.

**Comment by ndkeen** [comment]
Running 5 days of ne30 using jul14th checkout of machine/frontier is BFB.  Which might point to the last commit to the branch (bringing in changes from master).


```
4452a2027e 2023-09-05 17:31:40 -0400 crterai            Merge remote-tracking branch 'origin/master' into machines/frontier
587f02628a 2023-07-19 13:12:23 -0400 crterai            Merge remote-tracking branch 'origin/master' into machines/frontier
931a725b70 2023-07-13 18:57:33 -0400 crterai            Merge branch 'master' into machines/frontier
68a1749025 2023-06-27 16:51:29 -0400 Andrew M. Bradley  Frontier: Copy CICE -O0 mods.
```

**Comment by crterai** [comment]
Looking at the git history, it looks like there are two merges of master between July 14th and Sept 5th. Do you have a machines/frontier checkout between Jul 19 and Sept 05?

**Comment by ndkeen** [comment]
Ah yep, got mixed up on dates -- indeed I should get a checkout after Jul19th (before Sep5) to rule out that second commit on the list above.

**Comment by bartgol** [comment]
> However, I do have cases using `simulations/cess-v1` checked out on Aug 31st. Those seem BFB. Not sure the differences between machines/frontier on that date.

That should help us narrow down the list of PRs that went into master that may have caused it. On that branch, the last commit I see is
```
323efd91e8 - (6 weeks ago) EAMxx: fix history restart writing bug 
```
which still leaves us with a lot of potential PRs...

**Comment by bartgol** [comment]
Update: I am quite positive we're missing a team barrier in `eamxx_tms_process_interface.cpp`
```c++
    // Calculate z_mid
    PF::calculate_dz(team, pseudo_density_i, p_mid_i, T_mid_i, qv_i, dz_i);
    const Real z_surf = 0.0; // For now, set z_int(i,nlevs) = z_surf = 0
    PF::calculate_z_int(team, nlevs, dz_i, z_surf, z_int_i);
    team.team_barrier();
```
between the calculation of `dz` and `z_int`. Speculation supported by @ndkeen experiments, which show BFB when TMS is not on, and non-BFB when it's on. The fix is to add a team barrier. Testing it now.

**Comment by ndkeen** [comment]
It does look like we are not BFB with TMS. I have tested ne30 on both frontier and pm-gpu, running 10 days total (with restart at 5) and we are BFB without TMS.

**Comment by ambrad** [comment]
Nice detective work!

**Comment by ambrad** [comment]
@tcclevenger do we have a CIME v1 test with TMS on? If not, I suggest adding it to an existing ERS, ERP, or PEM one so we get BFB checking on it.

**Comment by crterai** [comment]
Wow, impressively quick narrowing down of the source of the non-BFB and finding fix, @bartgol!

**Comment by bartgol** [comment]
Thanks. But @ndkeen narrowed it down to TMS. That package is relatively small, so it was ready to track down the issue once I knew where to look.

**Comment by tcclevenger** [comment]
@bartgol Approved the PR. I remember hunting down that needed team barrier in shoc interface.. Maybe I'll learn for the next interface that uses it..
