### ISSUE TITLE
Add baseline testing for standalone EAMxx

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2541]
Our struggle tracking down the problem in #2534 suggests we need to improve our ad-driven tests. In particular, we do not check for consistency across runs. For CPU builds, we have _some_ coverage, since we do check that np1 produces the same output as npN. However, our weaver testing runs with `SCREAM_TEST_MAX_RANKS=1`, so we don't have any guarantee that our runs are bfb.

The easiest thing is to store our nc files in the `data` subfolder of our standalone builds (perhaps create subfolders in there), the run `cprnc` against the baselines in our standalone tests.

**Comment by ndkeen** [comment]
what about running more on pm-gpu?

**Comment by bartgol** [comment]
The standalone testing system is a bit rigid, due to how it was developed (we added feature over feature, a bit at a time, in the early scream days). In particular, it does not allow to use more than 1 node, since it uses a combination of ctest feature and OS's taskset to ensure different tests don't use the same cores/GPUs (for speed).
On GPU system, we have 3 concurrent builds (debug, release, single precision), and doing them in || makes PR testing faster (since most of the time is spent building a handful of files). That means that we have each build using 1 GPU (well, one lucky build will have 2), which forces us to run 1 rank at most.

We may try to work on making test-all-scream work on multiple nodes, but it may require some effort. I think pursuiing baseline testing may be easier to achieve in terms of changes needed in our testing scripts.

**Comment by bartgol** [comment]
This was completed in #2750
