### ISSUE TITLE
Multiple definitions of cxx_log

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2604]
I'm not sure why this is not picked up in master, but I'm getting this error on a branch were I was doing some cmake changes.

The function cxx_log is declared in `physics_share.cpp` with C linkage (so no namespace qualification), to make it Fortran interoperable. However, in Homme, we also declare a cxx_log function with C linkage, in `BfbUtils.cpp`. I am not sure how these two are not already colliding in master. It looks to me as if they should.

I'm going to investigate this a bit more.

**Comment by bartgol** [comment]
This is something of a mistery to me. Here's what I found.

In a branch, I'm working on cleaning up some cmake logic to create unit tests. Among other things, I added a macro that creates AD-driven unit tests using a template cpp file, which I use for most of the tests in `tests/coupled` and `tests/uncoupled`. This reduces code duplication, and should make creating system tests less prone to copy+paste errors and copy+paste pointless leftovers. Here's how I invoke it

```
CreateADUnitTest(homme_shoc_cld_p3_rrtmgp
  LIBS cld_fraction ${dynLibName} shoc p3 scream_rrtmgp
  LABELS dynamics shoc cld p3 rrtmgp physics
)
```
The macro simply hardcodes the src file and a few needed libs (like control, io, diagnostics), and then calls the standard CreateUnitTest maro we use everywhere. As is, the above call triggers the error regarding the multiple definitions of `cxx_log`. BUT, if I move `${dynLibName}` to the end of the list, the link error goes away. This is _very_ strange, since all linked libs are cmake targets, with _no_ circular dependency.

It gets trickier: I tried the same thing in master: i took this test, and move the dyn lib at the end of the link line. No error.

I'm trying to bisect on the changes, to see what _really_ triggers the error. The thing is though: I think the error is _legit_. I don't understand why master does not exhibit the same behavior though...

**Comment by bartgol** [comment]
Ok, I was able to trigger the erro in master as well. But the way it triggers it raises more questions.

In the `homme_shoc_cld_p3_rrtmgp` test, we have this list of libs
```
set (NEED_LIBS cld_fraction shoc p3 scream_rrtmgp ${dynLibName} scream_control scream_share physics_share diagnostics)
```
Moving dyn lib to the front, is not enough to trigger the error, but if in addition, I remove `physics_share`, I do get the link error:
```
/home/lbertag/workdir/bin/gdb/ld: ../../../../src/physics/share/libphysics_share.a(physics_share.cpp.o): in function `cxx_log':
/home/lbertag/workdir/scream/scream-src/branch/components/eamxx/src/physics/share/physics_share.cpp:98: multiple definition of `cxx_log'; ../../../../src/dynamics/homme/tests/libtheta-l_kokkos_4_72_10.a(BfbUtils.cpp.o):/home/lbertag/workdir/scream/scream-src/branch/externals/ekat/extern/kokkos/core/src/impl/Kokkos_ViewMapping.hpp:3122: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeFiles/homme_shoc_cld_p3_rrtmgp.dir/build.make:131: tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/homme_shoc_cld_p3_rrtmgp] Error 1
make[1]: *** [CMakeFiles/Makefile2:7164: tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeFiles/homme_shoc_cld_p3_rrtmgp.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
Notice that the place listed as "first defined here" is completely off (there's no mention of `cxx_log` in `Kokkos_ViewMapping.hpp`, as one would expect).

What puzzles me is that removing `physics_share` from the list of libs should have no impact, since it's already brought in by p3/shoc/rrtmgp, which all link against it. I'm also puzzled by the fact that, rm-ing `physics_share` in the original list of libs does _not_ trigger the error; one needs the dyn lib to appear "early on" in the list of libs to link, more precisely before the physics libs (which are the ones bringing in physics_share). But then, if linking the dyn lib after the phys libs causes double definition (rightfully so), why doesn't linking it after also cause double definition?

@jgfouca @tcclevenger @jeff-cohere @ambrad pinging you in hope that your C++/CMake expertise could help shed some light on this nonsense...

**Comment by ambrad** [comment]
Just guessing, but maybe the linker is being selective about only recording definitions it needs, and something about that process makes certain sequences of libs hide the issue. But I agree the underlying issue is valid.

**Comment by bartgol** [comment]
I suppose we could move these bfb wraps to a common place (ekat?), so that it is built just once. It should not be hard for homme standalone to simply grab the hpp/cpp pair from ekat (without having to pull in the whole ekat). I may try that real quick, and if it fixes the issue, issue a PR in e3sm.

**Comment by ambrad** [comment]
Could also just rename one of them.

**Comment by bartgol** [comment]
Yeah, that's easier. I'm tempted to rename the Homme one, but that requires a lengthier process upstream, so I'll just rename the scream ones.
