### ISSUE TITLE
incoherent units of ccn in spa

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2608]
(This was motivated by Hassan's suggestion to check the units of CCN3)

Different SPA files have the units for CCN3 as:
- #/cm3 (this is how CCN3 is defined in E3SM)
- kg/kg (this makes little sense to me; I assume it's a typo in the files)
- no units given

In the SPA code:
- [this inline comment](https://github.com/E3SM-Project/scream/blob/7cb3c208c7a9367b55ee656de794533ed2e9dbfe/components/eamxx/src/physics/spa/spa_functions.hpp#L110-L114) gives the units as #/cm3 (wrong units for the optics, they should be nondim) --- `view_2d<Spack> CCN3;        // CCN concentration at S=0.1: units = #/cm3, dimensions = (ncols,nlevs)`
- [this computed field](https://github.com/E3SM-Project/scream/blob/7cb3c208c7a9367b55ee656de794533ed2e9dbfe/components/eamxx/src/physics/spa/eamxx_spa_process_interface.cpp#L57) gives units of 1/kg (correct units for the optics) --- `add_field<Computed>("nccn",   scalar3d_layout_mid,    1/kg,   grid_name,ps);`

I think eventually CCN3 becomes nccn and then nccn_prescribed in P3. Here's how that turns out:

```cpp
    if ( not_drymass.any() ) {
      hydrometeorsPresent = true; // updated further down
      // Apply droplet activation here (before other microphysical processes) for consistency with qc increase by saturation
      // adjustment already applied in macrophysics. If prescribed drop number is used, this is also a good place to
      // prescribe that value
 
      if (do_prescribed_CCN) {
         nc(k).set(not_drymass, max(nc(k), nccn_prescribed(k)/inv_cld_frac_l(k)));
      } else if (predictNc) {
         nc(k).set(not_drymass, max(nc(k) + nc_nuceat_tend(k) * dt, 0.0));
      } else {
         // nccnst is in units of #/m3 so needs to be converted.
         nc(k).set(not_drymass, nccnst*inv_rho(k));
      }
 
    }
```

```f90
       if (qc(k).lt.qsmall) then
      !--- apply mass clipping if mass is sufficiently small
      !    (implying all mass is expected to evaporate/sublimate in one time step)
          qv(k) = qv(k) + qc(k)
          th_atm(k) = th_atm(k) - exner(k)*qc(k)*latent_heat_vapor(k)*inv_cp
          qc(k) = 0._rtype
          nc(k) = 0._rtype
       else
          is_hydromet_present = .true.    ! updated further down
      !--- Apply droplet activation here (before other microphysical processes) for consistency with qc increase by saturation
      !    adjustment already applied in macrophysics. If prescribed drop number is used, this is also a good place to
      !    prescribe that value
 
          if (do_prescribed_CCN) then
             nc(k) = max(nc(k),nccn_prescribed(k))
          else if (do_predict_nc) then
             nc(k) = max(nc(k) + nc_nuceat_tend(k) * dt,0.0_rtype)
          else
             nc(k) = nccnst*inv_rho(k)
          endif
       endif
```

There must've been a change of in-cloud/in-grid between the implementations? We likely should synchronize if so. If not, there might be a bug. I didn't check because I don't necessary care about the Fortran version here.

In either case, in the max ( nc, nccn_prescribed ) logic, both units must be the same. In the C++ fm, nc has units of 1/kg. Ironically, in the Fortran pbuf, it has units of 1/m3 (the one with 1/kg is NUMLIQ). Nonetheless, CCN3 is defined as #/cm3 in E3SM. 

Fixes:
1. Retain #/cm3 as units of CCN3 to be consistent and then convert to 1/kg before applying the max limiter
2. Rename the SPA CCN3 to something else (I am proposing to add CCN3M as the 1/kg equivalent of CCN3)

**Comment by PeterCaldwell** [comment]
> in the max ( nc, nccn_prescribed ) logic, both units must be the same

Agreed. I'd suggest converting units of CCN in the `max( nc, nccn_prescribed )` in order to preserve our existing CCN netcdf files while also providing clear provenance that the netcdf input had wrong units and we are fixing this. Does that make sense?

**Comment by PeterCaldwell** [comment]
Sounds good. And I agree with you that kg/kg is clearly a bug.

**Comment by AaronDonahue** [comment]
Yes, I think @hassanbeydoun will have the most insight on this.

**Comment by hassanbeydoun** [comment]
We decided CCN should be a mixing ratio in the SPA files. As for the preemptive multiplying by cloud fraction, that's done because nc is cell average while CCN is in cloud. @mahf708 I think you are quoting the EAM and not SCREAM p3 F90 version up there. The comment in micro_p3_interface about preemptive multiplying is deprecated and should be removed. In both the C++ and F90 versions, nccn_prescribed by multiplied by cloud fraction to take into account the fact that the CCN value is in cloud.
