### ISSUE TITLE
Error! Month out of bounds. round2

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2662]
Similar to https://github.com/E3SM-Project/scream/issues/2396 which was fixed, so not sure what changed.

Using scream master on pm-gpu.
These are same tests I've run previously, but after some recent change, I see:

```
 4:  FAIL:
 4: mm>=1 && mm<=12
 4: /global/cfs/cdirs/e3sm/ndk/repos/se86-jan5/components/eamxx/src/share/util/scream_time_stamp.cpp:20
 4: Error! Month out of bounds. Did you call `days_in_month` with yy and mm swapped?
```

Case:
`/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se86-jan5/cess-v2-cntl.ne30pg2_ne30pg2.F2010-SCREAMv1.se86-jan5.n0004t4xX.allyaml`

**Comment by bartgol** [comment]
I can reproduce on mappy. I will run through a debugger and find out the issue.

**Comment by bartgol** [comment]
I found the issue. Working on a fix.
