### ISSUE TITLE
nudging grid setting issues after PRs of regional & coarse data nudging

### ISSUE THREAD

**Issue by jsbamboo** [E3SM-Project/scream#2666]
nudging tests using both regional nudging (#2580) & coarse data nudging (PR #2613) throw out errors (simulation setup attached below):
1. The grid settings for nudging weights do not match. This is because the grid of the nudging weights was previously `grid_ext`, and the coarse data nudging PR #2613 requires setting the grid of the nudging weights to be `grid_int`

>  Error! Input field to 'add_field' is defined on a grid different from the one stored.
>  field manager grid: coarse_grid
>  input field grid: Physics PG2

Have tested that this error can be solved by this modification: `AtmosphereInput src_weights_input(m_weights_file, grid_int, fields);` , here grid_ext -> grid_int.

2. There may be a mismatch between `p_mid_v` (model horz grid) and `tmp_state_view` (external horz grid), which causes an error in `perform_vertical_interpolation`. 

>  FAIL.
>  x_tgt.extent_int(0) == output.extent_int(0)

Haven't confirmed the cause yet. Both np4 and pg2 grid have been tested as the coarse nudging inputs.

#

Some settings in my runscript:
```
export RES=CAx32v1pg2_CAx32v1pg2
./xmlchange RUN_STARTDATE="2015-01-01"
./xmlchange SCREAM_CMAKE_OPTIONS="SCREAM_NP 4 SCREAM_NUM_VERTICAL_LEV 128 SCREAM_NUM_TRACERS 10"

./atmchange mac_aero_mic::atm_procs_list+=nudging
./atmchange mac_aero_mic::nudging::nudging_filename=\
${nudging_inputs_root}/h4.TQUV.2015-01-01.128levs.ncpdq_FillValue.p_mid.nc,\
${nudging_inputs_root}/h4.TQUV.2015-01-02.128levs.ncpdq_FillValue.p_mid.nc
#${nudging_inputs_root}/h4.TQUV.2015-01-01-2015-01-02.levs.highorder_se2fv_ne30pg2.ncpdq_FillValue.p_mid.nc
./atmchange mac_aero_mic::nudging::nudging_fields=T_mid,qv,U,V
#./atmchange mac_aero_mic::nudging::source_pressure_type="TIME_DEPENDENT_3D_HYBRID"
./atmchange mac_aero_mic::nudging::source_pressure_type="TIME_DEPENDENT_3D_PROFILE"
./atmchange mac_aero_mic::nudging::nudging_refine_remap_mapfile=/p/lustre2/zhang73/grids2/CAne32x32v1/map_ne30np4_to_CAx32v1pg2_nco.se2fv_stt.highorder.20240109.nc
#./atmchange mac_aero_mic::nudging::nudging_refine_remap_mapfile=/p/lustre2/zhang73/grids2/CAne32x32v1/map_ne30pg2_to_CAx32v1pg2_nco.fv2fv_flx.mono.20240109.nc
./atmchange mac_aero_mic::nudging::nudging_timescale=10800
./atmchange mac_aero_mic::nudging::use_nudging_weights=True
./atmchange mac_aero_mic::nudging::nudging_weights_file="/p/lustre2/zhang73/take_AND_give/Xingqiu/nudging_weights_eamxx_CAne32x32v1pg2L128.v11252022.nc"

./atmchange output_yaml_files=\
${eamxx_out_files_root}/screamv1_output.nudging_update.1mA.yaml,\
${eamxx_out_files_root}/screamv1_output.nudging_update.1dA.yaml
./atmchange Filename=/p/lustre2/zhang73/DATA/IC/screami_CAx32v1np4L128_hiccup-era5-20150101_011024.ncpdq.nc

```

**Comment by jsbamboo** [comment]
I'd ping @AaronDonahue and / or @xyuan first since Naser is out for the week

**Comment by rljacob** [comment]
@jsbamboo who are you?

**Comment by jsbamboo** [comment]
@rljacob I'm Jishi, the postdoc working with Peter Bogenschutz on RRM long-term simulations. so we are testing v1 nudging for our application now

**Comment by jsbamboo** [comment]
@mahf708 Thanks Naser. Due to a very tight testing schedule and unfamiliarity with the PR process, I'll probably just start by making small changes locally

**Comment by jsbamboo** [comment]
yes, the weights are on the same grid as the model PG2 grid, so it seems it works when just change:
 `AtmosphereInput src_weights_input(m_weights_file, grid_ext, fields);` 
to
 `AtmosphereInput src_weights_input(m_weights_file, grid_int, fields);`  
in components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
--that line previously used grid_ext because grid_ext have to be the same as the model grid before introducing the coarse data capability 

> 
> netcdf nudging_weights_eamxx_CAne32x32v1pg2L128.v11252022 {
> dimensions:
>         time = 1 ;
>         ncol = 67872 ;
>         lev = 128 ;

unfortunately i dont have an account on chrysalis.. i have accounts on LC / perlmutter, can i send those files to perlmutter?

**Comment by jsbamboo** [comment]
i just put all the files needed and my runscript on perlumutter: /global/cfs/cdirs/e3sm/www/zhang73/forNaser/
let me know if you cannot access them 

the grid setup i am using is not on master, and `bogensch/CA_32xRRM` branch is needed. the first problem may be able to reproduce using any_coarse_data_grid -> ne30pg2? if so, i also put a nudging_weight file for ne30pg2 on perlmutter

**Comment by jsbamboo** [comment]
yes Aaron made the simialr comment about rewriting the interface (let "nudging users describe their case and see if there is a unified way to proceed"

**Comment by PeterCaldwell** [comment]
@jsbamboo (and others) - perhaps I didn't read the discussion carefully enough, but I don't understand whether the problem is that 

1. nudging never works in RRM mode
2. nudging never works when the nudged data is coarsened
3. nudging never works when regional nudging weights are used
4. RRM nudging never works with coarsened nudged data
5. RRM nudging never works when regional nudging weights are used
6. RRM nudging doesn't work ONLY when nudging data is coarsened AND regional nudging weights are used

Can you clarify?

**Comment by PeterCaldwell** [comment]
> there is a limitation that the weights must be provided at the model's resolution

My vision was that anyone who wanted to do regional nudging - particularly on an RRM grid - should have a good understanding (or at least a copy!) of that grid and could quickly mark up the areas they do and don't want to nudge (e.g. by writing a python script that made nudging weight 1 where cell area> some threshold and weight=0 where cell area is small enough). If they were doing that on the coarse+uniform grid of the nudging data, it would be more confusing and more error-prone because they probably want to nudge where the RRM grid is coarse, but specifying nudging on a coarse uniform grid would sever the connection between the RRM grid and the nudging weights. I had assumed that the regional weighting would be applied via elementwise multiplication with the nudging tendency once that tendency was calculated, while the coarsening regridding would need to be implemented before the nudging tendency could be calculated.

What went wrong with this? I must have not paid enough attention to implementation.

**Comment by jsbamboo** [comment]
@PeterCaldwell  for your 6 points above, at least in my short tests:
1. no. RRM grids and uniform grids by themselves make no difference to nudging
2. should be no. When I added an extra condition to bypass the vertical interpolation (which applies to the case I tested), it worked
3. no. Xingqiu provides a python script for generating nudging weights with the same algorithm as v0 nudging (tanh function), just changed to calculate weights offline. Before coarse data nudging was introduced, the nudging data had to be exactly the same as the model physical grid, so v1's weighted nudging worked just like v0
4. should be no, same as 2
5. no, same as 3
6. yes and no. It works after the revision introduced in the first point of this issue, and before that it was yes. Because of 3, nudging weights were previously grid_ext (same as m_grid before, but different from m_grid now). nudging weights should have been changed to grid_int (same as m_grid now) when coarse data capability introduced.


it seems that my description of the issues at the beginning was very unclear. 

- the first error I encountered here corresponds to 6 above, which has already been resolved, and just requires Naser or someone else to push the changes to master
- the second error I encountered has nothing to do with a conflict between regional & coarse data nudging, but rather a problem in coarse data nudging with vertical interpolation (point 2 mentioned by Naser in his reply to you). btw, for my tests, I don't actually need to do vertical interpolation, so I can change the code locally to bypass this error (but not for cases where vertical interpolation is required)

**Comment by jsbamboo** [comment]
i think it might be better to just let the weight grid be strictly equal to m_grid, since the weights are directly applied in calculating the nudging trend (which is on m_grid). Also, there is a case where the coarse data grid is very coarse and the nudging horizontal window is very small, so the window for the weights generated directly from the coarse data grid can be very inaccurate, which is what i encountered when i generated the weights file for ne2 and ne4 tests

**Comment by jsbamboo** [comment]
@mahf708 yes the RRM test could be troublesome to touch (i missed that all the grid config files are on LC

thanks for informing me about Luca's PR! yes i'm quite sure it can work when i remapped the nudging data offline + nudging weights applied (actually i tested it first, then adding the coarse data test)

**Comment by jsbamboo** [comment]
cool please feel free to close this issue
