### ISSUE TITLE
scorpio interface doesn't seem to handle reading scalar0d fields...

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2671]
Consider this check:

https://github.com/E3SM-Project/scream/blob/cc36493037d40d577bfe0bec8fc075dd6c109f3b/components/eamxx/src/share/io/scream_scorpio_interface.cpp#L342

What do we expect the second conditional to be in the case of a scalar0d layout? Hint: SEGFAULT (!)

**Comment by bartgol** [comment]
I am a bit puzzled about why one would save a 0d quantity that doesn't depend on time as a PIO variable rather than a PIO global attribute. In my mind, a var must have some sort of dimension.
