### ISSUE TITLE
Create gh action that ensures all possible input data is on the E3SM server

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2680]
The action should scavenge the `namelist_defaults_scream.xml` file, and ensure that all entries with the `type="file"` meta attribute are uploaded on blues.

A few options for when to run this:
1. before each PR is merged, blocking merging if it fails
2. after each PR merge, automatically opening an issue if it fails
3. nightly or weekly. Open an issue if it fails.

Option 1 is preferable over 2, I think. We could also only run it if the PR touches the defaults xml file. I would still also do 3, regardless of 1-vs-2, since we want to avoid someone accidentally deleting a file on the server.

**Comment by bartgol** [comment]
If you create the PR with that action, I can easily modify it to accommodate arrays of files (like the one you showed).

**Comment by rljacob** [comment]
Just focus on SCREAM for now.

In #2682 you said there was disk space error.  But aren't you just comparing lists of filenames?  You shouldn't be downloading any actual files for this right?

**Comment by bartgol** [comment]
We definitely don't want to download! The ne1024 files are quite large...
