### ISSUE TITLE
Vertical grid (lev) variable missing in vertically regridded output

### ISSUE THREAD

**Issue by crterai** [E3SM-Project/scream#2686]
Currently, our vertically regridded output don't have the lev output, which makes it difficult to figure out where in the vertical each level corresponds to (need to hunt down the persons running the simulation to learn what vertical grid file was used to interpolate the 3D data. 
An example output file is:
```
/global/cfs/cdirs/e3smdata/simulations/Cess/cess-control.ne1024pg2_ne1024pg2.F2010-SCREAMv1.cess-oct2/run/output.scream.Cess.6hourlyAVG_ne30.AVERAGE.nhours_x6.2019-08-01-00000.nc
```
It would be useful to include in the output files what the target levs are (like we do for `lat` or `lon` for spatial regridding).

**Comment by bartgol** [comment]
I'm not sure I understand what the `lev` var should contain. The vert grid depends on `ps` as well as the `hyai/hyam` and `hybi/hybm` coefficients. The hybrid coeffs should be in the output file, while ps may have to be requested.

**Comment by crterai** [comment]
For the vertically regridded output file that I pointed to above, the vertical grid file (`/global/cfs/cdirs/e3sm/inputdata/atm/scream/maps/vrt_remapping_p_levs_20230926.nc`) includes 221 pressure levels on which we'd requested output. I'm wondering whether it's possible to include `lev` or some other variable named something like `target_lev` with the same length as the vertical dimension of the regridded output that includes the values of those pressure level values that we regridded the output onto. Let me know if it's still unclear.

**Comment by whannah1** [comment]
I think "plev" would be a good coordinate name when remapping to pressure levels.

**Comment by bartgol** [comment]
Ah, now I understand. Yes, we should definitely add that var. @AaronDonahue I think it should be as easy as adding geo data to the tgt grid of the vert remapper (so that it gets written to output later on with the rest of the geo data), but I would have to double check. If I'm right, this is a 5min issue.
