### ISSUE TITLE
Use of deleted RationalConstant default constructor in Units constructor

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/scream#269]
Hit this compile error on a newly-updated Linux box with an extra persnickety C++ compiler:

```
/home/jeff/projects/sandia/scream/components/scream/src/share/util/units.hpp:55:31: error: use of deleted function ‘scream::util::RationalConstant::RationalConstant()’
   55 |    , m_exp_format (Format::Rat)
      |                               ^
In file included from /home/jeff/projects/sandia/scream/components/scream/src/share/util/units.hpp:4,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/field/field_identifier.hpp:6,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/field/field_header.hpp:4,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/field/field.hpp:4,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/util/scream_test_utils.hpp:6,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/util/scream_catch_main.cpp:7:
/home/jeff/projects/sandia/scream/components/scream/src/share/util/rational_constant.hpp:48:3: note: declared here
   48 |   RationalConstant () = delete;
```

Looks like we need to be more specific about how to initialize the `m_exp_format` field in the Unit class for that constructor. Anyone have any thoughts? I'm not familiar enough with how this stuff is used to have an opinion yet.

**Comment by jeff-cohere** [comment]
Actually the compile error is a little misleading. I think initializing the `m_units` array with a bunch of zeroes on line 54 might be failing because we're relying on the compiler to promote the zeroes to `RationalConstants`, and somehow it's not doing it (even though there is an `IntType` constructor. I'll see if I can figure this out a little better.

**Comment by jeff-cohere** [comment]
Okay, seems like we need a "converting" constructor with a single argument that takes an `IntType`. The existing one has two parameters, with a default for the second. This is real hair-splitting stuff, but I think I can fix it.

**Comment by bartgol** [comment]
Hey Jeff, this is code I wrote, so I'm the one to blame for possible bugs.

I vaguely remember some errors in the past, related to the fact that I couldn't "nest" implicit conversions in the ctor of Units. I'm not sure what compiler it was, but it might be related to what you are seeing. I'll comment more on the PR.
