### ISSUE TITLE
Nudging data time error when reference time is in the distant past

### ISSUE THREAD

**Issue by whannah1** [E3SM-Project/scream#2693]
While trying to develop a generalized HICCUP workflow for generating SCREAM nudging data I kept hitting this error baout time values occurring more than once:
```
 772:  FAIL:
 772: map_of_times_to_vector_idx.count(time)==0
 772: /autofs/nccs-svm1_home1/hannah6/SCREAM/SCREAM_SRC0/components/eamxx/src/share/util/eamxx_time_interpolation.cpp:288
 772: Error! TimeInterpolation::set_file_data_triplets - The same time step has been encountered more than once in the data files, please check
 772:     TimeStamp cur: 1850-01--24854--11648
 772:     TimeStamp ref: 1850-01-01-00000
 772:      Filename: /lustre/orion/cli115/proj-shared/hannah6/scream_scratch/nudge_data/HICCUP.nudging_uv_era5.2020-01-20.ne128pg2.L128.nc
```

The simulation start data was in the year 2020, but I used the reference time of 1850 with the justification that no one would ever want to do a nudged run before this year. However, it seems that this choice caused an integer overflow when the time coordinate gets converted into seconds.  In particular, within the `set_file_data_triplets` method in `components/eamxx/src/share/util/eamxx_time_interpolation.cpp` we have this line:
```
auto time = ts_snap.seconds_from(ts_ref);
```
I think this is where the integer overflow happens, but based on the use of 64-bit integer types it seems this should not happen... so I'm confused about how this is actually happening.

However, assuming that this was an actual overflow issue I just changed the reference time (both the `case_t0` global attirbute and the time coordinate unit as "hours from...") to use a more recent year, 2000 in this case, and the error went away.

**Comment by bartgol** [comment]
@whannah1 it is possible that the `seconds_from` routine is buggi, and messes up when `case_t0` is in a different year/century. I will hack the unit tests locally to run a battery of tests.

**Comment by bartgol** [comment]
Nope. That routine seems to work fine. I printed `seconds_from` for about 200 years gap, and it seems to give the right answer:
```
At beg of 2046, it's been 6185203200 seconds from beg of 1850
At beg of 2047, it's been 6216739200 seconds from beg of 1850
At beg of 2048, it's been 6248275200 seconds from beg of 1850
At beg of 2049, it's been 6279897600 seconds from beg of 1850
```

**Comment by bartgol** [comment]
It may help to print more stuff. Since the timestamp comes from here
```
      auto time_snap = scorpio::read_time_at_index_c2f(filename.c_str(),tt+1);
      TimeStamp ts_snap = ts_file_start;
      if (time_snap>0) {
        ts_snap += (time_snap*time_mult);
      }
```
it may help to print also `time_snap`, `ts_file_start`, and `time_mult`.  Assuming they are all good, the problem may be in `TimeStamp::operator+=`. I think these lines are dangerously suspicious:
```
TimeStamp& TimeStamp::operator+=(const double seconds) {
...
  auto& sec  = m_time[2];
...
  sec += seconds;
```
If `seconds` is larger than ~2billion, then `sec` will overflow. I think this may be the issue. I'll double check.

**Comment by bartgol** [comment]
Yup, that's the problem:
```c++
    TS base ({1850,1,1},{0,0,0});
    for (int i=1; i<=200; ++i) {
      TS curr ({1850+i,1,1},{0,0,0});
      auto diff = curr.seconds_from(base);
      TS time = base;
      time += diff;
      std::cout << "at beg of " << 1850+i << ", diff=" << diff << ", time=" << time.to_string() << "\n";
    }   
```
leads to
```
at beg of 1915, diff=2051136000, time=1915-01-01-00000
at beg of 1916, diff=2082672000, time=1916-01-01-00000
at beg of 1917, diff=2114294400, time=1917-01-01-00000
at beg of 1918, diff=2145830400, time=1918-01-01-00000
at beg of 1919, diff=2177366400, time=1850-01--24854--11648
at beg of 1920, diff=2208902400, time=1850-01--24854--11648
at beg of 1921, diff=2240524800, time=1850-01--24854--11648
at beg of 1922, diff=2272060800, time=1850-01--24854--11648
at beg of 1923, diff=2303596800, time=1850-01--24854--11648
```
I will cook up a fix to make this a bit more stable.
