### ISSUE TITLE
Create testmods for different output types, get rid of "default" output files.

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2724]
The default output files are, imo, confusing. There is no "default" output; each production campaign has its own needs. Besides, having a "default" output gives a false sense of security that "all the basic stuff is already there". On top of that, our nightly tests are not stress testing all the possibilities in output. Not even close. Which is why every time we have a new campaing, while running preliminary tests, we always find some bugs.

So I propose the following battle plan.

- Get rid of default output files. Instead, we can have templates, in the docs, where we show how to request a certain type of output.
- Add a few testmods, requesting different types of output. Each testmod folder will contain a yaml file, with a different configuration. E.g., horiz remap, vert remap, fill value, dyn->gll remap, avg type, frequency, diagnostics, etc. It may add up to a lot of files and testmods. Which brings me to...
- Create a script that generates a yaml file based on options. Or maybe just modifies an existing one. Something that can be invoked like this: 
	- generate empty yaml: `edit_output_stream -g -f output.yaml`, which will contain dummy prefix, freq units `never`, invalid avg type, empty list of fields, ...
	- add remap:`edit_output_stream -f output.yaml --horiz-remap=/path/to/map.nc'
	- change avg, freq: `edit_output_stream -f output.yaml --set-avg=Average --freq=2 --freq-units=nmonths`
	- add output fields on "Dynamics" grid, but remapped to "Physics GLL" grid `edit_output_stream --grid='Dynamics' --io_grid='Physics GLL' --fields+='vtheta_dp_dyn,dp3d_dyn'` 
	- ...
- Make the testmods be "modular": one sets ne30->ne4 remap, one adds basic fields, one adds a new stream (atmquery for the number of stream N, and create a new one, called output${N+1}.yaml in the case dir), one adds diag fields, one adds rad fields, a few to set avg types, a few to set common freq/freq_units, etc.
- Change our nightly tests (and maybe some AT ne4 tests) to use some of these testmods. Recall that CIME allows to use 2+ testmods, via `[TESTSPECS].testmod1--testmod2--...--testmodN`
- Possibly, create some "shorthand" testmods, which "pipe" a bunch of these generic testmods, so that our test names can be short. E.g., something like `[TESTSPECS].scream-output-preset1`, `[TESTSPECS].scream-output-preset2`.

**Comment by AaronDonahue** [comment]
I'm fairly certain this issue was addressed in your testmods PR @bartgol, is that a fair assumption?  Can we close this issue?

**Comment by bartgol** [comment]
Yes, thank you. I forgot to link this issue to the PR. Closing.
