### ISSUE TITLE
Reduce number of macros and make them all uppercase

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#28]
Macros are almost universally upper case, to help reader understand they are dealing with a macro (not a function or a variable). We should use this convention as well.

Furthermore, we should not use macros to shorten 2 lines of code into 1. If possible, use lambdas or templates for that. When possible, resort to (C++) language features, not CPP (in the sens of 'C-Pre-Processor') ones.

**Comment by bartgol** [comment]
Note: I am referring mostly to macros defined in the library headers (not in the tests).

**Comment by ambrad** [comment]
I'm pretty sure this issue concerned packs and I persuaded others to leave the packs header as is.
