### ISSUE TITLE
SHOC and HOMME use different definitions of vtheta

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2813]
(This was inspired by a conversation I had with @oksanaguba about the physics--dynamics interface of HOMME and the assumptions made. In particular, I was interested in retrieving theta_l (liquid theta) for some diagnostics I am working on, and @oksanaguba warned me that SHOC may have it somewhere, but it may not be what I wanted. The definition of theta_v in the SHOC code is just below the definition of theta_l. The definition for theta_l was the same as the one I had in mind, but I noticed that SHOC uses a different definition for theta_v than the one used in HOMME.)

In SHOC (and also Wikipedia), 
$$\theta_{\text{v}} = \theta (1 + \beta q_{\text{v}} - q_{\text{c}}) $$

In HOMME,
$$\theta_{\text{v}} = \theta (1 + \gamma q_{\text{v}}) $$

However, both SHOC and HOMME *almost* converge on $\beta$ and $\gamma$. I calculated them to be:

$$ \beta = 0.6077948168566272 $$

<details><summary>SHOC</summary>
<p>

```ipython
>>> (((6.02214e26*1.38065e-23)/18.016)/287.042)-1 # SHOC
0.6077948168566272
```

</p>
</details> 

$$ \gamma = 0.6077930728241567 $$

<details><summary>HOMME</summary>
<p>

```ipython
>>> 1/(18.016/28.966)-1 # HOMME
0.6077930728241567
```

</p>
</details> 

So, HOMME ignores $q_{\text{c}}$ and SHOC (dis)counts it.

**Comment by oksanaguba** [comment]
I always thought clubb and shoc use theta l (liquid), not virtual PT. Besides that There are other inconsistencies in thermodynamics of eam and homme. We can document them in more detail.

**Comment by mt5555** [comment]
It looks to me like the Wikipedia/SHOC formula is assuming mixing ratios relative to total mass (dry + vapor + condensates).    So the Wikipedia formula is removing the q_c contribution when computing the dry + vapor mass used in the theta/theta_v relation.  

SCREAM and EAM mixing ratios are written with respect to a total mass that is only dry + vapor.   This suggests the HOMME formula is correct when written in terms of SCREAM mixing ratios.

**Comment by PeterCaldwell** [comment]
I never thought I'd say - we should correct the Wikipedia article about us! ^^ @bogensch !

**Comment by oksanaguba** [comment]
@mahf708 could you please point which code you refer to in shoc when referring to the formula right after `In SHOC (and also Wikipedia), ...` ?

Separately, since you mentioned PR https://github.com/E3SM-Project/scream/pull/1059/files, it seems that the change for virt temp there was about switching from 'dry' qv to 'wet' qv only.
