### ISSUE TITLE
are we not checking OOB? 

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2828]
This bug was causing an elusive (to Naser) segfault. The test was passing on pm-gpu just fine, but failed on other machines.

Are we not checking OOB as rigorously as we could?

              ```suggestion
        const int icol   = idx / nlevs;
```

ht @bartgol

_Originally posted by @mahf708 in https://github.com/E3SM-Project/scream/pull/2822#discussion_r1603644915_

**Comment by jgfouca** [comment]
Checking OOB on what? Kokkos Views?

**Comment by jgfouca** [comment]
@bartgol , do we not turn on Kokkos view bounds checks in Debug mode? Seems like we should.

**Comment by bartgol** [comment]
That was my thought too. Maybe we disabled them b/c it makes debug runs much much slower? I don't know. But I think that a "full debug" build should turn on all bells and whistles. I will change our configs if needed.

**Comment by bartgol** [comment]
Amazingly, we don't. I'm adding it to our dbg build, but I'm leaving it off from other builds.
