### ISSUE TITLE
IOP link error when building with shared libs

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2854]
I don't know if this is the problem, but spa needs IOP, but IOP is build after the physics packages are built. This is an example of spaghetti connections in the code.

@tcclevenger what do you think of moving IOP in share? It does not depend on anything other than share folder stuff.

To reproduce the issue, try running test-all-scream with `-c BUILD_SHARED_LIBS=ON`.

**Comment by tcclevenger** [comment]
I have no objections. If you want I can make a PR tomorrow.

**Comment by bartgol** [comment]
Yes, please. Thanks!

**Comment by bartgol** [comment]
To be honest, I have no idea how things can work with static linking. SPA (as any other atm proc that uses IOP) needs to know about IOP. But neither spa nor scream_share links against the scream_control lib, so there is no way they can get the symbol. I am really puzzled as of how the spa unit tests can compile
