### ISSUE TITLE
set track_avg_cnt: true by default

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2922]
>@AaronDonahue should we maybe turn on avg count tracking automatically for this diag? Or, more in general, for any field that can have a certain extra data set in the header (something like "can_have_invalid_data" or something)?

> Yes, I think we would want to do that rather than have users try to figure out why some fields are nan, or otherwise bad values.

_Originally posted by @AaronDonahue in https://github.com/E3SM-Project/scream/issues/2916#issuecomment-2251330164_

**Comment by bartgol** [comment]
Having `track_avg_cnt: true` by default implies that we need to accumulate and write to file a few more fields. While the number of extra fields may not be remarkable, for use cases where we split output into many files (like prod runs often do), it may add up to a non negligible amount of extra output. As such, I am inclined to have IO detect whether or not `track_avg_cnt` should be on, and remove it from the yaml file options.
