### ISSUE TITLE
Frontier: issues with rocm/5.4.3 or higher

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/scream#2925]
Currently, there are 8 available ROCm modules on Frontier, with version 5.7.1 set as the default:
```
module avail rocm
------------------------------------------------------------------------------------ /opt/cray/pe/lmod/modulefiles/core ------------------------------------------------------------------------------------
   rocm/5.3.0    rocm/5.4.0    rocm/5.4.3    rocm/5.5.1    rocm/5.6.0    rocm/5.7.0    rocm/5.7.1 (D)    rocm/6.0.0
...
```
Apart from the older 5.3.0 and 5.4.0 modules, other versions (which require CCE 16 or 17 to build SCREAM) either cause memory access errors or p3 post-condition property check failures for some SCREAM simulations. If we plan to use ROCm versions 5.4.3 or higher in the future, we must first address these confirmed issues.
- rocm/5.4.3: p3 post-condition property check failure
- rocm/5.5.1: Memory access fault by certain GPU nodes
- rocm/5.6.0: Memory access fault by certain GPU nodes
- rocm/5.7.0: p3 post-condition property check failure
- rocm/5.7.1: p3 post-condition property check failure
- rocm/6.0.0: p3 post-condition property check failure

@ambrad is working on the confirmed p3 issue.

**Comment by ambrad** [comment]
The fix is a deoptimization in P3: https://github.com/E3SM-Project/scream/commit/e15c01ffdfd29958912d55212b78b48468f86948. This is for the small-kernels code path.
