### ISSUE TITLE
split small kernels into two distinct cmake logic

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2963]
p3 sk -----> 2x slowdown
shoc sk ---> 2x speedup

**Comment by ndkeen** [comment]
For a ne120 (starting with Cess script), running on 8 pm-gpu nodes with no IO and no cosp.
The current `SCREAM_SMALL_KERNELS` option yields a slower overall time as P3 time increases.
However, the SHOC time does give a nice improvement.

```
timer name               original   SMALL_KERNELS
a:EAMxx::shoc::run         6.3           3.8
a:EAMxx::p3::run          14.3          28.1
```

And then with a launch bound improvement, I could get `a:EAMxx::p3::run` down to `13.1 seconds`

**Comment by ambrad** [comment]
Do you know whether the small-kernels P3 version is slower primarily because of all the array allocations? If so, a solution is to make those buffers.

**Comment by bartgol** [comment]
I think it's likely. Regardless, I think two separate knobs for p3 and shoc may be a good debugging tool, even if we'll always end up having both or neither on.

**Comment by ambrad** [comment]
Oh, yes, definitely.
