### ISSUE TITLE
Call MPI_Abort on exceptions.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2964]
Two approaches:

1. Add MPI_Abort to the exception macros.
2. In the-top level C++ routine, wrap everything in a try-catch block with a catch-all block: `catch (...) { /* print mesage */;  MPI_Abort(comm, -1); }`.

**Comment by bartgol** [comment]
I think 2 is preferable. The exception macros may be used by a library that does not use MPI (I think Haero or one of the EAGLES-related libs was originally meant to build even without MPI, @jeff-cohere may correct me). What to do in case of errors should be an app-specific choice.
