### ISSUE TITLE
Fix Field sync methods in case the field is a subfield

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#2973]
E.g, for D2H, doing `Kokkos::deep_copy((m_data.d_view,m_data.h_view);` will copy the full N+1 dim field. Besides being more than what we asked, it may also be conceptually _wrong_.

~If the field is a subfield, we should~
- ~create a "scratch" view at construction time (or, better, lazy init that scratch inside this call)~
- ~reshape into the correct view, and (e.g., for D2H) deep copy from m_data.d_view into the scratch (done on dev), then from scratch call D2H.~

Edit: perhaps we don't need the scratch pad. We can simply switch on the field rank, call `get_view<DT,Host>()` and `get_view<DT,Device>()` and call deep copy on those... So it should be quick to implement...

**Comment by ambrad** [comment]
As an alternative for the savvy caller, could they request transfer of a bundle exactly once?

**Comment by bartgol** [comment]
You mean something like

```c++
f1.sync_to_host();
// no need to call on f2, ..., fN, since they are all subfields of F, and sync_to_host() syncs the parent field
```
? Yes, that's an alternative. But it won't work once this is implemented, so I would discourage it. Unless you have access to the parent field, in which case it's completely fine:
```c++
F.sync_to_host();
// not needed if f1,..,fN are subfields of F.
// f1.sync_to_host();
...
// fN.sync_to_host();
```

**Comment by tcclevenger** [comment]
> We can simply switch on the field rank, call get_view<DT,Host>() and get_view<DT,Device>() and call deep copy on those... So it should be quick to implement...

Turns out we cannot deep copy two non-contiguous views where no "copy_space" exists between dst and src, i.e., `for deep_copy(dst, src)` requires
```
src.span_is_contiguous() && dest.span_is_contiguous() && 
std::is_same<ViewDest::array_layout,ViewSrc::array_layout>::value, 

or there exists an ExecutionSpace "copy_space" (either given or defaulted) such that

SpaceAccessibility<copy_space, ViewDest::memory_space>::accessible == true && 
SpaceAccessibility<copy_space,ViewSrc::memory_space>::accessible == true.
```
(from https://kokkos.org/kokkos-core-wiki/API/core/view/deep_copy.html)

I think I will explore the scratch view option you first mentioned.

**Comment by bartgol** [comment]
@tcclevenger I would like to avoid the scratch view path, if possible, since it requires a lot of machinery. However, in EAMxx we have only one scenario where the view is not contiguous, and that is when we are subviewing a parent field along the 2nd dimension. In this case, we can deep copy all subviews one by one (without fences, to avoid unnecessary sync!). Something like this (say, for rank 3):

```c++
v_h = get_view<Real***,Host>();
v_d = get_view<Real***,Device>();
for (size_t i=0; i<v_h.extent(0); ++i) {
   sv_h = ekat::subview(v_h,i);
   sv_d = ekat::subview(v_d,i);
   Kokkos::deep_copy(sv_h, sv_d);
}
```

So the code may be a bit long (a switch on the rank, with an if inside each case to check if the view is contiguous).

**Comment by bartgol** [comment]
If you want to be fancy, you could put an if statement at the top, to avoid all the work if host and dev are the same mem space (for CPU runs), so we save some time. Something like `if (v_h.data()==v_d.data()) { return; }`.
