### ISSUE TITLE
I/O possible check to implement: Make sure no two output streams have the exact same name

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#3020]
I recently helped troubleshoot a case where someone couldn't run their simulation because I/O gave an error about redefining the time dimension when it already existed.  It took us awhile to figure out it had nothing to do w/ the time dimension in the file, instead, they had two output streams with the same filename prefix and frequency, etc.  So ultimately, two output streams attempting to access the same file.

We could implement a check in the driver that quickly checks all OM that have been setup to ensure no two share a name, if so, throw an error that is human readable and makes it easy to fix.

**Comment by bartgol** [comment]
This check is better suited for buildnml phase.

**Comment by AaronDonahue** [comment]
oh yes, that would be a fantastic place to put it.  Quick question on that, would be able to support cases where the `filename_prefix` was the same but the `averaging_type` was different?  Which in EAMxx would be fine since the filenames would ultimately be different.

**Comment by bartgol** [comment]
Also check #2986 . 

@AaronDonahue I don't get your question. We already support that. The PR i linked is fixing a bug related to restart for that precise case.

**Comment by AaronDonahue** [comment]
huh, strange.  Then I'm not sure why Hassan was hitting an error which was resolved when he changed prefixes.  I can close this issue and investigate more on Hassan's side.
