### ISSUE TITLE
ilev not being written to output files

### ISSUE THREAD

**Issue by bogensch** [E3SM-Project/scream#3022]
Coordinate variable "ilev" is not being written to output files, even though hyai and hybi are.  Verified that this is occurring in both the global model and DPxx.

**Comment by bartgol** [comment]
What's the content of "ilev" supposed to be? 0,1,...,128? `p0*hyai+ps*hybi`? Something else?

**Comment by bogensch** [comment]
It's the hybrid level at interfaces.  It should be defined like "lev" is defined but with the hyai and hybi coefficients:
1000.*(hyai+hybi)

**Comment by AaronDonahue** [comment]
@bogensch , general question.  Should the units for `lev` and `ilev` be `Pa` or `mbar`?  Right now they are `mbar`.

**Comment by bogensch** [comment]
In E3SM and SCREAMv0 they have always historically been hPa (so mbar) for whatever reason.
