### ISSUE TITLE
Cases using 128 vertical levels on frontier not BFB

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#3053]
With Oct 16th checkout, I was trying to do some performance tests on frontier.
I noticed that every single case had different bfbhashes than the others.
Trying to find a `create_test` reproducer led to a different issue: the standard tests we use are all using 72 vertical levels.
But for all cases of interest, we use 128 levels. It looks like cases using 72 levels are BFB, while those using 128 levels are not.

These pass:
```
ERS.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu
ERS_P64.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu.scream-small_kernels
PEM_P64.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu.scream-small_kernels
PET.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu
PET_P32.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu.scream-small_kernels
REP_P16.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu
REP_P16x6.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu
```

And these fail:
```
REP_P16.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu.scream-L128
ERS_P1024.ne256pg2_ne256pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu.scream-small_kernels
PEM_P1024.ne256pg2_ne256pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu.scream-small_kernels
```

Note that @mahf708 found location where we are setting default levels of resolutions 256,512,1024 to be 128, and then still at 72 for the others.  Therefore, to get 128 levels with ne30, I'm using the `scream-L128` test modifier.  This is not quite working with ne4 (to make even simpler reproducer). There is a SCREAM-HR, but I ran into runtime issues using this with ne30.

**Comment by whannah1** [comment]
@mahf708 sure, I can make one.

**Comment by bartgol** [comment]
Why do we need to run 128 levels at ne4?

**Comment by whannah1** [comment]
We don't really need this other than it might help to figure out the non-BFB test results that Noel mentioned. also, generating a ne4 L128 IC file is trivial.

**Comment by whannah1** [comment]
@mahf708 I don't think I created or added those - but I just created a new one and uploaded it to chrysalis - I was going to run a test on Frontier

**Comment by whannah1** [comment]
@ndkeen @mahf708 I just created this PR and ran a quick test on Frontier which passed except for baseline comparison since no baseline exists.
https://github.com/E3SM-Project/scream/compare/whannah/eamxx/add-ic-ne4-L128

**Comment by ambrad** [comment]
Running with full BFB hashing shows that SHOC is the likely issue.

**Comment by ndkeen** [comment]
With the change Walter made to add ne4 IC, I can now run:
```
REP_P8.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu.scream-L128
```
which does fail compare in same way.

Note I have not seen the fail on pm-gpu, but have not tested as many diff tests.

Now trying with:
```
      Kokkos::parallel_for(Kokkos::TeamVectorRange(team, nlev_packs), [&] (const Int& k) {
        zt_grid(i,k) = z_mid(i,k) - z_int(i, nlevi_v)[nlevi_p];
        zi_grid(i,k) = z_int(i,k) - z_int(i, nlevi_v)[nlevi_p];

        // Dry static energy                                                                                                                                         
        shoc_s(i,k) = PF::calculate_dse(T_mid(i,k),z_mid(i,k),phis(i));
        if (k+1 == nlev_packs) zi_grid(i,nlevi_v)[nlevi_p] = 0; //ndk add from pr3058                                                                                
      });
      //zi_grid(i,nlevi_v)[nlevi_p] = 0; //ndk rm from pr3058                                                                                                        
      team.team_barrier();
```

**Comment by whannah1** [comment]
@ndkeen @ambrad could this have anything to do with the "pack size"?
I recall that this being set to the number of levels, but I'm not sure if that's still the case.
Would a larger pack size be potentially problematic for reproducibility?
Could we fix the pack size at something smaller and retest both grids?

**Comment by ambrad** [comment]
> could this have anything to do with the "pack size"?

This is on a GPU system, for which pack size is always 1.

**Comment by ndkeen** [comment]
I was wondering if the machine-file changes could have been related

**Comment by ambrad** [comment]
> I was wondering if the machine-file changes could have been related

Yes, definitely. S/w stack changes often lead to nondeterminism hunts.
