### ISSUE TITLE
test-all-scream and gather-all-data don't work on lassen.llnl.gov

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#306]
When I issue `cd /g/g11/caldwep/gitwork/scream/components/scream'; ./scripts/test-all-scream $(which mpicxx) -i -m lassen` on lassen.llnl.gov, I get:

> Last commit on ref 'PeterCaldwell/P3port/ice_melting3':
>      805e979 _commit msg here_
> ERROR: Command: 'git submodule update --init --recursive' failed with error 'You need to run  this command from the toplevel of the working tree.' from dir '/g/g11/caldwep/gitwork/scream/components/scream'"

This seems to be saying I'm running the command from the wrong directory... but I just cd'd to the correct directory. Weirdly, this command works on quartz.llnl.gov - which is the CPU brother of lassen. 

When I try to run `./scripts/gather-all-data './scripts/test-all-scream $(which mpicxx) -m $machine' -l -m lassen` I get 

> ERROR: Expected to see ./scream

This suggests to me that I'm running from the wrong directory and/or that I need to have built a scream executable already and be in the directory where I built it. I tried running gather-all-data from both $scream_root and $scream_root/components/scream/ and got the same result. My recollection is that I got the same error trying to use gather-all-data from quartz.

For both errors, problems occurred even after I `module purge --force;export LLNL_USE_OMPI_VARS='y'; module load <stuff>`.

**Comment by PeterCaldwell** [comment]
@AaronDonahue , @jgfouca - do you have a sense of what's happening or what I should try? I feel like I'm probably doing something dumb with gather-all-data. And Aaron says we're using lassen for nightlies, so there must be a solution to this problem...

**Comment by PeterCaldwell** [comment]
> My recollection is that I got the same error trying to use gather-all-data from quartz.

I've now confirmed this.

**Comment by bartgol** [comment]
A quick look at line 60 of `gather_all_data.py` confirms that gather-all-data has to be run in the directory right above the repo root. And it may also assume that the repo folder name is 'scream'. For the first requirement, just change the directory you launch it from. For the second, you can create a symlink `scream` to the current repo folder.

**Comment by PeterCaldwell** [comment]
Good hint, Luca. Thanks! This command seems to be working: `./scream/components/scream/scripts/gather-all-data './scripts/test-all-scream $(which mpicxx) -m quartz'   -l -m quartz`

Still unsure about test-all-scream

**Comment by bartgol** [comment]
If you only run `test-all-scream`, on the other hand, you have to be running it from inside the scream _component_ folder.

**Comment by PeterCaldwell** [comment]
Update on using gather-all-data on lassen: when called from the correct directory on lassen, I get the same error message as test-all-data: `ERROR: Command: 'git submodule update --init --recursive' failed with error 'You need to run this command from the toplevel of the working tree.' from dir '/g/g11/caldwep/gitwork/scream/components/scream'`

**Comment by PeterCaldwell** [comment]
And in terms of inconsistency in where to call gather-all-data and test-all-scream from: it is kind of confusing but so long as our documentation is clear, I don't think it needs to be fixed unless it is easy to do.

**Comment by bartgol** [comment]
Do you have access to a newer version of git? AFAIK, old versions of git required you to update submodules from the git root directory, but newer versions allow you to do it from any point of the git tree. Not sure which version is the critical one. I'm guessing 2.X should be fine though.

**Comment by PeterCaldwell** [comment]
Tried with git2.2.0 and had the same problem. Aaron seems to be able to run. He gave me his script - I'll tinker with it to see if I can replicate his success.

**Comment by jgfouca** [comment]
@bartgol , I totally agree, the scripts should be less picky and more flexible regarding root directories, where they get run from etc.

@PeterCaldwell , if the default git on lassen is too old for test-all-scream, then the environment block for lassen in gather_all_data.py:METADATA should probably load a git module.

**Comment by PeterCaldwell** [comment]
Thanks Jim. updating git didn't help and Aaron ran successfully with the old git version (1.8). This command is either working or lassen is hung: `./scream/components/scream/scripts/gather-all-data './scripts/test-all-scream $(which mpicxx) -m lassen --test="sp" --submit' -l -m lassen`. It differs from my previous attempt by --test="sp" (use single precision only... I doubt this is it) and --submit. I'm not sure why --submit would fix the problem either.

**Comment by jgfouca** [comment]
@PeterCaldwell , please note that the first thing gather_all_data will do on lassen is a module purge, so any git modules you have loaded before you run the command will be gone. I recommend adding a newer git module here:

```
    "lassen" : (["module purge", "module load gcc/7.3.1 cuda/10.1.243 cmake/3.14.5 spectrum-mpi netcdf/4.7.0 python/3.7.2", "export LLNL_USE_OMPI_VARS='y'"],
```

**Comment by PeterCaldwell** [comment]
Ah, that makes sense but doesn't explain Aaron's success (since he also didn't module load git in his script). I'll do it and try again, though my current attempt is neither succeeding or failing... must be hung.

**Comment by jgfouca** [comment]
@PeterCaldwell , Aaron may have a hardcoded path to a newer git in his environment.

**Comment by PeterCaldwell** [comment]
adding a newer version of git to the module load list in gather_all_data.py and/or adding "--submit" to the embedded test-all-scream call seems to have gotten me further along on Lassen testing. We will see whether this lucky streak continues...

**Comment by bartgol** [comment]
The `--submit` thing is probably a red herring. Also, beware that with that flag you add an entry to the cdash. Not sure if that's your goal or if you were simply manually testing a branch.

**Comment by PeterCaldwell** [comment]
Thanks Luca. Most recent attempt failed with the completely opaque but somewhat poetic
> User defined signal 2
>                     lassen failed

I'm trying again in case this was a random problem, and also trying on cori.

**Comment by bartgol** [comment]
@PeterCaldwell is this still an issue or can we close?

**Comment by bartgol** [comment]
@PeterCaldwell 
> @PeterCaldwell is this still an issue or can we close?

**Comment by PeterCaldwell** [comment]
I checked this last time you pinged me and still couldn't get these things working on Lassen. I wanted to dig in more, but got distracted by higher priority items. My recollection is that @AaronDonahue *can* get these to work, so maybe we need to change the title to "team lead incapable of running basic codes"? ;-). Seriously though, I'd like to keep this issue open to remind me to work on it.

**Comment by PeterCaldwell** [comment]
Just checked again, and gather-all-data worked on lassen now. Benefits of procrastination?

**Comment by bartgol** [comment]
More likely benefits of #603 . ;)
