### ISSUE TITLE
Need additional testing 

### ISSUE THREAD

**Issue by jgfouca** [E3SM-Project/scream#32]
* Tests we should add:
  - test coverage for 2nd timestep (it=2 in p3_main)... does it crash and does it change answers.
  - add regression test for log_predictNC=.true. (which we will use for our very first E3SM
implementation and should keep as an idealization option)
  - more generally, make sure we have complete code coverage
  - add testing for the p3_interface subroutine (not ready yet)

**Comment by ambrad** [comment]
@PeterCaldwell will let us know if this is a higher priority. Otherwise, Either @jgfouca or I will handle this in approx late Oct or early Nov, when we switch from the micro-app to the main P3 code.

**Comment by ambrad** [comment]
A fair bit of testing was added since this issue was opened.
