### ISSUE TITLE
Testing script wish list

### ISSUE THREAD

**Issue by jgfouca** [E3SM-Project/scream#325]
Let's use this issue to track features we want to add to the testing infrastructure.

- [x] 1. Multi-GPU support
- [x] 2. Refactor machine specification dictionary that currently lives at the top of gather_all_data.py and move it into it's own file. It's generally useful beyond gather_all_data.
- [x] 3. Separate compilation resources from testing resources. On CPU machines, they would coincide, but on GPU machines, one does not want to issue `make -jN` with N being the number of GPUs, but rather the number of CPU cores.
- [x] 4. Remove possibility of providing kokkos installation to test-all-scream. The e3sm submodule for kokkos is now the only supported way, so we should not mislead the user into thinking any kokkos version would do.
- [x] 5. When building baselines, do not build execs not needed to generate baslines (HOLD ON: see #408 discussion).
- [ ] 6. Have test-all-scream run a git diff of branch compared to master, and run tests only in the subdir affected by the PR.
- [x] 7. When running with `-i` AND `--baseline-dir` options, add a flag (say, `--rebuild-outdated`) which makes test-all rebuild baselines (in the same dir as specified by `--baseline-dir`) if the sha of the baselines is older than the current version of `origin/master`. This could also be the behavior whenever `-i --baseline-dir /path/to/baselines` is used (without the need for an additional flag).
- [x] 8. This is a combo item. When using `-p` in test-all-scream, it can be detrimental to run *all* builds in parallel. E.g., some tests require N ranks. On gpu, given the limited number of GPUs on node, we need to either a) run builds serially, or b) limit N to 1. Either approach is suboptimal. Instead, do this:
   - Split build and test phase: during the build phase, it is likely always ok to parallelize over *all* builds, since we have many cpus, and there is no "requirement" in terms of resources by each build (like we have instead during test phase). So the build phase can use maximum parallelism.
   - In the test phase, check whether parallelize over all builds makes sense. On CPU, it likely does (we have enough cores to accomodate N ranks for each build), but still need to check: if we add, say, 2 or 3 more builds, then on _certain_ machines (e.g., developer's laptop/workstation) we might run out of cores (some tests require 4 cores). On GPU machines, we _likely_ can't affort all builds and/or all mpi ranks we'd like. So test-all-scream should establish how many builds it can afford, based on the maximum number of ranks each build requires. It is hard/impossible to figure this out automatically, so we will have to update test-all-scream every time we add a test with more max ranks than the current master (not a big burden). As of now, scream uses at most 4 ranks in a test. Our GPU testing mach (weaver) has 4 gpus, so we can afford to test at most 1 build at a time (unless we lower the number of ranks to 2).
- [x] 9. To get around all the issues with #8, we could do something hacky: we can create a CTestTestfile in ctest-build, and run ctest in parallel over all builds. Pro: can run a single ctest instance, which can optimize resource (all the node resources, without splitting them across builds). Con: in the output, we don't see which build each test belongs to (but if they fail, the --output-on-failure flag would show the output of the scream arch/config header, which should help to identify the build by looking at size of Real and FPE mask).

**Comment by bartgol** [comment]
I think number 2 might be needed soon. Bowman and blake builds are quite fast: less than 5min for blake, and about 12min on bowman. On white, after 16 minutes, we're still building baselines.

We need to improve the machines dictionary, by including compilation resources and ctest resources separately. The former are used for the `make` commands, the latter for `ctest` ones.

Note: for CPU machines, the two resources would coincide, but for GPU machines, one would have compilation resources being the number of available CPU cores, and ctest resources being the number of GPUs. Notice that, in order to use the number of GPUs correctly, one would have to set the KOKKOS_DEVICE_ID env var to a different number for each test. We can implement compilation-vs-ctest resources differentiation first, and leave the smart use of GPUs for later.

**Comment by bartgol** [comment]
PR #410 is taking care of 2 and 3.

**Comment by PeterCaldwell** [comment]
@jgfouca - have we addressed these goals yet, or should this issue stay open?

**Comment by jgfouca** [comment]
@PeterCaldwell , it looks like all except 6. have been done.

**Comment by bartgol** [comment]
I think number 6 will likely remain on the wishlist forever (or, at least, for a very long time). I think it might require quite a bit of analysis of code dependencies, which for a library relatively small as scream might not be worth it.

I'm ok with closing this issue.

**Comment by PeterCaldwell** [comment]
Hmm. Item 6 would be really cool, but i can see that it would be a lot of work. I'm going to leave this to @jgfouca to close if he doesn't think it will realistically ever get done. Otherwise I'm happy with it being a long-running wishlist item. Xmas is coming, so who knows!

**Comment by jgfouca** [comment]
Our standalone testing is already pretty fast, so I think 6 is probably more trouble than it's worth.
