### ISSUE TITLE
Permissions to P3 table data files keep changing

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#333]
There is a current issue with the permissions on the p3 lookup tables, `p3_lookup_table_2.dat*` which I think might be traced back to PR #327 .  What seems to be happening is that when a scream run is set up the tables are copied to the atm data directory with read/write permissions set to only the user.  

If two users are running jobs at the same time the permissions will change and one users job will fail, unable to access the lookup tables.

Looking at the commit from PR #327, 
```
safe_copy(os.path.join(scream_data_dir, item), os.path.join(din_loc_root, "atm/cam/physprops"))
```
it looks like `atm/cam/physprops` is a universal directory shared by all users, hence the problem.

**Comment by AaronDonahue** [comment]
adding @bogensch  since he is also experiencing the issue.

**Comment by jgfouca** [comment]
OK, this is a problem we have hit a lot. The issue is that too many users have their umask set such that group collaboration is impossible. We have mechanisms in CIME to ensure that files are created with group accessibility. The only requirement is that the root of the directory is set to do group inheritance (chmod +s)

**Comment by jgfouca** [comment]
I will make a PR to have those buildnmls use the CIME SharedArea

**Comment by jgfouca** [comment]
You may need sysadmin to fix up the files that's already there.

**Comment by AaronDonahue** [comment]
@PeterCaldwell , do you know who we would have to contact to have the ` /usr/gdata/climdat/ccsm3data/inputdata/atm/cam/physprops` directory have group inheritance?  Could any of us go ahead and do that?
