### ISSUE TITLE
Migrate p3 micro-app to main repo

### ISSUE THREAD

**Issue by jgfouca** [E3SM-Project/scream#34]
Things to consider:
* unit tests need to be ported to catch2
* merge scream_pack (version in scream might be a bit out of date)
* Focus on "share" and "p3/*function*" and unittests
* scream tables need unit tests

**Comment by ambrad** [comment]
Also:
- Bring over MIMIC_GPU cmake option for OpenMP-based detection of fine-grained ||ism race conditions.
- Update Travis CI to run OpenMP exe space with ~7 threads and MIMIC_GPU turned on.
