### ISSUE TITLE
Precompile scream test lib, including scream_catch_main.cpp

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#344]
With many unit tests, we're recompiling the same cpp file many times for no reason. We could compile a scream_testing library once, consisting of the scream_catch_main.cpp, plus whatever test-related file we may need.

Note: whatever is compiled in this library will _not_ be available outside unit tests framework (since the library defines the main function).

**Comment by PeterCaldwell** [comment]
This seems like a good idea. Are you saying 1). every time we start running all of our tests, we would first create this library which all tests can use, or 2). we would build an external library now, which all tests would use forever after (until we decide to update that library)?

**Comment by bartgol** [comment]
It's number 2. We build the main file once. Then each test will link against it. Currently, we have 24 tests created with `CreateUnitTest`. All of those use scream_catch_main.cpp. For normal, short, unit tests, this is by far the longest file to compile (among those needed by the test).

**Comment by bartgol** [comment]
This has been done in EKAT. Closing.
