### ISSUE TITLE
rename p3_functions_math* => p3_saturation*???

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#345]
p3_functions_math_impl.hpp only contains 2 functions right now: one to compute saturation vapor pressure and another to convert it into saturation mixing ratio. Since p3 porting is almost done now, can we assume saturation-related stuff is all that will be in this file and rename it to better reflect what it includes? @pressel and @pbtoast - I have a vague sense you may have been involved in the creation of this file...

And on a more general note, it bugs me that all of our functions are named "p3_functions_<name>" because this seems unnecessarily verbose. Could we change all file names in components/scream/physics/p3/ to just be "p3_<name>"?

**Comment by jeff-cohere** [comment]
Hey Peter,

I agree with you about the verbosity/redundancy in the p3 names. I haven't touched this file, though. To find out who's implicated in the creation and modification of a file, you can always run

```
git log <filename>
```

When I do that on `p3_functions_math_impl.hpp`, I see pawprints from you, Kyle, and @jgfouca . And Kyle's change is via a merge commit, so really it's you and Jim.

(By the way, "pbtoast" is my personal GitHub alter-ego. My E3SM-savvy GitHub account is "jeff-cohere".)

**Comment by PeterCaldwell** [comment]
Renamed/solved this a long time ago.
