### ISSUE TITLE
Subcolumns not supported in P3

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#358]
The version of P3 in SCREAM does not support sub-columns, which is an option in the E3SM model.  Given the scales we plan to run P3 we don't anticipate using sub-columns, however, it is possible that in the future someone may try to run coarse resolution with P3 and sub-columns which will most likely not cause an error but could cause unexpected behavior in the solution.

We should include a check in the init phase of P3 that errors out if P3 is active and sub-columns are turned on.

**Comment by PeterCaldwell** [comment]
@AaronDonahue - can I assign this back to you? It is easy but I suspect you'll get to it before I will...

**Comment by AaronDonahue** [comment]
I'm closing this, if we want subcolumns in P3 I'm sure we'll remember it.
