### ISSUE TITLE
Add updated fields to AtmosphereProcess

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#366]
Right now, fields that are in-out have to be declared twice, and set twice, in the atm process (once as required, and once as computed). This can be cumbersome, and copy+paste may lead to errors down the road.

Todo: add `get_updated_fields()`, `set_updated_field(f)`, and `updates(f)` methods. 

Note: these are meant to be shortcuts for a repetition of the same field F among required and computed fields.

**Comment by PeterCaldwell** [comment]
@bartgol - I don't understand this issue at all. Is this fixed?

**Comment by bartgol** [comment]
No, it's not implemented. But I think I decided that implementing it might create ambiguities and/or more complex logic on the AD side. I'm closing this.
