### ISSUE TITLE
SHOC second moment refactor 

### ISSUE THREAD

**Issue by bogensch** [E3SM-Project/scream#387]
For further refactor, lines 1305-1310 for the calculations of (co)variances share same formulation and could be calculated using a new subroutine call.  

In addition, lines 1314-1329, the calculations of the vertical fluxes all share the same formulation and could be calculated using a new subroutine call. 

https://github.com/E3SM-Project/scream/blob/a49de6776c1bf6e440c0036411f463ebde874e22/components/cam/src/physics/cam/shoc.F90#L1296-L1332

 In addition, for the lower boundary conditions, I've identified two potential areas to make new testable subroutines.

Do we want to make 1157-1162 into a separate subroutine with ustar and wstar as outputs? 

In addition, lines 1167-1169 the formulations for the surface boundary conditions share the same formulations so could share a same subroutine.  

https://github.com/E3SM-Project/scream/blob/a49de6776c1bf6e440c0036411f463ebde874e22/components/cam/src/physics/cam/shoc.F90#L1157-L1170

**Comment by xyuan** [comment]
please check this PR,
https://github.com/E3SM-Project/scream/pull/390
