### ISSUE TITLE
Add a brief guide to SCREAM's source tree organization.

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/scream#394]
A few of us think that navigating SCREAM would be easier with a document containing a brief description of our directory structure, starting at `components/scream/` or possibly `components/scream/src/`. Such a document could be linked to by other documents that describe our development process, including porting guides and the like.

The guide would be a simple Markdown document with one-line descriptions of folders and perhaps a paragraph or two describing the overarching structure and/or motivation(s).

Now for some questions:

+ Where does this belong? It's been suggested that we put it into `components/scream/docs`, which contains the (LaTEX) design documents for SCREAM and a `README.md`. Could we just stick it into a Markdown file in that directory called `Source-tree.md` or something? It's kind of an odd fit, with the purpose of that directory being the design doc, but maybe that doesn't matter?
+ Should it include everything starting at `components/scream`, or just the stuff in `components/scream/src/`?

@bartgol, @PeterCaldwell: you were the two who seemed to have the most thoughts about this on Monday. Is there anything missing here? Can you answer either of these questions?

**Comment by bartgol** [comment]
I think it's ok to put _any_ documentation in the docs subfolder, not just the design documents. Directory tree explanation is definitely ok there. I would still put a comment in our main README.md about that. 

Regarding point 2, I would describe both. The reader needs to know what's in the scream project folder overall (what's the cmake folder, the test folder, the external folder?), and then also how the source code is organized. So I would explain:
- content of `components/scream`: what each of those dirs is (one line)
- content of `components/scream/src': which parts of the code belong to the individual folders. What goes in control, what goes in share, what goes in physics?
- [perhaps together with the previous] explain that each additional physics parametrization needs to have its own subfolder (maybe submodule?) in `components/scream/src/physics`. How it is organized internally, it's not our business, but it _should_ contain unit tests internally (so do not confuse with `components/scream/tests`, which contains _whole-scream_ tests).

Extra: I would also _not_ put build/run instruction in the main README.md, and defer them to a document in the docs subfolder. The main README is to give an overview of what the git project is, and where to find additional info. Perhaps we can incorporate such mod in this PR?

**Comment by PeterCaldwell** [comment]
Yeah, I think it's great to put this in components/scream/docs/. And I agree that documenting the entire scream directory structure rather than just scream/src/ is best. Thanks for doing this!
