### ISSUE TITLE
SHOC: out of bounds

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#400]
At this line,
https://github.com/E3SM-Project/scream/blob/0923ce13163e9029962ae967f53e5eb531ba8939/components/cam/src/physics/cam/shoc.F90#L3315
thv_zi is declared as having nlev levels, but it should be nlevi. Its use in the subroutine assumes nlevi. The caller has nlevi levels, though, so it's a problem in DEBUG builds only.

**Comment by ambrad** [comment]
@pressel this looks like something from a refactor PR.

**Comment by pressel** [comment]
Thanks, @ambrad you are correct. Fixing this now.

**Comment by pressel** [comment]
Ths bug was fixed with PR  #402.
