### ISSUE TITLE
Enhance testing 

### ISSUE THREAD

**Issue by jgfouca** [E3SM-Project/scream#41]
I'm currently getting good results from using gather_all_data to drive test_all on different platforms:

```
% ~/scream-docs/perf-scripts/gather_all_data ''  --test-all -s
Starting test-all analysis on bowman with cmd: cd ~/scream-docs-perf-bowman/micro-apps && git fetch && git reset --hard origin/master && cd ~/scream-perf-bowman/components/scream && module load openmpi/1.10.6/intel/17.2.174 git/2.8.2 cmake/3.5.2 && git fetch && git checkout 89575d4 && srun ~/scream-docs-perf-bowman/micro-apps/test-all $(which mpicxx) $HOME/kokkos-install-bowman/install
Starting test-all analysis on blake with cmd: cd ~/scream-docs-perf-blake/micro-apps && git fetch && git reset --hard origin/master && cd ~/scream-perf-blake/components/scream && module load openmpi/2.1.5/intel/19.1.144 git/2.9.4 cmake/3.9.0 && git fetch && git checkout 89575d4 && srun ~/scream-docs-perf-blake/micro-apps/test-all $(which mpicxx) $HOME/kokkos-install-blake/install
Starting test-all analysis on white with cmd: cd ~/scream-docs-perf-white/micro-apps && git fetch && git reset --hard origin/master && cd ~/scream-perf-white/components/scream && module load devpack/20181011/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88 git/2.10.1 cmake/3.9.6 && git fetch && git checkout 89575d4 && OMPI_CXX=$HOME/kokkos-install-white/install/bin/nvcc_wrapper bsub -I -q rhel7G ~/scream-docs-perf-white/micro-apps/test-all $(which mpicxx) $HOME/kokkos-install-white/install
Starting test-all analysis on waterman with cmd: cd ~/scream-docs-perf-waterman/micro-apps && git fetch && git reset --hard origin/master && cd ~/scream-perf-waterman/components/scream && module load devpack/latest/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88 git/2.10.1 cmake/3.9.6 && git fetch && git checkout 89575d4 && OMPI_CXX=$HOME/kokkos-install/install/bin/nvcc_wrapper bsub -I -q rhel7W ~/scream-docs-perf-waterman/micro-apps/test-all $(which mpicxx) $HOME/kokkos-install/install
Completed test-all analysis on white
Completed test-all analysis on waterman
Completed test-all analysis on blake
Completed test-all analysis on bowman
```

This approach is currently Sandia-centric, but it wouldn't be hard to add additional machine support to gather_all_data. I was planning to add some dashboard capabilities to test-all and add jenkins jobs to do the equivalent of what you see above.

If we go in this direction, it makes the contents of test-all very important. Right now, the testing is a bit limited:

```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$cpp_compiler -DKokkos_DIR=$kokkos_dir ..
make -j8
make baseline
OMP_NUM_THREADS=17 make test # some of our unit tests do their own thread-sweeping, so we are getting better thread-count coverage here than it appears

/bin/rm -rf *
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$cpp_compiler -DKokkos_DIR=$kokkos_dir -DSCREAM_DOUBLE_PRECISION=FALSE ..
make -j8
# no run 
```

So, we're doing a standard debug build with a full set of tests and a single-precision build. It seems like there's a lot more we could be testing:
1) Optimized builds
2) Optimized tests (may have to avoid baseline tests due to vectorization making BFB difficult)
3) Different large and small pack sizes
4) Different Kokkos configurations (serial, openmp)
5) Some configuration that supports FPE
6) Baseline testing with single precision (with tolerances)

I would love to hear what others think.

**Comment by bartgol** [comment]
I'm not familiar with gather_all_data. I looked at it quickly, and, from my low level of python, it seems it connects to those machines, and launches the tests on all of them. Does it give any detail if a test fails? Or is it simply a sort of wrapper to dispatch tests on all machines with one command?

**Comment by jgfouca** [comment]
@bartgol , it stores all the output from each machine in a log file, so the details would be there.

> Or is it simply a sort of wrapper to dispatch tests on all machines with one command?

Yes, that's its primary purpose.

**Comment by jgfouca** [comment]
The output and return code from gather_all_data should make it clear if it worked. I admit, the output could definitely be a bit a cleaner when things fail...

**Comment by bartgol** [comment]
If the output makes it clear when it works, then it's ok. We can work on improving the output for failures later. As long as it's clear from the output whether the tests passed or not (on each individual machine).

Another question is: do we want to pass all our options via command line or maybe parse a test-options file? The former may become a bit cumbersome if we increase the amount of functionalities we test (like the ones you suggested).

**Comment by jgfouca** [comment]
@bartgol , yes, it would be easy to add options to configure what gets tested. What do you think we should test in a "full" configuration?

**Comment by ambrad** [comment]
Quite a bit has been done to implement these.
