### ISSUE TITLE
Build failure for FSCREAM-SA on Cori-KNL

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#432]
The FSCREAM-SA compset is unable to build on Cori-KNL, failing with the following error during build time:

`CMake Error at /global/common/sw/cray/cnl7/haswell/cmake/3.14.4/gcc/8.2.0/2hef55n/share/cmake-3.14/Modules/FindLAPACK.cmake:417 (message):
  A required library with LAPACK API not found.  Please specify library
  location.
Call Stack (most recent call first):
  scream/src/dynamics/homme/homme/CMakeLists.txt:205 (FIND_PACKAGE)`

This has caused a persistent FAIL in the CDASH testing now that the FSCREAM-SA compset has been added to the list of nightly tests.

**Comment by AaronDonahue** [comment]
@ndkeen , @bartgol , @PeterCaldwell ; I'm assigning you three because I think one of you might have some insight on how to fix the issue.

**Comment by bartgol** [comment]
I know what the deal is. We need to tell homme where to find blas/lapack. If there is a lapack/blas avaialble in the LD path, cmake should find it. The error suggests there's no lib in the ld path, so we should probably load a module. @ndkeen knows more about Cori-KNL, so he can tell us what modules we need to load, so we can put them in our python scripts.

**Comment by AaronDonahue** [comment]
Excellent, once we hear from @ndkeen could you (@bartgol ) put in a PR and make me reviewer so we can get it in pretty quick and get back to a pretty all-green CDASH?

**Comment by ndkeen** [comment]
I would just have to try repeating the problem and debugging. Would we want to use use MKL for Intel/Cori?

**Comment by bartgol** [comment]
I just realized I can just use whatever setup scripts we were using for homme, since...this is for homme.

**Comment by bartgol** [comment]
@AaronDonahue , do you think we can close this for now?

**Comment by bartgol** [comment]
Closing, since #534 removed the test from our nightlies until we have a complete infrastructure for the mct coupler.
