### ISSUE TITLE
Difficulty building scream unit tests on Cori-KNL

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#436]
Running test-all-scream on Cori I run into issues.  Running `test_all_scream` and `gather_all_data` results in the same fail during the building of baselines:

```
RUN: cmake -DCMAKE_CXX_COMPILER=/opt/cray/pe/craype/2.5.18/bin/CC -C /global/u1/a/adonahue/Code/scream/components/scream/cmake/machine-files/cori.cmake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_PACK_SIZE=1 -DSCREAM_SMALL_PACK_SIZE=1 -DSCREAM_BASELINES_ONLY=ON /global/u1/a/adonahue/Code/scream/components/scream
FROM: /global/u1/a/adonahue/Code/scream/components/scream/ctest-build/baselines/debug_nopack_fpe
WARNING: Failed to configure baselines:
CMake Error at ekat/cmake/YamlCpp.cmake:24 (add_subdirectory):
  The source directory

    /global/u1/a/adonahue/Code/scream/externals/yaml-cpp

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  ekat/CMakeLists.txt:26 (include)


CMake Warning (dev) at ekat/cmake/EkatSetCompilerFlags.cmake:91 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable CUDA_ROOT is set to:

    /usr/common/software/cuda/10.2.89

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  ekat/CMakeLists.txt:78 (SetCompilerFlags)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

looking at the machine_specs file is looks like Cori doesn't load any modules in gather_all_data:

```
    "cori"   : (["eval $(../../cime/scripts/Tools/get_case_env)", "export OMP_NUM_THREADS=68"],
                "$(which CC)",
                "srun --time 02:00:00 --nodes=1 --constraint=knl,quad,cache --exclusive -q regular --account e3sm",
                68,
                68,
                ""),
```

**Comment by AaronDonahue** [comment]
I'm curious if the list of modules in gather_all_data needs to be updated, or if something else is missing.

**Comment by AaronDonahue** [comment]
@ndkeen , pinging you because it is an issue I'm running into on Cori, but nowhere else.

**Comment by PeterCaldwell** [comment]
@jeff-cohere might have intel on this as well.

**Comment by jeff-cohere** [comment]
I've not run into this problem. But the error is complaining about a missing file in an external dependency, which suggests to me that you need to update your submodules. Have you tried that?

**Comment by AaronDonahue** [comment]
Ahh yes, that fail may be a red-herring.  I verified that my submodules are up to date, I still get a failure with test-all-scream, but a different error.  I'm going to run gather-all-data to see if I get the same behavior.  I'll report back when that finishes.

**Comment by bartgol** [comment]
@AaronDonahue I agree with jeff that the error you posted was due to modules not being correctly updated. As for your other errors, test-all and gather-all should do the same thing (provided you invoke test-all in the same way in both cases).

**Comment by bartgol** [comment]
@AaronDonahue I just noticed your comment regarding the cori entry in the mach specs file. I think that when we added support for cori in that dictionary, we _assumed_ that we'd be running everything from cime. If you try to run test-all and gather-all directly, that won't work.

I am inclined to change that entry. Maybe we should have two dictionaries, `machine_specs` and `machine_specs_cime_run`. @jgfouca what do you think? It would be nice for a user to be able to manually run testing script on our repo, without the need of wrapping it inside some cime call just to get the env setup...

**Comment by jgfouca** [comment]
@bartgol if the CIME env is what we want for a machine, then we should use the `get_case_env` tool:

```
    # Get the default CIME env and load it into your current shell env 
    > eval $(./get_case_env)
```

**Comment by bartgol** [comment]
Sure, but what if someone wants to just run test-all-scream on cori? There's no case in that case (no pun intended).

**Comment by jgfouca** [comment]
get_case_env does not need an existing case, it is a standalone tool.

**Comment by bartgol** [comment]
Ah, cool! I'm assuming you pass to it the same args (at least the one that impact env) that you would give to `create_newcase`?

**Comment by jgfouca** [comment]
You can give it a case if a default case is not what you want.

**Comment by bartgol** [comment]
Don't I need to at least specify the machine/compiler?

**Comment by jgfouca** [comment]
Not if machine defaults are what you want. CIME can already probe machine via hostname.

**Comment by bartgol** [comment]
Ah, ok, then I guess default might work.
