### ISSUE TITLE
View bounds error on Compy

### ISSUE THREAD

**Issue by singhbalwinder** [E3SM-Project/scream#445]
@pressel and I got this error on Compy with both GCC and Intel compilers. The error is:
```
ExecSpace name: OpenMP
ExecSpace initialized: yes
sizeof(Real) 8 avx -AVX512F-AVX2-AVX compiler Intel FPE off #threads 4
terminate called after throwing an instance of 'std::runtime_error'
  what():  View bounds error of view  ( -1 < 80 )
Traceback functionality not available
```
I get this error if I run `p3_tests`( `shoc_tests` runs fine)

I used totalview and here are my findings (which may not be that useful):

The failure always seem to occur differently. I am noting here the consistent behavior. During p3_tests, failure occurs in the call to run_bfb_p3_main  which then calls P3F::p3_main. The code dies just calling this function while working on the arguments. That is, it doesn’t actually goes into p3_main function. While working on the arguments, it calls the following function in Kokkos_View.hpp :
```
template< class RT , class ... RP >
  KOKKOS_INLINE_FUNCTION
  View( const View<RT,RP...> & rhs )
    : m_track( rhs.m_track , traits::is_managed )
    , m_map()
    {
      typedef typename View<RT,RP...>::traits  SrcTraits ;
      typedef Kokkos::Impl::ViewMapping< traits , SrcTraits , typename traits::specialize >  Mapping ;
      static_assert( Mapping::is_assignable , "Incompatible View copy construction" );
      Mapping::assign( m_map , rhs.m_map , rhs.m_track );
    }
```
The above function is called twice and the code dies after the second call. It seems to take different routes after this, if I run it again and again. 

[Here](https://gist.github.com/singhbalwinder/1fdfc6021a6d316b06ae32dd8340d8b5) is a gist file which has the trace from gdb (thanks @ambrad !)

**Comment by singhbalwinder** [comment]
@jgfouca : I tentatively assigned it to you but please feel free to reassign.

**Comment by bartgol** [comment]
@singhbalwinder Does the error appear also when using Serial as kokkos backend? Sometimes it's hard to debug openmp code, due to the context switch of the threads. If this error appears only with more than 1 thread, we might not be able to reproduce it with Kokkos::Serial, but if it happens also with 1 thread, we could probably debug this in Serial.

The error message suggests we're trying to either a) access a view that has not been allocated or b) access a view as if it was of rank N, while it is indeed of rank M<N. However, the backtrace from gdb points to a line that seems completely innocuous. Again, it might be that the thread context in openmp is causing gdb to not show the backtrace we're interested in. Being able to run with Serial device would help.

**Comment by singhbalwinder** [comment]
Thanks @bartgol . I compiled the code in serial and got the following error:
```
/qfs/people/sing201/scream/2srccode/scream/components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp:564: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  View bounds error of view  ( -1 < 80 )
  Traceback functionality not available
```
Which is similar to what I got before except there is one additional error which is not very explicit.
I ran `p3_tests` on prompt directly (not via `ctest`) and got the following:
```
$ ./p3_tests
ExecSpace name: Serial
ExecSpace initialized: yes
sizeof(Real) 8 avx -AVX512F-AVX2-AVX compiler GCC FPE off #threads 1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p3_tests is a Catch v2.9.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
p3_main
-------------------------------------------------------------------------------
/qfs/people/sing201/scream/2srccode/scream/components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp:564
...............................................................................

/qfs/people/sing201/scream/2srccode/scream/components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp:564: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  View bounds error of view  ( -1 < 80 )
  Traceback functionality not available

===============================================================================
test cases:     45 |     44 passed | 1 failed
assertions: 111471 | 111470 passed | 1 failed

terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos allocation "dnu" is being deallocated after Kokkos::finalize was called

Traceback functionality not available

[compy01.pnl.gov:mpi_rank_0][error_sighandler] Caught error: Aborted (signal 6)
Abort (core dumped)

```
[Here](https://gist.github.com/singhbalwinder/e6c0aea61cc76d63e684bf6e5717d548) is the new GDB output.

**Comment by bartgol** [comment]
Errors of the form `Kokkos allocation "blah" is being deallocated after Kokkos::finalize was called` are relatively innocuous. Basically, some views are not cleaned up before we exit the program.

I don't know what that view is, or how p3 works. But my guess is that there is some structure holding a bunch of views, which is not correctly "cleaned up". At the very least, it is not cleaned up _when some test fails_. Perhaps the unit test calls a cleanup routine only at the end of the `TEST_CASE` section, but since a test fails (and Catch throws an exception), we never get there, and the cleanup never happens.

As long as we don't see those errors when tests pass, it's not that bad.

**Comment by bartgol** [comment]
Unfortunately, I think the backtrace from gdb is only showing the error relative to the view not being deallocated. I think this is because someone is throwing an exception in a destructor (which is usually *not good*). Unfortunately C++ does not support exception _while unwinding another exception stack_, so I think the stack of the original exception (the bounds error) gets lost.

The only thing to do is to make gdb break when exceptions are thrown:

```
$ gdb ./p3_tests
...
(gdb) catch throw
(gdb) run
```

This should stop the execution when the first exception is thrown (hence, before the second exception messes up the stack), so you can see where it is generating.

**Comment by singhbalwinder** [comment]
For some reason, I am not able to run gdb with p3_tests. The trace I posted is from the core file (with help from @ambrad) using gdb:
```
gdb p3_tests core.xxx
```
I am working with Compy support to figure out the gdb issue. I will try your suggestion when I get gdb working on Compy.

**Comment by ambrad** [comment]
Just looked at this. Looks like we can reproduce the issue on any machine.

@jgfouca or @bartgol, we probably should add `-D Kokkos_ENABLE_Debug=On` to all the debug builds. Maybe we had that at some point or Kokkos did that automatically based on CMake build type, but it's definitely not happening automatically at present.

The failing code is [linked here](https://github.com/E3SM-Project/scream/blob/cb83c93904f781ea1b4c4607716554f82b160b0b/components/scream/src/physics/p3/p3_functions_rain_sed_impl.hpp#L126). The `+1` is the problem.

In the [original F90](https://github.com/E3SM-Project/scream/blob/cb83c93904f781ea1b4c4607716554f82b160b0b/components/cam/src/physics/cam/micro_p3.F90#L3505), the `rflx` array is 1 larger than other arrays. Probably in the C++ code rflx needs to be 1 larger, too, with the usual pack arithmetic applicable here.

**Comment by singhbalwinder** [comment]
Thanks @ambrad ! In my totalview session, I found that exception is thrown at:
`const auto flux_qx_pk = index(sflux_qx, range_pack-1);` line in `p3_functions_rain_sed_impl.hpp`, which look very similar to what you have mentioned.

**Comment by ambrad** [comment]
Right. The exception is thrown at the line you mention b/c the line I linked sets up an index range that includes one out-of-bounds index.

**Comment by ambrad** [comment]
@bartgol @jgfouca one little detail: we need `-D Kokkos_ENABLE_Debug=On` in a build with pack size > 1, so FPE off, CMake build type Debug, and Kokkos_ENABLE_Debug=On. That is likely missing from the AT and nightlies. I suggest just adding Kokkos_ENABLE_Debug=On, CMAKE_BUILD_TYPE=Debug to one of the current pack>1 builds.

**Comment by bartgol** [comment]
@ambrad good catch! Our machine files all set kokkos debug features to OFF. We should just modify the test-all script, to overwrite kokkos debug cmake options. CMAKE_BUILD_TYPE is already set to debug. But we need, as you said, to enable kokkos debug (and we might have to explicitly turn on kokkos bounds check, I forgot whether kokkos debug turns them on or not, I suspect not).

**Comment by jgfouca** [comment]
@ambrad , I see this in the kokkos cmake integration file:

```
  # We want Kokkos to be in debug mode if the host project is in debug mode. This is a bit hacky                                                                                                                                                
  # since we can't use Kokkos_GMAKE_DEVICES yet.                                                                                                                                                                                                
  set(NO_DEBUG_ARGS Volta70 Pascal60)
  if (CMAKE_BUILD_TYPE_ci STREQUAL "debug" AND NOT Kokkos_ARCH IN_LIST NO_DEBUG_ARGS)
    set(Kokkos_ENABLE_DEBUG TRUE)
  endif()
```

So, it should be on already. If not, there's a problem.

**Comment by bartgol** [comment]
@jgfouca your point makes me think that the KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK needs to be explicitly set to ON.

Side question: why not enabling kokkos debug for GPU builds?

**Comment by jgfouca** [comment]
@bartgol , I wish I could remember the details. I think it just didn't work?

**Comment by bartgol** [comment]
It might be worth trying again, and see if we get any error. I think if it was something intrinsic to Kokkos, they would disable it already internally to kokkos. Maybe we were doing something wrong, and maybe it got fixed at somepoint.

**Comment by ambrad** [comment]
I think there's a capitalization issue: should be `Kokkos_ENABLE_Debug` not `Kokkos_ENABLE_DEBUG`, at least in our submodule checkout of Kokkos.

**Comment by jgfouca** [comment]
thanks @ambrad , let me confirm that that's the issue and I'll make a PR.

**Comment by bartgol** [comment]
I think the version of kokkos we use still supports `KOKKOS_BLAH`, while the new ones want `Kokkos_BLAH`. Even stuff like `KOKKOS_ARCH:STRING=SKX` is no longer good with a newer kokkos, where they have individual variables for each arch.

**Comment by jgfouca** [comment]
@bartgol , it doesn't appear to work at all. I just did a debug build on melvin and:

```
-- ****************** Kokkos Settings ******************
-- Execution Spaces
--   Device Parallel: None
--     Host Parallel: OpenMP
--       Host Serial: Serial
-- 
-- Architectures:
--     None
-- 
-- Enabled options
--   KOKKOS_ENABLE_SERIAL
--   KOKKOS_ENABLE_OPENMP
--   KOKKOS_ENABLE_LIBRT
--   KOKKOS_ENABLE_PROFILING
--   KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION
-- 
-- Final kokkos settings variable:
--   env;KOKKOS_CMAKE=yes;KOKKOS_SRC_PATH=/home/jgfouca/scream/externals/kokkos;KOKKOS_PATH=/home/jgfouca/scream/externals/kokkos;KOKKOS_INSTALL_PATH=/usr/local;KOKKOS_ARCH=None;KOKKOS_DEVICES=OpenMP,Serial;KOKKOS_DEBUG=no;KOKKOS_OPTIONS=aggressive_vectorization,disable_deprecated_code,disable_dualview_modify_check;KOKKOS_USE_TPLS=librt;KOKKOS_CXX_STANDARD="c++11"
```

**Comment by bartgol** [comment]
So you passed `-c KOKKOS_ENABLE_DEBUG=ON` to test-all? I think they may have a problem printing the option, but the option might be there. If you look at `kokkos_options.cmake`, they only check the suffix `Debug` when it's time to print enabled options, but the name of the option has an uppercase suffix (DEBUG).

You should check in `KokkosCore_config.h` whether the KOKKOS_ENABLE_DEBUG macro is defined.

**Comment by jgfouca** [comment]
Fix coming
