### ISSUE TITLE
[SHOC] Machine-level rounding change produces large differences in single-precision calculation.

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/scream#455]
According to @PeterCaldwell , @ambrad reported an instance in which code changes to SHOC that produce machine-level changes end up yielding answers with significantly larger changes when compiled and run using single precision.

I'm not sure we have any more information than this at the moment. Peter suggested that we try to reproduce this issue by introducing a machine-level ("epsilon") change to something in SHOC--a constant, perhaps--and looking at differences in the computed solutions between the unchanged and changed code. The differences could be compared using `shoc_tests` as documented in the Testing section on [this page](https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/925502063/SHOC+Performance+Portable+Code+Conversion). Briefly:

1. Run `shoc_tests` without the change and look at the results. You can generate Python scripts to write out plots. The scripts embed the solution data, so you can also use them for direct comparisons.
2. Make a change by adding `epsilon` to a physical constant or something else that gets used by SHOC.
3. Rerun `shoc_tests` and compare/contrast the new and original results.
4. ???
5. Profit!

**Comment by bogensch** [comment]
Why not change an instance of x**2 to x*x?  An example of where this could be done is in:

https://github.com/E3SM-Project/scream/blob/5f10b6eac80483dc8153f64cd5e9c7988c868c59/components/cam/src/physics/cam/shoc.F90#L2971-L2981

could change ugrad**2 to ugrad*ugrad on line 2979.

**Comment by jeff-cohere** [comment]
I can take a stab at this on Thursday or Friday if no one else gets to it.

**Comment by PeterCaldwell** [comment]
That would be great - I suspect nobody else will.

**Comment by PeterCaldwell** [comment]
Heads up - I just made this change on a CPU machine and it was BFB. I have a vague sense that it won't be on GPU, which I think is what we want...

**Comment by jeff-cohere** [comment]
Hey Peter. Are you saying that this error growth was only observed on a GPU machine? If so, that's worth noting in the description.

**Comment by ambrad** [comment]
The issue, if it exists, has nothing to do with GPU; SHOC doesn't run on the GPU yet. The issue is based on observing SP vs DP output in, e.g., https://github.com/E3SM-Project/scream/pull/390

**Comment by jeff-cohere** [comment]
Thanks for the context, @ambrad . That makes sense.

**Comment by AaronDonahue** [comment]
@jeff-cohere , now 3 years later and running on GPU's is it safe to say this is no longer an issue we need to track?

**Comment by jeff-cohere** [comment]
Yes, I think we're all good here.
