### ISSUE TITLE
Reorganize top-level P3 interface to use structs, not individual variables.

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/scream#465]
Here's the conversation surrounding this task:

https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/1594786870/Pass+Structs+Not+Vomit?focusedCommentId=1621262995#comment-1621262995

Briefly, we're introducing a number of structs to gather input/output data for use with `p3_main`:

+ `P3PrognosticState: qc, nc, qr, nr, th, qv, qitot, qirim, nitot, birim`

+ `P3DiagnosticInputs: ncnuc, naai, qc_relvar, icldm, lcldm, rcldm, pres, dzq, pdel, exner`

+ `P3DiagnosticOutputs: mu_c, lamc, cmeiout, prt_liq, prt_sol, diag_effc, diag_effi, diag_rhoi, prain, nevapr, prer_evap, rflx, sflx`

+ `P3Infrastructure: dt, it, its, ite, kts, kte, log_predictNc, col_location`

+ `P3HistoryOnly: iq_ice_exchange, vap_liq_exchange, vap_ice_exchange`

This task consists of the following steps:

1. Clean up the p3_main function interface (and its callers) to remove variables we don’t actually use and to order the variables according to their grouping into the above structs.

2. Clean up the boilerplate code to expect structs rather than individual variables.

3. Prepend the appropriate “<struct_name>.” in front of all non-local variables within the actual `p3_main` code.

4. Modify `p3_main_unit_tests.cpp` and `p3_run_and_cmp.cpp` (the only functions which call `p3_main`) to pass structs.

**Comment by jeff-cohere** [comment]
One detail of the implementation: because we're about the jettison the Fortran version of P3, these changes will be confined to the C++ P3 interface (unless we discover issues with this approach). Comments are welcome (especially from folks like @bartgol , who have weighed in on this topic with detailed technical considerations).

**Comment by jeff-cohere** [comment]
The following variables are currently passed to `p3_main` but aren't present in any of the above structs:

+ `diag_ze` (equivalent reflectivity)
+ `diag_vmi` (mass-weighted fall speed of ice)
+ `diag_di` (mean diameter of ice)
+ `lamc`(size distribution slope parameter for radiation)
+ `pratot` (accretion of cloud by rain)
+ `prctot` (autoconversion of cloud to rain)

I believe these are all output variables. Does this mean that we don't actually end up using these variables in SCREAM? Or is there an oversight in here?

@PeterCaldwell @AaronDonahue

**Comment by bartgol** [comment]
You will also need to adapt the `atmosphere_microphysics.*pp` files, so that they call the new p3 interfaces. Some of those structs can probably be setup once and for all (with views set in them as soon as fields are passed to P3Microphysics with `set_required_fields_impl` and `set_computed_fields_impl`). Others, like P3Infrastructure, will likely need to be updated at every call of `P3Microphysics::run(..)` (at least the dt value, some other stuff might be constant over the simulation and set at init time).

**Comment by jeff-cohere** [comment]
Hey @bartgol , I'm ready to make changes to the atmosphere_microphysics stuff. Do you have a recommended `cmake` command with which I can configure all this stuff so it gets built, and so `ctest` ensures that any related tests pass?

**Comment by bartgol** [comment]
I don't think there's any cmake specific machinery that needs to happen. However, now that I look at atmosphere_microphysics.cpp, I notice it was still using the f90 interface to p3. Maybe we should keep the change to that class for a second PR. Hooking up P3xx to the AD might take a few tests/iterations.

**Comment by jeff-cohere** [comment]
That sounds fab to me!
