### ISSUE TITLE
Provide a Python interface to SCREAM P3 microphysics and SHOC macrophysics

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/scream#467]
We've been discussing the need for an environment with which we can "pick at" the low-level functions within p3 and SHOC in SCREAM. This is especially needed at the moment because we're trying to chase down bugs in either or both of those packages that are preventing global simulations from running.

There are short-term solutions to this problem, but the need for an easy way to fiddle with physics-related functions is going to remain even after we address our short-term issues. The goal of this task is to provide an optional parameter to our build system that provides a standalone Python module that exposes our low-level P3 and SHOC subroutines.

Because we're getting ready to jettison the Fortran version of P3, this task will focus on exposing our C++ implementation of P3. SHOC only exists in Fortran at this point, so the initial delivery of a SCREAM physics Python module will make use of the Fortran implementation of SHOC.

**Comment by PeterCaldwell** [comment]
Status: We're using f2py to do this for F90 codes. We still need a solution for C++. Jeff is working on that at very low priority. A confluence page onf the f2py solution is at https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/764739624/Calling+SCREAM+functions+from+python.

**Comment by bartgol** [comment]
I don't think this is still on our todo list, so I'm closing. Feel free to reopen if that's not true.
