### ISSUE TITLE
Blake CI job reported 'PASS' even if the job didn't really run

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#474]
Not sure if this is a fluke, but I want to open an issue for tracking purposes. Even if we don't find anything wrong, if it happens again, it will be easier to find a log of when it happened before.

During the testing of #471, the AT job on blake had some issue with slurm, and could not run the tests. However, our testing scripts reported a PASS. This can potentially be quite dangerous (assuming there's a bug in our scripts, and it wasn't just a misterious glitch).

Here's the end of blake's log for that job:

```
+ SUBMIT=
+ BASELINES_DIR=AUTO
+ ./scream/components/scream/scripts/gather-all-data './scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -p -i -m $machine ' -l -m blake
srun: error: task 0 launch failed: Slurmd could not execve job
Starting analysis on blake with cmd: cd /home/jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/scream/components/scream && module purge && module load openmpi/2.1.5/intel/19.1.144 git/2.9.4 cmake/3.12.3 && export PATH=/ascldap/users/jgfouca/packages/Python-3.6.8-blake/bin:$PATH CTEST_PARALLEL_LEVEL=48 && true && OMP_PROC_BIND=spread srun ./scripts/test-all-scream --baseline-dir AUTO $(which mpicxx) -c EKAT_DISABLE_TPL_WARNINGS=ON -p -i -m blake 
RUN: cd /home/jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/scream/components/scream && module purge && module load openmpi/2.1.5/intel/19.1.144 git/2.9.4 cmake/3.12.3 && export PATH=/ascldap/users/jgfouca/packages/Python-3.6.8-blake/bin:$PATH CTEST_PARALLEL_LEVEL=48 && true && OMP_PROC_BIND=spread srun ./scripts/test-all-scream --baseline-dir AUTO $(which mpicxx) -c EKAT_DISABLE_TPL_WARNINGS=ON -p -i -m blake 
FROM: /home/jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake
Completed analysis on blake
Sending e-mails to: jgfouca@sandia.gov
Build was marked for publishing on https://software-login.sandia.gov/hudson/
Finished: SUCCESS
```

**Comment by bartgol** [comment]
So slurm documentation says that srun exit code is whatever exit code was provided by the program launched with srun. However, I cannot find anything saying what error codes srun reports if the error happens inside the slurm framework (like in the case of our job, where likely there was a comm issue between head node and compute node).

**Comment by jgfouca** [comment]
We could potentially handle this similarly to E3SM. A case cannot be considered to be a PASS until its TestStatus file has PASS for all the key test phases. We could use sentinel files in test-all-scream to achieve a similar thing.

**Comment by bartgol** [comment]
This is quite annoying. I can't believe srun does not return a non-zero exit code when internal errors to slurm happen.

The hard thing is that I can't really reproduce the problem (unless I can come up with a command that generates internal slurm errors, which I doubt).

**Comment by bartgol** [comment]
I guess we could redirect srun output to a file, grep for 'OVERALL STATUS: PASS` (which is what test-all prints), then cat the output file again (so it can be shown on the jenkins log).

**Comment by PeterCaldwell** [comment]
@bartgol - did we ever solve this? If so, can you close it?

**Comment by bartgol** [comment]
We never really tackled this. To be fair, the chance of this happening are relatively low. On the other hand, if it does happen, we risk that a potentially buggy branch is labeled as good-to-merge.

To be honest, I'm not too concerned about this. I'd be ok closing this and forgetting about it. @jgfouca , what do you think?

**Comment by jgfouca** [comment]
The consequences of a false PASS are high, so I'll take a look at this. I can add some additional tests to the standalone tests and maybe add some additional protections to test-all-scream/gather-all-data.

**Comment by bartgol** [comment]
The issue is that these false PASS are probably hard to reproduce. I tried to request a partition that did not exist, and got an exit code 1, and gather-all caught it. I'm not sure what happened in this case. Honestly, I would not spend more than an hour or so trying to investigate this.

**Comment by jgfouca** [comment]
Now that scream/scripts has its own testing, I don't think there's much more we can do here.
