### ISSUE TITLE
For CIME build YAML input file is not strictly a runtime option

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#506]
For the CIME build, when issuing the command `case.submit` to resubmit a run (namely an F2000-SCREAM-SA run) the `scream_input.yaml` file in the `run/data` directory get overwritten.  Effectively making it not a way to control run time options.

**Comment by bartgol** [comment]
I thought `scream_input.yaml` (just like namelists) was generated during case.setup and case.build, allowing one to change values before the submit phase. @jgfouca is this normal or is something wrong with the way we generate `scream_input.yaml`?

**Comment by PeterCaldwell** [comment]
I've never figured out how our yaml input file gets generated, but it will be one of the main ways users interact with our code so deserves attention. We should discuss this in a telecon, but I can't figure out whether the physics telecon, the AD telecon, or maybe the all-scream telecon would be most appropriate. Do any of you have an opinion?

**Comment by jgfouca** [comment]
I see the problem, fix coming.

**Comment by AaronDonahue** [comment]
@PeterCaldwell , to answer your question, there is a default template stored in scream/data/scream_input.yaml.  That is copied to the run directory for use.

**Comment by jgfouca** [comment]
@AaronDonahue , yep. It's copied by the scream/cime_config/buildnml script. Since scream doesn't really use namelists like the other components, our buildnml is used for general setup stuff like this.

**Comment by AaronDonahue** [comment]
Could we have a similar paradigm as user_nl?  Where the default YAML file is copied to the case_scripts dir and then during `case.submit` the version from the case_scripts is copied to the run dir?

**Comment by jgfouca** [comment]
@AaronDonahue , can you clarify? I don't see anything happening with user_nl files in scream/cime_config/buildnml

**Comment by AaronDonahue** [comment]
@jgfouca .  I was thinking more in terms of the current paradigm in E3SM.  On the user end I have grown accustomed to the case_scripts directory always having the `user_nl_*` files in it.  And when I wanted to change a runtime option I would change the appropriate file there and it would then show up later when the namelist files were generated in the `run` directory.
Our treatment of YAML is different for sure.  But in some ways the scream_input.yaml is replacing the `atm_in` file.  In the current paradigm for the treatment of the YAML file I would need to change the values in the `run/data` directory, which is not intuitive to E3SM users.  I was wondering if we could set it up so like the `user_nl_cam` treatment, a default yaml file was generated in `case_scripts`, which could be adjusted for runtime options.  And have CIME copy that yaml file to `run/data`

**Comment by jgfouca** [comment]
@AaronDonahue , would you like to see a symlink to $rundir/data/scream_input.yaml somewhere accessible within your $casedir?

**Comment by AaronDonahue** [comment]
I honestly don't know what the best strategy is.  I guess I was thinking it would be easier to change runtime options if that change could be made in the case_scripts directory, which is where we tend to make all other changes (like run length, restart yes or no, etc.)  Instead of having to go into the `run/data` directory and change the YAML file there. 

A symlink would probably be perfect, and would be simpler than always copying the yaml from case_scripts to run dir.

**Comment by jgfouca** [comment]
ok, i'll see what i can do after #507
