### ISSUE TITLE
Manage randomization in unit test input better

### ISSUE THREAD

**Issue by jgfouca** [E3SM-Project/scream#550]
Some thoughts:
* Do we want different random (seed=sec since epoch) values every time the test is run?
* Or do we want repeatability? Even if we are running different subsets of tests? I think this would require every test to select a seed.
* Do we want a hybrid where we can get either of the above based on user input?

**Comment by bartgol** [comment]
Notice that catch can handle repeatability (we use the feature in homme unit tests). You can pass `--rng-seed N` to the executable, if you want to reuse the same random seed. Here's how we use it in homme:

```
      std::random_device rd; 
      using rngAlg = std::mt19937_64;
      const unsigned int catchRngSeed = Catch::rngSeed();
      const unsigned int seed = catchRngSeed==0 ? rd() : catchRngSeed;
      std::cout << "seed: " << seed << (catchRngSeed==0 ? " (catch rng seed was 0)\n" : "\n");
      rngAlg engine(seed);
```
Then:

```
$ my_test
seed: 798235639 (catch rng seed was 0)
...
$ my_test
seed: 2748672677 (catch rng seed was 0)
...

$ my_test --rng-seet 1984
seed: 1984
...
```

So the default behavior is to use the system headers to generate a random seed. But if something goes bad once every, say, 10 times, one can check what was the seed used for that bad run, and use it for debugging.

We should probably add a printout of the random seed in EKAT, in `ekat_catch_main.cpp`.

**Comment by PeterCaldwell** [comment]
Did we ever sort out the random seed question for creating random inputs for unit tests? If so, we can close this issue? @jgfouca ?

**Comment by jgfouca** [comment]
@PeterCaldwell , nope, I still need to do this.
