### ISSUE TITLE
[AD] Create a SCREAM::Context class

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#565]
Create a Scream::Context class similar to the Homme::Context class to store C++ objects that persist through the E3SM simulation.

We note that the rest of E3SM is run from F90.

**Comment by PeterCaldwell** [comment]
Is context really an accurate description? Wouldn't "Persistent" be a better descriptor?

**Comment by bartgol** [comment]
I think Context is a common name in this kind of situation.

**Comment by PeterCaldwell** [comment]
> I think Context is a common name in this kind of situation.
> 
> Edit: I mean in this kind of code situations.

Ok, that's fine. Just asking.

**Comment by bartgol** [comment]
This is done. See `src/mct_couplin/ScreamContext.hpp`.
