### ISSUE TITLE
Making changes to P3 is super hard

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#569]
Revamping evaporate_rain via PR #554 reminded me that making changes to P3 which require modifications to function argument lists is really hard. I don't think we can ask people outside SCREAM to do this - they will run screaming the other way. Are there things we could do to make this sort of task easier? Here are some thoughts:

- Changing the variables passed to evaporate_rain required changing 24 different files and took me a week. Most of these changes and most of my time was spent on the F90<=>C++ bridging. Working purely on the C++ side was actually quite pleasant. Maybe we shouldn't worry too much about changing our paradigm because we're going to quit supporting F90? Maybe we should insist on not sharing code until we abandon F90 to hide outsiders from the current complexity? Maybe we should internally try our hardest not to make any code changes until we can ditch the F90?
- A particular problem is that our testing suite won't compile at all until all of the boilerplate is implemented. This means you end up doing almost all of the coding before you can test anything. Lack of immediate feedback makes it much easier to make mistakes and means that you've forgotten what you did by the time you do start testing. I started by making changes in F90-P3 and testing them via E3SM runs and running P3 directly from python. Then I implemented all the interface stuff but didn't change the interior of the C++ evaporate_rain function and iterated until tests were running again and only failing where expected by evaporate_rain differences. Then I implemented the new C++ evaporate_rain implementation and only ran the evaporate_rain unit test until I got it to be BFB. Then I ran p3_main unit test and p3_run_and_cmp until they were BFB. Then I tinkered with the p3_standalone and p3_shoc_standalone AD tests. Can you think of any way I could have broken the coding down into smaller steps?
- Function interfaces are kind of brittle in the sense that the number of inputs and outputs is often hardcoded in unexpected places. Perhaps the Data struct for each process should all contain NUM_INPUTS and NUM_OUTPUTS variables so we can set this info just 1x. There are also a bunch of different versions of each function or its data with slightly different requirements on argument order or list of included variables which is hard to keep straight. I think Jim's recent improvements help with this, but it could be even better.

So - thoughts? I'm not sure if we should change anything, but asking if there's any low-hanging fruit here.

**Comment by jgfouca** [comment]
Yeah, we didn't invest much in encapsulation, so every detail is exposed at all levels. I think we have people thinking about how to bundle stuff into structs, which would help some. I will think on this since I'm trying to get us in a better situation with SHOC. We may need a code generator script.

**Comment by bartgol** [comment]
I have not developed anything in P3, so I don't really know what one has to go through for adding/modifying features.

I did look at the code a few times though, and it seemed to me that the functions are a bit entangled. In #478 I exposed some thoughts on this subject, but the discussion never led to constructive solutions.

As you said, taking away the f90 bridges seems to reduce the code complexity quite a bit, so it is possible that your frustration would go away when we drop f90 support.

**Comment by jgfouca** [comment]
@PeterCaldwell , @bartgol , proposal:

A python-based code generator script that uses the reference f90 file (micro_p3.F90 or shoc_p3.F90) to provide a database of basic subroutine info: name, args, arg types. The script will use that info to generate (or refresh (replace existing)):
* f90 -> cxx bridge subroutine (item in *_f.f90)
* cxx -> f90 bridge subroutine (item in *_c.f90)
* A guess at a likely CXX function sig in $phys_functions.hpp
* A blank implementation of the above sig in $phys_$funcname_impl.hpp
* All the $phys_functions_f90.hpp stuff:
  * _c decl
  * _f decl and blank implementation (might even be able to guess a reasonable impl)
  * *Data struct
  * UnitTest struct and blank BFB test

CLI:
```
./gen_cxx <subroutine-name> [--overwrite] [--limit-to-piece=<piece-name>] [--needs-to-launch-kernel]
```
In the above, `piece-name` could refer to any of the items in the list above.

As our understanding of what the best pattern is evolves, the script could evolve and contain this understanding.

I think this could have saved a lot of effort in the P3 port if it worked well. My one concern is that this script is covering up a flawed design which made the script necessary in the first place. Unfortunately, we haven't thought of any way to have all this testing and bridging without repeating the arg lists of converted subroutines in 10 or so places.

**Comment by bartgol** [comment]
@jgfouca How hard would that be? Do you think it is still worth the time, considering that f90 code is on life support? I don't have an opinion, just asking.

**Comment by PeterCaldwell** [comment]
Thanks for the proposal, Jim. We have talked about code for automatically creating this boilerplate in the past, but I never thought about using it to overwrite the old boilerplate when making changes. I think this would be very helpful.

Luca asks a good question about whether this is worth doing retroactively for P3. I'm on the fence about that. P3 is kind of problematic because it is the first thing we ported and the thing that we have the least confidence in... I suspect we will have to make a bunch of changes in the future... but maybe we could do that in the pure-C++ version.

I think that @singhbalwinder has already written a script to help him auto-generate boilerplate. I'd be curious to hear from him how much work it would take to make the script usable by all. @jeff-cohere has also been talking about a more general approach to automatic code writing, so I'd be curious to hear his view as well. 

Let's talk about this during today's physics porting meeting.

**Comment by jgfouca** [comment]
@PeterCaldwell , we should expect that a good code generator script should work for both P3 and SHOC (and any future conversion projects).

**Comment by jgfouca** [comment]
@bartgol , I don't think it would be too hard; I would guess about 8 hours of python coding.

**Comment by bartgol** [comment]
Would such script be easier if p3 didn't wrap all functions in a single file? I'm especially thinking about the p3_functions_f90.*pp files (though not wrapping all c++ fcns in a single file might have some minor benefits too).

**Comment by PeterCaldwell** [comment]
There's probably more work to do, but #611 does a lot. Closing for now.
