### ISSUE TITLE
Switch machine files, PR testing, and nightlies from bowman to other KNL platforms.

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#571]
The  "bowman" testbed at SNL will be decommissioned soon, so we need to make sure our testing is moved to alternative KNL machines before this happens.

**Comment by PeterCaldwell** [comment]
@bartgol - I think this is done, right? Would you mind closing?

**Comment by bartgol** [comment]
We never added a KNL testing machine though. We added mappy (AMD), but we should probably start some testing on a KNL testbed at some point...

**Comment by PeterCaldwell** [comment]
Ok. I thought we decided that just having a CPU machine (Blake) was sufficient and we didn't actually need a KNL machine (at least until we start getting mysterious fails on cori-knl but not elsewhere). We can keep this issue upen in case.

**Comment by bartgol** [comment]
I don't have a strong opinion. I don't think we use any KNL specific stuff (at least not explicitly) in scream, so _maybe_ it's ok to just test an intel compiler on SKX. Still, if we found a "friendly" testbed like bowman was, I would not be opposed to another AT build (since they run in parallel, it would not slow our CI down).

**Comment by bartgol** [comment]
I don't think we'll add a KNL test for AT or nightlies (except the cime testing on Cori, which is already in place, but uses different scripts). At least not anytime soon. I'm gonna close this.
