### ISSUE TITLE
[AD] Restructure SHOC-AD Interface to prepare for eventual fully C++ implementation

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#580]
The SHOC-AD interface is very old and was created before SHOC was fully implemented in SCREAM.  Now that there is a C++ to Fortran bridge to run in stand-alone mode it is possible to restructure the interface to put in place hooks that will facilitate a transition to fully C++ when it is possible.

**Comment by PeterCaldwell** [comment]
I think we shouldn't do anything on the SHOC-AD interface until SHOC is done and we can complete our final impl. I'm going to close this issue and create a new, more modern one.
