### ISSUE TITLE
[AD] AD-RRTMGP Interface

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#581]
Creating an issue to formalize this AD task.

Create the interface between the SCREAM-AD and RRTMGP.

**Comment by PeterCaldwell** [comment]
@brhillman - is there a PR for the AD-RRTMGP interface yet? If so, I'd suggest closing this issue since we can track progress via the PR. But maybe others think that's a bad idea?

**Comment by brhillman** [comment]
Addressed by #810
