### ISSUE TITLE
[AD] Eliminate CAM dependencies for CIME build of HOMME in SCREAM

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#582]
Formalizing this task as a git issue.

Bring in the infrastructure to build SCREAM with HOMMEXX active during a CIME build. 

This is a necessary first step before Issue #568 can be addressed.

Requires development to E3SM master and then an upstream merge to bring those changes into SCREAM.

**Comment by PeterCaldwell** [comment]
I think this is done, right @bartgol ?

**Comment by bartgol** [comment]
I think so? Closing.
