### ISSUE TITLE
[AD] Infrastructure to call SCORPIO from SCREAM

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#583]
Formalizing this task as a git-issue.

Establish the framework for calling scorpio routines from scream.  In particular the AD.  This task has a number of goals:

1. C++/Fortran bridges to call SCORPIO routines.  -DONE
2. Establish a SCORPIO class in SCREAM to manage all output streams. 
3. Establish a SCORPIO class in SCREAM to manage all input streams.
4. Hook up to scream-AD

**Comment by PeterCaldwell** [comment]
Implemented via #690 . Closing.
