### ISSUE TITLE
[AD] Timestamp helper functions

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#585]
The current simulation timestamp information (i.e. total seconds since start-date) is stored by the AD.  Some processes (specifically Radiation and IO) will need access to this information.

Task: Create a set of helper functions to allow processes to access the timestamp information in various formats, such as seconds, hours, days, months, year, days in year.

**Comment by AaronDonahue** [comment]
@jeff-cohere , would you be interested in taking up this task in the AD development?

**Comment by jeff-cohere** [comment]
Sure! Because I'm just getting started with the AD, can you point me to one or two relevant source files that show me the context in which this stuff would be used?

**Comment by AaronDonahue** [comment]
Excellent! I think @bartgol  is more knowledgeable about the timestamp infrastructure than I am.  So he may be able to chime in.  It looks like the timestamp we want query can be found in:
```scream/src/share/util/scream_time_stamp.hpp/cpp```

The AD is responsible for updating the simulation timestamp.  From the timestamp code it looks like a lot of the functionality is there.  I guess we just need to put in helper functions that allow an individual process to access the the time in the appropriate format.

**Comment by bartgol** [comment]
@jeff-cohere Feel free to remove/add/modify anything, of course. I did that class long time ago, and some things may not be even used (now or ever).

**Comment by AaronDonahue** [comment]
@jeff-cohere , for testing you can add a timestamp query to `scream/src/physics/p3/atmosphere_microphysics.cpp` and run the `p3_stand_alone` unit test.

**Comment by jeff-cohere** [comment]
Great. Thanks for the guidance!
