### ISSUE TITLE
Inconsistancy in P3 rimed mass and volume 

### ISSUE THREAD

**Issue by JS-WRF-SBM** [E3SM-Project/scream#592]
Throughout the P3 code, the routine `calc_bulkRhoRime()` may update the `in-cld` values of rimed mass (`qrim`) and rimed volume (`brim`). For consistency, especially at the sedimentation section, the `cell-avg` values needs to be corrected as well, for example:
```
call calc_bulkRhoRime(qitot_incld(k),qirim_incld(k),birim_incld(k),rhop)
qirim(k) = qirim_incld(k)*icldm(k)
birim(k) = birim_incld(k)*icldm(k)
```

**Comment by PeterCaldwell** [comment]
Thanks Koby! Addressed via #595
