### ISSUE TITLE
Can we slim down our restart files?

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#596]
@ambrad did nice work recently by removing the Q array from our restart file since it can be recalculated from Q_dp: https://github.com/E3SM-Project/E3SM/pull/3841. His success raises the question of whether we can further trim down our restarts. Below is a list (also courtesy of Andrew) of 3d variables in our scream-hr restarts. Does anyone see something we don't need? @brhillman - I have a vague notion you've looked at this before. I took a quick look but will need to dig in more to identify variables we can drop and to figure out how to drop them. Take a quick gander or dig in if you want to!

        double DTCORE(pbuf_00128, ncol) ;
maybe        double CLDO(pbuf_00128, ncol) ; --- I think this is CLD from prev which hasn't been used since CAM5?
        double PRER_EVAP(pbuf_00128, ncol) ;
        double RELVAR(pbuf_00128, ncol) ;
        double ACCRE_ENHAN(pbuf_00128, ncol) ;
yes        double QV_PREV(pbuf_00128, ncol) ;
yes        double T_PREV(pbuf_00128, ncol) ;
        double WTHV(pbuf_00128, ncol) ;
        double TKH(pbuf_00128, ncol) ;
        double TK(pbuf_00128, ncol) ;
        double tke(pbuf_00129, ncol) ;
        double kvh(pbuf_00129, ncol) ;
        double kvm(pbuf_00129, ncol) ;
Maybe?        double AST(pbuf_00128, ncol) ; --- is currently max(AIST,ALST) but might change in future?
yes        double AIST(pbuf_00128, ncol) ;
yes        double ALST(pbuf_00128, ncol) ;
yes        double QIST(pbuf_00128, ncol) ;
yes        double QLST(pbuf_00128, ncol) ;
no        double CONCLD(pbuf_00128, ncol) ; --- not needed for HR compset but is for LR compsets
yes        double CLD(pbuf_00128, ncol) ;
        double RAD_CLUBB(pbuf_00128, ncol) ;
        double DGNUM(pbuf_00384, ncol) ;
        double DGNUMWET(pbuf_00384, ncol) ;
no?        double DP_FLXPRC(pbuf_00129, ncol) ;
no?        double DP_FLXSNW(pbuf_00129, ncol) ;
no?        double DP_CLDLIQ(pbuf_00128, ncol) ;
no?        double DP_CLDICE(pbuf_00128, ncol) ;
        double QRS(pbuf_00128, ncol) ;
        double QRL(pbuf_00128, ncol) ;
        double ICIWP(pbuf_00128, ncol) ;
        double ICLWP(pbuf_00128, ncol) ;
        double T_TTEND(pbuf_00128, ncol) ;

**Comment by mt5555** [comment]
Some notes on restart:

The restart happens in cam_run4().  For other reasons, the time stepping loop in CAM should be thought of as a loop over: atm_import()(fluxes), cam_run2(), cam_run3(), cam_run4(), cam_run1().
A restart run will call cam_run1(), and then enter the above loop.   

Thus I think we can conclude:  
All input to cam_run1() needs to be output to the restart file.  This includes:
    - prognostic variables: handed by dycore restart
    - fluxes:  handled by cam.rs restart
It's the other variables which are tricker.  In particular:
   - fluxes that might be modified by cam_run2() and used in cam_run1.    
   - other variables modified in cam_run2() and used by cam_run1().  
  -  some physics (those with state "memory"?) have their own restart: chemistry, prescribed ozine/ghg/aero/volcano
   - other situations?  

 Some examples from above:

DTCORE:   set in tphyasac(), used in tphysbc(), so needs to be on restart file
but it's a diagnostic, so it could be removed if not an active output variable

dp_cldlic, dp_cldice: these appear to be set to zero and never used.  They are set to zero in cam_run1(), so even if they are used, probably dont need to be output for restart.

T_TTEND:  initialized in cam_run1(), output in cam_run2() , so I dont think this needs to be on the restart file.

**Comment by AaronDonahue** [comment]
@PeterCaldwell , I think we already did this for EAM right?  And EAMxx doesn't have this problem, so can this issue be closed?

**Comment by PeterCaldwell** [comment]
This looks like v0 stuff. V1 restart looks to be in good shape.
