### ISSUE TITLE
Shoc tests failing in master

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#600]
The error looks like the following:

```
/shoc/tests/shoc_pdf_compute_qs_tests.cpp:79: FAILED:
  REQUIRE( SDS.qs1 < qs1_test1 )
with expansion:
  0.622 < 0.622
```

@singhbalwinder and @tcclevenger first reported this kind of failure. @AaronDonahue also noticed it in LLNL machines nightlies, and I was able to reproduce it on my laptop. The error occurs not every time, which pointed to uninited memory. Valgrind seemd to confirm the suspicion, so the task is now to go up the update-tree and see which of the variables contributing to qs1 is not initialized.

**Comment by bartgol** [comment]
Actually, I am now able to reproduce the error _at every single run_.

**Comment by bartgol** [comment]
@bogensch it appears that `shoc_assumed_pdf_compute_liquid_water_flux` uses `w_first` in its formula, but that variable is never inited in `shoc_pdf_compute_liqflux_tests.cpp`. I added a line initing it, and it removed valgrind error.

I don't know what's the correct value to pick though, so I can't fix the test. Could you take a look at it?

**Comment by bogensch** [comment]
@bartgol thanks for reporting.  I will fix this.

**Comment by singhbalwinder** [comment]
Thanks @bartgol for looking into it and finding the issue.
