### ISSUE TITLE
Create macro for baseline-type tests to run with cprnc

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#618]
The macro should do something like this:

```
macro (ScreamCreateBaselineTest [args])
   # Create test that run the exec
   ScreamCreateUnitTest (args)

   # Create cprnc test
   add_test (NAME ${test_name}_cprnc COMMAND cprnc [args like out file and baseline file])
   set_test_properties (${test_name}_cprnc [set dependency on the above test]) 
endmacro()
```
We could also avoid using `ScreamCreateUnitTest`, if need be. In fact, likely, the normal run just needs to run; no catch2 logic in there, and no threading/mpi combinations neede. This can of course be achieved with `ScreamCreateUnitTest` (e.g., with option `EXCLUDE_MAIN` or by not specifying threading/mpi configs), but maybe it's just easier to do `add_executable+add_test` straight into the macro. These are impl details, we can nail them down as we write the macro.

Note: this feature requires to make sure that cprnc is compiled. In CIME builds it should always be, in standalone builds, it might require us adding cprnc subdir. This should be done similarly to how ekat builds submodules, with a `BuildCprnc` macro that allows for 'lazy-add-subdirectory'.

**Comment by PeterCaldwell** [comment]
@bartgol - I don't understand the context for when/why we would need cprnc. Our C++ unit tests compare variables directly and existing CIME tests already know how to use cprnc... What am I missing?

**Comment by bartgol** [comment]
Right now, you're right, we don't need this. My original thought was to do some netcdf file comparison once we have nc output. This would basically do what homme's tests do: run the test, saving some nc output files, and upon (successful) execution, check that the two nc files contain the same data.

I guess we could close this for now. Once scorpio output is integrated, we can set up some tests (standalone scream, no cime) that run and save some output files. Once that's working, we can think of whether (and how) to add cprnc comparison tests on those outputs.

**Comment by PeterCaldwell** [comment]
Ok, that makes sense. I think this is part of a bigger task of "revamp scream tests to take advantage of netcdf output" which we will tackle once scorpio is working for us. I'm inclined to close this issue and not open the "revamp tests" issue because I think it will be obvious/hard to forget that we want to use netcdf files for testing once we can.
