### ISSUE TITLE
Create separate FieldTag's for level midpoint and level interface

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#648]
This helps distringuishing fields defined at level midpoints and fields defined at level interfaces.

Notice that these are already "different", even with the current VERTICAL_LEVEL tag, due to the different extent in the last dimension. However, having a different tag helps to reduce typos, and increases the differences between the two fields.

**Comment by bartgol** [comment]
I'm bumping up the priority because I think this might be very useful (if not necessary) for I/O. In particular, when specifying fields dimensions in nc files, we'll need something like `LEV` and `ILEV`, and it is just easier if one can simply query the FieldTag's of a 3d field, to figure out which one it is.

@AaronDonahue

**Comment by AaronDonahue** [comment]
Agreed.  This shouldn't be too hard to implement either.
