### ISSUE TITLE
[AD] Clean up the field declarations in the ZM interface and use universal saturation vapor pres function

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#698]
Since ZM is not a part of the main scream physics we delayed a clean-up step for the ZM-AD interface.  Two tasks remained which will need to be done in the future:
1. The fields as declared need to have the proper units assigned, and an audit of if they are IN, OUT and IN/OUT type variables.
2. ZM as implemented in SCREAM uses a hardcoded version of the saturation vapor pressure calculation taken from an older version of P3.  Now that there is a universal saturation vapor pressure function, ZM should use that instead.

**Comment by bartgol** [comment]
Since we're not working on ZM in scream (strictly speaking), and since ZM has probably fallen out of sync with the AD infrastructure, I'm gonna close this for now. If someone wants to bring ZM back to life, it's relatively obvious that they need to do some changes...
