### ISSUE TITLE
[AD] Implement CF-Compliance Checking in Field Repo

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#700]
Implement the infrastructure to check all newly registered variables in the field manager against the CF compliant dictionaries. Note that PR #757 makes the first step towards this goal by creating a _standalone_ tool that checks if a name is in the CF database but does not implement _online_ checking.

As a developer tool, establish a script or executable which can parse the CF compliant dictionaries and return possible long-name strings given a set of inputs. For example, if the developer wants a variable and isn't sure what the name should be, but does know the units are in Pa, query for all variables with unit=Pa.  Or that the variable is related to pressure, sure for instances of the string "pres" or "pressure".

This is step 2 of getting CF compliance in SCREAM.

Addresses #527 , #528 and  #699

**Comment by PeterCaldwell** [comment]
To be clear, I don't see CF naming as a top-tier priority right now. I'd rather finish our work getting theta dycore working with the AD, getting P3 working with the AD, getting rad working with AD, getting IO working, and getting surface coupling done. Only then do I think we should crack this CF task open. I just don't want to put more balls in the air than we need to...

**Comment by PeterCaldwell** [comment]
I think PR #757 partially addresses this issue. Should this issue be revamped (or closed and replaced with a more targeted issue) to reflect the current reality? @jeff-cohere , @bartgol , @AaronDonahue

**Comment by jeff-cohere** [comment]
Yeah, to be honest, I'm not sure what we decided about how much validation happens within the Field Repo, as opposed to developers just using the standalone tool. But either way, the tool is written in C++ (in part to allow the Field Repo to use the same validation code, if we choose to go that route). So I think we can close this in favor of a narrower task.

**Comment by bartgol** [comment]
I think that #757 didn't complete this issue. This issue is about having a _runtime_ check of fields names during the registration process. That PR created a script that developers can use during development in order to query the database. That query _can_ be used to find out the CF name that is close enough to your particular variable, but also does more.

This task is to ensure at runtime that names are CF compliant, which is I think different.

**Comment by PeterCaldwell** [comment]
Ok, I updated the initial comment on this issue to clarify the distinction between offline and runtime checking.
