### ISSUE TITLE
Get rid of SE_NodeBased grid type

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#703]
That grid type is basically implementing the same thing as `MeshFree`. I propose to make SEGrid to _always_ be what we now call `SE_CellBased` type, and unify MeshFree and SE_Node_Based. In particular:

- GridType should contain `Undefined, SE, Point`, with the latter replacing MeshFree.
- SEGrid should just be of type SE, and always store elem/gauss-pt information (like the SE_CellBased currently does)
- Rename `SimpleGrid` into `PointGrid`, reflecting the type `Point` in `GridType`.

This will help keep code duplication low, and the code clearer and cleaner.

**Comment by jeff-cohere** [comment]
@bartgol : this is finished, right?

**Comment by bartgol** [comment]
Done in #716
