### ISSUE TITLE
ERROR: validate: tau/ssa values out of range -- all on same KNL compute node nid05683?

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#724]
We've been seeing an error come up with our ne1024 runs on cori-knl.
```
ERROR: validate: tau values out of range
or
ERROR: radiation_utils: validate: ssa values out of range
```
The error doesn't always happen and if it does, it doesn't happen at the same stage of the code -- once it failed with this error before reaching any ATM steps, but typically we simulate many ATM steps before this error.

I have 5 such examples of this with scream repo and ne1024 (most 1536 nodes, but one was 3072 nodes). The dates of when I launched the jobs range from late May to early November.

The suspect compute node is `nid05683`

I've not yet verified how often this same node is used for runs that do NOT hit the error. 

```
s13-may26/f.ne1024pg2.s13-may26.DY1.n1536p24576t16x441141.24s.nr/run/e3sm.log.31161467.200527-093000: 7436:  ERROR: radiation_utils: validate: ssa values out of range
    0: GLOBAL NODE 464 [ nid05683 ] : ( 16 MPI TASKS ) 7424 7425 7426 7427 7428 7429 7430 7431 7432 7433 7434 7435 7436 7437 7438 7439
s25-sep15/f.ne1024pg2.s25-sep15.F00DY1.n1536p12288t08xX11181.24s.nr.f2.mm1.3bfb.revap/run/e3sm.log.34415569.200916-011613:  5414:  ERROR: validate: ssa values out of range
    0: GLOBAL NODE 676 [ nid05683 ] : ( 8 MPI TASKS ) 5408 5409 5410 5411 5412 5413 5414 5415
s32-oct22/f.ne1024pg2tri.s32-oct22.F10DY2.n3072p24576t08xX11181.nc02.24s.wr.st064/run/e3sm.log.35427989.201023-060335: 7790:  ERROR: validate: tau values out of range
    0: GLOBAL NODE 973 [ nid05683 ] : ( 8 MPI TASKS ) 7784 7785 7786 7787 7788 7789 7790 7791
s34-nov1/f.ne1024pg2tri.s34-nov1.F10DY2.n1536p12288t08xX11181.ne03.snow.6h.wr.pbs16M.st096M1.top/run/e3sm.log.35883999.201105-050915
    0: GLOBAL NODE 560 [ nid05683 ] : ( 8 MPI TASKS ) 4480 4481 4482 4483 4484 4485 4486 4487
s34-nov1/f.ne1024pg2tri.s34-nov1.F10DY2.n1536p12288t08xX11181.ne04.snow.6h.wr.pbs32M.st096M1.top/run/e3sm.log.35888942.201105-132634: 4206:  ERROR: validate: ssa values out of range
    0: GLOBAL NODE 525 [ nid05683 ] : ( 8 MPI TASKS ) 4200 4201 4202 4203 4204 4205 4206 4207
```

**Comment by crterai** [comment]
Below are details for a simulation where I encountered the same error on the same node. 

```
Job id: 35868491
Run directory: /global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne1024pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2.cori-knl_intel.3072x8x16.DY2_bogensch_plus_Kobby_Nov03_no3D.20201103-18/run
Error message:
    0: GLOBAL NODE 966 [ nid05683 ] : ( 8 MPI TASKS ) 7728 7729 7730 7731 7732 7733 7734 7735
 7734:  ERROR: validate: tau values out of range
 7734: Image              PC                Routine            Line        Source             
 7734: e3sm.exe           000000000373265A  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000001E56A4E  shr_abort_mod_mp_         114  shr_abort_mod.F90
 7734: e3sm.exe           00000000007092C5  radiation_utils_m         344  radiation_utils.F90
 7734: e3sm.exe           00000000006EA048  radiation_mp_radi        1966  radiation.F90
 7734: e3sm.exe           00000000006CB778  radiation_mp_radi        1443  radiation.F90
 7734: e3sm.exe           00000000008EAECC  physpkg_mp_tphysb        2734  physpkg.F90
 7734: e3sm.exe           00000000008E2DC1  physpkg_mp_phys_r        1055  physpkg.F90
 7734: e3sm.exe           000000000329BB33  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003245DDA  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003244E31  Unknown               Unknown  Unknown
 7734: e3sm.exe           000000000329BF1A  Unknown               Unknown  Unknown
 7734: e3sm.exe           00000000033AD509  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003CD873F  Unknown               Unknown  Unknown
 7734: Rank 7734 [Wed Nov  4 12:28:01 2020] [c5-2c1s12n3] application called MPI_Abort(MPI_COMM_WORLD, 1001) - process 7734
 7734: forrtl: error (76): Abort trap signal
 7734: Image              PC                Routine            Line        Source             
 7734: e3sm.exe           0000000003740594  Unknown               Unknown  Unknown
 7734: e3sm.exe           00000000033B25B0  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003805D50  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003C57721  Unknown               Unknown  Unknown
 7734: e3sm.exe           00000000034E7012  Unknown               Unknown  Unknown
 7734: e3sm.exe           00000000034B4B6B  Unknown               Unknown  Unknown
 7734: e3sm.exe           00000000034BB8C5  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000001F87E3A  shr_mpi_mod_mp_sh        2127  shr_mpi_mod.F90
 7734: e3sm.exe           0000000001E56AFC  shr_abort_mod_mp_          69  shr_abort_mod.F90
 7734: e3sm.exe           00000000007092C5  radiation_utils_m         344  radiation_utils.F90
 7734: e3sm.exe           00000000006EA048  radiation_mp_radi        1966  radiation.F90
 7734: e3sm.exe           00000000006CB778  radiation_mp_radi        1443  radiation.F90
 7734: e3sm.exe           00000000008EAECC  physpkg_mp_tphysb        2734  physpkg.F90
 7734: e3sm.exe           00000000008E2DC1  physpkg_mp_phys_r        1055  physpkg.F90
 7734: e3sm.exe           000000000329BB33  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003245DDA  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003244E31  Unknown               Unknown  Unknown
 7734: e3sm.exe           000000000329BF1A  Unknown               Unknown  Unknown
 7734: e3sm.exe           00000000033AD509  Unknown               Unknown  Unknown
 7734: e3sm.exe           0000000003CD873F  Unknown               Unknown  Unknown
srun: error: nid05683: task 7734: Aborted
```

**Comment by ndkeen** [comment]
I also see that there were jobs (not sure if they were same types of jobs as those above that failed) that used that potentially bad KNL node and did NOT fail.

**Comment by worleyph** [comment]
For the record (repeating comments on Slack): Was not able to reproduce an error using master and an F case (ne4_ne4, both 64x1 and 8x16, running only on nid05683 for one simulated month. Also had no problems running an F case with ne30pg2 on 4 nodes (also including nid05683 for 5 simulated days. Two ne4_ne4 jobs were BFB.

**Comment by worleyph** [comment]
Reran ne30_pg2 case, again on 4 nodes including the suspect one - other 3 are different nodes, and it is BFB with the first run, so no signs of problems (with these experiments).

**Comment by ndkeen** [comment]
I created NERSC ticket.  Feel free to suggest clarifications/edits (or comment on the ticket itself)

INC0162133

**Comment by PeterCaldwell** [comment]
A couple of comments/questions: 
1. I don't think I have permissions to see NERSC ticket INC0162133. That's fine, but don't assume I can see what's going on with that ticket.
2. What is NERSC doing in reaction to our ticket? Have they taken nid05683 out of service? Are they going to?
3. Am I correct that submitting jobs excluding a particular node will spend much longer in the queue than a normal job?

**Comment by worleyph** [comment]
> Am I correct that submitting jobs excluding a particular node will spend much longer in the queue than a normal job?

Just guessing, but there should be very little extra time in the queue, unless you are allocating the final "N" nodes available in the system. (Unlikely since there are lots of nodes.) Requiring a particular node can add time, as you need the job currently using it to finish first.

**Comment by ndkeen** [comment]
Peter: yes good point, I forgot NERSC tickets are so locked down -- I think I can add some watchers (or whatever it's called) to the ticket.

I haven't yet explicitly asked them to remove from service.  I would think the evidence of foul play is enough to warrant at least node probation, but they may be stumped here as clearly we are the only code running into this problem.

The only reply I've gotten is: "This is quite an interesting bug. I am referring this ticket to the Computational Systems Group."

**Comment by ndkeen** [comment]
Noting here that this look similar to
https://github.com/E3SM-Project/E3SM/issues/3768
though it fails in different routine.

And then more recently, on Theta here:
https://github.com/E3SM-Project/scream/issues/933

**Comment by AaronDonahue** [comment]
@ndkeen , is this still an issue?

**Comment by ndkeen** [comment]
I've not seen this issue occur again, but we have not been running this case on cori-knl -- or much of any large jobs. Closing.
