### ISSUE TITLE
SHOC tests exibit seemingly random behavior, depending on CTEST_PARALLEL_LEVEL 

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#742]
Try to manually run `ctest -R shoc_tests` and `CTEST_PARALLEL_LEVEL=40 ctest -R shoc_tests`. The latter, on mappy as well as my laptop, passes, while the former has 3 tests failing. A midground with || level 4 has just 1 test failing.

**Comment by bartgol** [comment]
If I remove `shoc_diag_second_moments_tests.cpp` from the list of files to compile into `shoc_tests`, then tests pass.

This is on mappy (gcc).

**Comment by jgfouca** [comment]
Just glancing at this, I think there's likely just some team barriers needed. I will investigate.
