### ISSUE TITLE
Fix Livermore Computing machine files to use module environment variables rather than hard-coded

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#748]
A few of the variables in the machine files for livermore computing machines use hard-coded pathes which is not robust against updates to modules in the future.  These should be changed to rely on variables added to the path by specific modules.

**Comment by bartgol** [comment]
Could we piggy back something to a PR that address this issue? It's probably time to update all our mach files, to include netcdf and possibly other deps specs (can't think of any other than netcdf right now though). So far, we only have kokkos specs in our mach files (which simply get those specs from ekat).

**Comment by bartgol** [comment]
Looking at `scripts/machine_specs.py`, it seems this has been done. @AaronDonahue , if something is still needed, feel free to reopen.

**Comment by AaronDonahue** [comment]
I believe this has now been taking care of, except in the case of lassen.  But there really isn't much we can do about it at this point.
