### ISSUE TITLE
Implement python or small C++ program to query CF database

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#749]
The script should allow one to query the database, in a few ways. The most important is to look for the CF name of a variable, given a "guess", like this:

```
  $ query-cf-database -s <name guess>
```
`-s` stands for search, but maybe `-f` for "find"?
E.g:

```
$ query-cf-database -s "surface_temperature"

   Input name: 'surface temperature'
   Best matches:
      surface_temperature
      sea_surface_temperature
      sea_ice_surface_temperature
      solid_earth_subsurface_temperature
      square_of_sea_surface_temperature
```
The script should report all matches with a similarity index above a certain threshold. This threshold should be configurable (to allow user to search "worse" matches if he/she cannot provide a decent guess), and should have a default determined by trial and error. I ran the Jaro and Jaro-Winkler similarity functions in EKAT on a "good" guess, and got this:
```
enter 1st string: evaporation water flux
enter 2nd string: water_evaporation_flux
similarity indices:
 j : 0.786284
 jw: 0.786284
```
but also
```
enter 1st string:temperature
enter 2nd string:pressure
similarity indices:
 j : 0.626263
 jw: 0.626263
```
so maybe we should pick something between 0.6 and 0.8 (if using J/JW indices).

Possible flags for the script:
- "-f" or "-t" <string>: search for var names similar to <string>.
- "-d": get description for a given variable; require exact var name, this would not do similarity search. It might help in case one is not 100% sure what the variable is about.
If using `-f` (or `-s`, or whatever it is), one could also specify:
- "-t <float number>": threshold for the index (between 0 and 1). As I said, we should default this to a value somewhere in 0.6-0.8
- "-n <int number>": max number of items to report. Default maybe to 5, or something not too big.
- "-b": ignore threshold, and report list of best matches (limited by -n option), regardless of how bad/good the matches are
- "-v": verbose mode, to show index for each match (could help user "learn" good values for future use).

Note: there are J/JW similarity index computation routines in `ekat_string_utils.*pp`. They are relatively small, so one should not have a hard time rewriting them in python. If you do, and want to test your mini script, in `tests/util/utils_cxx` in EKAT, there is a small dictionary of strings, with their expected J/JW similarity indices.

Note 2: it might be that J/JW indices are not great for our purposes. The fact that `evaporation water flux` and `water_evaporation_flux` have an index of 0.78 while `pressure` and `temperature` have 0.62 makes me think these indices may not be suitable for "sentences", where words are never misspelled, but might be rearranged.

**Comment by jeff-cohere** [comment]
The Jaccard index algorithm might be a better fit if we're trying to validate against properly-spelled words. It's token-based, so for example "hello world" and "world hello" both have an index of 1.0. And "hello new world" and "hello world" have an index of 0.666.

**Comment by bartgol** [comment]
That's a good fit, probably. We just need to split for tokens based on spaces as well as underscore (that's what CF uses).

And yes, if we don't find any match above a certain threshold, we may try the J/JW indices to check if there's a misspelling (or something like "temp" for "temperature").

**Comment by jeff-cohere** [comment]
In the interest of eliminating ambiguities in our tools, I'm putting together a small C++ program to do this, and adding a Jaccard index function to EKAT.
