### ISSUE TITLE
Weird behavior of testing scripts on weaver

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#754]
This issue is to keep a log of the debugging of the odd failures we are seeing on weaver for the AT. I'm putting my findings in random order:

- on weaver, we see ctest reporting 100% tests pass, but still test-all-scream reports FAIL.
- you can manually reproduce on weaver (I used pr 743 with sha 3970abd) with any of the 3 build.
- adding a few print statements, I was able to find out that the subpipe executing the ctest command return 255, which test_all_scream.py interprets as a fail.
- the subpipe returns 255 even if we comment build/test phase in ctest_scripts.cmake, meaning that build/tests have nothing to do with this. However, it returns 0 if we also comment the `ctest_configure` line.
- if you copy the ctest command (as shown by test-all-scream) and run it manually, then check the bash return code, you get 0.

All the above seems to suggest something is off with the subpipe in our python scripts. I tried to play with the subprocess module stuff (like replace 'Popen' with 'run'), with no luck.

I should point out that some builds on weaver went through, and seemingly random behavior is quite annoying. That said, I consistently get the 255 return code when running manually.

Tagging the python demi-god @jgfouca , in case something rings a bell.

**Comment by bartgol** [comment]
I still don't understand it, but this seems to fix it. Change

```
ctest_configure(OPTIONS "${OPTIONS_LIST}" RETURN_VALUE CONFIG_ERROR_CODE)
```
to
```
ctest_configure(OPTIONS "${OPTIONS_LIST}" RETURN_VALUE CONFIG_ERROR_CODE CAPTURE_CMAKE_ERROR CMAKE_ERR_CODE)
```
inside `ctest_script.cmake`. From [the documentation of ctest_configure](https://cmake.org/cmake/help/v3.18/command/ctest_configure.html):

> `CAPTURE_CMAKE_ERROR <result-var>`
>    Store in the `<result-var>` variable -1 if there are any errors running the command and prevent ctest from returning non-zero if an error occurs.

So my guess is that something goes wrong running cmake (perhaps some compiler check subprocesses?), and that causes ctest to return something that is not 0. Now, the very unclear thing is that _running the same ctest command that test-all-scream runs by hand returns 0_, which is puzzling.

@jgfouca, unless you have any other idea of what could possibly be happening here, I might add this fix to the scripts fix PR I have open, and call it a day. I'm not happy with the fact that test-all has ctest returning 255 (or probably -1, which underflows to 255 somehow), while running the same ctest command by hand return 0. However, this has already sucked too much of my time...

**Comment by jgfouca** [comment]
This is pretty urgent since it invalidates all our testing on weaver. I'm going to add a standalone test-suite for test-all-scream since it's so important to our workflow and hopefully solve this specific issue while I'm working on it.
