### ISSUE TITLE
Rework PD remapper to parallelize over fields as well

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#780]
Currently, the PD remapper does a host for loop over the registered fields, and for each field it dispatches a parallel for for the local remap. Once all those are done, for the fwd version only (P->D), it performs a halo exchange.

Inside the host for loop, there are a few info on each field that are retrieved (via host-only functions), which is why we can't ||ize over fields, as the impl stands. However, all that info can be pre-computed at `registration_ends` time, stuffing all info in device friendly views. Then, we can dispatch a team policy || for, with league size equal to nfields*ncols (we might adjust team size in order to make it balanced).

This should be beneficial on both CPU and GPU. On CPU, it increases caching (making icol stride slower than ifield), while on GPU it will fuse kernels, and increase ||ism.

**Comment by PeterCaldwell** [comment]
I'm tagging this as a wishlist item because we can get the model running without it. I'm envisioning that we'll get the model working, then will pivot to performance enhancements. However, if we want to do this task now while we have a clear vision of how it should work, I'm fine with that.

**Comment by bartgol** [comment]
Peter, I think this is more than a wishlist. I think we will need this to run efficiently on GPU.

As you said, we _can_ run without this. But it will certainly affect performance (especially on GPU). I'm changing it to medium

P.s: it is also a good issue for conrad, cause it involve getting to know better grids/fields structures.

**Comment by PeterCaldwell** [comment]
Ok. I was on the fence between wishlist and low or medium, so I'm happy with this shift.

**Comment by tcclevenger** [comment]
Moved to "In Progress" group.

**Comment by tcclevenger** [comment]
Removing link to PR (which should merge today). Seeing a bump in performance for most cases now, but I will immediately work on another PR which changes the team policy to make the parallel distribution much more efficient.  If no objections, I'll just continue to update the same issue here.

**Comment by bartgol** [comment]
Another thing I just thought of, that you could do when you rework the team policy: it might be best to make it so that `num_fields` is the number of fields to _actually remap_ (rather than all fields, including those that have a parent). Otherwise you pollute the policy with "empty" iterations, which mean cuda blocks dispatched for nothing. 

You could probably purge the fields that have a parent during the call to `initialize_device_variables`. In particular, in that fcn you could first loop over all registered fields, and if a field is found that has a parent, 1) check that the parent is registered (otherwise crap out), 2) remove that field. After the removals, one can proceed with the creation of helper structs.
