### ISSUE TITLE
[AD] SCORPIO-Interface: Better handling of output frequency

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#790]
Currently the output frequency can only be in number of steps.  So the user needs to know a) the timestep and b) how many steps needed to get the wanted frequency.

This is woefully inadequate.  It doesn't even provide a path to monthly output because each month has a different number of steps.

The infrastructure is in place to declare hourly, daily, monthly, yearly, etc. output frequency.  What is needed now is the infrastructure for the output_manager and/or output_instance class object to query the timestamp and determine if output is warranted given the frequency provided.

**Comment by PeterCaldwell** [comment]
I switched this from medium priority to wishlist because I don't think we need to do anything beyond hourly type output for 9 months or so (until we start runs on summit). I guess it is more medium priority than some tasks because it *does* need to be done eventually... but is lower priority than anything needed to get the model running.

**Comment by bartgol** [comment]
I'm in favor of relegating the non-urgent stuff to wishlist tags or low priority tags. One comment though: if we want feature A evenetually, we should make sure that in the meantime our code does not evolve in a way that makes it impossible to add A later on.

In this case, for example, if we want output frequency to have many options later, but for now we're fine with monthly, we should keep developing code _as if_ hourly, yearly, etc. were supported options. That means we should add checks and whatnots that handle the frequency as a configurable option (even though only one type works), including error messages, if statements,... This way, we don't accidentally hard code options in a way that gets hard to spot down the road.

Note: this is just for things that we _know_ we want (at some point). And yes, sometimes we'll end up hardcoding things; but keeping this approach can help reducing the places where the assumption goes unnoticed.

**Comment by PeterCaldwell** [comment]
Yeah, I keep thinking about not exercising options now means we might preclude them later. @bartgol 's comment is well taken.
