### ISSUE TITLE
[AD] SCORPIO-Interface: Create an IO class that has output and input as sub-classes

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#794]
Currently the output class and input class are independent of each other.  Although they do share a number of sub-routines.  Given that, it would make sense to instead have input and output be sub-classes of a master IO class, such that they inherit common routines.

This would make changing these common routines easier and less prone to bugs.

It would also trim down the input and output class code and make it easier to read/understand.

**Comment by bartgol** [comment]
Interesting idea, but probably not really needed. Closing.
