### ISSUE TITLE
[AD] SCORPIO-Interface: Make an "averaging type" class for future flexibility

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#795]
This would be a nice feature to have in the future.

Currently, the only output averaging options are: 
1. Instant - a direct snapshot in time
2. Average - the average value over time from the last output written.
3. Min or Max - same as average except with minimum or maximum.

We could design an "averaging class" that is generally defined, which would allow for the user to define their own averaging type on the fly, and easily, without having to go through the code and add another "else" statement everywhere averaging type is used.

This idea comes from a similar approach that @jeff-cohere used to set up a way to quickly and easily define property tests for fields.

**Comment by PeterCaldwell** [comment]
It isn't really an "average class", right? I think it's a generalization of the average operator to allow for more general operations? I feel like folks have wanted outputs that this abstraction could allow but couldn't figure out how to do them. A random example is "I want to output the monthly average of the daily minimum temperature". Or "what is the 99th percentile precipitation rate for this month (or year)".

**Comment by AaronDonahue** [comment]
Yes, the name should definitely be improved.  Probably throughout even the comments, which refer to an "averaging flag".  I'm open to suggestions.

Maybe "output metric" or "output rule".

**Comment by PeterCaldwell** [comment]
👍 . Maybe "output_operation"? Or "special_output" if this is in addition to the existing average operator? It seems like we could create a class for "output_operation" and have average, min, and max be instances of that class?

**Comment by AaronDonahue** [comment]
Yes, absolutely.  That probably wasn't clear in the description.  I think we should replace "average", "max", "min" and "instant" with instances of a basic class.  And then new instances can be defined if users want something that isn't already there.  Then we could remove all the "if averaging_type==BLAH" code and replace it with a call to the output_operation/rule/etc object.

**Comment by bartgol** [comment]
For a limited set of flags, using strings/enums/ints is fine. I don't see something like

```
switch(flag) {
  case AVG:
     ...
  case MAX:
   ...
  case ...
}
```
as a bad code. If the body of each `case` is large, then one can simply wrap it in a method/function, to keep each functional segment of the code limited (for ease of inspection/maintenance).

**Comment by bartgol** [comment]
I think it's ok to keep it relegated to a spearate function in the output class, as it's done in #1162
