### ISSUE TITLE
[AD] SCORPIO-Interface: Make restart a separate sub-class of the output class

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#797]
Currently, the restart output stream is just a boolean flag in a typical output stream.  But restarts are unique when compared with typical output.

This task is to explore the merit of making a restart class that is a sub-class of the output class.  If it is decided that this is the right path to take, go ahead and implement it.

**Comment by bartgol** [comment]
I think for now it's fine to have the output class handle also the model restart output. It didn't add _that_ much code.
