### ISSUE TITLE
[AD] SCORPIO-Interface: Get restarts working as expected

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#798]
A series of tasks needed to make sure that restarts are behaving correctly in the SCREAM-AD

- [ ] A restart run should gather the timestamp from the restart file to ensure continuity in date/time.
- [ ] A corollary to this, is to check the timestamp against the date/time the component coupler has and throw an error if different.

*Previously:*
Any restart run *should* update the timestamp given the time from the restart file.  Currently this isn't being done.

This is high priority because time management is a key component of a full scale run and it is important that any restart simulation have the correct timestamp.

**Comment by PeterCaldwell** [comment]
I don't understand this issue. We can't run with the AD at all yet so we certainly can't do restarts now... so isn't this medium priority at best? And the idea is that AD runs always start their timestep at Jan 1, 0001 and we want to be able to read in the appropriate starting timestep from file on a restart run? Isn't this a natural part of the "make restart runs work" task which we haven't started?

**Comment by AaronDonahue** [comment]
Yes, you are correct.  Perhaps the task can be changed from high to medium priority and be broadened in scope to "make restarts work" in a full run.

I'll note that restarts are written and a new run will read the rpointer file and load the appropriate data for both restarts in general and restart histories.  The only issue is that "time" always starts at t=0. 

I originally put "high" priority given that it is a necessary step before we can realistically run the AD for long-term simulations.  But I would agree it really doesn't need to be addressed until after we have the AD running all the procs in a CIME build in general.

**Comment by PeterCaldwell** [comment]
Ok, can you rework this issue to generalize it to "make restarts work"?

**Comment by PeterCaldwell** [comment]
I think this is a new version of issue #652?
