### ISSUE TITLE
[AD] SCORPIO-Interface: Make input able to handle files with more than one timesnap

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#799]
Currently only one timesnap from an input file can be read in.  In most simulations this is not a problem, a typical restart output for example has only the last timesnap to read in.

However, in some cases, such as with nudging, it is necessary to read data from a file that has stored multiple timesnaps of data.

This task is to refactor the scorpio_input class to be able to handle input that contains more than one timesnap.

This task also would involve designing an interface with the input class that can be used when multiple timesnaps are required.   In other words, how would the AD or a specific process designate that it wants 1, 2 or more timesnaps.  How would that data be stored, considering that fields in the field manager currently don't have the time dimension by default.

Essentially there would need to be some design discussion before anything could be implemented.

**Comment by bartgol** [comment]
I don't understand why one would need 2+ timestamps. Do you need to read more than 1 timestamp or do you simply need to "navigate" the file to locate the desired timestamp?

**Comment by AaronDonahue** [comment]
There are special cases, like when using "nudging" or maybe for the prescribed CCN work, where you might have a file with multiple snaps in it.

With PIO you need to sync the timesnap you want using a particular PIO routine.  I left this part out of input to simplify the interface seeing as how we don't need it for now.

**Comment by PeterCaldwell** [comment]
If I understand correctly, right now infld opens a file, extracts data, and closes it all at once. This issue would allow us to open a file and leave it open so we could read from it every couple steps if we wanted. This would require a lot of infrastructure for keeping track of open file ids. My take is that we shouldn't bother until we have a case that requires it. Why build something specifically for nudging when we won't add nudging until SCREAMv2? I'm pretty sure that prescribed aerosol has different variables for the 2 time levels it needs to interpolate between and doesn't leave files open.

**Comment by AaronDonahue** [comment]
right, this task came out of my questioning the broader E3SM community about netCDF files with more than one timesnap.  Rob suggested the nudging example and Walter suggested that MMF might need the capability.  I'm happy to couch this task until it comes up as a need.

Peter's description of what is happening now is correct.  The input call opens, reads from and closes the file all in one step.  This is in contrast to the output which can keep a file open if more than 1 timesnap is requested.  There is a fair bit of bookkeeping needed with keeping files open, which is why I didn't put the functionality in with the first SCORPIO PR.

**Comment by AaronDonahue** [comment]
solved by #1233
