### ISSUE TITLE
[AD]: Upstream merge to sync NH++ between e3sm and scream repos

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#811]
#730 allows AD to use the C++ nonhydrostatic SE dycore in scream repo. This was implemented to allow us to make progress while a similar PR worked its way through the slower e3sm repo. Now that that has completed via https://github.com/E3SM-Project/E3SM/pull/3928 and https://github.com/E3SM-Project/E3SM/pull/3812, we should do an upstream merge and resolve conflicts to have a more uniform impl.

**Comment by PeterCaldwell** [comment]
we want these integrated first:

1. doubly periodic SCREAM: https://github.com/E3SM-Project/E3SM/pull/3987
2. SCM fixes: https://github.com/E3SM-Project/E3SM/pull/3943
3. cime fixes for v1 (from Jim) 
4. NH++ changes (done)

**Comment by bartgol** [comment]
Sorry, I didn't keep up with this task. Luckily, from your comment, it looks like we want to wait for a few things to be completed before proceeding, so I take back my words: I _did_ keep an eye on this issue, I was just waiting on the other pre-requisites to be checked out first. :)
