### ISSUE TITLE
[AD] Get CIME to build the C++ version of SCREAM

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#813]
Add SCREAMv1 as an optional atmosphere choice in CIME and get CIME to build a C++ executable when SCREAMv1 is chosen. Initially, this will probably just include building the AD and the dycore because other processes aren't fully linked to the AD yet. Eventually, we will need to also build P3, SHOC, and RRTMGP and their interfaces with the AD.

**Comment by bartgol** [comment]
When I tested the surface coupling branch, I was already telling CIME to build SCREAMv1. I am not sure how meaningful the compset was though (I don't know, e.g., if other components were active). I think this task goes hand-in-hand with #817.
