### ISSUE TITLE
[AD] implement mechanism for passing run options to SCREAMv1

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#815]
Right now, the SE dycore expects options to be specified via a namelist. We were planning on having SCREAM use yaml files to specify options (and this seems to be working really well already for output variable requests). It is tempting to use the existing namelist structure from EAM since it has defaults and infrastructure that we could easily co-opt. @rljacob warns us that the eam approach is the result of decades of unplanned accretion of stuff and suggests that creating our own strategy would be better.

What will be a coherent, easy-to-manage strategy for passing runtime options to SCREAMv1 runs? The goal of this issue is to determine a strategy (probably via comments below).

**Comment by bartgol** [comment]
Given the current status, I think the choice is between
 - namelists-only: atm_mct_comp will have to fwd all namelist entries to the driver;
 - mixed nameliists-yaml: still have a big atm_in namelist (easy to fwd to homme), but all the AD parameters are in a yaml file (whose name is either hardcoded, like 'atm_in.yaml', or read from the atm_in namelist).

Namelist pro: there's already a lot of cime infrastructure for creating namelists defaults, and integrating user changes to namelists defaults for a particular case.

YAML pro: it is highly flexible, and does not require the parser to know _a priori_ the structure of the namelist. E.g., you can have a variable number of sublistst.

An important piece for deciding this is whether we can "generate" a yaml file based on case configs (via buildnml), and if we can integrate user changes to the default.

**Comment by PeterCaldwell** [comment]
I generally agree with Luca's assessment but:
1. I think most namelist variables are read directly by atm code rather than passed from atm_mct_comp?
2. using existing cime infrastructure is a benefit, but also a curse because it has a lot of legacy baggage. 
3. I like Luca's last comment about generating a yaml from case configs. Maybe more generally we can say that the big use case we need to handle is the ability to choose a compset and for that to automatically set all the default parameter settings, input files, etc but for the user to be able to override these defaults somehow.

**Comment by bartgol** [comment]
I think generating a yaml file should not be hard (there's a yaml python module that can be used for read/write easily, though it's not standard, so it might not be available everywhere). The interesting piece is how we handle user mods. I don't know how cime setup/build/run works, so I may be saying something naive. If the user mods must be possible _after_ the namelist/yaml-file has been built, it is a bit tricky, but if they must be done before all the inputs are generated, then it is probavly not too hard.

**Comment by rljacob** [comment]
CIME takes the base fortran namelist and combines it with whatever the user put in user_nl_eam to generate the runtime namelist.  The "preview_namelists" function is run several time in the workflow including right before submission so that any user mods make it to the final namelist.

As the name implies, "user_nl_eam" is in Fortran namelist format.  If you had a "user_scream.yml" file in the case directory, and you had a routine to take whatever is in there and overwrite the base yaml values, you could duplicate CIME workflow.

I guess this would take some mods to CIME to handle yaml files in preview_namelist.   Or write a "preview_yaml" routine?

**Comment by bartgol** [comment]
If we had access to the yaml module (I think it is PyYAML), then merging two yaml files might just be as easy as doing (pseudo-python):

```
default = pyaml.load(default_fnamel)
user    = pyaml.load(user_fname)
if len(user)>0:
    # add some validation code before the update maybe?
    default.update(user) # pyaml loads into dictionaries
default.dump(final_fname)
```

Note: pyyaml is also available [on github](https://github.com/yaml/pyyaml), so it _could_ be submoduled (if not available)

**Comment by PeterCaldwell** [comment]
Plan is to create a yaml with **all** runtime settings (based on https://github.com/E3SM-Project/scream-docs/blob/master/v1_settings/SCREAMv1_input.txt) and have CIME convert the dycore-related parameters to namelist before case.submitting. As Luca notes above, this requires installing pyyaml on CIME machines (which shouldn't be hard).
