### ISSUE TITLE
Prototype settings list for SCREAMv1

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#829]
In order to sort out how users will specify parameter settings, input data, etc in SCREAMv1, we should come up with an initial list of the things users should expect to set. Note that because SCREAM is trying to work in just one config initially, this list will initially be short. It will accrete options as SCREAM gets used for more things.

**Comment by PeterCaldwell** [comment]
see https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2131329223/Prototype+settings+for+SCREAMv1+run

**Comment by PeterCaldwell** [comment]
@bartgol and @jgfouca  - I think my task is done. See https://github.com/E3SM-Project/scream-docs/blob/master/v1_settings/SCREAMv1_input.txt . Note that this pseudo-code file includes a fair number of variable names and functionality that doesn't exist in SCREAMv1 yet.

**Comment by jgfouca** [comment]
Nice!

**Comment by bartgol** [comment]
Thanks Peter!
