### ISSUE TITLE
Port SHOC to C++/Kokkos

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#831]
Currently includes shoc_main port (along with review of structs passed into/out of it) and pblh routine.

**Comment by xyuan** [comment]
All done now.

**Comment by tcclevenger** [comment]
@xyuan Awesome! Thanks for the update.

**Comment by tcclevenger** [comment]
`shoc_main` PR created: https://github.com/E3SM-Project/scream/pull/856#pullrequestreview-566456266

**Comment by tcclevenger** [comment]
`shoc_main` successfully ported. @PeterCaldwell are we good to close this issue?

**Comment by PeterCaldwell** [comment]
Yup! Nice job!!!
