### ISSUE TITLE
Finalize C++ version of Simple Prescribed Aerosol (SPA)

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#835]
Once #834 is done, use it as a template to make our C++ code also use SPA forcings appropriately.

**Comment by bartgol** [comment]
@AaronDonahue I think this was done by #1153 , right? I mean, we still miss horiz interpolation, but assuming one has the aerosols nc file at the same res of the state, then SPA _is_ working, right? Can we close?

**Comment by AaronDonahue** [comment]
I'm all for closing issues, and #1153 did get us most of the way there.  That being said,this issue is to finalize the code and that isn't finished yet.  I think I can reference this issue in the next SPA PR so we don't lose sight of it and go ahead and close the issue when that PR is merged.

**Comment by bartgol** [comment]
@AaronDonahue can this be closed now that 1260 went in?
