### ISSUE TITLE
Improve format of Atm Proc sequence in yaml input file

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#843]
Currently, the sequence is specified as:

```
  Atmosphere Processes:
    Number of Entries: 3
    Schedule Type: Sequential
    Process 0:
      Process Name: Homme
      [homme options]
    Process 1:
      Process Name: P3
      [p3 options]
    Process 2:
      Process Name: SHOC
      [shoc options]
```
It would be nice to specify them in a more compact way, like this
```
  Atmosphere Processes:
    Processes: seq(Homme, P3, SHOC)
    Homme:
       [homme options]
    P3: 
       [p3 options]
    SHOC:
       [shoc options]
```
This will help reduce the complexity of input files. E.g., it will reduce the number of lines, and the indentation levels.

Note: in case of parallel splitting, one would use the following syntax:
```
   Processes: par(50 Homme, 50 seq(P3, SHOC))
   Homme:
     ...
   P3:
     ...
   SHOC:
     ...
```
The `par` and `seq` keywords are to express parallel/sequential splitting, and the leading integer is the percentage of atm ranks to dedicate to the current proc in the parallel splitting (with a runtime check that enforces zero remainder in N_atm*50/100).

**Comment by bartgol** [comment]
@jeff-cohere This is the issue I was thinking about for the yaml file atm proc specs change. The `par/seq` thingy could be deferred till we actually have a parallel splitting. I think the named processes sublists would already increase readability.

**Comment by AaronDonahue** [comment]
@luca, i feel like our current format fixes this right?

**Comment by bartgol** [comment]
Right.
