### ISSUE TITLE
Check whether SCREAMv0 conserves energy

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#849]
SCREAMv0 inherited the E3SMv1 energy fixer, which should work. It also avoids recent energy leaks found in the gravity wave parameterization (by not using gravity wave drag in high-res mode). We haven't tested whether SHOC, P3, and RRTMGP conserve energy though, so maybe there are bugs. We should do this check.

**Comment by oksanaguba** [comment]
A run for ne30, dyamond2 branch, SCREAM HR compset ran for 6+ years (crashed). There is nothing alarming in that run, except that it is too short to see trends. Another option is to run with diagnostic calls from one of energy diagnostic branches (energy-diagn3).

**Comment by oksanaguba** [comment]
closing this since it is probably not interesting anymore.
