### ISSUE TITLE
[AD] Remaining tasks for P3-AD interface

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#864]
There are two remaining tasks to resolve before P3 is "fully" integrated into the AD:

- [x] post-processing of P3 output to prepare variables used by other processes.
  The pre-processing is already put in, but there are a number of steps that must follow the call to p3_main to update variables used by SHOC and Radiation.
- [ ] A more robust unit test.
  The current unit test just uses a text file input that is derived from p3_run_and_cmp output.  A more robust unit test - and p3_initializer setup - would be to utilize netCDF input and allow for pass/fail based on cprnc.

**Comment by bartgol** [comment]
@AaronDonahue I'm tempted to call this issue solved. The remaining half part, namely to get cprnc-based tests, is probably more general, and has nothing to do with p3-ad interfaces.

**Comment by AaronDonahue** [comment]
Yeah, we can probably call this resolved now that I've done a pretty thorough analysis of the p3-ad values compared with p3_run_and_cmp.
