### ISSUE TITLE
Break p3_tests into a few subset of tests (and possibly similarly for shoc_tests)

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#871]
Running p3_tests on GPU took me 178s, roughly 3 minutes. That executable is running a lot of tests (roughly one for each p3 function). Every other test (except shoc_tests) was done in less than 30s.

If one only ran tests serially, then this issue would be moot. But when running manually, one could do `CTEST_PARELLEL_LEVEL=N ctest`, then having p3_tests split into multiple tests might allow it to be faster.

A quick look to the src files suggests a group for "p3_*_conservation_tests.cpp" (5), one for "p3_ice_*_unit_tests.cpp" (7), one for "p3_*rain*_unit_tests.cpp" (5), and one for everything else (19).  But maybe an eye more knowledgeable on p3 can group tests better than me (I am grouping them just looking at file names). I think if we could split these 35 files in N groups of <10 files, it might take the testing time down by a good margin (for || ctest exec, that is).

**Comment by PeterCaldwell** [comment]
Your breakdown sounds good to me, Luca. Good idea.

**Comment by AaronDonahue** [comment]
@bartgol is this still an issue?
