### ISSUE TITLE
Build error with ne4 F case in physpkg.F90

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/scream#878]
This build error is reproducible with compset FC5AV1C-L and res ne4_ne4 on
Cori, Theta and anlworkstation.

[GNU compiler]
```
components/eam/src/physics/cam/physpkg.F90:850:42:

     call radiation_init(phys_state,pbuf2d)
                                          1
Error: More actual than formal arguments in procedure call at (1)
```
[Intel compiler]
```
components/eam/src/physics/cam/physpkg.F90(850): error #6784: The number of actual arguments cannot be greater than the number of dummy arguments.   [RADIATION_INIT]
    call radiation_init(phys_state,pbuf2d)
---------^
```
This error is only reproducible with scream (not reproducible with E3SM).

**Comment by oksanaguba** [comment]
I think it is the same error that popped up before, from scream slack by Ben:
```
Looks like commit 0216d0c8 broke RRTMG (we only test RRTMGP on SCREAM):
```

**Comment by dqwu** [comment]
> I think it is the same error that popped up before, from scream slack by Ben:
> 
> ```
> Looks like commit 0216d0c8 broke RRTMG (we only test RRTMGP on SCREAM):
> ```

That commit is from PR #743, which has changed "call radiation_init(phys_state)" to
"call radiation_init(phys_state,pbuf2d)".
