### ISSUE TITLE
Potential issue with "-i" (integration) flag in test-all-scream

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#884]
I _think_ there might be an issue with our `-i` flag, which might cause problems if manually used without proper care.

The `-i` flag (i stands for 'integration') causes `test-all-scream` (TAS) to compare against baselines whose sha must match the one of `origin/master`. If providing a baseline dir, TAS checks the sha used to generate the baselines in that dir, stored in a file called `${baselines_dir}/baseline_git_sha`. If missing, or if the sha does not match the one of `origin/master`, it _assumes_ the baselines are outdated, and proceeds to generate new ones with the current version of `origin/master`.

This is what our AT jobs do. When the AT runs, it does a fresh clone of the github repo, so `origin/master` is _for sure_ up to date. So this workflow is *safe*.

Now the issue: if I'm running manually on one of the testing machines (e.g., weaver, to make sure my branch works on GPU), and I want to make sure I pass baseline tests, I might be tempted to do an integration tests. However, if my local repo is "old", my version of `origin/master` might very well be *behind* the one that was last used to generate baselines (likely by the AT or the nightly testing). If so, TAS might think baselines are outdated, and proceed to generate new ones using _my old version of `origin/master`_.

I haven't tried this yet (in fear I'm right), but I might at some point, if there are no PRs going on, just to make sure my fears are founded.

Possible solutions:
- if doing an integration test, run `git fetch origin` first, to ensure `origin/master` is up to date.
- instead of matching the baselines sha with `origin/master`'s sha, run `git rev-list --left-right --count origin/master...$baselines_sha`, which returns two numbers: how many commits the 1st branch is behind and ahead of the 2nd, respectively. Then error out if the 1st number is non-zero (my repo's version of `origin/master` is behind the one that was last used to generate baselines), generate baselines if the second one is non-zero (my version of origin/master is ahead of the sha last used to generate baselines), and do nothing otherwise (baselines are up to date).

@jgfouca What do you think?

**Comment by jgfouca** [comment]
@bartgol , I agree, we need to tweak the behavior. I'll look at it.
