### ISSUE TITLE
[AD] Adjust DAG logic to handle bundled tracers.

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#889]
The infrastructure which handles tracers may cause the DAG to throw a false-negative error.

The DAG will check if an individual tracer, required by a process has been declared and set elsewhere.  However, if the other process is say dynamics then each individual tracer will have been set, but as part of a bundled tracer array.

The DAG will interpret this as the individual tracer has not been set, even if the whole tracer array has been set.

**Comment by AaronDonahue** [comment]
@bartgol , I put this in per our meeting yesterday.  Can you give it a quick read-over and make sure I got it right?

**Comment by bartgol** [comment]
I already had an opened issue (#876). To avoid duplicates, I'll close this.
