### ISSUE TITLE
Fix p3 unit tests

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#90]
Commit e0f9a87b60c1861324fd6c8dbf252ca9659ece57 (which I believe went in master with #88 ) changed the `FortranData` structure in p3, but did not change p3's unit tests. As a result, tests fail because the structure has more fields than the tests expects.

Solution: adjust the tests expected values.

@AaronDonahue , I'm assigning this to you since you're the one that did the commit. Let me know if you don't have time to fix this.

**Comment by AaronDonahue** [comment]
@bartgol , Yes, I can take care of this.

**Comment by bartgol** [comment]
I believe this is done. Closing.
