### ISSUE TITLE
Use rougher topography for high-res SCREAM runs

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#903]

**Comment by PeterCaldwell** [comment]
@mt5555 - how is this task going? Is there an associated PR?

**Comment by mt5555** [comment]
PR for code improvements:  https://github.com/E3SM-Project/E3SM/pull/4142
ready for merging.

Current plan is to do some 3 month tuning runs at NE256 on Cori to see if NE30 tuning results hold up.

**Comment by mt5555** [comment]
new recommendation:  (topo data sets added to data server)

pgrad_correction=1
hv_ref_profiles=0
hv_theta_correction=0

bnd_topo=USGS-gtopo30_ne1024np4pg2_x6t-SGH.nc 

based on the analysis:
https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2821095670/F2010+NH+evaluation
https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2716598273/NE256+NH+simulations

**Comment by AaronDonahue** [comment]
@tcclevenger , has this issue been addressed?  If so, can we close it?
