### ISSUE TITLE
Improve DYAMOND2 land surface initial condition

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#904]
We should improve our land initial condition for DYAMOND2 simulations. In particular, we should confirm that snowpack over the US is large enough.

**Comment by AaronDonahue** [comment]
@wlin7 , has this been addressed in our latest DYAMOND2 simulations?

**Comment by AaronDonahue** [comment]
@crterai can you confirm this is a finished task?

**Comment by crterai** [comment]
Yes, we can close this issue.
