### ISSUE TITLE
Optimize Scorpio for SCREAM ne1024 runs

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#908]
Make sure I/O is as efficient as possible for our next round of ne1024 simulations. @PeterCaldwell 's understanding is that the config of I/O used for DYAMOND2 was suboptimal. This is discussed at https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2350416313/DYAMOND2+timer+output+analysis and https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2139488259/Performance+of+DYAMOND2+simulation.

**Comment by bartgol** [comment]
@AaronDonahue I think the I/O plumbing is roughly done, and we could probably start trying it at large scale. E.g., we could run the io tests (hacked, to have ncols equal to whatever ne1024 features) on the full summit system, and see if they seem to perform as we expected.

An alternative (maybe better) would be to take one of our standalone ad tests (e.g., p3), and add some output requests, and run the test for N timesteps, at ne1024. This, unlike the io unit test, will factor out io setup costs and possible caching, leaving us with a better feeling of "how much IO costs".

Also, possibly, we should run our full scale IO testing with different numbers of out fields (e.g., with 5 or 50 fields).
