### ISSUE TITLE
Run land on atm grid at ne1024

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#909]

**Comment by wlin7** [comment]
Follow the HOWTO procedure for generating land surface data]( https://acme-climate.atlassian.net/wiki/spaces/ED/pages/872579110/Adding+support+for+new+grids+-+internal#7.-Generate-land-surface-data-(fsurdat)) compiled by @brhillman .

Notes for what are being done:

- Use v2 code base prior to elm name change (E3SM PR #3810). If using current v2 code base, mkmapdata still assume the model (--phys) is clm4_5 and even after creating symbolic links for namelist definition and defaults files (and their config counterparts) to recognize model clm4_5, there is remaining issue in resolving input grids.
- Commit 74c7928476418dcc4bc447870c009a2e74d066b8 is being used
- set sim_year=2010 in mkmapdata.sh
- running in mkmapdata.sh in debug mode didn't generate file clm.input_data_list as indicated in the HOWTO document. It did list what grid files to locate and if they exist. Update the links under NERSC:/global/cfs/cdirs/e3sm/inputdata/lnd/clm2/mapping/grids (/project/projectdirs/ccsm1 were used).

Example command line for generating a map (from 0.5z0.5 AVHRR)
`/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.4.0/bin/ESMF_RegridWeightGen --ignore_unmapped -s /global/cfs/cdirs/e3sm/inputdata/lnd/clm2/mappingdata/grids/SCRIPgrid_0.5x0.5_AVHRR_c110228.nc -d /global/homes/w/wlin/pe3sm/remap/ne1024pg2-elm/ne1024pg2_scrip.nc -m conserve -w map_0.5x0.5_AVHRR_to_ne1024pg2_nomask_aave_da_c210324.nc --src_type SCRIP --dst_type SCRIP --64bit_offset`

Completed weight generation successfully, but said 'input in flex scanner failed".  rmdups.ncl saw no duplicated weights. But mkmapdata.sh still exit with an error status and not proceeding to generating other maps. The other maps could be generated using standalone commands produced when running mkmapdata.sh in debug mode. But it is necessary to figure out what causing mkmapdata.sh to exit to make sure the map generated is valid.

Further note, given the destination grid is at higher resolution than the source grid, is aave suitable?

**Comment by PeterCaldwell** [comment]
Great work, @wlin7 ! Thanks. It seems like we should be using bilinear interpolation when the destination grid is higher-res. Is that an option? 
@brhillman - do you have any reaction to Wuyin's experience since you've dealt with this stuff before?

**Comment by wlin7** [comment]
A quick note on pg2 grid for lnd: Water Cycle simulations are using atm and lnd on ne30np4.pg2 grid when not using tri-grid.

**Comment by AaronDonahue** [comment]
@wlin7 , I feel like this has been fixed right?

**Comment by AaronDonahue** [comment]
@brhillman  or @PeterCaldwell  can you confirm this is fixed and I can close the issue?

**Comment by AaronDonahue** [comment]
We are using bigrid, this should be resolved.
