### ISSUE TITLE
Turn on coupler history output for SCREAM production runs

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#910]
@rljacob - just let me know what commands I should add to the SCREAM run scripts to make this happen. I'd like to make this change soon so we can make sure it doesn't cause performance or output size issues.

**Comment by rljacob** [comment]
./xmlchange HIST_OPTION=ndays
./xmlchange HIST_N=1

Other options for HIST_OPTION are: none,never,nsteps,nstep,nseconds,nsecond,nminutes,nminute,nhours,nhour,ndays,nday,nmonths,nmonth,nye     ars,nyear,date,ifdays0,end

**Comment by AaronDonahue** [comment]
This is now a part of our workflow.  Closing
