### ISSUE TITLE
Results not BFB on Theta when using threads and scream compsets

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#916]
First noticed that several dyamond2 ne1024 runs that used different number of MPI's were not BFB with each other on Theta. To narrow down, we tried tests such as these:

```
ERS_P96x2.ne4pg2_ne4pg2.F2010-SCREAM-LR
PEM_P96x2.ne4pg2_ne4pg2.F2010-SCREAM-HR
REP_P96x2.ne4pg2_ne4pg2.F2010-SCREAM-LR
```

which fail. These fail using dyamond2 branch as well as scream master as of March 1st. The same tests pass on cori-knl (additionally the ne1024 runs on cori-knl all look BFB). Note the default PE layout on Theta for these ne4 tests does not use threads (it uses 64x1). We can force using threads with "PMx2" string in testname, but cori uses 96 MPI's which is a little faster hence my using "P96x2" above (I also verified same issues with 64x2).

One difference between theta and cori-knl is that cori uses the Intel flag `-fimf-use-svml`. When I try adding this, the above tests do pass. I have not yet tried larger problems using this flag.

When I tried using DEBUG builds, I also see non-bfb results. And in that case, using `-fimf-use-svml` does not seem to help. Also, DEBUG builds fail on cori-knl as well and I therefore created a separate issue for non-bfb results when using DEBUG builds which may or may not have same root cause as non-debug builds:
https://github.com/E3SM-Project/scream/issues/911

I verified that tests tried using `ne4pg2_ne4pg2.FC5AV1C-L` all pass on Theta with or without DEBUG.

I was documenting general progress with tracking errors on following confluence page:
https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2377121851/Tracking+errors+and+non-BFB+issues+with+dyamond2+branch

**Comment by PeterCaldwell** [comment]
Added the SCREAMv0.1 project label because we need to fix this in order to do production runs on theta (which is where we have allocation to do these runs).

**Comment by PeterCaldwell** [comment]
what does -fimf-use-svml do?

**Comment by ndkeen** [comment]
The `-fimf-use-svml` flag:

```
Instructs the compiler to use the Short Vector Math Library (SVML) rather than the Intel® Math Library (LIBM) to implement math library functions. 
```

The benefit is that when using "safe" fp-model options (which on KNL's we currently use the absolute safest of `consistent`) it "can significantly improve performance by enabling the compiler to efficiently vectorize loops containing calls to math library functions. "

https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/floating-point-options/fimf-use-svml-qimf-use-svml.html

**Comment by ndkeen** [comment]
Using the "use svml" flag, I tried a set of ne30 cases on Theta which also passed. That is, these tests:
```
ERS_P512x2.ne30pg2_ne30pg2.F2010-SCREAM-HR
PEM_P512x2.ne30pg2_ne30pg2.F2010-SCREAM-HR
REP_P512x2.ne30pg2_ne30pg2.F2010-SCREAM-HR
```

**Comment by ndkeen** [comment]
Again using the SVML flag, these two ne256 tests passed on theta:
```
PEM_Ln48_P16384x2.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2
REP_Ln48_P8192x2.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2
```

The PEM and ERS test both required more than 128 nodes (8192 MPI's runs on 128 nodes, while 16384 MPI's runs on 256 nodes).  The ERS test failed with an odd error (https://github.com/E3SM-Project/scream/issues/927), but I don't think it has anything to do with our BFB issue -- ie the above ne256 tests are further evidence that this SVML flag is helping.

Note I also ran 1 complete day of our ne1024 problem using this flag using 1024 nodes. I've been waiting for another complete day to run using a different number of MPI's to compare the two results. I do see that the performance is better with the SVML flag.

**Comment by ndkeen** [comment]
The ultimate test would be to run the dyamond2 cases for 1-day and still see BFB results with simply adding this compiler flag. I ran a 1024-node job which completed (and was ~19% faster!), but need to run another one with different node count to have results to compare. I have a 1536-node, and 3072-node jobs in the queue. Unfortunately, the 4096-node job failed with error below. Note this is the same type of error I saw on other occasions (with dyamond2 runs on Theta) and documented in above confluence page (in first post of this issue). I was hoping that changing the compiler flag might have an impact, but apparently not.  

```
After ATM step 133
14223:  get_cloud_optics_sw: ssa_out outside range at i,j,k =            4          76
14223:           14 ; x(i,j,k) =    8.15050198001623
14223:  ERROR: get_cloud_optics_sw: ssa_out outside valid range
14223: Image              PC                Routine            Line        Source
14223: e3sm.exe           000000000371E716  Unknown               Unknown  Unknown
14223: e3sm.exe           0000000001E3E12E  shr_abort_mod_mp_         114  shr_abort_mod.F90
14223: e3sm.exe           0000000000D3D5A9  assertions_mp_ass          71  assertions.F90
14223: e3sm.exe           0000000000D47BBD  cam_optics_mp_get         196  cam_optics.F90
14223: e3sm.exe           00000000006CEA98  radiation_mp_radi        1279  radiation.F90
14223: e3sm.exe           00000000008EC6AB  physpkg_mp_tphysb        2734  physpkg.F90
14223: e3sm.exe           00000000008E45F4  physpkg_mp_phys_r        1055  physpkg.F90
14223: e3sm.exe           0000000003270513  Unknown               Unknown  Unknown
14223: e3sm.exe           0000000003232F1E  Unknown               Unknown  Unknown

/projects/ClimateEnergy_4/ndkeen/dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck.svml
```

**Comment by ndkeen** [comment]
We have results from a 1024-node run to compare directly with 1536-node run on theta using the SVML flag. They are indeed BFB! At least by looking at atm.log* values.

The 1536-node job was only about 7% faster than the run without using SVML -- but of course, being BFB is what is important here.

**Comment by ndkeen** [comment]
As it looks like we have a fix for #911 (the implicit save bug that allows bfb with DEBUG and threads), @amametjanov suggested I try that fix on Theta *without* the SVML flag. Indeed using this fix looks like it may also allow BFB results with this current issue. So it may be that we close both of these issue with that fix and then address potential performance improvement from using SVML flag as separate issue. I will do a little more testing.

**Comment by ndkeen** [comment]
Also, a 3072-node job just completed on Theta that used both the SVML flag *and* the implicit save fix in P3. It not only completed (recall that this job failed with only SVML flag as noted above), but it's BFB with the 1024-, and 1536-node runs.

AND it's overall 19% faster!  Note these are 1 full day of dyamond2, but do not include any IO.

**Comment by PeterCaldwell** [comment]
19% is a big speedup! It's not often that making things BFB actually speeds up your code!

**Comment by ndkeen** [comment]
When I run a simple ne30 aquaplanet speed test with E3SM master, there does not appear to be any benefit from this flag. 
For example, this test:
```
PFS_P64_Ld1.ne30_ne30.F-EAM-AQP1
```

When I run a simple ne30 test with scream repo (using F2010-SCREAM-HR-DYAMOND1, ne30pg2, 8 nodes with 64x2, no IO), it is about 15% faster overall to use SVML.  Looking more closely at timers, the speedup is all in CAM_run1 (in at least 3 places).  It's quite possible there is (new) code in scream that is not vectorizing on KNL (for whatever reason) -- with this SVML flag helping, it may indicate it's specifically in math functions (which may be easier to find). 

I think we should merge the implicit save fix for P3 asap and then consider performance improvement in another issue.

**Comment by ndkeen** [comment]
Closing this issue as https://github.com/E3SM-Project/scream/pull/947 will allow BFB results on Theta.  Will open another issue regarding SVML flag and performance.
