### ISSUE TITLE
Use GitPython in our scripts to handle git repo queries/manipulation

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#920]
In the past, we've been bitten by our implementation of git manipulation missing some detail. Since there's a nice [python package](https://gitpython.readthedocs.io/en/stable/index.html) (installable via pip), it might be worth it to use that.

@jgfouca what do you think?

**Comment by jgfouca** [comment]
@bartgol , could be something to explore. I'm pretty comfortable with git's CLI, so I'd be tempted to continue using that via python run_cmd unless there was significant upside to moving to GitPython. Looking at the tutorial, the GitPython API is not super intuitive, so I imagine we'd both be spending lots of time digging into documentation, even to do simple things. GitPython strikes me as something that would be more useful for intensive Git work than we are doing in our scripts.

**Comment by bartgol** [comment]
Fair enough. :)
