### ISSUE TITLE
PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints on Theta with ne256

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#923]
I ran `ERS_Ln48_P8192x2.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2` on Theta with scream master of March 1st and I see the following error:

```
0: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (/projects/ClimateEnergy_4/ndkeen/wacmy/s09-mar1/externals/scorpio/src/clib/pioc_support.c: 3214)

case
/projects/ClimateEnergy_4/ndkeen/s09-mar1/ERS_Ln48_P8192x2.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2.theta_intel.svml
```

**Comment by jayeshkrishna** [comment]
This issue could be related to https://github.com/E3SM-Project/E3SM/issues/4109 (CIME update removed -D_PNETCDF flag and this results in "xmlchange PIO_NETCDF_FORMAT=64bit_data" not working as expected)

**Comment by ndkeen** [comment]
Ok thanks.  Actually, it looks like this test has `PIO_NETCDF_FORMAT="64bit_offset"` where we normally use `PIO_NETCDF_FORMAT="64bit_data"` for ne256/ne1024. I can try test again with `64bit_data`, but should we make a change somewhere so that this is default for larger problems?

**Comment by jayeshkrishna** [comment]
That makes sense. Since we no longer need to support older versions of PnetCDF it might be better to change the default. I will work on changing the default.

**Comment by ndkeen** [comment]
Closing old issue as machine no longer available.
