### ISSUE TITLE
[AD] Scorpio-Interface: For field tag DIM, save to netCDF file with dimension name dimN where N is the size.

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#930]
The general field tag DIM is meant to handle vectorized quantities, for example velocity in dynamics which is stored as a vector quantity of size 2.  However, DIM is not limited to just one application in scream.  One could imagine that in physics velocity could be stored with size 3 representing horizontal and vertical velocities.

The task is to adjust the scorpio_output registration of dimensions in a netCDF file to support multiple instances of DIM being used.

The simplest approach would be to detect the use of DIM as a field tag in use and append an integer N to the dimension name in the netCDF file which represents the length of this usage of DIM.  In the above example this would correspond to a dimension `dim2` for the dynamics velocities and `dim3` for the physics velocities.

DIM would need to be added to the `get_nc_tag_name` function in the `scream_scorpio_interface.hpp` code, and a test would need to be created.

**Comment by bartgol** [comment]
This is already done. See [here](https://github.com/E3SM-Project/scream/blob/c7f209bed92c7b4a55e58ab0848fcc843a437c6f/components/scream/src/share/io/scream_scorpio_interface.hpp#L81).
