### ISSUE TITLE
ERROR: get_cloud_optics_sw: ssa_out outside valid range (or asm_out outside of valid range) -- possible sick node nid00985

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#933]
With dyamond2 branch, I've hit the following error a few times now. In these cases, they are with ne1024 jobs and all on Theta. The error message is either `ssa_out outside valid range` or `asm_out outside valid range`. The values printed do not indicate fails at a particular index. The fails have been at different ATM steps. With these recent runs, it has only failed when using 3072 and 4096 nodes (not yet with 1024, 1536, or 2048 nodes).

I've documented several of these fails in a little more detail here https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2377121851/Tracking+errors+and+non-BFB+issues+with+dyamond2+branch

Using the standard run script to launch a dyamond2 job.

```
13791:  get_cloud_optics_sw: ssa_out outside range at i,j,k =            8          72
13791:           14 ; x(i,j,k) =    3.64583753066899
13791:  ERROR: get_cloud_optics_sw: ssa_out outside valid range
13791: Image              PC                Routine            Line        Source
13791: e3sm.exe           0000000003730B16  Unknown               Unknown  Unknown
13791: e3sm.exe           0000000001E46ECE  shr_abort_mod_mp_         114  shr_abort_mod.F90
13791: e3sm.exe           0000000000D3C609  assertions_mp_ass          71  assertions.F90
13791: e3sm.exe           0000000000D46C1D  cam_optics_mp_get         196  cam_optics.F90
13791: e3sm.exe           00000000006CDE78  radiation_mp_radi        1279  radiation.F90
13791: e3sm.exe           00000000008EAD1B  physpkg_mp_tphysb        2734  physpkg.F90
13791: e3sm.exe           00000000008E2C64  physpkg_mp_phys_r        1055  physpkg.F90
13791: e3sm.exe           0000000003282913  Unknown               Unknown  Unknown
13791: e3sm.exe           000000000324531E  Unknown               Unknown  Unknown
13791: e3sm.exe           00000000032443EE  Unknown               Unknown  Unknown
```

I also see the same error after using the `-fimf-use-svml` flag -- which may be needed to achieve BFB results on Theta.

**Comment by singhbalwinder** [comment]
This error generally indicates something going wrong somewhere else in the code (e.g. some state variables getting unphysical values). Is it possible to run it in debug mode? Debug mode run might fail earlier than this run and might provide us with some more useful info.

**Comment by ndkeen** [comment]
I tried to run the 3072-node and 4096-node cases again with both the SVML and the implicit save bug fix (https://github.com/E3SM-Project/scream/pull/935).  The 3072-node run completed!  And was BFB with the 1024- and 1536-node runs (which were with SVML and without bugfix). Again this is with the dyamond2 branch on theta.

However, the 4096-node run just failed after ATM step 9 with:

```
14239:  get_cloud_optics_sw: ssa_out outside range at i,j,k =           12         109
14239:           14 ; x(i,j,k) =    1314.12039692787
14239:  ERROR: get_cloud_optics_sw: ssa_out outside valid range
14239:  get_cloud_optics_sw: ssa_out outside range at i,j,k =           12          84
14239:           14 ; x(i,j,k) =    1.60196234804847
14239:  ERROR: get_cloud_optics_sw: ssa_out outside valid range
14239: Rank 14239 [Thu Mar 18 19:44:31 2021] [c5-0c0s6n1] application called MPI_Abort(MPI_COMM_WORLD, 1001) - process 14239
14239: forrtl: error (76): Abort trap signal
```


```
The 3072-node run that completed:
20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.3072x16x8.1d.no.nocheck.svml.DECZ

The 4096-node run that failed:
/projects/ClimateEnergy_4/ndkeen/dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck.svml.DECZ
```

Balwinder: I can try to run in DEBUG, but as the only way I've seen this fail is with large-node runs, was thinking we could try other things first. I've run ne256 in DEBUG with scream master -- only with 256 nodes and only for ~24 steps)

**Comment by ndkeen** [comment]
I did go ahead and launch a DEBUG attempt with 4096 nodes. It ran for 140 ATM timesteps and stopped after hitting wallclock time limit.  Note it ran longer than the job above (which stopped after 9 ATM steps).

```
/projects/ClimateEnergy_4/ndkeen/dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck.svml.DECZ.DEBUG
```

**Comment by ndkeen** [comment]
I also ran this same case with two other PE layouts. The above was using 16x8 and I tried both 8x16 and 32x4. The 8x16 case failed here https://github.com/E3SM-Project/scream/issues/969 and the 32x4 case failed mysteriously in init. There is no indication of what went wrong, but it does *not* look like it was something simple as running out of time. The last line of cpl.log for the 32x4 case:

```
(component_init_cc:mct) : Initialize component atm
(component_init_cc:mct) : Initialize component lnd
```

All 3 casedirs are:
```
/projects/ClimateEnergy_4/ndkeen/dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x8x16.1d.no.nocheck.svml.DECZ
/projects/ClimateEnergy_4/ndkeen/dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck.svml.DECZ
/projects/ClimateEnergy_4/ndkeen/dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x32x4.1d.no.nocheck.svml.DECZ
```

All of these are without IO, include the implict-save bugfix (where we init vars to 0), and use the SVML compiler flag.

**Comment by ndkeen** [comment]
I'm trying to run scream v0.1 and I hit this same error on theta with 3072 nodes.
This time it was after 165 steps. And I ran the same repo and inputs on cori-knl with 3072 nodes for a full day.

```
5023:  get_cloud_optics_sw: asm_out outside range at i,j,k =            5          40
5023:           14 ; x(i,j,k) =    1587.16866543329
5023:  ERROR: get_cloud_optics_sw: asm_out outside valid range
5023: Image              PC                Routine            Line        Source
5023: e3sm.exe           000000000375F3C6  Unknown               Unknown  Unknown
5023: e3sm.exe           0000000001E4DC4E  shr_abort_mod_mp_         114  shr_abort_mod.F90
5023: e3sm.exe           0000000000D56B79  assertions_mp_ass          71  assertions.F90
5023: e3sm.exe           0000000000D6123D  cam_optics_mp_get         198  cam_optics.F90
5023: e3sm.exe           00000000006E5356  radiation_mp_radi        1425  radiation.F90
5023: e3sm.exe           000000000090424B  physpkg_mp_tphysb        2689  physpkg.F90
5023: e3sm.exe           00000000008FC874  physpkg_mp_phys_r        1050  physpkg.F90
5023: e3sm.exe           00000000032CD343  Unknown               Unknown  Unknown
5023: e3sm.exe           000000000328E6DE  Unknown               Unknown  Unknown
5023: e3sm.exe           000000000328D7AE  Unknown               Unknown  Unknown

/projects/ClimateEnergy_4/ndkeen/SCREAMv010.SCREAM-DY2.ne1024pg2.20210505.n3072.topo2.ts4
```

I submitted another job with `state_debug_checks=.true.` to see if we could learn more.

Does it make sense to add some more debug output when this happens so we can learn more?

**Comment by ndkeen** [comment]
A job which is the same as above, except I added `state_debug_checks` ran and hit same error. Nothing new seems to be included.  This job stopped after 41 ATM steps.

```
4983:  get_cloud_optics_sw: asm_out outside range at i,j,k =            5          46
4983:           14 ; x(i,j,k) =    478.255134330844
4983:  ERROR: get_cloud_optics_sw: asm_out outside valid range
4983: Image              PC                Routine            Line        Source
4983: e3sm.exe           000000000375D6C6  Unknown               Unknown  Unknown
4983: e3sm.exe           0000000001E4286E  shr_abort_mod_mp_         114  shr_abort_mod.F90
4983: e3sm.exe           0000000000D557D9  assertions_mp_ass          71  assertions.F90
4983: e3sm.exe           0000000000D5FE9D  cam_optics_mp_get         198  cam_optics.F90
4983: e3sm.exe           00000000006E4848  radiation_mp_radi        1425  radiation.F90
4983: e3sm.exe           0000000000902A8B  physpkg_mp_tphysb        2689  physpkg.F90
4983: e3sm.exe           00000000008FB0B4  physpkg_mp_phys_r        1050  physpkg.F90
4983: e3sm.exe           00000000032CB643  Unknown               Unknown  Unknown
4983: e3sm.exe           000000000328C9DE  Unknown               Unknown  Unknown

/projects/ClimateEnergy_4/ndkeen/SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n3072a8x16.topo2.IC2.sdc
```

**Comment by PeterCaldwell** [comment]
So is the summary of this thread that 3072 node ne1024 jobs on theta reliably fail with asm out of bounds errors but 1536 node versions of the same case run without problems?

**Comment by ndkeen** [comment]
I'm not sure we have enough info to make that claim and there is something I've been meaning to look at regarding these runs (will do soon).  And here is another piece of information: a similar setup as above failed on theta, but only using 1536 nodes.

```
2207:  get_cloud_optics_sw: ssa_out outside range at i,j,k =           16         111
2207:           14 ; x(i,j,k) =    49629.4421826981
2207:  ERROR: get_cloud_optics_sw: ssa_out outside valid range
2207: Image              PC                Routine            Line        Source
2207: e3sm.exe           000000000375F3C6  Unknown               Unknown  Unknown
2207: e3sm.exe           0000000001E4DC4E  shr_abort_mod_mp_         114  shr_abort_mod.F90
2207: e3sm.exe           0000000000D56B79  assertions_mp_ass          71  assertions.F90
2207: e3sm.exe           0000000000D6118D  cam_optics_mp_get         196  cam_optics.F90
2207: e3sm.exe           00000000006E5356  radiation_mp_radi        1425  radiation.F90
2207: e3sm.exe           000000000090424B  physpkg_mp_tphysb        2689  physpkg.F90
2207: e3sm.exe           00000000008FC874  physpkg_mp_phys_r        1050  physpkg.F90
2207: e3sm.exe           00000000032CD343  Unknown               Unknown  Unknown
2207: e3sm.exe           000000000328E6DE  Unknown               Unknown  Unknown
2207: e3sm.exe           000000000328D7AE  Unknown               Unknown  Unknown
2207: e3sm.exe           00000000032CD770  Unknown               Unknown  Unknown
2207: e3sm.exe           00000000033E1509  Unknown               Unknown  Unknown

/projects/ClimateEnergy_4/ndkeen/SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n1536a16x8.topo2.ts4.os1
```

**Comment by ndkeen** [comment]
I've been meaning to look at the compute node id's for all of the runs that are OK vs all of the runs that hit this error to see if there are any suspect nodes on the machine.  I did this and narrowed it down to a potential set of hundred or so, but it turns out we don't really need that as there is enough info from the 3 fails that we have as they all fail on same node id:

```
grep 5023 SCREAMv010.SCREAM-DY2.ne1024pg2.20210505.n3072.topo2.ts4/run/e3sm.log.518605.210512-212313
0: GLOBAL NODE 627 [ nid00985 ] : ( 8 MPI TASKS ) 5016 5017 5018 5019 5020 5021 5022 5023
5023:  get_cloud_optics_sw: asm_out outside range at i,j,k =            5          40
5023:           14 ; x(i,j,k) =    1587.16866543329
5023:  ERROR: get_cloud_optics_sw: asm_out outside valid range

thetalogin4% grep 2207 SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n1536a16x8.topo2.ts4.os1/run/e3sm.log.519587.210523-100654
0: GLOBAL NODE 137 [ nid00985 ] : ( 16 MPI TASKS ) 2192 2193 2194 2195 2196 2197 2198 2199 2200 2201 2202 2203 2204 2205 2206 2207
2207:  get_cloud_optics_sw: ssa_out outside range at i,j,k =           16         111
2207:           14 ; x(i,j,k) =    49629.4421826981
2207:  ERROR: get_cloud_optics_sw: ssa_out outside valid range

gthetalogin4% grep 4983 SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n3072a8x16.topo2.IC2.sdc.ts4/run/e3sm.log.519171.210516-181514
0: GLOBAL NODE 622 [ nid00985 ] : ( 8 MPI TASKS ) 4976 4977 4978 4979 4980 4981 4982 4983
4983:  get_cloud_optics_sw: asm_out outside range at i,j,k =            5          46
4983:           14 ; x(i,j,k) =    478.255134330844
4983:  ERROR: get_cloud_optics_sw: asm_out outside valid range
```

This shows compute node `nid00985` is always involved.

And, as this is clearly following the same type of failures we saw on Cori, I see that it's always the last rank of the node. With the similar fails on Cori, it would always fail on a certain core of the node (based on which logical rank failed).

**Comment by PeterCaldwell** [comment]
Great thinking Noel! So we think this is a bad node on theta?

**Comment by ndkeen** [comment]
I don't know exactly what defines a "bad node" as clearly other apps must be using it fine. And this was also the case on Cori -- nobody else had a problem with the problem nodes we identified. But yea, it looks like our ne1024 jobs don't do well on this node. 
 
a) Can ask ALCF to take the node out of service
b) I know we can use batch options to avoid a node, but that only hurts us as it makes it more difficult to schedule a job. 
c) We add some code to do a little trick. When we ask for N+1 nodes, if this node is in the pool, simply don't use it.

**Comment by ndkeen** [comment]
Last night I had 3 more jobs fail due to this issue -- but it looks like they ran one after another, so not surprising they ended up with the same node `nid00985`.

Noting this issue has a similar look to these on cori-knl, where NERSC removed the node(s):
https://github.com/E3SM-Project/E3SM/issues/3768
https://github.com/E3SM-Project/scream/issues/724

**Comment by naromero77** [comment]
@ndkeen Asked me to take a look, I am going into a _marathon_ of meetings this afternoon so these are quick comments off the top of my head. 

At first, I did not think there was a hardware bug here. However, as I read through this really really long thread. It looks like the same error occurred on Cori-KNL and NERSC took that node out of service? Please send a ticket to support@alcf.an.gov and then first thing you need to say is that you found this same error on NERSC Cori-KNL and they took the node out of service. Do not first start with your rationale for the node being bad -- first say that NERSC took this action to help you out. But afterwards, do please include your rationale for why you think that node is bad and do give the node id. I think as an interim solution, you should try that batch option that was mentioned in the thread.

Something for you guys to consider. I have not seen numerical issues like this in old hardware. In early hardware, it is common. What I have seen is sometimes in old hardware, is that the DMA starts to slowly degrade over time.

Do you have any code that uses asynchronous communication iSend/iRecv? If so, can you switch to blocking Send/Recv? Non-block communication can really exercise the DMA on processors. 

Is the out-of-range warning coming from RTE+RRTMGP? If so, can you point me to the code. Not sure what version you are using.

**Comment by ndkeen** [comment]
I sent the following email. Pasting here to make it easier to track. The batch option mentioned for the jobs on Cori was for slurm. Theta does not use slurm -- do you know how to ask a job to avoid a node on Theta @naromero77 ?

```
We have been tracking a particular type of failure in our jobs. The code stops with an error in a routine named get_cloud_optics_sw
during some basic range checking -- ie our code spots value out of range and stops. However, the same or similar problem sometimes
runs fine, that is, we don’t suspect there is a real issue, but clearly that routine is seeing different data with different jobs.
After some debugging, I noticed that these errors always happen on the same node of Theta (nid00985).

The error will happen after initialization (which can be 5-30 minutes depending on size of problem) and during the time stepping.
It seems to happen fairly early in the simulation after init (before say step 200), but not always on the same step.

I think the earliest date I've seen this error on nid00985 of Theta was a job from Feb of 2021. While it’s true I’ve run
many other E3SM jobs previously, we didn’t start writing out the node id’s to our log files until recently — which just
prevents me from easily grepping further back.

Note that we also had 2 similar issues as this on the KNL nodes of Cori. These KNL issues are similar in behavior in that:
a) jobs always fail when the node is used and do not fail otherwise. (some jobs using the sick node do complete, but only run for very short time,
   such as as 24 steps).
b) looking at the MPI rank that reports the fail, it will be in the same logical place on the node --
  suggesting the problem is likley a specific core of the node. Out code uses MPI/openmp
Note that during the debugging with the jobs on Cori, we did try running several smaller problems on the
affected node to find a smaller reproducer and were not able. Eventually, NERSC simply removed the
nodes from the pool and we have continued to run fine on Cori.

During Feb and March of 2021, I ran a series of benchmarks where I used the same repo,
same input problem, but changed the number of nodes and MPI's per node. 16 of those jobs completed
one full simulated day (which consists of 1152 steps). However, 7 of them failed with this error described.
All of the successful runs did NOT use the sick node, while the 7 fails did. In this set of experiments,
the only failures were jobs using 3072 or 4096 nodes.  All of the 1024 and 1536 node count jobs completed.
However, below we see 1536 node jobs fail. Obviously, jobs using more nodes will have greater chance of getting
stuck with the sick node.

jobid     case in /projects/ClimateEnergy_4/ndkeen
503042    dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.3072x16x8.1d.no.nocheck.svml
497513    dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.3072x16x8.1d.no.nocheck
503032    dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck.svml
504224    dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck.svml.DECZ
498056    dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck
498492    dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x16x8.1d.no.nocheck
508882    dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x8x16.1d.no.nocheck.svml.DECZ

The most recent set of jobs were mostly in May of 2021. There were 10 such jobs all using similar repo and
running similar problems that completed a full day of simulation. However the following 7 jobs all failed
with the same error -- again the jobs completing did not use Theta node nid00985, while the failed
jobs did (and the error points to node nid00985).

jobid    case in /projects/ClimateEnergy_4/ndkeen
518605   SCREAMv010.SCREAM-DY2.ne1024pg2.20210505.n3072.topo2.ts4
519171   SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n3072a8x16.topo2.IC2.sdc.ts4
519587   SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n1536a16x8.topo2.ts4.os1
520414   SCREAMv010.SCREAM-DY2.ne1024pg2.may18.n1536a16x8.topo1.ts4.spa
520492   SCREAMv010.SCREAM-DY2.ne1024pg2.may18.n1536a16x8.topo1.ts4
522740   SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n1536a16x8.topo1.ts4.eo
522737   SCREAMv010.SCREAM-DY2.ne1024pg2.may18.n1536a16x8.topo1.ts4

Would it be possible to remove this node from the pool on Theta?
I understand there is an option to tell the job to avoid certain nodes, but we know
this can significantly increase the Q time.
```

**Comment by naromero77** [comment]
I will ask about how to avoid a node in Cobalt.

**Comment by ndkeen** [comment]
I'm trying what is suggested here. https://stackoverflow.com/questions/38749433/exclude-or-include-specific-nodes-in-pbs-pro

**Comment by naromero77** [comment]
Check your Slack DM. This version of Cobalt looks like PBS, but is not PBS.

**Comment by ndkeen** [comment]
To get current list of compute nodes available, do `find-location -q default`.

For example:
```
thetalogin6% find-location -q default
24-47,52-75,84-139,148-395,404-459,468-523,532-779,788-815,820-843,852-907,916-1163,1172-1227,1236-1291,1300-1547,1556-1611,1620-1675,1684-1935,1940-1995,2004-2059,2068-2155,2157-2319,2324-2351,2356-2379,2388-2443,2452-2703,2708-2763,2772-2827,2836-3087,3092-3119,3124-3147,3156-3211,3220-3601,3603-3823,3840-4607
```

Then, modify that list to chose the nodes you want your job to qualify for and then can use the `--attrs=location` option to make that happen.  For example:

```
qsub --attrs=location=24-47,52-75,84-139,148-334,336-395,404-459,468-523,532-657,659-779,788-815,820-843,852-907,916-984,986-1075,1077-1163,1172-1227,1236-1291,1300-1547,1556-1611,1620-1675,1684-1935,1940-1995,2004-2059,2068-2155,2\
157-2271,2273-2319,2324-2351,2356-2379,2388-2443,2452-2500,2502-2703,2708-2763,2772-2827,2836-3087,3092-3119,3124-3147,3156-3211,3220-3437,3439-3601,3603-3823,3840-4607 -A ClimateEnergy_4 -t 14:00:00 -n 850 -q default -M ndkeen@lbl\
.gov --jobname SCREAMv010.SCREAM-DY2.ne1024pg2.may10.n1536a16x8.topo2.ts4.os1 --mode script ~/stingray/pbs_nofail.sh .case.run --skip-preview-namelist
```

should avoid `nid00985`.  Note this is suboptimal solution as this will cause larger delay in the Q.

**Comment by amametjanov** [comment]
I've tried `e3sm_hi_res_master` tests in 128- and 145-node jobs that include node `nid985` -- all passed with no errors:
- SMS.ne120_ne120.FC5AV1C-H01A.theta_intel
- SMS.ne120_oRRS18v3.A_WCYCL2000_H01AS.theta_intel.eam-cosplite
- SMS.T62_oRRS30to10v3wLI.GMPAS-IAF.theta_intel

Next thing to try is ne256 and ne1024 runs. Can you post a path to run-scripts? Just need to `./case.submit -a="--attrs=location=916-1043"` for a 128-node job. Need a smaller node-count that works.

**Comment by ndkeen** [comment]
Closing issue as we are no longer running these (or any) jobs on Theta.
