### ISSUE TITLE
RRTMGP needs efficient access to a subset of tracer fields

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/scream#940]
RRTMGP needs to compute combined optical properties from a number of atmospheric gases. Right now, we have very rudimentary tests that use standard atmosphere profiles, but as soon as we want to couple RRTMGP to the rest of the atmosphere processes, we will want to get these from elsewhere in the model. These will probably all come from the model tracers. RRTMGP stores the mixing ratios for the gases of interest internally in an array dimensioned `ncol,nlay,ngas`. While we could probably copy each gas explicitly from the tracer data structure into this RRTMGP data structure, it might be much easier and more efficient if the field manager could provide a reshaped grouping of relevant tracers.

**Comment by bartgol** [comment]
This is somewhat related to what SHOC needs to do with tracers. For clarity, the field manager stores the set of all tracers as a _bundled_ single array, of dimensions `(ncols,ntracers,nlevs)`. Each individual tracer is a subview of this field. SHOC, however, prefers the layout `(ncols,nlevs,ntracers)`, so it "transpose" the data internally from the FM format to its internal one, and back.

Furthermore, SHOC does not transpose the whole array, but rather the _portion_ (wrt to the 1st dimension, ncols) that is currently worked on. This allows for the temporary to be `(nslots,nlevs,ntracers)`, which can be smaller than `(nslots,nlevs,ntracers)`. Here, `nslots` is the number of concurrent teams that the used TeamPolicy might be using. The transposition is performed _inside_ the outermost parallel for (over ncols), and each thread team transpose the column(s) it is currently working on.

For RRTMGP, we need to see if this can be done. Namely, accept a `(ncols,ngas,nlevs)` field, and, internally, transpose a single column (or a bunch of columns, depending on the team policy specs) to the preferred rrtmgp format. If not, the interface to the AD will have to transpose _the whole_ `(ncols,ngas,nlevs)` array to `(ncols,nlevs,ngast)` format before calling rrtmgp (and viceversa upon return).

Aside of _where_ the transposition happens (outside the ncols loop, or inside), there's a second issue: can the FM help out SHOC and RRTMGP by allocating their tracers "contiguously"? That would allow them to subview a contiguous set of tracers indices, along the line of `my_tracers=tracers(ncols,1:num_my_tracers,nlevs)`. This will help the transpose routine. Notice that the overall subview will still be strided. However, `my_tracers(icol,:,:)` will become a _contiguous_ array, making the transposition within a single column faster.

Currently, we have shoc_tracers==dynamics_tracers, so things are easy. It is my understanding that if/when we have prognostic aerosols, shoc_tracers will be a subset of dynamics_tracers. rrtmgp_tracers will also be a subset of dynamics_tracers (of course), but I don't know its relationship with shoc_tracers. Either way, it _should_ be possible to rearrange the order of shoc_tracers and rrtmgp_tracers in such a way that they are both contiguous (whether they overlap or not). But it will require some logic to be added to the AD. In particular, we might have to add some data to the `GroupRequest` struct, like a flag that requests the fields in the group to be contiguous.

**Comment by bartgol** [comment]
I think this is not possible, as described in the comment above. Closing.
