### ISSUE TITLE
Add a macrophysics condensation output variable 

### ISSUE THREAD

**Issue by hassanbeydoun** [E3SM-Project/scream#946]
This should just involve defining a new variable named "condensation_macro" and have it store the value of "CMELIQ" in p3_interface. It would be compatible with SHOC and CLUBB.

**Comment by AaronDonahue** [comment]
@hassanbeydoun , is this still desired?

**Comment by AaronDonahue** [comment]
@hassanbeydoun , did you add this in your latest round of P3 changes?  Is this resolved?

**Comment by AaronDonahue** [comment]
From @hassanbeydoun : "Close. Included in v1 diags"
