### ISSUE TITLE
Compute dry static energy in SHOC from T and z

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#955]
v1 SHOC currently assumes "s" (dry static energy) is passed as an input. It should instead be computed in the SHOC interface via DSE = cp*T_atm_mid + g*(z_mid + surf_geopotential). Inclusion of surf_geopotential is needed because z_mid is actually a relative geopotential assuming the surface height is 0. 

It might make sense for this DSE calculation to be a universal function rather than stuffed into SHOC itself in case other future parameterizations want DSE.

**Comment by tcclevenger** [comment]
See PR https://github.com/E3SM-Project/scream/pull/983
