### ISSUE TITLE
Remove nevapr, precip_total_tend, and qr_evap_tend from P3 interface

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#959]
nevapr, precip_total_tend, and qr_evap_tend were needed by MAM aerosols... which we're not porting to C++. In addition, these names don't really make sense or describe what they actually did. And the way they were implemented seems wrong. So we should just delete all mention of them.

**Comment by AaronDonahue** [comment]
@PeterCaldwell , Should we remove these variables from all of P3?  Including the F90, SCREAMv0 code?

**Comment by PeterCaldwell** [comment]
good question. I'm inclined to say we should follow Conrad's lead and skip F90 changes just out of laziness. Also, I think Koby wants these things in F90 for low res... not that he's using our code for that, but someday he might.

**Comment by AaronDonahue** [comment]
okay cool, sounds good.

**Comment by AaronDonahue** [comment]
Solved by #987
