### ISSUE TITLE
Clean up activated nc and ni activation variables passed to P3

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#960]
Cloud droplet and ice crystal activation (i.e. the number of aerosol particles available to nucleate liquid or ice drops) are calculated outside P3, but are passed into P3 to actually update the model state. For historical reasons, the variables used for liquid vs ice phase have different units and different names. In addition, prescribed CCN has been added as a 3rd variable even though it's basically the same as the activated nc. We should replace nc_nuceat_tend and nccn_prescribed with a single nc_activated variable. This will require modifying the p3_main interface to change/reduce the number of input variables and will require some slight modifications where nc is calculated.

**Comment by AaronDonahue** [comment]
@hassanbeydoun , can you comment on this issue.  Is this still something we need to work on?

**Comment by AaronDonahue** [comment]
@hassanbeydoun said we can close this
