### ISSUE TITLE
Merge gas_vmr into tracers array

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#962]
Radiation uses an array called gas_vmr, which contains volume mixing ratios for gas species which should mostly be advected, but some may not be advected. We think gas_vmr should be included in the tracers variable which currently contains all variables that need to be advected. By ordering gases which should be advected first and non-advected last, we think we can keep memory contiguous while providing HOMME a single array to advect. The task here is to get rid of gas_vmr in rrtmgp's interface and replace it with tracers. Tweaks for subsetting will also be needed.

**Comment by PeterCaldwell** [comment]
Comment from Ben on https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/1927512393/Field+Manager+Variable+Names: 

> On 9), note that the behavior in EAM involves an intermediate interface (actually, probably multiple intermediate interfaces) to grab the gas mixing ratios from pbuf/state/wherever they live and then get them into the format needed by RRTMGP (volume mixing ratio with specific units). Grabbing the mass mixing ratios from the appropriate places happens via the rad_constituents module, and then within the RRTMGP interface we have to convert mass mixing ratios to volume mixing ratios, and also convert specific humidity to a volume mixing ratio for the water vapor. So most likely, these will need to be computed within our radiation interface, with data for the mass mixing ratios taken from the TRACERS array. I don’t expect to be able to just grab the data from the Field Manager without having to derive things I guess, so to say these will be “merged into the tracers array” might be a little misleading.

Reply: Ok. I guess the strategy will be to add whatever variables to the tracers array as appropriate, then to also add the appropriate conversions in the postamble of the radiation interface layer necessary to actually use them.

**Comment by PeterCaldwell** [comment]
@brhillman and @AaronDonahue - didn't we complete this task via a slightly different pathway? Isn't this done now?

**Comment by AaronDonahue** [comment]
@PeterCaldwell , yes, I think so.  I think this was handled by PR #1069 .  I'm going to close this now.
