### ISSUE TITLE
Create functions to calculate T_atm_int, p_int, z_int, and z_mid

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#963]
We want to compute T_atm_int, p_int, z_int, and z_mid on the fly every time they're needed rather than saving them as field-managed variables. For T_atm_int, p_int, and one of z_int or z_mid, this will just be done via simple interpolation/extrapolation using the tools already being made available in #954 . Getting z from T and p will additionally require the hypsometric equation. 

These functions should be made available in our universal functions directory.

**Comment by PeterCaldwell** [comment]
Partially addressed by #954

**Comment by AaronDonahue** [comment]
It looks like we still have `p_int` as a field managed variable.  Is this something we could easily take care of?  Can we calculate `p_int` the same way we calculated `T_int`?  If so it looks like `p_int` is only used in SHOC and RRTMGP

**Comment by AaronDonahue** [comment]
closing in favor of #1035
