### ISSUE TITLE
Decide what optical property scheme we want to use and how to make that scheme consistent with P3 assumptions

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#966]
lamc and mu_c are parameters for the gamma PDF for subgrid variability in qc. They were used in older versions of radiation's subcolumn generator but aren't part of the current RRTMGP setup. This isn't necessarily a good idea, but is a topic for a longer-term discussion. For our initial SCREAMv1 impl, we can delete lamc and mu_c from the p3_main interface since they aren't used outside P3. These variables are used a lot in P3 so we can't delete them completely.

**Comment by AaronDonahue** [comment]
Should already be addressed by #987
