### ISSUE TITLE
Write output using CF convention long names

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#968]
https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/1927512393/Field+Manager+Variable+Names provides CF names for variables in the field manager. 

- [ ] Make SCREAM output use these CF variable names
- [ ] Include code to change units to CF-standard where needed (for units marked in red in our Field Manager Variable Names confluence page)
- [ ] Find CF names for variables missing a CF name column if possible
- [ ] Where no CF name exists, come up with one using http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html

**Comment by AaronDonahue** [comment]
I would add to this list that it is dependent on the first task of adding a "longname" option to the field repository registration.

**Comment by bartgol** [comment]
I had started to add the long name to the FieldIdentifier in [this branch](https://github.com/E3SM-Project/scream/tree/bartgol/field-stack-changes). I was also cleaning up a bit the Field stack (which after 2 years of patches starts to have some pointless things), but only gave it a couple of jabs. Still, putting the ref here in case someone wants to pick it up.

**Comment by PeterCaldwell** [comment]
Closing in favor of #2186
