### ISSUE TITLE
DYAMOND2 job hit assertion fail in set_daynight_indices on Theta at large node count

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#969]
As I try to better understand what is happening with https://github.com/E3SM-Project/scream/issues/933, I ran another 4096-node job on theta with a different layout -- in this case I tried 8 MPI's per node with 16 threads each. It failed here:

```
7111:  ERROR:
7111:  Assertion failed: set_daynight_indices: count(day_indices > 0) != count(coszrs
7111:  > 0)
7111: Image              PC                Routine            Line        Source
7111: e3sm.exe           000000000372F516  Unknown               Unknown  Unknown
7111: e3sm.exe           0000000001E4EF1E  shr_abort_mod_mp_         114  shr_abort_mod.F90
7111: e3sm.exe           0000000000D3E27F  assertions_mp_ass         190  assertions.F90
7111: e3sm.exe           00000000006E1A52  radiation_mp_set_        2181  radiation.F90
7111: e3sm.exe           00000000006CFEFB  radiation_mp_radi        1315  radiation.F90
7111: e3sm.exe           00000000008EC6AB  physpkg_mp_tphysb        2734  physpkg.F90
7111: e3sm.exe           00000000008E45F4  physpkg_mp_phys_r        1055  physpkg.F90
7111: e3sm.exe           0000000003281313  Unknown               Unknown  Unknown
7111: e3sm.exe           0000000003243D1E  Unknown               Unknown  Unknown
7111: e3sm.exe           0000000003242DEE  Unknown               Unknown  Unknown
```

It happens in init, where the last line of cpl.log written is `(component_init_cc:mct) : Initialize component atm`

`/projects/ClimateEnergy_4/ndkeen/dy2/20210204.dyamond2.F2010-SCREAM-HR-DYAMOND2.ne1024pg2_r0125_oRRS18to6v3.theta.4096x8x16.1d.no.nocheck.svml.DECZ`

**Comment by ndkeen** [comment]
I'm not sure, but it could easily be something going wrong elsewhere (code or machine) and just happens to stop here.

The code:
```
...
      day_indices(:) = 0
      night_indices(:) = 0

      ! Loop over columns and identify daytime columns as those where the cosine                                                                                                     
      ! solar zenith angle exceeds zero. Note that we wrap the setting of                                                                                                            
      ! day_indices in an if-then to make sure we are not accesing day_indices out of bounds
      iday = 0
      inight = 0
      do icol = 1,size(coszrs)
         if (coszrs(icol) > 0._r8) then
            iday = iday + 1
            day_indices(iday) = icol
         else
            inight = inight + 1
            night_indices(inight) = icol
         end if
      end do

      ! Check indices                                                                                                                                                                
      call assert(count(day_indices > 0) == count(coszrs > 0), &
                  trim(subname) // ': count(day_indices > 0) != count(coszrs > 0)')  !<-- stops here
```

**Comment by PeterCaldwell** [comment]
Interesting code - it's hard to imagine count(coszrs>0)!=count(day_indices>0) since day_indices was literally just set to 1 wherever coszrs>0. I suspect coszrs is NaN. It might be worth changing the assert to an if statement which dumps diagnostics before calling abort. Obvious checks would be whether day_indices+night_indices != size(coszrs) and whether iday=count(day_indices>0). On one hand, this fail could reflect problems somewhere else and may not be reproducible. On the other hand, this failure is so clean that it seems like it should offer insight. In particular, it seems like the only way for a fail here is coszrs to be NaN and I think coszrs is the cosine of the zenith angle for that timestep which comes from a simple calculation of latitude and longitude...

**Comment by ndkeen** [comment]
I added some write statements and ran again. Unfortunately, the code did NOT crash again in this location. Instead it completed init, ran 21 ATM steps, and failed with the `ERROR: get_cloud_optics_sw: ssa_out outside valid range` error which is a different issue #933

**Comment by ndkeen** [comment]
Closing issue as we are no longer using Theta and are not running large v0 jobs elsewhere.
