### ISSUE TITLE
[AD] create a new field manager registration for "internal" variables

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#985]
There are a handful of variables in SCREAM that must be in the field manager because they are both a) persistent across time steps and b) needed for BFB restarts.  However, they are only needed by one process and should not be changed by any other process.

An example of this sort of variable would be `T_prev_micro_step` which is needed by P3 microphysics, but nowhere else.

After some discussion with @bartgol we decided there was a need for a new class of field managed variable, other than the "computed" and "required" registrations we have now.  A possible name might be "internal" or "private" or "local".

By registering a field managed variable as "internal" we can do a number of things.
1. We can check that no other process is registering a variable with the same name, to protect against inadvertent changing of local persistent variables.
2. We can treat these differently at initialization.  Note this was the primary motivation for the correspondence between @AaronDonahue and @bartgol.  In other words, instead of requiring internal variables to be initialized by the AD, we can have the FM set the variable to NaN's and allow the init_impl of the process itself to set the value.
- Note, we could add even more functionality, such as checking to see if initialization is possible using the init netCDF file, but not throwing an error if it isn't found.  This would be required for restart runs.

**Comment by PeterCaldwell** [comment]
I think the name "local" is a bit more descriptive than "internal". Calling it RestartOrOutput is tempting, but I think is a bad idea in case we think of other uses for this type later.

**Comment by bartgol** [comment]
I would have voted 1."internal" 2."private" 3."local. I find the word "local" a bit overloaded in this context: local as in "on this rank vs across all ranks", vs local as in "dependent on earth position vs global", vs local as intended in this context.

 More precisely, I think of the resulting atm proc interface:
```
std::set<FieldIdentifier> get_required_fields () const;
std::set<FieldIdentifier> get_local_fields () const;
std::set<FieldIdentifier> get_computed_fields () const;
```
vs
```
std::set<FieldIdentifier> get_required_fields () const;
std::set<FieldIdentifier> get_internal_fields () const;
std::set<FieldIdentifier> get_computed_fields () const;
```
vs
```
std::set<FieldIdentifier> get_required_fields () const;
std::set<FieldIdentifier> get_private_fields () const;
std::set<FieldIdentifier> get_computed_fields () const;
```
Which one of these signatures conveys the meaning better? And the meaning here is "these fields are mine, and mine only". I'm leaning on internal or private. But I'll live with whatever the consensus is.

**Comment by PeterCaldwell** [comment]
good point about "local" being overloaded, @bartgol . "Private" also has special CS meaning. I change my vote to "internal".

**Comment by jeff-cohere** [comment]
A bit late to the game here, with a wrench to toss: what about "exclusive"? That word isn't used anywhere else, and conveys that a field belongs exclusively to a given process. And it's the same number of syllables as "internal". :-)

I know, I know. I'm just being difficult.

**Comment by bartgol** [comment]
I like that. `internal` does not convey that nobody else should use it.
