### ISSUE TITLE
Handle syrah and quartz cmake issues in machine_specs.py instead of *.cmake

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#999]
There was an issue building the latest version of the Kokkos sub-module on the Livermore Computing systems quartz and syrah, related to the gcc compatibility of the intel compiler on those two machines.

After a set of cmake trial and error tests the solution was found and implemented in PR #996 .  But the solution was a bit hacky.  The root of the problem, that CMAKE was still linking to the wrong version of gcc, even when the intel compiler was pointed to a newer version, was not explicitly solved by this fix.

With the help of LC support we determined the issue and found a more elegant fix, which should be implemented eventually, but is not a high priority.  The fix is to add the following to the `machine_specs.py` file under syrah and quartz:

```
export CXXFLAGS=-gxx-name=/usr/tce/packages/gcc/gcc-8.3.1/rh/bin/g++
export CFLAGS=-gxx-name=/usr/tce/packages/gcc/gcc-8.3.1/rh/bin/g++
export FFLAGS=-gxx-name=/usr/tce/packages/gcc/gcc-8.3.1/rh/bin/g++
```

**Comment by AaronDonahue** [comment]
For reference here is a copy of the correspondence that led to this solution:

```
This is indeed a quirk of cmake. It finds the mpicc wrapper and looks at the link command that it invokes, without respecting the additional -gxx-name flag that you are adding. As such, it finds the default 4.9.3 gcc compiler path and then constructs its own link commands using the 4.9.3 path. Another potential work around would be if you were to add an additional wrapper layer such that your mpicc, etc. commands actually invoke the LC `mpicc -gxx-name=....`. I don't know if it's worth the effort, though, since you have a viable workaround.
```

and finally the solution:

```
I think I found a proper solution. It looks like CMake honors CXXFLAGS, CFLAGS, anf FFLAGS in one's environment as default, while the CMAKE_CXX_FLAGS are added after CMake generates its compiler command. I created a modified script that appears to build your code OK:
[donahue5@quartz188:gcc_linking_error_testing]$ diff lee218.sh build_ekat.sh
6,8c6
< export CXXFLAGS=-gxx-name=/usr/tce/packages/gcc/gcc-8.3.1/rh/bin/g++
< export CFLAGS=-gxx-name=/usr/tce/packages/gcc/gcc-8.3.1/rh/bin/g++
< export FFLAGS=-gxx-name=/usr/tce/packages/gcc/gcc-8.3.1/rh/bin/g++
---
>
13a12,13
>   -D CMAKE_CXX_FLAGS:STRING="-cxxlib=/usr/tce/packages/gcc/gcc-8.3.1/rh -gxx-name=../bin/g++" \
>   -D CMAKE_CC_FLAGS:STRING="-cclib=/usr/tce/packages/gcc/gcc-8.3.1/rh -gxx-name=../bin/g++" \
```

**Comment by bartgol** [comment]
@AaronDonahue Is this still an issue?

**Comment by AaronDonahue** [comment]
I'm not sure if this has been addressed.  It doesn't seem like its a major issue.  But as far as I can tell it looks like we still force the path in the quartz.cmake and syrah.cmake files, see

```
set(CMAKE_CXX_FLAGS "-w -cxxlib=/usr/tce/packages/gcc/gcc-8.3.1/rh" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-L/usr/tce/packages/gcc/gcc-8.3.1/rh/lib/gcc/x86_64-redhat-linux/8/ -mkl" CACHE STRING "")
```

If we are keen to remove issues I suppose we can delete this.  At the moment it seems like when we are cleaning up the code it might be nice to have this note to remind us what the strategy is to make this cleaner.  Of course, maybe it's perfectly fine to include everything in the quartz.cmake file and this isn't an issue at all.

**Comment by bartgol** [comment]
Coming to think of it, I think it's best to keep this in the cmake mach file. The machine_specs.py script is only used by test-all-scream, you don't get it when doing 'manual runs'. In other words, test-all _does_ read the cmakke mach file, but cmake _does not_ read the python mach specs file.

I am for closing this, unless you are not satisfied with the current solution.

**Comment by AaronDonahue** [comment]
Good call.  I agree.
